### ISSUE TITLE
Select Input Options

### ISSUE THREAD

**Issue by minimoogclone** [json-api/json-api#1016]
How do I include a Resouce Ojbect Collection for the keys and values used for HTML 'options' tags of 'select' inputs?  

For example, I have an HTML form to edit an 'Author', and wish to set the 'Country' select input by choosing from a list of 'Countries' found in my JSONAPI payload.  Where would the Countries Resouce Object Collection be found within the document?

Do I use a different endpoint and make a second request?  Is there a way I can instead include them in the 'included' member to eliminate the second request?

The ids for 'countries' resources would not appear in the primary data or related resources as 'full linkage'.  Would this be allowable?

The JSONAPI specs state that any Resource Object Id under the 'included' member must also be referenced in the primary data, or related resources.  All but 1 of my 'countries' Resource Objects found in the collection will have an ID reference at one given time, so it may go against the specification, and I'm not clear on how to proceed.

An example would be much appreciated.  

Many thanks

**Comment by ethanresnick** [comment]
> The JSONAPI specs state that any Resource Object Id under the 'included' member must also be referenced in the primary data, or related resources. All but 1 of my 'countries' Resource Objects found in the collection will have an ID reference at one given time, so it may go against the specification, and I'm not clear on how to proceed.

Right... the included resources should just contain the country referenced from the primary data. The standard approach, therefore, would be to make a second request. (?include is meant to eliminate most such requests, but it doesn't eliminate all of them.)

Another option would be to put the full list of countries (possibly with only a subset of the fields for each) in the top-level `meta`, like so:

```
{
   "data": { /* author resource object */ },
   "included": [
     { /* resource object for author's country */}, 
     /* other included resources, if any */
   ],
   "meta": {
     "countries": [/* list of country resources for the autocomplete */]
}
```

In the near future, it'll [be possible](http://github.com/json-api/json-api/pull/957) to assert that the meaning of a member in `meta` is governed by a particular extension, where the extension will be identified with a URI. That way, generic clients that understand the extension will be able to make sense of any `meta` info (rather than meta's contents being totally opaque and non-standard). Unfortunately, that isn't ready just yet...but if you put this data in `meta` now, you'll be able to associate it with an extension retroactively once that mechanism exists.
