### ISSUE TITLE
Main Website Compound Document Violates the Full Linkage Requirement?

### ISSUE THREAD

**Issue by scott-mcdonald** [json-api/json-api#1017]
I believe the main website compound document on the first page violates the "full linkage" requirement of jsonapi compound documents.

The included comment (type="comments" id="5") has resource linkage to an author (type="people" id="2") but that person (type="people" id="2") does not exist in the included section of the included document.

I believe this violates the full linkage requirement of compound documents?

**Comment by csantero** [comment]
@scott-mcdonald The way I interpret "full linkage" is that every resource in `included` must have a corresponding resource identifier object somewhere else in the document, but the reverse is not required. It is valid, and perhaps useful, to have "naked" resource identifier objects that don't correspond to a resource representation in the same document.

Though my interpretation could be wrong too...

**Comment by scott-mcdonald** [comment]
@csantero I re-read the full linkage part of the specification and you may be right... I believe though most developers would expect if a resource is referenced via a resource identifier in the data section of a relationship it would appear somewhere in the document (primary or included sections) to make the document "complete" and "atomic", but I would be interested to hear what others think and the original intent from the specification owners...

**Comment by ethanresnick** [comment]
The intent as I understand it is what @csantero described. That said, I'd be open to any ideas for making the wording clearer.

> I believe though most developers would expect if a resource is referenced via a resource identifier in the data section of a relationship it would appear somewhere in the document (primary or included sections)  to make the document "complete" and "atomic"

I think I understand what you're saying (i.e., that some people might expect "if there's a resource identifier object, I should be able to match that to a resource within the document"), and it'd be perfectly reasonable to build an API that functions that way (and so returns links rather than resource identifier objects for resources that aren't included). I think our intention though was always that resource identifier objects could be useful on their own, to tell clients if the relationship's contents have changed, even if the referenced resources aren't included.

**Comment by dgeb** [comment]
The relevant verbiage re: "full linkage" is:

> Compound documents require "full linkage", meaning that every included resource MUST be identified by at least one resource identifier object in the same document. These resource identifier objects could either be primary data or represent resource linkage contained within primary or included resources.

The example is not in violation, as @ethanresnick and @csantero have said, so I'm going to close this now. But please open a fresh issue or PR if you have ideas to improve the clarity of the wording.
