### ISSUE TITLE
Require relationship links

### ISSUE THREAD

**Issue by lukasoppermann** [json-api/json-api#1027]
I did not find anything mentioned about if/when `relationship links` **MUST** be returned.

Personally I would suggest that they should always be required to be returned, as long as it is not a `sparse fields` request. The json format for those links is already defined in the specs.

```
"relationships": {
  "tags":{
    "links": {
      "self": "/articles/1/relationships/tags",
      "related": "/articles/1/tags"
    }
  }
},
```

This would make apis more discoverable and the additional payload is not really that huge.

**Comment by ethanresnick** [comment]
Returning relationship links is definitely a best practice, but we decided in 1.0 not to make any `links` required (since some people still don't grok hypermedia). And, now that 1.0 is finalized, we can't make this a MUST without violating our compatibility promises. That said, I'd be very open to a recommendation (for the recommendations page) that encourages people to use links. Would you be willing to work up a PR for that?

**Comment by lukasoppermann** [comment]
Hey @ethanresnick, that sounds pretty good. I will work on a PR for that. 👍

**Comment by lukasoppermann** [comment]
Closing due to #1031
