### ISSUE TITLE
Numeric data types

### ISSUE THREAD

**Issue by deividaspetraitis** [json-api/json-api#1084]
Hello,

I'm confused a little bit about numeric data types. 
In all examples I've seen so far including official docs & examples ( http://jsonapi.org/examples/ ) numeric types is casted as strings. 
Is it a rule to cast everything as a strings including numeric data types? If so, why is it? Why we can't return numbers as numbers and strings as strings?

Thanks.

**Comment by steveklabnik** [comment]
I just skimmed the examples, but it looks like every bit of numeric data was for an ID. IDs must be strings, but 

> Attributes may contain any valid JSON value.

So when describing your resources, if they contain numeric data, you can store them as a number, just fine.

(Since this isn't a bug in the spec, I'm going to give it a close. Thanks!)

**Comment by deividaspetraitis** [comment]
Thanks @steveklabnik!
