### ISSUE TITLE
Valid blank relationship?

### ISSUE THREAD

**Issue by richmolj** [json-api/json-api#1092]
Per the docs:

> The value of the relationships key MUST be an object (a “relationships object”)
> A “relationship object” MUST contain at least one of the following:

And then specifies `data`, `links`, and `meta`.

However, both of the following seem incorrect according to that documentation, but pass schema validation:

`relationships: { author: {} }`
`relationships: { author: null }`

My question is: are either of these responses actually considered valid? Should the documentation or schema be improved to reflect this?

**Comment by dgeb** [comment]
@richmolj Good catch! Neither value is valid and the schema should be updated to reflect this.

**Comment by richmolj** [comment]
@dgeb thanks for the clarification!

As a quick follow-up, we are discussing this over at AMS - let's say I'm requesting `/posts`. And we _could_ sideload comments, but for this request we're not. And no `link` is available for comments.

Ideally I'd like to tell the consumer "the 'comments' relationship exists, but this response doesn't contain any information about it". I am thinking the best way to do this would be to respond with:

`relationships: { comments: { meta: {} } }`

Sound about right?

**Comment by ethanresnick** [comment]
If no link is available, then `relationships: { comments: { meta: {} } }` seems reasonable. If a link is available, I think `relationships: { comments: { links: {/*self or related*/} } }` would be preferable, of course.

**Comment by NullVoxPopuli** [comment]
@ethanresnick what should be the default in this scenario? should 

`relationships: { comments: value }`
where value could be `{ data: {} }`, `{ meta: {} }`, or `{ links: {} }` ?

which one means what?

**Comment by richmolj** [comment]
PR to fix the schema: https://github.com/json-api/json-api/pull/1094

**Comment by ethanresnick** [comment]
@NullVoxPopuli 

>  what should be the default in this scenario? should
> 
> relationships: { comments: value }
> where value could be { data: {} }, { meta: {} }, or { links: {} } ?

`data` and `links` are generally more useful than `meta`, because they tell the client either what resources are in the relationship, or where to go to look that up.  So I'd prefer those keys. 

That said, `{data: {}}` is not a valid value; if you're trying to express an empty relationship `data: null` is the way to do that. (The `data` key in a relationship object holds [resource linkage](http://jsonapi.org/format/#document-resource-object-linkage).)

If you don't want to provide info in `data` (e.g. because it's too much work to fetch it, and clients are unlikely to need it), then provide links, so clients can fetch it manually if needed. 

If you don't want to provide `data` and `links`, as in @richmolj's case (e.g. because you don't want the comments to be fetchable directly, but only by using `?include`), then just providing a relationship object with a `meta: {}` key is a decent way to indicate the presence of a relationship.
