### ISSUE TITLE
[Proposal] Compact include query parameter

### ISSUE THREAD

**Issue by beauby** [json-api/json-api#1130]
Currently, the `include` query parameter accepts a tree, represented by a comma-separated collection of paths, each represented by a dot-separated list of relationship labels. This representation leads to overly-verbose descriptions.

Example:
`?include=posts.comments.author,posts.comments.tags,posts.comments.likes,posts.comments.replies`

This could be represented by the more compact:
`?include=posts.comments.(author,tags,likes,replies)`

which would work exactly the same way as the `{foo,bar,baz}` shell expansions.

**Comment by bf4** [comment]
@beauby `(` and `)` are reserved characters. My notes (after [searching through the spec](https://github.com/json-api/json-api/issues/363)):

<pre>
All member names used in a JSON API document 
MUST be treated as case sensitive by clients and servers,
 and they MUST meet all of the following conditions:

Member names MUST contain at least one character.
Member names MUST contain only the allowed characters listed below.
Member names MUST start and end with a "globally allowed character", as defined below.

To enable an easy mapping of member names to URLs, it is RECOMMENDED that member names use only non-reserved, URL safe characters specified in RFC 3986.
http://tools.ietf.org/html/rfc3986#page-13

Allowed Characters


The following "globally allowed characters" MAY be used anywhere in a member name:

  U+0061 to U+007A, "a-z"
  U+0041 to U+005A, "A-Z"
  U+0030 to U+0039, "0-9"
  U+0080 and above (non-ASCII Unicode characters; not recommended, not URL safe)

Additionally, the following characters are allowed in member names, except as the first or last character:

  U+002D HYPHEN-MINUS, "-"
  U+005F LOW LINE, "_"
  U+0020 SPACE, " " (not recommended, not URL safe)

Reserved Characters

The following characters MUST NOT be used in member names:

  U+002B PLUS SIGN, "+" (used for ordering)
  U+002C COMMA, "," (used as a separator between relationship paths)
  U+002E PERIOD, "." (used as a separator within relationship paths)
  U+005B LEFT SQUARE BRACKET, "[" (used in sparse fieldsets)
  U+005D RIGHT SQUARE BRACKET, "]" (used in sparse fieldsets)
  U+0021 EXCLAMATION MARK, "!"
  U+0022 QUOTATION MARK, '"'
  U+0023 NUMBER SIGN, "#"
  U+0024 DOLLAR SIGN, "$"
  U+0025 PERCENT SIGN, "%"
  U+0026 AMPERSAND, "&"
  U+0027 APOSTROPHE, "’"
  U+0028 LEFT PARENTHESIS, "("
  U+0029 RIGHT PARENTHESIS, ")"
  U+002A ASTERISK, "*"
  U+002F SOLIDUS, "/"
  U+003A COLON, ":"
  U+003B SEMICOLON, ";"
  U+003C LESS-THAN SIGN, "<"
  U+003D EQUALS SIGN, "="
  U+003E GREATER-THAN SIGN, ">"
  U+003F QUESTION MARK, "?"
  U+0040 COMMERCIAL AT, "@"
  U+005C REVERSE SOLIDUS, ""
  U+005E CIRCUMFLEX ACCENT, "^"
  U+0060 GRAVE ACCENT, "`"
  U+007B LEFT CURLY BRACKET, "{"
  U+007C VERTICAL LINE, " "
  U+007D RIGHT CURLY BRACKET, "}"
  U+007E TILDE, "~"
  U+007F DELETE
  U+0000 to U+001F (C0 Controls)


For API-specific query parameters (i.e. those not defined by JSON API),
a server may choose to ignore an invalid parameter and have the request succeed,
rather than respond with an error.
API-specific query parameters MUST adhere to the same rules as member names
AND MUST contain at least one non a-z character (U+0061 to U+007A).
It is RECOMMENDED that a
  U+002D HYPHEN-MINUS, "-",
  U+005F LOW LINE, "_", or
  capital letter
is used (e.g. camelCasing).
http://jsonapi.org/format/#query-parameters

Implementation specific query parameters MUST adhere to the same constraints as member names 
with the additional requirement that they MUST contain at least 
  one non a-z character (U+0061 to U+007A). 
It is RECOMMENDED that a 
  U+002D HYPHEN-MINUS, “-“, 
  U+005F LOW LINE, “_”, 
  or capital letter is used (e.g. camelCasing).
</pre>

I tried to make a regex once but didn't finish

```ruby
member_name.size > 0
member_name =~ /\A#{globally_allowed_character}#{allowed_characters}*#{globally_allowed_character}?\z/
globally_allowed_character = /([\u{0061}-\u{007A}]|[\u{0041}-\u{005A}]|[\u{0030}-\u{0039}])/
globally_allowed_character_not_url_safe_not_recommended = /[\u{0080}-]/
allowed_characters = /([\u{0061}-\u{007A}]|[\u{0041}-\u{005A}]|[\u{0030}-\u{0039}]|\u{002D}|\u{005F}|\u{0020})/
reserved_characters = /(\u{002B}|\u{002C}|\u{002E}|\u{005B}|[\u{0021}-\u{002A}]|\u{002F}|[\u{003A}-\u{0040}]|\u{005C}|\u{005E}|\u{0060}|[\u{007B}-\u{007F}]|[\u{0000}-\u{001F}])/
j
implementation_specific_query_parameters =~ member_name && 
  implementation_specific_query_parameters =~ /[\u{0061}-\u{007A}]/
recommended_implementation_specific_query_parameters =~ /\u{002D}|\u{005F}|[A-Z]/
```

**Comment by bf4** [comment]
though I guess arguably that's for this scenario...

**Comment by beauby** [comment]
@bf4 I believe the reserved characters apply to the query parameter, not its value. Anyways, the proposal is more on the principle than on the exact syntax.
