### ISSUE TITLE
routing for updating multiple records

### ISSUE THREAD

**Issue by dplummer** [json-api/json-api#116]
What's the proper RESTful routing for an update to multiple child resources? Say a user has a cart with multiple line items. They're viewing their cart and decide they want to buy 5 of each of their 3 items.

Either the client could make 3 separate requests:

```
PATCH /cart/line_items/1
[{"op": "replace", "path": "/cart/0/line_items/1/qty", "value": 5}]

PATCH /cart/line_items/2
[{"op": "replace", "path": "/cart/0/line_items/2/qty", "value": 5}]

PATCH /cart/line_items/3
[{"op": "replace", "path": "/cart/0/line_items/3/qty", "value": 5}]
```

Or a single request to the cart:

```
PATCH /cart
[{"op": "replace", "path": "/cart/0/line_items/1/qty", "value": 5},
{"op": "replace", "path": "/cart/0/line_items/2/qty", "value": 5},
{"op": "replace", "path": "/cart/0/line_items/3/qty", "value": 5}]
```

The second proposal of a single patch makes more sense to me (except the /0/ for a singleton resource).

Can you clarify?

**Comment by dplummer** [comment]
Oh, re-reading the JSON PATCH RFC I think I got the /0/ wrong - looks like the correct "path" would just be "/cart/line_items/1/qty" since that's the path of in the JSON.

**Comment by guillec** [comment]
JSON Patch is a subject that keeps coming up a lot in the issues, its something that still needs to be discussed more by the group. 

In summary the difficulty is JSON API docs specify that, "While to-many relationships are represented as a JSON array, they are updated as if they were a set."

But the JSON Patch RFC doesn't have a "set-like" behavior. https://github.com/json-api/json-api/issues/100

With that taken care of, I would say your second sample ( PATCH /cart ) should be fine since that is what JSON Patch is for, to perform multiple operations on one document.

This is what your target document would look like if you were using the "cart/0/line_items/1/qty" path and sticking to the JSON Patch RFC:

{ cart: [{ line_items: [ { qty: 3 }, { qty: 2 } ] }] }

For "cart/line_items/1/qty" it should look like this if sticking to the RFC

{ cart: { line_items: [ { qty: 2 }, { qty: 1 }, { qty: 4 } ] } }

One thing to keep in mind is when using "replace" according to the RFC the item must exist in order for the operation to be successful.

Hope I was helpful!

**Comment by dplummer** [comment]
Thanks! That does help a lot. Is this something that should be distilled into the docs?

**Comment by dgeb** [comment]
Details are now covered in both the [updating relationships section of the base spec](http://jsonapi.org/format/#crud-updating-relationships) and the new [Patch extension](http://jsonapi.org/extensions/patch/).
