### ISSUE TITLE
Offset pagination context in consecutive requests

### ISSUE THREAD

**Issue by TrevorHinesley** [json-api/json-api#1163]
It's very possible I'm missing something.. but if I were to use limit and offset pagination:

1. How would first/last links be generated? Let's say the offset is 2 and limit is 6. Is the first link going to have offset 0 and limit 2?

2. How would consecutive requests know the previous request's context? For instance, assume the example above. Once I go to the first page, how would I know to make the next link have offset 2 and limit 6 rather than offset 2 and limit 2?

**Comment by beauby** [comment]
Basically all the spec requires is that you send pagination-related parameters via the `page` query parameter – the rest is up to you. You can do something like `POST /articles?page[offset]=0&page[limit]=6`.

**Comment by ethanresnick** [comment]
@beauby is right that the spec just leaves this up to you.

Here's how I think about the situation, though: if the client knows how to set the offset and limit values, it should do that directly and ignore the links; a client that's following links should be doing so precisely because it doesn't know how to set the offset and limit manually, because it treats the server's urls as opaque. In the case of a client that only follows links, then, the server has full control over the values of offset and limit, because it gets to set them whenever first it links into the paginated set — most likely on the first page. It can use that control to ensure that the offset is always a multiple of the limit, in which case the problems you're describing go away. Likewise, the problem goes away if the client always sets the values manually. So, this problem only occurs for clients that sometimes set offset/limit manually and sometimes follow links, which strikes me as odd behavior.

All that said, my answers to your questions would be:

>  Let's say the offset is 2 and limit is 6. Is the first link going to have offset 0 and limit 2?

Yes.

> How would consecutive requests know the previous request's context? For instance, assume the example above. Once I go to the first page, how would I know to make the next link have offset 2 and limit 6 rather than offset 2 and limit 2?

I don't think it's worth it/a good idea for the subsequent request to know about the previous request's context, and so I would just give the next link an (offset, limit) of (2, 2) rather than (2, 6). Yes, this is somewhat problematic, because it means that a client that directly jumped to offset 2 with limit 6, then used the `prev` link to go back a page, and then the `next` link to go forward, wouldn't end up where it started. But: 1) per the above, this should never happen in practice for a client that only follows links; and 2) this "problem" seems like an almost inevitable function of the overlapping pages allowed by offset limit pagination. A server that wants to prevent it could error if the offset isn't a multiple of the limit—but, at that point, you've re-invented (page_size, page_num) pagination instead of the (more-flexible) offset/limit scheme. Ultimately, I'd say that the solution for this is for the client to simply be consistent about always constructing the url itself using its knowledge of the pagination scheme.
