### ISSUE TITLE
HEAD ?

### ISSUE THREAD

**Issue by Inkimar** [json-api/json-api#1167]
Hello,

I cannot find any references to HEAD in your specification.
I find the following 

> " The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request. This method can be used for obtaining metainformation about the entity implied by the request without transferring the entity-body itself. This method is often used for testing hypertext links for validity, accessibility, and recent modification. " 

ref : https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html 

Would it be good to have a section on HEAD underneath the http://jsonapi.org/format/#fetching ?

regards, i

**Comment by ethanresnick** [comment]
@Inkimar As you pointed out, HTTP itself already specifies that the HEAD response should be exactly the same headers as a GET response, with no response body. So, since JSON:API specifies the GET response already, I'm not sure we have to specify the HEAD response explicitly. What would you want our specification to say about HEAD?
