### ISSUE TITLE
[Proposal] Compound documents: `included` should be an object

### ISSUE THREAD

**Issue by adam-lynch** [json-api/json-api#1170]
> In a compound document, all included resources **MUST** be represented as an array of resource objects in a top-level `included` member.

\- [Compound Documents](http://jsonapi.org/format/#document-compound-documents)

Why does it need to be an array? Why couldn't `included` contain nested objects instead? I.e. `included` would be an object in which each key is a `type` and the value is an an object which maps `id`s to resource objects.

### Relevant quotes from the spec

- >A resource object **MUST** contain at least the following top-level members: 
  >- `id`
  >- `type`
  
  \- [Resource Objects](http://jsonapi.org/format/#document-resource-objects)
- >A “resource identifier object” **MUST** contain `type` and `id` members.
  
  \- [Resource Identifier Objects](http://jsonapi.org/format/#document-resource-identifier-objects)
- >A compound document **MUST NOT** include more than one resource object for each `type` and `id` pair.
  
  \- [Compound Documents](http://jsonapi.org/format/#document-compound-documents)

### Examples

Instead of this (example from [Compound Documents](http://jsonapi.org/format/#document-compound-documents)):

```json
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "5",
    "attributes": {
      "body": "First!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    },
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "attributes": {
      "body": "I like XML better"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    },
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
```

It could be like this:

```json
"included": {
  "comments": {
    "5": {
      "type": "comments",
      "id": "5",
      "attributes": {
        "body": "First!"
      },
      "relationships": {
        "author": {
          "data": { "type": "people", "id": "2" }
        }
      },
      "links": {
        "self": "http://example.com/comments/5"
      }
    },
    "12": {
      "type": "comments",
      "id": "12",
      "attributes": {
        "body": "I like XML better"
      },
      "relationships": {
        "author": {
          "data": { "type": "people", "id": "9" }
        }
      },
      "links": {
        "self": "http://example.com/comments/12"
      }
    }
  },
  "people": {
    "9": {
      "type": "people",
      "id": "9",
      "attributes": {
        "first-name": "Dan",
        "last-name": "Gebhardt",
        "twitter": "dgeb"
      },
      "links": {
        "self": "http://example.com/people/9"
      }
    }
  }
}
```

#### Pros

- As a consumer of the API, I won't ever have to loop over *n* entities of irrelevant `type`s.
- As a consumer of the API, it's easier to get an entity by ID.
- As a consumer of the API, it's easier  to check if an entity exists in the object (kind of the same as the last point). 

  Why wouldn't it exist? `relationships` support pagination (correct me if I'm wrong).
- As a consumer of the API or an API developer, it's more obvious that only one entry per `id` exists in the object / per `type`, due to the nature of objects. 
  
  I know this is a small thing but "don't make me think!" (or read the specification) 😄.
- As an API developer, it's no longer possible to accidentally put duplicates in `included`, due to the nature of objects.
- ~~As a consumer of the API or an API developer, `included` would be more consistent with `relationships`; for example (from [Relationships](http://jsonapi.org/format/#document-resource-object-relationships)):~~
  

  ```json
  "relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": "http://example.com/articles/1/author"
      },
      "data": { "type": "people", "id": "9" }
    }
  }
  ```

  ~~`relationships` is also a nested object, although a key difference still remains; the keys in `relationships` can be arbitrary (correct me if I'm wrong) whereas the keys in my proposal for `included` must match the `type` of resource objects.~~
  
  *Update*: nevermind, I misunderstood something about `relationships`.

#### Cons

- If `id`s are numbers, dealing with string numbers isn't nice.

  You don't have to use the key if you don't want; the `id` still exists within the resource object (as a number if you implement it that way). `id`s aren't always numbers anyway and the example from the specification even has string numbers *within* the resource object, so I don't think this is a valid concern.
- Something I'm missing?

**Comment by smrgeoinfo** [comment]
I'm new to the is spec and haven't studied it, but based on what you quote ("A compound document MUST NOT include more than one resource object for each type and id pair."),  an ID could repeat if it was bound to a different type, but an object can repeat the same key, so your example would break down.  Maybe I'm misunderstanding something.  It does seem odd that the spec doesn't require an object ID to be unique within a document.

**Comment by adam-lynch** [comment]
@smrgeoinfo I'm not sure if I understand you correctly. Are you talking about a situation like this?

```json
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "9",
    "attributes": {
      "body": "First!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    },
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "attributes": {
      "body": "I like XML better"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    },
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
```

The first two included entities have the same IDs but different types. This is how it would look like according to what I'm proposing:

```json
"included": {
  "comments": {
    "5": {
      "type": "comments",
      "id": "5",
      "attributes": {
        "body": "First!"
      },
      "relationships": {
        "author": {
          "data": { "type": "people", "id": "2" }
        }
      },
      "links": {
        "self": "http://example.com/comments/5"
      }
    },
    "9": {
      "type": "comments",
      "id": "9",
      "attributes": {
        "body": "I like XML better"
      },
      "relationships": {
        "author": {
          "data": { "type": "people", "id": "9" }
        }
      },
      "links": {
        "self": "http://example.com/comments/12"
      }
    }
  },
  "people": {
    "9": {
      "type": "people",
      "id": "9",
      "attributes": {
        "first-name": "Dan",
        "last-name": "Gebhardt",
        "twitter": "dgeb"
      },
      "links": {
        "self": "http://example.com/people/9"
      }
    }
  }
}
```

It's still possible because there's an object per type. 

---

P.S.

> It does seem odd that the spec doesn't require an object ID to be unique within a document.

I guess this is because a typical database design behind the API would contain a table per type with auto incremented ID columns.

**Comment by ethanresnick** [comment]
This has been discussed many times and, frankly, I agree with you that it probably would have made more sense to do things in the way you describe. At this point, though, changing the format of "included" to be an object rather than an array would break all consumers that expect it to be an array, and that breakage would go against our backwards-compatibility promises now that the spec is at 1.0.

I think the best we could do is introduce some new functionality (e.g., a new query param) that let's clients opt-in to receiving the includes in object format. I'm not totally opposed to that, but such a new feature would probably have to solve other problems at the same time to justify the complexity.

**Comment by adam-lynch** [comment]
@ethanresnick yeah, that's fair 👍

**Comment by dgeb** [comment]
> Something I'm missing?

I'm sure I've explained this in the past, but am having trouble finding my explanation, so here it goes... 

The spec goes to lengths to avoid repetition in the document. Resources that are included as primary `data` must not be repeated in `included`. This means that you can't reliably find resources in `included` - linked resources could also be in `data`. Imagine a search for people that includes friends - the same `people` resources might be included in either `data` or `included`. Of course, `data` must be an array, because it is sorted. It follows that it is essential to have a processing step to match up the linkage. Acceptance of this processing step is key to understanding the design rationale.

I accept that some servers might want to allow their clients to choose repetition to avoid extra processing. To handle those clients, I can foresee an option to `embed` instead of `include` - in other words, related records could be embedded in relationships rather than included in a separate collection. I'm willing to explore this as a client opt-in (i.e. never default) option.

**Comment by jamesplease** [comment]
Thanks for the explanation, @dgeb , but I think I may still be missing something. As I understand it, your comment can be summed up as:

The processing step is required either way, unless we add duplication to the document.

You're right here, but I think there are improvements to the document format even without adding duplication, because the loop over `included` would go away with this change. So although the processing step doesn't go away completely, it seems like it does get simpler, which I think is a good thing.

I would expect a justification for the array over the object syntax to involve there being some use case involving ordering of the resources within `included`, but I don't think that there is this use case. So the object syntax proposed here seems like an improvement all-around.

Do you agree with that, or am I misunderstanding?

Either way, I agree with @ethanresnick 's suggestion that it'd be best to only add this if it comes with some additional features, just to keep the spec lean.

**Comment by ethanresnick** [comment]
> You're right [that a processing step would still be needed], but I think there are improvements to the document format even without adding duplication, because the loop over included would go away with this change.

I agree with this.

I've also heard that `included` being an array causes problems for folks in statically typed languages, who have no problem typing the `data` array (because all resources in it are of the same type in their usage), but do have problems with the `included` array because its resources are of mixed types. An `included` object that segregated resources by type would have prevented this. Alas, this ship has probably sailed, and/or I may still be missing something.

**Comment by dgeb** [comment]
> I've also heard that included being an array causes problems for folks in statically typed languages, who have no problem typing the data array (because all resources in it are of the same type in their usage), but do have problems with the included array because its resources are of mixed types.

It is possible in a number of statically typed languages to define a union of possible types for a value, and then to differentiate between them based upon `type`.

Regardless, I do not see how this problem is unique to `included` and not `data`. Keep in mind that polymorphic relationships can exist, which lead to mixed type collections in `data` as well.

> Alas, this ship has probably sailed, and/or I may still be missing something.

Right. We can't re-litigate this for `included` because we are committed to backwards compatibility post 1.0. All I can do is provide the rationale used to arrive at the decision. Going forward we can consider alternatives to achieve different objectives (like the `embed` idea). I understand the tradeoff of minimizing processing in favor of allowing duplication, and personally think that an `embed` solution achieves this far better than a half measure to minimize processing to some extent. But I understand others may weigh tradeoffs differently and this can be frustrating. For instance, I've often wondered whether allowing polymorphism has been worth the complexity, but many others felt it was worth it which is why it's allowed in the spec.

**Comment by ethanresnick** [comment]
Yeah, I also don't want to rehash known tradeoffs in the current design—that's a waste of time. 

If there are new issues with the design that we discover, or the tradeoffs look different with time, those seem worth putting on the table, though, to see how we can move forward in a backwards-compatible way. My impression was that the static typing challenges around `included` were such an issue. (I don't remember them coming up pre 1.0, though maybe I just missed it.)

Anyway, none of us seem to be advocating changes at this point or saying the issues with `included` are particularly big, so it's all a bit hypothetical.

> Regardless, I do not see how this problem is unique to included and not data. Keep in mind that polymorphic relationships can exist, which lead to mixed type collections in data as well.

Again, don't want to get too in the weeds on this but, from what I remember, the folks I talked to about this just made sure their relationships/collections weren't polymorphic. Re tagged unions, I believe they were trying to write a client in Java, which has had pretty bad support for those iiuc (though I think later versions + some new libraries improve the picture).

**Comment by dgeb** [comment]
Thanks for the discussion. I think we need to close this for lack of tractable action on the proposal - but please reopen if you feel otherwise. 

Again, I'm personally open to considering new options that allow clients to opt-in to accepting more duplication for less processing.
