### ISSUE TITLE
Is json-api development... dead?

### ISSUE THREAD

**Issue by approxit** [json-api/json-api#1190]
Those, who implemented JSON-API in their Web API, know that this specification totally overkills all its competitors since end of may 2015. Its concept fixes tons of use cases and has many implementations.

But... Now, 2 years after 1.0 release, nothing important happened. 1.1 release is still "upcoming". Vast usage catches areas uncovered by spec which issues are without much response (relationship pagination, resource actions, sparse fields on meta fields, O(1) includes). Proposals are hanging without any attention.

The only thing that is updated is... implementation list PRs.
That's very sad.

It's only me, or this project is really starving?

In my opinion JSON-API is the best thing that could happen to JSON based Web API format. Right now I feel that we already have 2 years loss of its development. How can we push more life to it?

**Comment by remmeier** [comment]
I would also favor a few updates from  the spec side as various implementations seem to be in a very healthy state.

**Comment by jamesplease** [comment]
@approxit the authors appear to have been busy for some time, yes, but just a few days ago @ethanresnick posted in an issue that he’s got time to work on this again with the goals of solving some of the big outstanding questions. Perhaps we’ll see a release from that.

I don’t think the project is dead, though. Another author, @dgeb , comments on issues and merges PRs every now and again.

**Comment by steveklabnik** [comment]
Hi there!

It's not truly dead, but we *do* have a lack of time and energy, generally. @dgeb and I are still planning on doing some kind of work on the spec, but have been busy with other things.

In general, if some other people are interested in coming on as editors, I think that'd be great; I haven't had the energy to actually make a call for contributors.

**Comment by ballPointPenguin** [comment]
I for one find the slowness of movement in this project to be quite refreshing. The stability and completeness of the 1.0 spec has been a calm island in a churning sea of libraries.

**Comment by dgeb** [comment]
I agree that it's been a while since much work has surfaced publicly here. However, I'm glad to say that's beginning to change.

@ethanresnick has resumed his hard work on profile extensions - see https://github.com/json-api/json-api/pull/1196

Personally, I've reserved some significant time over the next few weeks to work on the spec, including long discussed and overdue work on "operations".

> I for one find the slowness of movement in this project to be quite refreshing. The stability and completeness of the 1.0 spec has been a calm island in a churning sea of libraries.

@ballPointPenguin Thanks for this <3 It's very important that we keep this in mind post-1.0 and proceed with care in order to maintain this stability.

Last but not least, I agree with @steveklabnik - feedback and involvement from the community is welcomed and encouraged.

More to come very soon ...

**Comment by dgeb** [comment]
Thanks for everyone's concern for the health of the spec. I'm going to close this now, but feel free to continue to ask questions here or at http://discuss.jsonapi.org/

**Comment by approxit** [comment]
Thank you very much for responses.

Now I'm pretty sure that JSONAPI will wake up from sleep and take big breath.
There is lots of work to do!
