### ISSUE TITLE
Add support for persisted queries

### ISSUE THREAD

**Issue by raderio** [json-api/json-api#1239]
Add support for persisted queries like in GraphQL
https://dev-blog.apollodata.com/persisted-graphql-queries-with-apollo-client-119fd7e6bba5
https://dev-blog.apollodata.com/5-benefits-of-static-graphql-queries-b7fa90b0b69a

This could saving bandwidth between the client and server by only sending a query ID or hash instead of an entire "include" query, also will improve "include" parsing performance.

**Comment by beauby** [comment]
This is basically what an endpoint is, no?

**Comment by raderio** [comment]
Nope.
Instead of for example `include=author&fields[articles]=title,body&fields[people]=name` we can send only `qid=xxxxxxxxx`

**Comment by ethanresnick** [comment]
I'm pretty sure this is already supported in a natural enough way:

Define a "queries" collection. `POST /queries` lets the user create a saved query and returns its id. `GET /queries/` or `GET /queries/:id` lists saved queries. Each query object has attributes describing the query and a single `results` relationship. That relationship is probably returned with jus a `related` link rather than `data` when you just do `GET /queries/:id`. Then, to use a query, do `GET /queries/:id?include=results`.

Does that work?

**Comment by jelhan** [comment]
Thanks a lot @ethanresnick for showing how this could be achieved within the existing specification!

I think this issue could be closed as no further questions have come up in the last years. Please speak up if you disagree.
