### ISSUE TITLE
Clarify 204 case for updating to-many relationships

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#1259]
Right now, under the section about updating to-many relationships, the spec [says](http://jsonapi.org/format/#crud-updating-to-many-relationships): 

> A server **MUST** return a `204 No Content` status code if an update is
successful and the representation of the resource in the request matches the
result.
>
> > Note: This is the appropriate response to a `POST` request sent to a URL
from a to-many [relationship link][relationships] when that relationship already
exists. It is also the appropriate response to a `DELETE` request sent to a URL
from a to-many [relationship link][relationships] when that relationship does
not exist.

The normative text simply seems wrong here — there is no "representation of the resource" in the request, so the MUST would never apply under a literal reading. The non-normative note doesn't seem right either (it talks about whether the relationship "exists", but presumably the relationship must exist or the url would trigger a 404). 

My best guess, based on the text for the 200 case, is that the intended meaning is: if the modification of the relationship succeeds, and the server doesn't change the relationship beyond adding/removing the specified resources to/from it, the server MUST return 204. Is that right?

If so, *requiring* a 204 in that case doesn't really seem to make sense. We usually use 204 when the client's representation is known to be still up to date, but the server here has no idea what state the client has for the relationship (since the client only sent the linkage to add/remove; it could've fetched the relationship who knows how long ago). So, my thought here is that we want to leave it up to the server to return either a 200 or a 204 (with the spec possibly saying one is a SHOULD).

Given all the above, what do we actually want the behavior to be, and how can we clarify/tweak the spec to say that?

**Comment by gabesullice** [comment]
We just dealt with this exact issue in detail here: https://www.drupal.org/project/jsonapi/issues/2977659

Don't pay attention to the suggestions in the issue summary. The patch in comment [#39](https://www.drupal.org/project/jsonapi/issues/2977659#comment-12728585) has the final, working set of rules we adopted.

We tackled the problem by creating 3 "sets" of resource identifiers, the incoming set, the current set and the final set. To determine what needs to be added or removed we either intersect or diff these sets. For removals, we intersect the incoming and current set. For additions, we diff the incoming and current set and add those.

To determine if we should respond with 200/204, we diff the incoming set with the final set. If there are differences, we respond with 200 and the full final set. Otherwise, 204 No Content.

**Comment by jelhan** [comment]
This has been addressed in v1.1:

> If an update is successful and the server doesn’t change the targeted relationship in ways other than those specified by the request, the server MUST return either a 200 OK status code and response document (as described above) or a 204 No Content status code with no response document.

Closing this issue.
