### ISSUE TITLE
FYI: empty string allowed as an id

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#1261]
Unless I'm overlooking something, JSON:API currently seems to allow the empty string as a resource's id. We may want to note this or disallow it (which is probably acceptable as a breaking change).

**Comment by joananeves** [comment]
This is a very good point, and my first thought was to agree that it should be disallowed, but I'm not so sure...
Although we are not using empty string identifiers, allowing it would be a good way to grant a single object response.

At my current company, we've implemented JSON:API for PostgreSQL using SPI, and last week we had a problem because we were being too restrictive for the resource id. We are using ragel to parse the URL, and I was using for the resource identifier the same rule that was defined to match member names.
I've checked JSON:API specification and could not find any specific restrictions, so ended up checking RFC 3986.
It seems now that I didn't check properly, because when I fixed the characters restrictions, I kept the assumption that an id should have at least one character...
We have some resources, used to report latest data, where it made more sense for us to always return a single object response, and to grant that we are using a phony identifier (because of that non-empty string assumption) which is just being ignored.

**Comment by freddrake** [comment]
Making the empty string invalid as an id would be backward incompatible.

I also don't see a problem with keeping it valid; if you don't use it, then the value becomes invalid in your application because it doesn't refer to anything anyway.

I have an application where I specifically chose to use the empty string as id for a "api root" object.  Since JSON:API (rightly) does not define the URLs for an application, an application is going to want a set of root URLs for various collections.  I then provide a resource with a known URL that clients can use to locate everything else they need.  Since there's only one instance of the type, there's no particular value in giving it anything interesting as an id.  At that point, making it small seems best.

I think this issue can be closed.

**Comment by freddrake** [comment]
@gabesullice ?

**Comment by gabesullice** [comment]
I agree that it would be a backward incompatible change. I think we need to figure out a procedure for noting things that we aren't going to fix for BC reasons, but which we want to fix in a new major version.

**Comment by gabesullice** [comment]
badabingbadaboom
