### ISSUE TITLE
what to do if a relationship link returns no data yet

### ISSUE THREAD

**Issue by EduardoSolanas** [json-api/json-api#1289]
My question is, what to do if a relationship link returns no data ? (example a price for a product)

Should we keep the link even though the response is going to be empty?
Should we remove the relationship link only if there is no data ?

At the moment we are removing the relationship when there is no data yet, so clients can save an extra call if there is nothing to retrieve.
But that means for every get even without the include param, we have to gather all the relationships data to build the relationships or not, adding a lot of unnecessary latency to just a simple get with no include params.

I have been reading the JsonApi spec but I can't see any documentation about this kind of behaviour.

In my mind, if the customer wants for example a price for a product, should always call product with the include=price, so in the case where there is no price for that product, the customer should check the data section at the price relationship level, if there is no data there is no price.

If they don't pass any include=price, and they go via price relationship link and find no price, there is an extra call but I guess that is the risk they take not using include param?

Any thoughts?

Thanks

**Comment by ethanresnick** [comment]
In general, JSON:API usage questions are better posted on our [Discourse site](https://discuss.jsonapi.org/), but I'll take a stab at this here.

> In my mind, if the customer wants for example a price for a product, should always call product with the include=price... If they don't pass any include=price, and they go via price relationship link and find no price, there is an extra call but I guess that is the risk they take not using include param?

I agree with this. If the client wants to see the contents of a relationship right away (i.e., as the relationship is at the time of their request), they should use the include parameter. Not using `include` means two round trips, which is not great even if the relationship link does return some data.

The advantage of links, really, is that it gives the client the option to lazily fetch the relationship's value later, or to refetch it at any time without getting all the resource's attributes. From that point of view, if you're including links at all, I think it makes sense to include them unconditionally, because the relationship might no longer be empty when the client goes to fetch the link later. 

Hope that helps.
