### ISSUE TITLE
ID as string ?

### ISSUE THREAD

**Issue by waghanza** [json-api/json-api#1312]
Hi,

According to https://jsonapi.org/format/#document-resource-object-identification fields `id` **MUST** be `strings`.

However, as using a database, id are auto-generated (generally as `int`)

As `json` could be type for `int`, is it not legitimate to consider `id` as `int ` instead of `string`  ?

Regards,

PS : Same question here, https://github.com/woohoolabs/yin/issues/75

**Comment by senid231** [comment]
@waghanza Hi
id can be not only `integer`.  A lot of people use `uuid` or some custom slug string as id.
id *MUST* to be a string because each of types listed above can be cast to string on server and cast back to some other type on client (if needed). It doesn't cause any problem for languages with strict type system, and easy to use in other languages.

**Comment by waghanza** [comment]
@senid231 if some are using `string` because of `uuid`, it could be legit to have a requirements : `id` or `uuid`, no ?

`id` and `uuid` are **NOT** the same. `id` are auto-generated by a database system, and `uuid` are defined in https://tools.ietf.org/html/rfc4122

**Comment by ethanresnick** [comment]
JSON:API was trying to make it easier on consumers by having id always be a string. This avoids potential issues like [the problems with large integer ids in some languages](https://developer.twitter.com/en/docs/basics/twitter-ids.html). It also let's library author in statically-typed languages type `id` as `string` rather than as `string | number`; if it's typed as `string | number`, the user of the library may have to constantly add boilerplate to keep the type system happy if they know it's always gonna be one or the other.

Like @senid231, though, I'm not sure I see the problem here. If you want the type to be an `int` for your application logic, you can deserialize the `id`s to ints upfront, and then convert them back to strings at the end of any processing in your serialization layer.

**Comment by ethanresnick** [comment]
Closing. @waghanza If you feel this hasn't been addressed adequately, feel free to comment again and we can revisit.
