### ISSUE TITLE
Allow duplicated resources in compound documents?

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#1332]
Right now, the spec forbids multiple resource objects with same (type, id) from appearing together in a compound document. I think the theory is that allowing duplication could result in the same resource being sent with two different sets of fields: 

> Note: This approach ensures that a single canonical resource object is returned with each response, even when the same resource is referenced multiple times.

Also, deduping saves data over the wire.

However, neither of those rationale make much sense to me: if the spec can require that a resource not appear twice, it could just as easily require that, if it appears more than once, it must always appear with identical content; and, with gzipping, the extra data from duplication is probably not much of a problem.

Moreover, my sense is that this forced de-duping comes with a real cost for server implementations, which have to track all the resources in the response document as they build it, or do an O(n) traversal through the response before sending it. As an implementer, this has always seemed like more trouble than it's worth, and I've simply skipped doing that check.

So, what are we actually getting from this restriction? Is it really worth keeping?

Btw, re the spec requiring instead that "if a resource object appears more than once, it must always appear with identical content", that's only one option (and would be very easy for servers that do all their queries inside a transaction to guarantee, without extra overhead). Another option would simply be to tell the client to take the representation that occurs latest in the document.

**Comment by kocsismate** [comment]
Just another implementor's experience: in my server implementation, I solved this problem efficiently using a Map data structure where keys are the combination of the types and IDs (https://github.com/woohoolabs/yin/blob/4ad1bbe120ba4ba2e21dde77e63deb854cc87bc4/src/JsonApi/Schema/Data/AbstractData.php#L114).

Personally, I like this forced de-duping (however, it wasn't easy to achieve). But I think I'd have to track the resources anyway even if this rule wasn't in effect, because multiple resources can include the same related resource, so it makes sense to only do so once, and tracking is the way to go as far as I know.

**Comment by ethanresnick** [comment]
> I solved this problem efficiently using a Map data structure... I think I'd have to track the resources anyway even if this rule wasn't in effect, because multiple resources can include the same related resource, so it makes sense to only do so once

Even using a Map, you're still doing one check for every resource in the document (it's just that now that check is ~O(1) instead of O(n)). Maybe these checks are worth it; as you imply, there could be pretty big duplication otherwise, but I'm still not sure. I appreciate more implementer perspectives, though... that was my hope in opening this issue

**Comment by wimleers** [comment]
> if the spec can require that a resource not appear twice, it could just as easily require that, if it appears more than once, it must always appear with identical content; and, with gzipping, the extra data from duplication is probably not much of a problem.

Sounds sensible.

### Related
This was discussed previously, in https://github.com/json-api/json-api/pull/1156. But with a different purpose: rather than simplifying implementations or clarifying the spec, in Drupal there can be multiple relationships from a resource `X` to a resource `Y`. It's not common, but it's allowed, and it is used in real-world situations.

We implemented @beauby's recommendation posted at 
https://github.com/json-api/json-api/pull/1156#issuecomment-325377995. That was implemented in 
https://www.drupal.org/project/jsonapi/issues/2864680. This is also why @gabesullice opened 
https://github.com/json-api/json-api/issues/1361: to turn this into an official profile.

**Comment by gabesullice** [comment]
> Maybe these checks are worth it; as you imply, there could be pretty big duplication otherwise, but I'm still not sure.

This was never a problem to implement. And the performance concern is a micro-optimization. By the time one has enough data for the check's processing time to be even remotely noticeable, the response size would so enormous that it would likely take an unacceptable amount of time to download.

I always felt like this was a reasonable requirement to keep document size down, improving perceived frontend performance (like sparse field sets). IMO, this is not worth the effort.

**Comment by jelhan** [comment]
I agree that this constraint overall has more benefits than trade-offs. Especially it prevents the edge case of having the same resource included with different state or representation. Dealing with that case in client would be way more challenging than preventing duplicates at server. I'm going to close this. Feel free to comment anyways if you face noticeable issues implementing it. Will reopen if concerns are backed with additional data.
