### ISSUE TITLE
Omission of relationship data

### ISSUE THREAD

**Issue by michaelsw95** [json-api/json-api#1365]
Due to data constraints, I have a requirement to build a JSON API compliant endpoint which returns an entity without its related data. The user would then request the relationship data separately. For example:

Entity Request: `v1/myentity/{entity-id}`.

Entity Relationship Request: `v1/myentity/{entity-id}/items`.

My endpoint currently returns this when an entity request is made:

```json
{
  "data": {
    "attributes": {
      "foo": 2,
      "bar": 1
    },
    "relationships": {
      "items": {
        "links": {
          "self": "http://localhost:60000/v1/myentity/1/relationships/items",
          "related": "http://localhost:60000/v1/myentity/1/items"
        },
        "data": []
      }
    },
    "type": "myentity",
    "id": "1"
  }
}
```

As you can see the `data` property is an empty array. This is somewhat misleading because there are related `items`, we have just not included them in this response.

In this [section of the specification](https://jsonapi.org/format/#document-resource-object-linkage), it is noted that data must be represented in one of four ways. But I have not been able to find anything about whether it is required in this case.

Would it be possible for me to omit the data property from within relationships and still have a JSON API compliant response?

Would anyone be able to advise on whether or not I can omit the property? Or perhaps is there a better way I can meet the requirement (of not returning all the data at once) and comply with the specification which I am unaware of?

**Comment by gabesullice** [comment]
@MichaelHancock, great question!

You're perfectly "within your rights" to omit the `data` member from the relationship object (the object under `items`), because [the spec says](https://jsonapi.org/format/#document-resource-object-relationships):

> A  “relationship object” **MUST** contain at least one of the following:
> ...
> - `data`...
> - `links`...
> - `meta`...

Meaning it's perfectly acceptable for you to _only_ have a `links` member and no `data` member.

The only caveat is that if you support `?include=items`, then `data` must not be empty if you're including those related items. In fact, this is sometimes preferable!

<hr>

Thanks for reaching out in the issue queue. We'd love to hear about your project when it's complete! Let us know what worked/didn't work for you. Good luck!

**Comment by michaelsw95** [comment]
Thank you for clearing that up!
