### ISSUE TITLE
Are @-members really allowed everywhere?

### ISSUE THREAD

**Issue by lode** [json-api/json-api#1367]
Right now the spec states:

> @-Members **MAY** appear anywhere in a JSON:API document.

I can understand they can appear in places like these:

```json
{
	"@ignore": "foo",
	"data": {
		"@ignore": "foo",
		"type": "user",
		"id": "42",
		"attributes": {
			"@ignore": "foo",
			"foo": "bar"
		},
		"relationships": {
			"friend": {
				"@ignore": "foo",
				"data": {"type": "user", "id": "24"}
			}
		}
	}
}
```

Some others I would find them weird though:

```json
{
	"links": {
		"@ignore": "foo",
		"self": "https://..."
	},
	"data": {
		"type": "user",
		"id": "42",
		"relationships": {
			"@ignore": "foo",
			"friend": {
				"data": {"type": "user", "id": "24"}
			}
		}
	},
	"included": [
		{"@ignore": "foo"},
		{"type": "user", "id": "24", "attributes": {"foo": "bar"}}
	]
}
```

Or:

```json
{
	"errors": [
		{"@ignore": "foo"},
		{
			"links": {
				"@ignore": "foo",
				"about": "https://..."
			},
			"source": {
				"@ignore": "foo",
				"parameter": "title"
			}
		}
	]
}
```

Is this anyway the case? Does the spec leave no restriction to where they may appear at all?

I read the discussion in https://github.com/json-api/json-api/pull/995 about where it should be allowed in. What I don't read there is some concrete examples though, only a generic discussion about that JSON-LD needs it in deep-down places. Now I'm not an expert in JSON-LD, but the places where I find it weird do have something in common which makes me feel it is weird to allow them there: it isn't clear what they describe.

So for example `@ignore` (at root level) describes the document, `data.@ignore` describes the resource, `data.relationships.*.@ignore` describe the relationship.

But `links.@ignore` describes the next link but not all? Or `data.relationships.@ignore` the next relationship but not all? And `included.#.@ignore` in a further empty resource says me nothing, idem for `errors.#.@ignore` in a further empty error object.

I can imagine the spec being changed to state it is not allowed:

1. as the only member of an object inside an array (`data.#.@ignore`, `included.#.@ignore` and `errors.#.@ignore`)
2. at root level of objects with a specific value (`links.@ignore`, `relationships.@ignore` and `errors.#.source.@ignore`), but do allow there were the values have a more free format (`data.attributes.@ignore`)

Would that work? Are there reasons to do have @-members in those places?

**Comment by ethanresnick** [comment]
1. Once we've allowed @-Members everywhere, we can't disallow them without potentially breaking existing implementations and violating our backwards compatibility promises, so discussing where they ought to be used a little bit moot;

2. But also, in the context of JSON-LD, using @-Members in some of the places you cite as not making sense actually is useful in some cases. Here's an example:
    ```
    {
      "@context": {
        "links": "_:links"
      },
      "links": {
        "@id": "https://api.example.com/people/1/relationships/father",
        "@context": {
          "related": {
            "@type": "@id",
            "@id": "http://www.iana.org/assignments/relation/related"
          }
        },
        "related": "https://api.example.com/people/1/father"
      }
    }
    ```

**Comment by lode** [comment]
> 1. Once we've allowed @-Members everywhere, we can't disallow them without potentially breaking existing implementations and violating our backwards compatibility promises, so discussing where they ought to be used a little bit moot;

I don't fully understand the last part of your sentence; to be sure: you mean we should discuss this? Or not because it is too late?

---

> 2. But also, in the context of JSON-LD, using @-Members in some of the places you cite as not making sense actually is useful in some cases. Here's an example:

How should one interpret the @-members in `links` if there's more links?

```json
{
  "@context": {
    "links": "_:links"
  },
  "links": {
    "@id": "https://api.example.com/people/1/relationships/father",
    "@context": {
      "related": {
        "@type": "@id",
        "@id": "http://www.iana.org/assignments/relation/related"
      }
    },
    "related": "https://api.example.com/people/1/father",
    "another": "https://api.example.com/people/2/child"
  }
}
```

Or:

```
{
  "@context": {
    "links": "_:links"
  },
  "links": {
    "@id": "https://api.example.com/people/1/relationships/child",
    "@context": {
      "related": {
        "@type": "@id",
        "@id": "http://www.iana.org/assignments/relation/related"
      }
    },
    "related": "https://api.example.com/people/1/father",
    "another": "https://api.example.com/people/2/child"
  }
}
```

I would say in these cases allowing @-members breaks using JSON:API to the fullest; adding these makes in unclear what the other members mean and what the relation between those is. But I can imagine that is all fine as JSON:API already states to ignore these members completely.

---

In the forums there was another good point: https://discuss.jsonapi.org/t/are-members-really-allowed-everywhere/1507/2?u=lode

> In your last two examples, once you ignore the @-members, you end up with empty objects ({}) which are not valid.

Of course an implementation could actually remove those objects But I think the exception I mentioned before ...

> as the only member of an object inside an array (`data.#.@ignore`, `included.#.@ignore` and `errors.#.@ignore`)

... is still a good to add. Or is there an example where that would be needed as well?

**Comment by ethanresnick** [comment]
> I don't fully understand the last part of your sentence; to be sure: you mean we should discuss this? Or not because it is too late?

I mean it's too late.

> How should one interpret the @-members in `links` if there's more links?

You would add another @-Member for the `child` link, as a sibling of `links.@context.related`. But I'm not sure what you mean by "how should one interpret them". @-Members are really only envisioned for JSON-LD, and JSON-LD defines exactly how to interpret them. If you didn't add a `child` sibling for the new link, that link would just be ignored by JSON-LD, whereas JSON-LD would "see" and process the link described by `links.@context.related`.

> [](https://discuss.jsonapi.org/t/are-members-really-allowed-everywhere/1507/2?u=lode)

> In your last two examples, once you ignore the @-members, you end up with empty objects ({}) which are not valid.

I think this is a key point. Implementations that aren't JSON-LD aware don't have to do anything special to handle @-Members. They just pretend the `@-Members` aren't there and go on exactly as they would in that case. Non-json-ld implementations should not, for example, be trying to associate @-Member data with specific JSON:API fields and then exposing that @-Member data with their APIs for performing JSON:API-specific actions like reading a field — you're right that that sort of thing won't work, because the mapping in JSON-LD isn't one-to-one like that. 

> as the only member of an object inside an array (`data.#.@ignore`, `included.#.@ignore` and `errors.#.@ignore`).. is still a good to add. Or is there an example where that would be needed as well?

I'm sure there are examples. More importantly, though, what value does this restriction add? It seems to me that it would just complicate the spec.

**Comment by lode** [comment]
> I mean it's too late.

Thanks for anyway taking the time to discuss!

It sounds logical. I guess I'd need to dive into JSON-LD if I want to understand the need and ideas. From the discussion in https://github.com/json-api/json-api/pull/995 I thought it was a more generic feature, and thus I assumed JSON:API defining how to use them.

What I find tricky is that if the feature is so loosely defined, we risk that every implementation does it different, and I would hardly call it part of the spec; no-one can rely on it.

For example: does the spec have any opinion on whether the @-members are part of the _resource identifier_? In my implementation I have an internal structure defining a _resource object_. I can use this in a document with a single resource, or for a document with a collection of resources, or as a way to add relations to other resources.

For example these resources, with an @-member on the related resource:

```
Resource:
- type: user
- id: 42
- attributes:
  - name: Zaphod Beeblebrox
- relationships
  - location: ship 1

Resource:
- @context: universe
- type: ship
- id: 1
- attributes:
  - name: Heart of Gold
```

When adding this resource as a relationship, is the @-member seen as part of the _resource object_?

```json
{
    "data": {
        "type": "user",
        "id": "42",
        "attributes": {
            "name": "Zaphod Beeblebrox"
        },
        "relationships": {
            "location": {
                "data": {
                    "type": "ship",
                    "id": "1"
                }
            }
        }
    },
    "included": [
        {
            "@context": "universe",
            "type": "ship",
            "id": "1",
            "attributes": {
                "name": "Heart of Gold"
            }
        }
    ]
}
```

or also as part of the _resource identifier object_?

```json
{
    "data": {
        "type": "user",
        "id": "42",
        "attributes": {
            "name": "Zaphod Beeblebrox"
        },
        "relationships": {
            "location": {
                "data": {
                    "@context": "universe",
                    "type": "ship",
                    "id": "1"
                }
            }
        }
    },
    "included": [
        {
            "@context": "universe",
            "type": "ship",
            "id": "1",
            "attributes": {
                "name": "Heart of Gold"
            }
        }
    ]
}
```

Is the answer the same? The spec has no opinion about this at all. And implementation should allow to add @-members to either resource, resource identifier, or both with the same values, or both with different values?

**Comment by lode** [comment]
Another question of the same kind: is the order of @-members defined? In JSON-LD they always seem to appear first in objects, but the spec doesn't mention this. The example of using them inside a relationship object (as in https://github.com/json-api/json-api/issues/1367#issuecomment-462466703) seems to indicate their order is important. E.g. is it also okay if an implementation would do it like this:

```
{
  "links": {
    "related": "https://api.example.com/people/1/father",
    "another": "https://api.example.com/people/2/child",
    "@id": "https://api.example.com/people/1/relationships/father",
    "@context": {
      "related": {
        "@type": "@id",
        "@id": "http://www.iana.org/assignments/relation/related"
      }
    }
  }
}
```

I assume JSON:API doesn't care, but from a JSON-LD perspective it would be seen as weird at least. Which gives me the impression that for an implementation to be spec 1.1 compliant it actually needs to implement a feature called 'JSON-LD', instead of just '@-members'.

**Comment by gabrielgrant** [comment]
I don't think I know enough about the JSON-LD spec to weigh in on this, but the questions seem valid, and, given that the v1.1 spec has re-entered Working Draft state, i think we can safely say that it is no longer "too late" to discuss this, right?

**Comment by dgeb** [comment]
> i think we can safely say that it is no longer "too late" to discuss this, right?

Yeah, it seems worthwhile to reopen this discussion.

While I completely agree that many of the examples cited in this issue would be weird / incompatible with JSON-LD, I also don't think that the JSON:API spec should be concerned with proper usage of JSON-LD. If we get too caught up in the particulars, then we will undoubtedly miss a valid present _or future_ use case for JSON-LD. The bottom line is that implementations that don't understand JSON-LD should simply ignore `@`-prefixed members.

A guideline that has been in JSON:API since 1.0 is that:

> Client and server implementations MUST ignore members not recognized by this specification.

This allows for evolution of the spec through additive changes.

With that said, I think it's worth discussing _how_ both JSON:API and JSON-LD could properly interact. In my view, the responsibilities of the base JSON:API spec end with simply allowing for interaction with JSON-LD. However, if you wanted to _require_ an understanding of both specs and specify exactly how they should interact, I think that would be a good use case for a JSON:API profile. Such a profile could address the concerns raised here about which `@`-members are allowed where, and what precisely do they mean when processed together with JSON:API.

Since we wouldn't want such a profile to be in conflict with the base spec, we should probably re-examine some of the absolute requirements added to the `@-Members` section. For instance:

> JSON:API processors MUST completely ignore @-Members (i.e. not treat them as JSON:API data).

And:

> Moreover, the existence of @-Members MUST be ignored when interpreting all JSON:API definitions and processing instructions given outside of this subsection.

I think these statements would be incompatible with a profile that specified _how_ to interpret the meaning of particular `@`-members.

**Comment by jelhan** [comment]
I think this one could be closed as soon with @dgeb comment above as soon as the clarification proposed in #1631 is merged.

**Comment by dgeb** [comment]
Upon reading and re-reading these issues and the current v1.1 section on `@` members, it now is clear to me that `@` members are fully in the domain of [implementation semantics](https://jsonapi.org/format/1.1/#semantics) rather than specification semantics. As such, their usage can be governed by profiles, but not the base spec or extensions.

If any clarification is needed to the spec, let's discuss in #1631.
