### ISSUE TITLE
Define the handling of unknown or unexpected attributes when creating or patching

### ISSUE THREAD

**Issue by pwolanin** [json-api/json-api#1387]
The spec doesn't define the expected behavior if a client sends an unknown or unexpected attributes when creating or updating a resource

Noticed this while working with the Drupal implementation:
https://www.drupal.org/project/jsonapi/issues/3047542

It would be helpful for the spec to define the expected (or allowed) behaciors in this case.

Options include rejecting the request or ignoring the attribute.

**Comment by wimleers** [comment]
Great catch!

I _suspect_ the spec has been silent on this because it has only thought of defining the more common case of allowing non-required fields to be omitted. The case of non-existing/unknown/unexpected fields being sent in request bodies probably has not yet been thought to be defined, but we should do that, to maximize interoperability.

**Comment by gabesullice** [comment]
I think that this needs to be left to the implementor and already falls under ["Other Responses"](https://jsonapi.org/format/1.1/#crud-updating-responses-other), specifically:

>A server **MAY** respond with other HTTP status codes.

and

>A server **MUST** prepare responses, and a client **MUST** interpret responses, in accordance with HTTP semantics.

It shouldn't/can't be further defined by the spec because some servers are built on top of document store databases that allow arbitrary keys. We can't break those use cases.

When arbitrary keys are not allowed, the appropriate response is `422 Unprocessable Entity` with an error pointing to the unknown property.

**Comment by wimleers** [comment]
Great point! :)
