### ISSUE TITLE
Enforcing arrays in the 'links' key

### ISSUE THREAD

**Issue by xcambar** [json-api/json-api#142]
Hi everyone,

I feel like there's a dissonance in the specs regarding the `links` property.
- It is stated at the beginning of the spec that every resource property must be wrapped in an array `to simplify processing` (quoting), as in

``` javascript
{
  "singleResource": [{/*...*/}]
}
```

or

``` javascript
{
  "multipleResources": [{/*...*/}, {/*...*/}, {/*...*/}]
}
```
- But in the examples, the `author` property (a link in a `post` resource), is a `String`:

``` javascript
{
  "posts": [{"id": "123", "links": {"author": "321"}}]
}
```

Which, in regards to my understanding of the spec, is breaking the first rule. I would have expected it to be an array, as follows:

``` javascript
{
  posts: [{is: "123", "links": {"author": ["321"]}}]
}
```

To add more confusion, whenever I will fetch the `author` resource (described with a string in the links property), the server will return a list of objects, as per the first rule.

Am I completely off the purpose of the `links` property? Does it really need to have a special "treatment"?

Thank you very much for the enlightenment to come, ladies and gentlemen :wink:

**Comment by samwgoldman** [comment]
My understanding of the spec is a bit different from yours.

You are referring to the documentation that states "Singular resources are represented as JSON objects. However, they are still wrapped inside an array."

This documentation refers to the top-level object, not references. I think it's reasonable that references occupied by a single document would be a single link, not an array.

**Comment by xcambar** [comment]
Why would we make it easier to process resource descriptions and NOT do it for object references?
Both describe resources, the difference being in the level of detail (no details on one side, full details on the other).

That's why I opened this discussion about a full array-enforcement both for resource description and references, and still advocate it.

Nonetheless, your point of view helped me grasp that specific point in the current spec, and made it clearer.

**Comment by samwgoldman** [comment]
I'm not sure I understand why references would be easier to process as an array.

The top-level document descriptions need to be arrays because of side loading. That is, a request for a single person could return multiple people, so it's simpler to always return collections.

Why would it be "easier" to process has-one references if they were encoded as an array? Honest question. I think the answer to this would need to explore what it means to be a JSON API client, which is something that isn't talked about much.

Let me take a stab at answering that question: a has-one type references would be a single link, but has-many type references would be an array. The client would have to know what kinds of references exist in the system. Take ember-data for example. When you define a DS.Model you specify the types of relationships (DS.hasMany/DS.belongsTo).

Some might argue that this is out-of-band knowledge, and they would be right. My hypothesis is that we must accept that out-of-band knowledge to make JSON API work, because clients need to know what operations are available. I wonder what @steveklabnik thinks about that.

**Comment by steveklabnik** [comment]
> My hypothesis is that we must accept that out-of-band knowledge to make JSON API work, because clients need to know what operations are available.

If something is currently out of band, then it needs to be brought as in-band as possible.

Always having an array is easier than sometimes having a singleton because you don't need to switch based on type to figure out what's up:

```
if object?
  # parse single object
elsif array?
  # parse array
end
```

goes to

```
# parse array
```

**Comment by samwgoldman** [comment]
I appreciate your input, but I think your example is a straw man. If we admit client-side out-of-band knowledge, specifically whether a relationship singular or plural, then the client would know how to parse the response, because it would know what to expect.

I want to break this into two separate points:
1. The client should know if a relationship is singular or plural.
2. Relationships should always be encoded as an array.

If point 1 is false, then I agree with point 2. If point 1 is true, then I disagree with point 2. I would argue that point 1 is true.

Actually, let me separate out some more points:
3. We should be able to write application logic in JSON API clients.
4. Clients need some out-of-band information to write this logic.

Point 3 is more of a mission statement type thing. I believe it to be true, but that's not up to me. If this is false, then I will probably not use JSON API and the resolution to these issues doesn't concern me.

Point 4 is I think the crux of this debate. There's more than one way to skin a cat, too. My opinions are formed by what I've seen in practice, but I haven't seen everything and I'm not current on the newest trends on the theoretical side.

Client-side "application logic" fundamentally means algorithms written on the client. Many algorithms rely on invariants. Algorithms that operate on tree-structured data rely on the invariant that nodes have a single parent. If we can't rely on a singular parent, we can only assume we have some kind of directed graph, and we can't write algorithms that operate on trees but not on graphs.

Furthermore, there is some prior art to suggest that encoding relationship arity on the client is reasonable. Ember Data, for example, requires that relationships be specified as either "hasMany" or "belongsTo."

**Comment by bartiaco** [comment]
I think that point Sam's first point: "1. The client should know if a relationship is singular or plural" is the most important question.

If we accept that even singular resources will be returned within a pluralized root key name and in an array, I'm not inclined to believe that a client should know/care whether or not a resource is singular.

Additionally, for consistency, if I have a link with {"author": ["/authors/1"]}, shouldn't I be able to look for the same key in the response? So, shouldn't it be {"authors": ["/authors/1"]}?

To be fair, if there _should_ to be a detectable difference between singular and plural links, there needs to be defined rules around pluralization that clients need to understand or some other programmatically understandable descriptor.  Perhaps something like this:

``` javascript
{
  "links":  {
    "authors": { "href": "/authors/1", "relType": "hasOne"},
    "comments": { "href": "/posts/123/comments", "relType": "hasMany"}
  }
}
```

However, if we go down this path, then we start to lose any conveniences we gained from returning singular resources with a pluralized root key, and inside an array.

**Comment by samwgoldman** [comment]
I was trying to emphasize something with my comment that I think I obscured: we should discuss the format in terms of what a client will/can do.

I see a lot of discussion about the format just focusing on the syntax in a vacuum. We should focus on what the server and the client want to accomplish first, and the format second.

If we just think about the format separate from its utility, we risk specifying a format that is not useful.

**Comment by xcambar** [comment]
Thanks for the clarification.

I didn't have the opportunity to go through your comments yet (sorry about that), but overall I agree on the client-focused orientation you have.

To fit with [Postel's Law](http://en.wikipedia.org/wiki/Robustness_principle), I guess we should define what it means for JSON-API to be "conservative" and how it can be reasonably "liberal".

Probably this discussion needs to take more input: @wycats, @dgeb and others, what do you think ?

**Comment by jcallaha** [comment]
@samwgoldman I get even more confused when I try to figure this out in the case of the URL-based API.  Under the URL-based API section the examples show five ways to represent a relation, three of which I don't believe the client can reasonably tell if they are has-many or has-one relationships:

```
  "author": "http://example.com/people/1"
```

Is `author` has-one or has-many?  Bet you can't be certain...
<br>

```
  "comments": "http://example.com/comments/5,12,17,20"
```

Okay now `comments` we can see must be has-many, but could a client figure this out?
<br>

```
  "comments": "http://example.com/posts/1/comments"
```

I can tell this is has-many, but only because I can infer the url represents all of post #1s comments
<br>

```
  "author": "1"
```

Obviously has-one
<br>

```
  "comments": [ "1", "2", "3", "4" ]
```

Obviously  has-many
<br>

What about this: always enclose has-many relations in arrays, regardless of if you are providing urls or ids?

```
"author": "http://example.com/people/1"
"comments": ["http://example.com/posts/1/comments"]
```

Or maybe its just not that important for a client to know?

**Comment by bartiaco** [comment]
@jcallaha 

I'm glad you brought that up.  I generally prefer describing relationships with urls vs ID's (feels a bit more HATEOS), but it makes for some tough choices with has_many relationships.

**Comment by dgeb** [comment]
I'm closing this because the unification of the URL and ID styles in 8d3adde90161ec4118f8ec5b0c758d807dfc4100 has removed the dissonance in `"links"`.
