### ISSUE TITLE
Relaxing the ID requirement for ephemeral data

### ISSUE THREAD

**Issue by multimeric** [json-api/json-api#1427]
Currently the spec states:

> Every resource object MUST contain an id member and a type member

However, as discussed in a number of places, there are use-cases where this doesn't necessarily make sense to require an ID:
* https://github.com/json-api/json-api/issues/181#issuecomment-33080956
* https://discuss.jsonapi.org/t/necessity-of-id-field-in-json-api-response-for-logging-audit-related-records/1615
* https://discuss.jsonapi.org/t/json-api-response-format-for-non-resource-data-like-oauth-token/74

These scenarios tend to be when the data resources have no stable ID, and it would make no sense to generate one:
* Plot data: the user requests the generation of a plot from certain parameters. What is the ID of this generated plot? A plot can be treated as a resource in all other regards
* Summary statistics: the user requests the mean, variance, or other summary statistics over a dataset (e.g. financial). The summary statistics report might be considered a report resource, but it doesn't have an identifier
* Data processing: the API provides a means for you to POST some data that it processes and returns to you. Lets say it does OCR. This can be modelled as a resource you are submitting, but the server won't store the processed data anywhere, so an ID would be useless.

How should this be implemented in JSON API? Should it be a profile for ephemeral data? Or part of the core spec?

**Comment by Doqnach** [comment]
I have implemented something like this as a meta document. The data itself is also not really typed then in many cases. It is more a collection of numbers...
It is not a resource that exists on the backend you could request again, so is a data document even the right way?

Work around is to generate a UUID for the report/plot that also matches maybe logging or such.

**Comment by multimeric** [comment]
I appreciate that this is a workaround, but it's not the ideal solution. The meta field is obviously designed for data describing the main data. It doesn't make sense for it to *be* the main data. In addition, by using the meta field, we lose a lot of the structure JSON API mandates for the main data.

As I explained in my examples, I believe that all of these can be considered resources/documents, and all of them could reasonably have their own resource URL, and a fixed schema. For example, my plot data schema defines two fields, a list `x` of type number, and a list `y`, of type number. The only thing missing here is the ID, which I naturally don't have.

**Comment by Doqnach** [comment]
JSON:API does 'allow' you to not supply the `ID` in the case of a `POST`. Maybe that could be extended to make it optional all together, or at least make some more (informal) rules about making it optional?

Even the meta field can be made 'typed' simply by having a spec defining it (like OpenAPI or Json Schema).

**Comment by gabesullice** [comment]
Why not just an ISO 8601 datetime? Like:

```json
{
  "type": "report",
  "id": "2019-08-28T14:00:50Z"
}
```

There's nothing in the spec that says that a resource must be retrievable at some URL like `/{type}/{id}` so I don't see a problem with providing something like a timestamp as the ID for resource that's ephemeral and can't be fetched.

My concern is that if we carved a rule out that says an ID is not required, we'd be unnecessarily complicating client implementations since the majority of applications don't have this edge case.

The pragmatic solution is simple: if your data doesn't have a meaningful ID, ignore it on the client-side and provide some easy-to-generate value on the server side that's tangent to the request that prompted the response.

For example, it could be the time at which the response was generated, it could be the IP address of the client which requested the response, it could be a serial value for the nth report generated, it could be a hash of the input data... it doesn't really matter, it'll be ignored anyway.

**Comment by multimeric** [comment]
>  if your data doesn't have a meaningful ID, ignore it on the client-side

This is exactly the issue. I don't want or need an `id` field polluting my data, because the ultimate destination of the data doesn't understand the `id` field. It should be the case that a JSON API server can send some data meeting some other data specification it doesn't know about, and when the client receives it, it only has to deal with the original, unprocessed data. After deserializing, the client shouldn't ever have to see the JSON API transfer format, which happens to have and `id` field, and puts everything inside a `data` key, and has relationships modelled as URLs etc. That should only be the concern of the JSON API implementations, not my code that merely uses them.

For example, my use-case is that my JS frontend requests plot data from my JSON API conformant server. I have a schema that defines a plotly data Series, **which is identical to the plotly input definition!**. My intention is that I can pass some data from the server to the client, using JSON API libraries, and I never have to imperatively change my data to meet the specification, I just have `marshmallow-jsonapi` and whatever JS library deal with that communication for me.

**Comment by ahx** [comment]
> My concern is that if we carved a rule out that says an ID is not required, we'd be unnecessarily complicating client implementations since the majority of applications don't have this edge case.

This is a pretty important aspect, I think. I would agree that in most cases having a resource identifier with type and ID makes sense and adding exceptions makes client implementation unnecessarily more complex.

**Comment by gabesullice** [comment]
> It should be the case that a JSON API server can send some data meeting some other data specification it doesn't know about, and when the client receives it, it only has to deal with the original, unprocessed data.

I don't think I agree with you. If your client doesn't want a JSON:API formatted response, then the client should send something like `Accept: application/json` or `Accept: text/csv` or whatever media type is best suited to that original, unprocessed data instead of `application/vnd.api+json`. There's no interdiction on serving alternative representations on a server that can also serve JSON:API responses.

IOW, if your client wants a representation of the data that doesn't conform to the JSON:API specification, then have it negotiate the most appropriate format to begin with.

**Comment by multimeric** [comment]
Sorry, I possibly wasn't clear. I don't mean that the client shouldn't receive JSON API formatted data, I meant that a JSON API client library should be able to recover the original data, which conforms to some other specification. And imposing an `id` on the data makes that more tricky. 

I guess some of my irritation isn't to do with the JSON API spec, but rather [`marshmallow-jsonapi`](https://github.com/marshmallow-code/marshmallow-jsonapi), which I'm treating as an exemplar of the spec. Basically `schema.load(json_response)` automatically unwraps the API response back to the original form, except that it includes the `id` in the final data, which I was hoping not to have to pull out.

Is there some better way of dealing with data I don't want modified in JSON API?

**Comment by ahx** [comment]
@TMiguelT from here your approach, using JSON:API just as a transport for whatever data, sounds good and seems to work if all that is bothering you is the additional id field. 
I cannot think of a better way to do this. This sounds like something that is best fixed in the de/serialization layer/library. Maybe you can wrap that part or add an option in marshmallow-jsonapi?

**Comment by multimeric** [comment]
@ahx yes, you're probably right. There's no reason there can't be an argument to the marshmallow's deserialize function that checks there's an ID in the message, but removes it from the output object so that I don't have to see it.

And indeed, I've realised why IDs are necessary even in the case of ephemeral data: [compound documents](https://jsonapi.org/format/#document-compound-documents). The IDs are the mechanism used to define the relationships between resources, and without it, we would have ambiguous relationships. 

I'm happy with either the UUID or the datetime solution for generating IDs. Although I suspect in most cases there is some value that can be used as a proxy ID that's more representative of the resource. For example in my graph situation it might be the name of the series ('stdev', 'mean' etc), which is not going to be globally unique, but that doesn't actually matter, since the data is ephemeral. I suppose the spec encourages global uniqueness, but you can solve this by appending a datetime or UUID to the natural identifier. e.g. `2019-08-31T14:00:00Z-mean`, `2019-08-31T14:00:50Z-mean`

**Comment by multimeric** [comment]
And, for anyone who is annoyed by this in marshmallow-jsonapi, you can do the following, which enforces ID validation in the schema, but will at least exclude it from the load result:

```python
class EphemeralSchema(Schema):
    id = f.String(dump_only=True)

data = EphemeralSchema(unknown=EXCLUDE).load(response.json)
```
