### ISSUE TITLE
Clean up the list of implementations

### ISSUE THREAD

**Issue by mfcochauxlaberge** [json-api/json-api#1448]
Would the maintainers of this repository be interested in a cleanup of the list of implementations? If so, I can volunteer.

I am asking before doing so that my work is not done for nothing.

I was thinking that simple and not very strict rules could remove quite a few projects that would be considered not useful by anyone. Not respecting at least one of them would mean that the project should be removed from the list. They would be as follow:

- No stable release AND no commit for at least 6 months
- Implementation that is clearly incompatible with JSON:API

If a maintainer is interested, I can put in a few hours anytime.

**Comment by lode** [comment]
I think it is a bit tricky. Playing the devil's advocate:

The first rule is simple to check but doesn't always say enough. Not every project uses releases and still it can be stable and used. Maybe checking the dependencies using the package can help, but that soon becomes a popularity contest (not necessarily in sorting, but in including or excluding).

The second rule is very hard to test I think. First it is more intensive, and second it requires good documentation. Some implementations are more of the helper kind, or more full-fledged. And what is the boundary? If small incompatibilities are seen? Maybe we should instead file a bug and help the ecosystem in that way.

Recently I went through the whole list for a certain language and noticed that each library serves the goal in a whole different way. I didn't really find any libraries clearly being wrong.

Btw, I join the wish for an up-to-date list. Maybe it is easier to create an issue on a certain library and/or here for specific libraries which are clearly wrong in your eyes, instead of testing the whole list against a set of rules.

**Comment by mfcochauxlaberge** [comment]
Any library with a minimum of quality will use versioning.

For my second point, I mention the word "clearly", so it's not very hard to test. I was mostly referring to libraries for older versions of the spec (pre 1.0).

For now, I'll close this issue, but my offer still stands.
