### ISSUE TITLE
json-api needs some more attention...

### ISSUE THREAD

**Issue by Ilyes512** [json-api/json-api#1453]
So I started using json-api 1-2 years ago, but since that time there have not been any (visible) progress (as in releases). Version 1.1 release date came and went by (now it doesn't even say when it will be released). There is an old issue talking about the same thing: https://github.com/json-api/json-api/issues/1190 There was some promise of more activity.

Looking at the project I see 43 open pull request!? Some of which are for minor fixes and cleanups that could easily be closed or merged. 119 issues, I think that could be a little less (there are probably some quick wins for lowering that number). 19 branches, some of which seem to be created a really long time ago. 

If time is the problem, maybe try and call for more contributors/help?

**Comment by auvipy** [comment]
agree

**Comment by mfcochauxlaberge** [comment]
I am available for any kind of help this project needs.

**Comment by akleiber** [comment]
actually there is: https://github.com/json-api/json-api/issues/1435#issuecomment-637041781

**Comment by freddrake** [comment]
@gabesullice: This issue should be closed.

**Comment by Ilyes512** [comment]
@freddrake I am wondering what made you think this issue can be closed? And why don’t you ask the OP first (having the extra advantage of not giving maintainers extra inconsequential tasks).

Anyways, I still think it’s mostly true... yes, I see some more activity, but I think there are still (minor?) house holding tasks to be done to cleanup the repo. I guess I will do my part by just closing this?

**Comment by freddrake** [comment]
@Ilyes512: I think this issue can be closed, because of the issue link @akleiber provided last June.

As for why I addressed Gabe with my comment instead of you:  I know he *can* close the issue, and manages to spend some time on JSON:API, while you let this linger for a long time after the mentioned link was added.  It was not intended as a slight toward you, and I hope you did not perceive it as such.

That said, I'm glad you *are* paying attention, and hopefully your concerns about the activity level here are fairly addressed by the referenced issue.  It's certainly something I've been giving thought as well.

**Comment by Ilyes512** [comment]
In regards to:
>  It was not intended as a slight toward you, and I hope you did not perceive it as such. 

Not at all (maybe I sounded to "passive aggressive"?). Was just wondering the "why" and you reply explains it well enough! Thanks!

**Comment by freddrake** [comment]
@Ilyes512: No, not too passive aggressive.  I'm just still recovering from the debacle of the last five years of politics here in the US.  This is going to be a long road.
