### ISSUE TITLE
Ambiguous Description for Top-Level Related Links

### ISSUE THREAD

**Issue by jrandolf** [json-api/json-api#1477]
> The top-level links object MAY contain the following members:
> * self: the link that generated the current response document.
> * related: a related resource link when the primary data represents a **resource relationship**.
> * pagination links for the primary data.

It is unclear whether the **resource relationship** is precisely a *resource linkage* or a *resource relationships object*. If it's the former, then there is no issue but the wording must be fixed. If it's the latter, then there is a contradiction in the spec since relationships have a *data* attribute.

**Comment by freddrake** [comment]
Perhaps saying just **relationship** would be better than **resource relationship** here, since the later is a term that does not appear to be defined, and a relationship is specifically from one resource to any number of other resources (depending on whether it's to-one or to-many).

When the self link refers to a relationship, you should expect the top-level of the response to be a **relationship object**, defined starting with the third paragraph in [Relationships](https://jsonapi.org/format/#document-resource-object-relationships).
