### ISSUE TITLE
"date" and "errors" in the same document

### ISSUE THREAD

**Issue by Ivanov-Anton** [json-api/json-api#1507]
from [page](https://jsonapi.org/format/)
> The members data and errors MUST NOT coexist in the same document.
and

from [page](https://jsonapi.org/examples/)
> Error responses may not contain the top-level data member, but can include all the other top-level members JSON:API defines.

Is it a mistake or I don't understand something, I think that in the second case you need to use "must" instead of "may",
we cannot have such keys as "date" and "errors" in the same document.

**Comment by gabesullice** [comment]
The second example that you linked to is on the examples page and is not part of the specification which means that the first link takes precedence over the second.

However, I agree that those two sentences might be a little confusing since the second uses the word _may_ (which has a specific meaning in the spec, but not elsewhere).

If you'd like to submit a PR that clears up the two sentences, I'd be happy to merge it. Perhaps something like "Error responses cannot contain the top-level `data` member, but can ..." would be better?

**Comment by Ivanov-Anton** [comment]
@gabesullice Looks great, thanks
