### ISSUE TITLE
Should this query parameter 400 response be OR as opposed to AND?

### ISSUE THREAD

**Issue by Relequestual** [json-api/json-api#1545]
> If a server encounters a query parameter that does not follow the naming conventions above, **and** the server does not know how to process it as a query parameter from this specification, it MUST return 400 Bad Request.

Should that be OR rather than AND?

Otherwise, I read it as, if the query parameter doesn't follow naming conventions but the server DOES know how to process it as a query parameter from this specification, then the behaviour is undefined.

I find this paragraph a little bit cryptic.

Is there a situation where the query parameter may not follow the naming convention but the server might still know how to process it as a query parameter from the spec?

What was the intent here?

**Comment by dgeb** [comment]
@Relequestual Thanks for raising this. I think you're correct that this should be `or`:

> If a server encounters a query parameter that does not follow the naming conventions above or the server does not know how to process it as a query parameter from this specification, it MUST return 400 Bad Request.

Once this correction is made, the original intent becomes clear: servers must reject, rather than ignore, query parameters that are reserved for this specification but which they don't understand. This prevents a misunderstanding between a future client, say using spec v1.5, sending the newly specified `foo` param, which a v1.0 server does not know how to process. The server must reject this request rather than give the client the false understanding that it's been fulfilled successfully.

There is a note below that sentence which attempts a clarification:

> Note: By forbidding the use of query parameters that contain only the characters [a-z], JSON:API is reserving the ability to standardize additional query parameters later without conflicting with existing implementations.

Perhaps this point could be made clearer. Regardless, I'm 👍 on starting with the change from `and` to `or`.

**Comment by dgeb** [comment]
@gabesullice thoughts?

**Comment by gabesullice** [comment]
I agree.
