### ISSUE TITLE
Documentation still vague about pagination of relational data

### ISSUE THREAD

**Issue by paul-uz** [json-api/json-api#1557]
As asked before here, https://github.com/json-api/json-api/issues/1291, the answer given is still pretty vague, and the documentation is still unclear.

In the sentence

| Any pagination links in a relationship object MUST paginate the relationship data, not the related resources.

What is the "relationship data" and what is the "related resource"?

If we assume "Bar" is the "relationship data" - do we just show the first, next and last pagination links and call it a day? 

Or is it trying to say we have to be able to call `/foo/123?page[number]=3` to get `Foo` with page 3 of `Bar`?

Or, is the "relationship data" something altogether? (perhaps `/foo/123/relationship/bar` ?)

**Comment by jelhan** [comment]
_Relationship data_ is the data included as [resource linkage](https://jsonapi.org/format/1.1/#document-resource-object-linkage). I see that it is confusing that the term _relationship data_ is used instead of _resource linkage_ at two places. It is only indirectly specified in the [fetching relationships](https://jsonapi.org/format/1.1/#fetching-relationships) section:

> A server MUST support fetching relationship data for every relationship URL provided as a self link as part of a relationship’s links object.

The term _related resources_ is used in the specification at several places. I think it is well defined as [resource objects](https://jsonapi.org/format/1.1/#document-resource-objects), which represent resources referenced by a relationship of another resource. This could be done either by a [related resource link](https://jsonapi.org/format/1.1/#document-resource-object-related-resource-links) or resource linkage. I don't see clarification needs for this term.

For pagination it means that pagination links belong to the `self` link of a relationship. Not to its related resource link (`related`). An example may look like this:

```json
{
  "type": "posts",
  "id": "7",
  "relationships": {
    "comments": {
      "data": [
        { "type": "comments", "id": "1" },
        { "type": "comments", "id": "2" },
        { "type": "comments", "id": "3" },
        { "type": "comments", "id": "4" },
        { "type": "comments", "id": "5" },
      ],
      "links": {
        "related": "/posts/7/comments",
        "self": "/posts/7/relationships/comments",
        "next": "/posts/7/relationships/comments?page[number]=2",
        "prev": null,
        "first": "/posts/7/relationships/comments",
        "last": "/posts/7/relationships/comments?page[number]=5"
      }
    }
  }
}
```
