### ISSUE TITLE
Are lowercase query parameter "family" names reserved?

### ISSUE THREAD

**Issue by cmeeren** [json-api/json-api#1566]
The spec says that query parameters must include at least one non-`a-z` character. Does `[` and `]` count?

Specifically, I'd like to use `aggregate[function]` and `aggregate[period]`. Does that violate the spec? Do I have to use e.g. `customAggregate[function]` or simply `aggregateFunction`?

**Comment by freddrake** [comment]
My reading on this:

Since query parameter names are restricted to valid member names, and member names exclude `[` and `]`, the "family" portion must conform to the rule about reserved names.

Since the `family[member]` serialization convention isn't mandated by HTTP, this should be clarified in the specification.

**Comment by cmeeren** [comment]
> Since the `family[member]` serialization convention

Is it a _serialization_ convention? I have always thought about it as a _naming_ convention. Just a nice-looking way to "semantically  group" related query parameters.

I realize of course that it _can_ be a serialization convention, but I have never thought about `page[offset]` and `page[limit]` as a way of specifying `offset` and `limit` properties on a `page` JSON object.

In any case, I agree that the original question should be officially clarified. (More opinions here help too, in the meantime!)

**Comment by lode** [comment]
> More opinions here help too, in the meantime!

Here's mine. To me the intention of the spec places the restriction on the _family_ name (`aggregate` in your case) quite clearly.

Here it is explicit about that the family must contain another char:

> Implementations **MAY** support custom query parameters. However, the names of these query parameters **MUST** come from a family whose base name is a legal member name and also contains at least one non a-z character (i.e., outside U+0061 to U+007A).

And recommending to do this with camel case and not with `[]`:

> It is **RECOMMENDED** that a capital letter (e.g. camelCasing) be used to satisfy the above requirement.

Only in the note at the end is it a little vague by not explicitly mentioning _family_:

> Note: By forbidding the use of query parameters that contain only the characters [a-z], JSON:API is reserving the ability to standardize additional query parameters later without conflicting with existing implementations.

However also there the reasoning ('to standardize additional query parameters later without conflicting with existing implementations') makes clear it must be about the family name. Otherwise the spec would never be able to standardize `aggregate` or `aggregate[period]`.

---

Also, the usage of `[]` is indeed not a serialization convention from the spec. It states explicitly:

> The two parameters are named `page[offset]` and `page[limit]`; there is no single `page` parameter.

It is only a serialization convention in web server software.

**Comment by cmeeren** [comment]
> Here it is explicit about that the family must contain another char:
> 
> > Implementations **MAY** support custom query parameters. However, the names of these query parameters **MUST** come from a family whose base name is a legal member name and also contains at least one non a-z character (i.e., outside U+0061 to U+007A).

That is not in the [current (v1.0) spec](https://jsonapi.org/format/). It does not mention "family" at all.

In any case, assuming the above is correct (at least going forward, if not currently), then that answers my question. Thanks a lot!

**Comment by lode** [comment]
Ah sorry, of course. I've been used to checking the 1.1 spec for so long now that I didn't think about that this might be vague in 1.0.

You can also read https://github.com/json-api/json-api/issues/1304 which shows that the changes in 1.1 are intended in this specific way.

**Comment by jelhan** [comment]
This question seems to be resolved. The specification has been clarified in upcoming v1.1 to avoid this confusion. I don't think a change to v1.0 is needed. Please speak up if you see a need to clarify it in v1.0 as well. Or if you think v1.1 could be still improved around this topic.
