### ISSUE TITLE
json set

### ISSUE THREAD

**Issue by IamMuhammadHasib** [json-api/json-api#1601]
private fun setValues(response: JSONObject) {
        var country = response.getJSONObject("sys").getString("country")
        address.text = response.getString("name") + ", " + country

        updated_at.text = dateFormat(response.getString("dt").toLong()).toString()

        weather.text = response.getJSONArray("weather").getJSONObject(0).getString("description")

        var tempr = response.getJSONObject("main").getString("temp")
        temp.text = "${farToCel(tempr.toFloat()).toString()}°C"

        var mintemp = response.getJSONObject("main").getString("temp_min")
        temp_min.text = "Min Temp: ${farToCel(mintemp.toFloat()).toString()}°C"

        var maxtemp = response.getJSONObject("main").getString("temp_max")
        temp_max.text = "Max Temp:  ${farToCel(maxtemp.toFloat()).toString()}°C"

        var sunsetTime = response.getJSONObject("sys").getString("sunset").toLong()
        sunset.text = timeFormat(sunsetTime)

        var sunriseTime = response.getJSONObject("sys").getString("sunrise").toLong()
        sunrise.text = timeFormat(sunriseTime)

        pressure.text = response.getJSONObject("main").getString("pressure") + " hPa"
        humidity.text = response.getJSONObject("main").getString("humidity") + "%"
        wind.text = response.getJSONObject("wind").getString("speed")
        sea_level.text = response.getJSONObject("main").getString("sea_level") + " hPa"
    }

**Comment by jelhan** [comment]
Hello Mohammad,

To be honest I'm not sure what this issue is about. It doesn't seem to be related to the JSON:API specification at all. Even if it would be, we would need some more information than only code snippets to help you.

Please feel free to open another issue if you see a need to change something in the JSON:API specification. For questions about the JSON:API specification either the [JSON:API discussion forum](https://discuss.jsonapi.org/) or [`[json-api]` tag on [StackOverflow](https://stackoverflow.com/tags/json-api/info) might be a better fit.

For general questions about HTTP APIs which serve JSON, other forums are a better fit. This GitHub project is focused on the JSON:API specification only.

Best
Jeldrik

**Comment by dgeb** [comment]
I agree with @jelhan that StackOverflow is a good place for general questions about working with JSON.
