### ISSUE TITLE
"bling" is not a meaningful name for issue labels

### ISSUE THREAD

**Issue by freddrake** [json-api/json-api#1605]
The names of issue labels should be fairly descriptive and self-explaining.  Vocabulary derived from slang can be particularly difficult for people who are not native English speakers.

**Comment by jelhan** [comment]
I fully agree. And to be honest I'm not sure myself what that label stands for. Maybe because I'm not a native speaker. 🤷‍♂️

I tried to derive meaning from it looking at issues labeled with it. But I wasn't able to identify any common criteria.

22 issues are labeled with "bling". Only two of them are still open. All of them are quiet old (2015/16).

Maybe we could delete rather than rename in this case?

**Comment by freddrake** [comment]
Ah, didn't realize the label was old; don't think I'd seen it until those issues crept back up the stack because of your recent efforts.

Perhaps just remove the label from those two issues, and avoid affecting the older issues, which were presumably handled by someone who knew what "bling" meant.

**Comment by dgeb** [comment]
"Bling" essentially means shiny and superficial, although it's not formal English. Its intent was to be used for cosmetic or presentation aspects of the site.

I don't remember which editor created this label, but I am completely fine removing it. It's good to know that this is a confusing term.

**Comment by dgeb** [comment]
> Perhaps just remove the label from those two issues, and avoid affecting the older issues

I just did this and thus will close this issue. Thanks for raising it.
