### ISSUE TITLE
Query parameter naming

### ISSUE THREAD

**Issue by rkh** [json-api/json-api#161]
How does naming in query parameters work in URI templates? I mean, we are trying to deprecate most of the APIs using them, especially if they actually use document attributes.

In URI templates, you can define query parameters like this:

```
/posts{?date,title,page}
```

Lets say date and title can be used for filtering posts, and page for pagination (with a hardcoded number of posts per page). The expand rules would be like this:

```
{ }                       => /posts
{ title: "Foo", page: 2 } => /posts?title=Foo&page=2
```

Both date and title reference attributes in a posts document. How do I express these.

Or are request params expected to contain the prefix, like this:

```
/posts?posts.title=Foo
```

If so, how does that work with relations, say the author name?

**Comment by wycats** [comment]
Interesting. I didn't consider the expansion into query parameters when I wrote this.

Two possible approaches:
- All query parameters use the full path before the `=`. This is simple and consistent but may be aesthetically unpleasant to some people.
- Query parameters can use the last part only if they are unambiguous. Otherwise, they are required to use the full path.

Since this is a (mostly) machine protocol, I strongly prefer the first option. Any objections?

**Comment by rkh** [comment]
I think the first approach should be fine, especially since there is nothing keeping the server-side implementation from also support the short parameter version.

**Comment by dgeb** [comment]
As of #341 (RC2), explicit URI template support has been removed from the spec.
