### ISSUE TITLE
Is it possible to do attribute updates differently than the standard way?

### ISSUE THREAD

**Issue by Amourlive** [json-api/json-api#1612]
Hi!

I'm trying to do a very simple billing, let's say I have an “Account” resource and I want to decrease or increase it.
By standard, I can update resource attributes simply by replacing the previous value with the new one.
This logic assumes that I first need to query the resource, then perform calculations on the client, and then send a request to update the resource with the result of the calculation.
But what if I don't want to query the resource and perform calculations on the client, instead I want to send commands:
```
increase the balance by 100
lower the balance by 50
...
```
What is the most correct way to do this within the specification?
Or do I have to make a custom endpoint anyway? https://jsonapi.org/faq/#position-uri-structure-custom-endpoints

**Comment by jelhan** [comment]
> What is the most correct way to do this within the specification?

Assignment operators are not supported out of the box as per my understanding of the specification. Attributes in a resource object included in the payload of a `PATCH` can only contain concrete values. Not relative values based on the current value of that resource.

But upcoming v1.1 allows to create extension. Such an extension could define a new member like `relativeAttributes` and the processing rules for it.

Such an extension may define that the `relativeAttributes` takes an object, which keys reference an attribute of the resource and which value is an _operator object_.

An _operator object_ has a `type` and optionally an `arguments` member. The type must be one of a fixed list of operators, which should be supported. E.g. `"increment"`, `"decrement"`, `"add"`, `"subtract"`, `"multiply"` etc.

The `arguments` member take one or more arguments. Some operators like `"increment"` may not support any arguments. Some other like `"multiply"` may require at least one argument. Up for the extension to specify.

Just as a quick draft, how you may solve this use case within the specification.

**Comment by jelhan** [comment]
I think it's also important to consider that such updates are _not_ idempotent. Triggering an update twice, which updates a value relative to its current value, will result in different outcome. This is problematic as a client may not able to tell if it was processed. If connection drops before client receives the response - especially its HTTP status code -, the client does not know if the request was processed or not. This is especially problematic if the client does not know the original value. In that case even fetching the current resource would not help. I guess such an extension would also need to support a way to uniquely identify a request so that a server can determine if it was already applied or not. Basically allowing a relative upgrade to be idempotent.

**Comment by Amourlive** [comment]
Thank you for the detailed explanation. Idempotency is a good nuance.
I guess the library I'm using won't let me do that.
Anyway, I only tried to make a test project and at the same time wanted to better understand how to use the standard.
Thanks!
