### ISSUE TITLE
What is the purpose of ext and profile members of jsonapi object?

### ISSUE THREAD

**Issue by jelhan** [json-api/json-api#1646]
The purpose of `ext` and `profile` members of `jsonapi` object is unclear to me. They are defined like this:

> - `ext` - an array of URIs for all applied extensions.
> - `profile` - an array of URIs for all applied profiles.

Both is already available as part of `Cotent-Type` header. Specification even states that value of `Content-Type` header is only source of truth for content negotiation:

> Clients and servers MUST NOT use an ext or profile member for content negotiation. Content negotiation MUST only happen based on media type parameters in Content-Type header.

What use case is addressed by having this information in `jsonapi` object as well?

I get that both is optional. An implementation may just decide to not use it. So having it may not cause much harm.

At the same time an implementation could add the same in `jsonapi.meta`. So it shouldn't cause much harm to _not_ have it at the same time.

I tend towards removing it. Unless there is a clear use case for it, which I missed.

**Comment by lindyhopchris** [comment]
Could it be that when the server is replying to a client, it might want to put these extensions/profiles in the `jsonapi` top-level member of the document? That means that the document contains the extensions/profiles that are applied in it, which could potentially be useful.

**Comment by dgeb** [comment]
> That means that the document contains the extensions/profiles that are applied in it, which could potentially be useful.

Yes, @lindyhopchris has essentially summarized the point: the aim of the `jsonapi` object is to allow a JSON:API document to be better understood by examining its contents. It provides a standard place to describe spec usage within the document itself, so that the document can be more self-descriptive. Now that extensions and profiles are becoming a formal part of the spec, it seemed appropriate to add them alongside `version` because they can also be essential to understanding spec usage.

I understand that it's arguable that the whole `jsonapi` object is unnecessary and it is in fact ignored by many implementations. However, since it's been around since 1.0, it can't be removed and adding these members to it is in keeping with its intended purpose.

**Comment by jelhan** [comment]
Thanks a lot for sharing that background. I agree that keeping intended purpose makes sense. Especially as removing it is not an option.
