### ISSUE TITLE
json-api  should support creating compound documents (in a single request)

### ISSUE THREAD

**Issue by harmv** [json-api/json-api#165]
http://jsonapi.org/ describes in detail how to handle compound documents in http _responses_.

What I'm missing however is creating (POST)  compound documents.

example: an ecommerce api to create
Where you have have orders, with (optionally) order items.

I'ld like to have an api to create an order, with its items in one post request.

How should this be done ?
How to handle ids ?

Why this is desirable.
- it makes clients simpler. (don't have to test for failures)
- it ensures the orders are created atomically. (with its items, or not at all)

**Comment by jcallaha** [comment]
This seems overly messy/complicated... unless the client is providing IDs and you populate the `links` object inside the `order` document with the IDs of the new items you are creating with the `items` document(s), how would the primary document be linked to the related documents?  

I don' think the server can just assume what the relation is between the primary document and the additional related documents you send, since there could be more than one relationship with the same type.

**Comment by steveklabnik** [comment]
There are a few duplicates of this issue: https://github.com/json-api/json-api/issues/202
