### ISSUE TITLE
How to add multiple extensions in header

### ISSUE THREAD

**Issue by drnkwati** [json-api/json-api#1667]
How can I add multiple extension urls in headers?
Here is single extension example:
`
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json; ext="https://jsonapi.org/ext/version"
// ...
`
How can I do the same for multiple extension url?: Something like this:
 `
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json; ext=["https://jsonapi.org/ext/version", "https://jsonapi.org/ext/scopes", ...]
// ...
`

Any ideas?

**Comment by jugaadi** [comment]
As per [docs](https://jsonapi.org/format/1.1/#media-type-parameter-rules):
`The values of the ext and profile parameters MUST equal a space-separated (U+0020 SPACE, “ “) list of extension or profile URIs, respectively. `

**Comment by drnkwati** [comment]
Like this?
`
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json; ext="https://jsonapi.org/ext/versionU+0020https://jsonapi.org/ext/scopes"
`

**Comment by freddrake** [comment]
On Wed, Sep 14, 2022 at 9:03 AM Divine ***@***.***> wrote:

> Like this?
> How can I do the same for multiple extension url?: Something like this:
> HTTP/1.1 200 OK
> Content-Type: application/vnd.api+json; ext="
> https://jsonapi.org/ext/versionU+0020https://jsonapi.org/ext/scopes"
>
> Message ID: ***@***.***>
>
Escaping the space is not required in the headers, so just use a space
character instead of U+0020.

(That may be what you meant, but better to be clear.)


  -Fred

-- 
Fred L. Drake, Jr.    <fred at fdrake.net>
"There is nothing more uncommon than common sense."
  --Frank Lloyd Wright
