### ISSUE TITLE
Bulk delete as either extention or implementation

### ISSUE THREAD

**Issue by fietser97** [json-api/json-api#1709]
Good day,

We as a big company as part of the Dutch government are implementing Json-api.
This is going quite well and it's helping us standardize and speed up creations of api's in spring boot and Java. With angular as front-end.

Right now we are looking at the following problem. 
We have a list of people in the front-end and we want to delete a lot of them in 1 go. 
We need to delete the people that are allowed to be deleted and get a 207 back with deleted and not deleted (with a reason)
Unfortunately our id's are getting so big that we hit the http url limit of 2048 chars.

We looked at using atomic. But that says that it fails when 1 operation can't be executed. Which in our case is not an option functionally.

Is there any implementation that would help us for example a bulk option without the fail on error?

**Comment by jelhan** [comment]
Glad to hear that JSON:API serves you well so far.

Deleting multiple resources ok a single request is not supported by base specification. But it can be implemented using an extension for sure. Both with and without atomic guarantee.

I'm not aware of any existing extension, which supports bulk deletion beside the [Atomic Operations extension](https://jsonapi.org/ext/atomic/). You would likely need to write your own extension.

In general, performing multiple operations in a single request is done due to atomic requirement. Otherwise people often use multiple, parallel requests instead.

Why is using multiple delete requests, one per resource, not possible for you? Do you fear overhead of individual requests or running into API rate limits due to number of resources?

**Comment by fietser97** [comment]
@jelhan Firstly thanks for the response. 
It's what I found that there was no extension without atomic at this moment.
For the current call we are afraid of overhead mostly in user (angular) space with every request needing to be sent. From the user to us and back. And then us compiling it all together to 1 single response. (which is logic we'd prefer to have in the api) or bff. 
Functionally it's just not possible to use the atomic function. It might sound like a weird functional requirement. But it's one of those things we just need :) 

We have internally been talking about solutions and were looking if there was any chance a bulk delete would come back in the spec. Or if an extension exists.

**Comment by jelhan** [comment]
I feel it's unlikely that bulk deletion support will be added to the base specification. Especially without being atomic. That sounds like an edge case to me.

I would recommend defining an extension yourself for this use case.

**Comment by fietser97** [comment]
Alright, Thanks for the information :)
I'll close the ticket then.
