### ISSUE TITLE
Clarify requirement level for id key

### ISSUE THREAD

**Issue by andrewsardone** [json-api/json-api#181]
Based on [a discussion](https://github.com/json-api/json-api/pull/180#issuecomment-33019512) in json-api/json-api#180, we need to revisit the requirement level of the `"id"` key in documents.

The ID-based format states that the `"id"` key is [a MUST requirement](https://github.com/json-api/json-api/blob/91a62475d48a24a03ed3071933b47504fb7536b3/format/index.md#singular-resources), whereas the URL-based format claims that it is [a MAY requirement](https://github.com/json-api/json-api/blob/91a62475d48a24a03ed3071933b47504fb7536b3/format/index.md#singular-resources-1).

Does this difference matter? Do we want to allow for [documents without `id`s](https://github.com/json-api/json-api/pull/180#issuecomment-32990457), or do we want to mandate a [MUST across the board](https://github.com/json-api/json-api/pull/180#issuecomment-33015237)?

**Comment by steveklabnik** [comment]
`MUST`s must receive the highest bar of validation, because they're a forever promise.

Unless we have a compelling reason to absolutely require an ID field, it should be a `SHOULD`.

I do think that we have a decent reason: it's the unique identifier for this particular bit of information. But based on the other discussion, there may be good reasons for not allowing it.

**Comment by andrewsardone** [comment]
I can get down with `SHOULD`, but I'd also be interested in some examples where requiring an `id` puts an unnecessary burden on either a server or a client.

**Comment by dgeb** [comment]
I'm opposed to forcing the server to generate `id`s that have no meaning to it or the client. This may be the case with raw read-only datasets like auto-complete data or scientific measurements.

If these fringe cases can still be covered by `SHOULD`, then that works for me too.

**Comment by gr0uch** [comment]
Is it possible that a URL may not actually be a unique identifier? For example, there may be multiple routes to get the same entity, i.e. `/post/1/comments/2` or `/comments/2`, in which case the URL does not uniquely identify the entity. 

_edit: entity not resource, my bad_

**Comment by steveklabnik** [comment]
@daliwali , in REST parlance, you mean 'entity,' not resource. `/post/1/comments/2` and `/comments/2` are two different resources that may happen to map to the same entity.

Your point still stands: it's not going to be unique on an entity basis, which is what we care about.

**Comment by andrewsardone** [comment]
@dgeb could you give an example of this auto-complete data or scientific measurements without an `id` in the context of a client-server workflow, that is, the actual request, why a client would make this, and what the response would be?

**Comment by dgeb** [comment]
Let's say that a server stores `receipts` with the `vendor` field as a string instead of being normalized into a separate table. It provides an autocomplete service to look up those vendors by name:

GET /vendors?name=a*

``` javascript
{
  "vendors": [
    {name: 'Amazon'},
    {name: 'Apple'}
  ]
}
```

Another example might be looking up excerpts in a book or library:

GET  /excerpts?containing=woot&length=90

``` javascript
{
  "excerpts": [
    {text: "He proclaimed 'woot!' and the rejoicing commenced.",
     page: 567,
     offset: 189,
     links: {book: "12"}},
    {text: "'Woot! Woot! Woot!' exclaimed the excited captives.",
     page: 897,
     offset: 10,
     links: {book: "51"}}
  ]
}
```

In both of these examples, the primary documents are "pseudo-entities" on the server that are extracted from other entities. Because they're not expected to be returned to the server, they shouldn't require server-side `id`s.

**Comment by andrewsardone** [comment]
Thanks, @dgeb – those examples helped me understand.

I think the `vendors` example is an interesting case where a document's attribute kind of straddles the line over to a relationship, and I'm not sure if JSON API really has a good answer for that at the moment.

I'd probably put an `id` on `excerpts` – a client might want to bookmark them or store them for a faster local search – but I can see the scenario where it'd be excluded:

> Because they're not expected to be returned to the server, they shouldn't require server-side ids.

This seems like a good argument for the `SHOULD`. I'll submit a simple PR that can be rejected accordingly if it's jumping the gun.

**Comment by dgeb** [comment]
@andrewsardone - Glad we're in agreement on `SHOULD`. I think it's more appropriate than `MAY` because these edge cases will probably not be encountered in most APIs. Perhaps we should clearly document the rationale for omitting `id`s.

Anyway, let's start by making them consistent. Thanks in advance for the PR :+1:

**Comment by steveklabnik** [comment]
> I think it's more appropriate than MAY because these edge cases will probably not be encountered in most APIs.

Agree, `SHOULD` is the appropriate level here.
