### ISSUE TITLE
type of ids

### ISSUE THREAD

**Issue by MajorBreakfast** [json-api/json-api#190]
Currently the format specification doesn't say which type ids have. I'd say it's a string. (But there are currently some examples that use a number, though) Is there a benefit in allowing Numbers? When the URL is built this information gets lost anyway.

**Comment by steveklabnik** [comment]
One of the problems with allowing non-string types is that JSON basically doesn't say what type its numbers are, though floating-point only is a good bet.

**Comment by guillec** [comment]
:+1: for string

**Comment by mrec** [comment]
:+1: for string. Given the importance of ids I'd actually go further than that and include some recommendations on choosing good id strings.

Partly that means character restrictions, especially since all the examples assume a `/type/id,id?queryargs`-style URI template. So `,`, `/`, `?` and `#` are right out. IIS by default always 404s any paths containing `%` or `.`. And so on. Something like "alphanumerics and hyphen only" sounds like a reasonable SHOULD.

There's also the question of how strictly to enforce the opacity of ids. The spec seems (?) to lean toward ids having no meaning outside navigation via the API, but for cases like countries or languages or currencies which have well-defined and widely-used ISO ids defined, refusing to use them on a point of principle is arguably forcing unnecessary chattiness on clients wanting to do any kind of interop.

EDIT: the character-restriction part looks like it overlaps with #69

**Comment by MajorBreakfast** [comment]
@mrec This restriction is not needed due to URI encoding ([give it a try here](http://meyerweb.com/eric/tools/dencoder/))

**Comment by mrec** [comment]
@MajorBreakfast No, URI encoding doesn't help for the path portion. The problem is that IIS [disallows certain characters there by default](http://blogs.iis.net/nazim/archive/2011/04/18/use-of-special-characters-like-in-an-iis-url.aspx) _even if urlencoded_, and I don't think it's the only one.

Yes, most issues can be probably worked around in config, but it'd be better to dodge it in the first place.

EDIT: better ref link for IIS behaviour.

**Comment by MajorBreakfast** [comment]
Okay, then: MUST be a string which SHOULD contain only alphanumeric characters. Urlencoding MUST be used (for security).

That alright? SHOULD/MUST is of course debatable but I chose MUST because url de/encoding only works well if both sides apply it once, plus it's easy to implement and very cheap.

**Comment by mrec** [comment]
First sentence looks broadly OK, though I'd be a bit looser; hyphen is safe and appears in many widely-used id candidates, e.g. ISO dates ("2014-02-26") and languages ("en-GB"). I strongly disagree with the second sentence, though; urlencoding where it makes any difference at all does so by _introducing_ `%` , and as explained in [the link](http://blogs.iis.net/nazim/archive/2011/04/18/use-of-special-characters-like-in-an-iis-url.aspx) above `%` in the path will tend to break things.

**Comment by MajorBreakfast** [comment]
Hmm. So we limit the charset to alphanumeric chars, dashes and underscores? Is it too strict?

**Comment by pnsantos** [comment]
Been following this spec evolution for some time, I'd like to leave myy 2¢ on this.

The only way to be _sure_ that id chars won't be percent encoded by servers and/or clients is to use the [Base64 and Filename safe alphabet](http://tools.ietf.org/html/rfc4648#section-5) which like MajorBreakfast said is `0-9` `a-z` `A-Z` `_` and `-`

Any other char can be percent encoded by an implementation (even though the [spec](http://tools.ietf.org/html/rfc3986) says there can be other characters which don't require percent encoding, some implementations do it anyway, common examples are `~` and `.`)

So at most I'd say it could be beneficial to say that ids _should_ use the aformentioned alphabet (the added benefit of this is that internally an id can have any number of characters, implementations can always Base64url encode the internal id and expose that in api representations in order to comply with the _should_).

**Comment by MajorBreakfast** [comment]
Link seems broken. Or rather ietf is currently down.
Two concerns about base64: It makes it unreadable for people and standard base 64 uses `/` and `+`.

**Comment by pnsantos** [comment]
Weird... the links work just fine here.

The base64url encoding is an alternative to the "standard" base64 encoding scheme. It uses `-` and `_` instead of `+` and `/` respectively (it intended purpose is exactly for systems where characters like `/`, `.` or `~` have special meaning).

But yes, encoding in base64url would make it unreadable for people, I only sugested that as a way implementation could even use "illegal" URI characters in ids and still able to expose them with a simple transformation.

Nevertheless I stand by my comment that it would be beneficial to present `0-9` `a-z` `A-Z` `_` and `-` as the recommended alphabet for ids.

**Comment by MajorBreakfast** [comment]
It really bugs me that IIS can't handle percent signs in URLs. URL encoding would have been perfect because it's transparent unless special characters are in use.

@mrec Are you sure URL encoding doesn't work? The article says _This configuration will never allow a bare ‘%’_ [...] _it must be escaped as "%25"_. That suggests that URL encoding is even desired.

**Comment by mrec** [comment]
(Re-commenting from original account for consistency)

@MajorBreakfast It's been a little while since I was banging my head against this, but I'm 100% sure that urlencoding doesn't work in the path, in the general case, with the default config.

From some quick experimenting just now: `.` is OK unless it's the last character of the path, in which case it doesn't work whether urlencoded or not. `%` doesn't work anywhere in the path whether urlencoded or not, per the "Layer 2: IIS request filtering (blocked characters = ‘%25’, ‘.’, ‘%2b’)" section of the article.

More fundamentally, and unrelated to any IIS peculiarities, I think urlencoding is supposed to be transparent, e.g. in the server-side frameworks I'm familiar with, `type/a%2Cb,c%2Cd` and `type/a,b,c,d` will be indistinguishable as normally presented to application code.

**Comment by MajorBreakfast** [comment]
Nobody actually uses ids with special characters. But restricting the charset for everybody is too strict. Since URLencoding is transparent it doesn't affect those who stick with the usual chars. Just those people who actually need special characters have to choose a server side framework that can deal with it. (e.g. express.js)

So I'm still for
MUST be a string which SHOULD contain only alphanumeric characters, dashes and underscores. Urlencoding MUST be used (for security).

@mrec That alright?

**Comment by mrec** [comment]
I can't see how requiring a client to urlencode ids that don't need urlencoding has anything to do with security.

If you _are_ stuck with ids with silly characters, IMHO it's much better to pass them on the querystring (where encoding has fewer issues) rather than in the path.

I'd be happy with @pnsantos' base64url charset as a SHOULD. I don't think the spec need require any particular workarounds when that's not possible, although a few suggestions (base64url encoding, querystring) might be nice.

**Comment by MajorBreakfast** [comment]
Not being able to parse URLencoded URL path segments can be considered a bug in IIS. Adding a new special IIS compatible encoding scheme or unreasonable strict character limitations into the standard isn't sensible. Especially since we already agreed on having a SHOULD for alphanumeric + dashes + underscores. Let's keep it simple. Nobody uses special characters anyway.

Quick reminder: base64url is bad, because the output doesn't resemble the input. A request for id `1` means you request `MQ==` o.O

**Comment by mrec** [comment]
Nobody is proposing a special IIS compatible encoding scheme or unreasonable strict character limitations or mandatory base64url-encoding. In fact, we all seem to be in violent agreement on the preferred SHOULD at this point.

**Comment by steveklabnik** [comment]
Adding to 1.0.

**Comment by SphtKr** [comment]
Coming to this because I saw #69 closed. A few comments from someone working on a server-side implementation in ASP.NET:

@MajorBreakfast Re: "Nobody actually uses ids with special characters". Unfortunately: I do. And the reason for that is twofold. Right now, I have a C# class library that attempts--among a few other things--to almost out-of-the-box act as a broker between Entity Framework model objects and JSON-API format REST endpoints. I'm having pretty good success so far. But, I have to handle a few things generally. 

One of which is an entity without a single-field primary key. At the moment, for any entity with a compound key, I actually _JSON serialize the EntityKey object and make that the ID_. That means the serialized format contains JSON characters including , and { } [ ], just for instance. Now, in that case, I've considered using base64 encoding or something similar--however, that's guaranteed to make the ID string even longer than it already is, and that bumps me up against the discussion in #72 though (as I said there) there's probably not a place in the spec to deal with that issue--the implementations will have to figure out batching or something similar.

However, second, because I'm trying to make a generalized library layer here, I don't know _what_ my users are going to use as IDs. Therefore, I need a way to reliably handle _any_ ID. Usually, that's simply a matter of looking at the spec for whatever and seeing what the string escaping rule is...which is why I opened #69 in the first place.

So, whatever the rule will be for dealing with commas and other special characters in an ID, please at least have one. I'm okay with requiring the rule to be URL-encoding. And to be clear, I think what we're talking about is actually double-URL-encoding...that is, requesting two objects with IDs `a,b` and `c,d` would look like `http://host/namespace/resource?ids=a%252Cb%2Cc%252Cd`. Because as @mrec correctly noted,  `type/a%2Cb,c%2Cd` and `type/a,b,c,d` are functionally identical--I think the server is required to see both of these as the same.

And yes, with the default config, IIS freaks out about this double-escaping. It's trying to save developers from themselves by preventing path traversals and other injection attacks that you haven't properly prevented yourself. Its almost as bad--but not quite--as PHP's `magic_quotes_gpc`. So, it's not quite that IIS _can't_ process URL-encoded path components, but that by default it prevents this. Yes, it was extremely annoying when I discovered it, but in my experience the bigger problem wasn't that IIS couldn't handle it without a config change, it was that Visual Studio's development server couldn't handle it _and couldn't be configured otherwise!_ (though I think that server has been deprecated as of VS 2012). As far as I'm concerned, I'm okay with requiring my users to change their config to deal with this (though I don't know, perhaps some hosts won't allow it?).

**Comment by MajorBreakfast** [comment]
Jep I think that's why URL encoding is a must. A situation like yours is what I had in mind.

**Comment by SphtKr** [comment]
Looking over what I wrote, now I'm having a brain-melting moment. Okay, if an ID is `a,b` a comma in it and you request that single object, you'd request `/type/a%2Cb`. However, if you need to request two objects `a,b` and `c,d`, you'd have to use `/type?ids=a%252Cb%2Cc%252Cd` ... this seems right and wrong at the same time. There's no need to double-escape the first instance, but double-escaping the second is necessary...on the other hand, shouldn't they be the same?

Incidentally, are we allowing requesting two objects like `/type/42,43` now? If so that's new since I checked.

**Comment by MajorBreakfast** [comment]
The comma remains unencoded

**Comment by MajorBreakfast** [comment]
Or more detailed: Commas are allowed in the URL itself. But they are reserved in components like IDs. We address this by URL encoding the ids. e.g. "/type/42,43" is a valid URL, "42" and "43" are url encoded. If "43" is a some complicated JSON id instead it's fine as well. BTW "/type?ids=42,43" would also do the trick. But we don't use that.

**Comment by MajorBreakfast** [comment]
I created a PR that addresses the points discussed in this issue. Is everybody happy with that?
https://github.com/json-api/json-api/pull/209

**Comment by SphtKr** [comment]
Sounds good to me. I'm happy as long as _something_ is specified.

**Comment by wycats** [comment]
This looks good to me. In Ember Data, we always convert IDs to strings at the boundaries (to avoid possible confusion when both strings and numbers are used), and this spec sounds great to me.

**Comment by wycats** [comment]
Superseded by #209
