### ISSUE TITLE
Requesting fields

### ISSUE THREAD

**Issue by indirect** [json-api/json-api#20]
Some objects have fields that are either large (like associated binary data) or expensive to calculate. Is there a conventional way to request optional fields, or limit the response to only fields that are relevant to the client?

**Comment by steveklabnik** [comment]
Outside of json-api, this is usually done by not including every field, and then relying on people following a `self` link to fetch a 'full' representation.

I'm not sure this issue is addressed in the type itself currently, though.

**Comment by paddycarver** [comment]
This could be simple enough to support using the querystring to filter objects?

**Comment by hjdivad** [comment]
It's certainly possible to do this while still conforming to the spec.  I think the discussion is whether or not supporting the feature should be required to be spec-conformant.

One possibility is to make the feature optional.  For example, we might say that a server MAY support requests for partial documents, but conforming servers that do support it are expected to follow some well known format.

Of the two suggested, I prefer letting clients specify fields rather than having the server provide URLs in advance that provide different sets of fields.  It's the client that knows what fields she needs.

**Comment by paddycarver** [comment]
I'm a fan of the MAY. It can be a lot of work to support this server-side, and to be forced to do it for every endpoint, regardless of how silly it may be (when was the last time you wanted to make a network request to get just a single field of a comment?) in order to be spec-compliant may be too onerous and turn people away from the spec. Saying it's optional, but if it's present, it should be in this format is a good way to provide the same structure without overburdening the implementers with unnecessary checklists.

**Comment by dgeb** [comment]
In an API I have under development, I support this by allowing an optional comma-separated list of fields to be specified for each resource type. For instance:

```
/posts/1?include=comments&post_fields=title,author&comment_fields=date,author
```

This is optional. Without specifying fields, all are included.

I have already centralized and generalized all this logic to work with AMS so that it's transparent to controllers and serializers, and I will gladly share if this approach is chosen for the spec.

**Comment by b** [comment]
"Outside of json-api, this is usually done by not including every field, and then relying on people following a self link to fetch a 'full' representation."

Right. Per our exchange on Twitter, this is why you actually want self links.

**Comment by kjwierenga** [comment]
self links +1

**Comment by steveklabnik** [comment]
Yup, I agree.

@wycats any issues with self links? I can't imagine there should be.

**Comment by dgeb** [comment]
There are strong client and server side performance benefits to providing a convention by which a client can request a subset of fields per resource type. As @indirect states, some fields are "either large (like associated binary data) or expensive to calculate." In fact, any unneeded fields become expensive when multiplied over a large enough response.

I don't think that just providing a default field set combined with `self` links to full representations is sufficient for many APIs. This approach places a pretty big bet that an API's clients are interested in the same default fields per resource, because the alternative is _an additional request per resource_ (to `self`) to fetch anything else. If I'm understanding this correctly, it seems inordinately expensive.

Of course, a default set of fields is needed per resource type. But I'd very much like to standardize a method to specify custom fields per resource type in a single request, like [my proposal above](https://github.com/json-api/json-api/issues/20#issuecomment-17460517). We don't have to choose performance vs. discoverability in this instance - we can have both.

**Comment by indirect** [comment]
Isn't the other option to provide some kind of aggregate option, so you can ask for the full data on objects with ids X, Y, and Z?

**Comment by b** [comment]
That is the either/or proposition Dan is suggesting we avoid. There is a
tension here between what belongs in the protocol and what belongs in the
resource design. If a field is actually a big blob of "associated binary
data" why wouldn't it be a link to another resource that only contains that
data? Are there real, common situations in which you want giant data fields
embedded in resources which you then need to avoid requesting?

**Comment by kjwierenga** [comment]
The HTML-browser analogy applies here. Would you inline binary images in a HTML document? In the same way you shouldn't inline large attribute values. 

KJ

Verstuurd vanaf mijn iPhone

Op 19 mei 2013 om 20:55 heeft Benjamin Black notifications@github.com het volgende geschreven:

> That is the either/or proposition Dan is suggesting we avoid. There is a 
> tension here between what belongs in the protocol and what belongs in the 
> resource design. If a field is actually a big blob of "associated binary 
> data" why wouldn't it be a link to another resource that only contains that 
> data? Are there real, common situations in which you want giant data fields 
> embedded in resources which you then need to avoid requesting?

**Comment by dgeb** [comment]
@kjwierenga Actually, I tend to in-line many images in css with `data-uri` when they are below a size threshold in order to avoid additional requests. If they are above that threshold, I'll provide a link for the images. Similarly, I think it's difficult to make rules about the appropriateness of allowing in-line data as fields for a resource in an API. While it may make perfect sense to in-line data for small avatar images along with a `user` resource, it's generally better to return links rather than extremely large images in-line. 

All this to say that I think that the appropriateness of in-line data vs links is best left to each implementation.

**Comment by kjwierenga** [comment]
I agree. There are reasons to have both inline and linked resources.
Op 20 mei 2013, om 04:11 heeft Dan Gebhardt notifications@github.com het volgende geschreven:

**Comment by SphtKr** [comment]
I think @dgeb made a good point: 

> In fact, any unneeded fields become expensive when multiplied over a large enough response.

So partly in response to @b's comment, I think there are real, common situations where you'd want to exclude fields from a response.

For example, I have a use case with a large list of people with a large number of fields each--none are particularly large data fields, but there are many. At the same time, I want to load a large number of these records (maybe even all of them) in order to make a autocomplete/typeahead control work for selecting a person by name. So what I want in the case of requesting a single person is all of their fields--but if I request all 500, I only want their ID and name fields (for this to work, the client library would have to support partially loaded records for non-relational data).

Reading this discussion and thinking about it, I'd think there'd be a case to make for both `include` and `exclude` parameters, and maybe even `exclude_all` and `include_all`, where the inverse specific overrides the all-inclusive parameter. E.g. `/people?exclude_all=true&include=id,first_name,last_name` and `/people/1?include_all&exclude=user_photo` (BTW, `exclude=id` would probably be illegal/ignored, and `exclude_all=true` would not exclude `id`, so `include=id` would be superfluous).

And I agree with @hjdivad and @paddyforan, it makes sense for most of this to be optional in the spec (using "MAY"). It might be worthwhile to specify that any service that serves a partial object (by default or by supporting `exclude`) then MUST support `?include` to retrieve the missing fields. But other than that this looks like "level 2" type API functionality.

**Comment by jcallaha** [comment]
I realize this issue is closed but I am concerned about the client having to request sparse fieldsets in seemingly two separate mutually exclusive ways: either a **fields** parameter if all the fields are in the primary document, or one or more **fields[DOCUMENT_TYPE]** parameter(s) if any fields are not in the "main" document?

Given that the example for including related documents is using dot-separated paths as follows:

```
GET /posts/1?include=comments.authors
```

...why not use the same dot-separated path for sparse fieldsets?

```
GET /posts?include=authors&fields=id,title,people.id,people.name
```

This seems easier to implement, easier to read, and more consistent than:

```
GET /posts?include=authors&fields=[posts]=id,title&fields[people]=id,name
```

I'm happy to draft a pull-request if this makes sense to anyone else?

**Comment by steveklabnik** [comment]
Do any existing projects use the dot notation? Many frameworks use the `[]`s.

**Comment by dgeb** [comment]
@jcallaha There is a difference (perhaps subtle) between dot and bracket usage. 

Dots are used to separate _paths_, as in `?include=comments.authors`. Another example usage is in the `links` section:

```
"links": {
    "photos.author": "http://example.com/people/{photos.author}"
  }
```

However, fields are specified for document _types_, such as `fields[people]=id,name`.

It's important that fields be specified by type rather than path because a compound document may group together documents of one type aggregated from multiple paths.

Another nice aspect of specifying fields by type is that the client can be explicit for certain types and accept default fields for others.

**Comment by jcallaha** [comment]
@dgeb Thank you for the quick and thoughtful response - I think I get the field/path distinction now and see why my example of **?fields=people.id** was incorrect.

So - if you'll indulge me - what about the following:

```
GET /photos?include=author&fields=id,title,author.name
```

This would seem to have some slight advantage in that if the server implemented the URL-based API and provided the top-level "links" object (providing the **type** of an **author**) then the client wouldn't have to know ahead of time what **type** of document an **author** was, and in fact the server could change the **author** to be another **type** without the client having to change either its request or its process as long as the fields it wanted were still present in the new type.  In this example the ?include=author could even be considered superfluous as requesting the author.name implies the inclusion.

Another use case that could be handy is where the primary document may have more than just one relationship of the same type (e.g. people), but wants different levels of detail depending on the relationship...

Sticking with your photos example, lets say a photo has one **author** but several **subjects**, both are relationships to **people** documents.  

A client might want the name, email, and a avatar of an author but just the names of subjects as there might be a number of them especially over several photos...

   GET /photos/1?include=author,subjects&fields=author.name,author.email,author.avatar,subjects.name

Imagine the photo is of 15 people (subjects), then the resulting compound document might end up like:

``` json
{
  "photos": [ { "id": 1, ..., "links": {"author": 1, "subjects": [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]} } ],
  "linked": {
    "people": [
      {"id":1,"name":"Photographer Pete","email":...,"avatar":...},
      {"id":2,"name":"Poser Paula"},
      {"id":3,...},
      ...
      {"id":16,"name":"Subject Steve"}
    ]
  }
}
```

The client now has exactly what it needs to render a view for photo 1.  Thoughts?

**Comment by dgeb** [comment]
@jcallaha URL-based APIs can specify the types of relationships in the `links` object. See the compound document example:

```
"links": {
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    },
    "posts.comments": {
      "href": "http://example.com/comments/{posts.comments}",
      "type": "comments"
    }
  }
```

I understand your point about wanting to return _exactly_ the fields required for each relationship, and how this would lead to the minimum possible payload. This would require a UNION of all the relationship fields per document, which gets tricky to implement efficiently. It gets even trickier when thinking about potentially sorting or even paginating those related documents by fields that may be present from one relationship but not another. Plus, the client can't deal with all the documents of each type uniformly. All things considered, it seems cleaner and clearer to me to keep fieldset, sorting, etc. concerns on a per-document-type level, even if it means that payloads are larger in some cases.

**Comment by steveklabnik** [comment]
>  even if it means that payloads are larger in some cases.

Yup, this is one of the tradeoffs of the hypermedia style. You can't have rigid definitions and minimum representations, occasionally larger payloads are traded for the flexibility such things bring.

**Comment by jcallaha** [comment]
@dgeb The "links" object is one of the reasons I find the path based field selection more intuitive - I may be thinking of it wrong but in the model in my head I am thinking of a generic client (think API explorer) as accessing any related document by using the "links" field, so in fact the client may not need to know a related document's type ahead of time if the server is providing the "links" object on every GET.

You are correct that it would require a UNION of the relationship fields, but only on the documents referenced through different relationships, not the entire set of documents of that type. Presumably the server implementation already has to do something to avoid duplication of the same document when included by different relationships?

Sorting and pagination in fact make it more interesting... I had initially thought sorting and pagination would only be applicable to the primary document, but if they were to be included for relationships to the primary document (e.g. the most recent 15 comments of a blog post) wouldn't the sorting and limiting necessarily have to be in the "links" object in the primary document rather than by a the related document's type in the "linked" object?

An example may be clearer than my poor words - with our photos with two separate relationships to "people" documents, author and subjects:

``` json
{
  "photos": [ { "id": 1, ..., "links": {"author": 1, "subjects": [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]} } ],
  "linked": {
    "people": [
      {"id":1,"name":"Photographer Pete","email":...,"avatar":...},
      {"id":2,"name":"Poser Paula"},
      {"id":3,...},
      ...
      {"id":16,"name":"Subject Steve"}
    ]
  }
}
```

What would a pagination mean on the "people"-type documents?  limit to 5 "people"?   Some of those people might be authors some might be subjects.  Wouldn't photos.links.author and photos.links.subjects have to be adjusted accordingly, so if the "people" object representing the "author" wasn't in the "page", the primary document would indicate no author?

If a client wanted to know the author, and say the first 10 subjects of a photo, or a blog post and the most recent 30 comments and their authors, these can be expressed using the path notation as follows:

   GET /photos/1?include=author,subjects&limit=subjects=10
   GET /post/1?include=comments,comments.author&sort=-comments.postTime&limit=comments=30

In the document type notation it might be:

```
GET /photos/1?include=author,subjects&limit[people]=10
GET /post/1?include=comments,comments.author&sort[comments]=-postTime&limit[comments]=30
```

The first case is essentially non-deterministic in the document-type notation because the author might not be included in the first 10 people (assuming author and subjects both populate the people related document).

We've gotten a ways off of the ?fields= issue so I apologize if it makes more sense to move this somewhere else, but I think this is very good discussion.  It has also made me think that the top-level "linked" object is broken, but I will save that for another issue.
