### ISSUE TITLE
Need "sideposting", or, the ability to do relationships when POSTing

### ISSUE THREAD

**Issue by fivetanley** [json-api/json-api#202]
Talked with @wycats in IRC about this one, basically, here is the scenario:

Say the canonical blog example has two models, a `Post` and an `Author`. The `Post` model needs an `Author` upon creation, otherwise the response is rejected. This means we cannot do a `PATCH` request later to add the relationships. For reasons unknown, the `Post` will not assume a default `Author`, or use the currently authenticated user as the `Author`. How do we create a relationship when `POST`ing to the server to create the new document?

Perhaps @wycats can expound upon what he meant by "sideposting" here.

**Comment by wycats** [comment]
I mean the opposite of sideloading of course! :wink:

**Comment by whatthewhat** [comment]
+1  for this

If I'm not mistaking this seems similar to https://github.com/json-api/json-api/issues/105.
Another blog-related example would be creating a `Comment` for a `Post`.

**Comment by jcallaha** [comment]
I believe Fortune implements this just by having a "links" attribute present in the POST document.  

```
POST /posts
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "posts": [{
    "title": "Rails is Omakase",
    "links": {
      "author": "9",
    }
  }]
}
```

Maybe we just need to add an example to the Creating a Document section?

**Comment by dgeb** [comment]
@jcallaha seems right to me :+1: 

@wycats maybe you don't intend this, but the term "sideposting" sounds like creating related resources (e.g. an `Author` and `Post`) with a single request and then linking them. This seems verrrry tricky, esp. with server-generated ids.

**Comment by gr0uch** [comment]
@jcallaha Correct, posting a document with links present will associate it to the linked resource(s). However, creating multiple entities that are interlinked with a single POST is impossible at the moment.

**Comment by whatthewhat** [comment]
Is @jcallaha's example still correct when using link objects to represent relationships?

i.e.

``` js
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": {
        "href": "http://example.com/people/17",
        "type": "people"
      }
    }
  }]
}
```

**Comment by gr0uch** [comment]
@whatthewhat It should be (though it is not implemented in fortune yet, I really need to maintain stuff)

**Comment by jcallaha** [comment]
I don't know if fortune has been updated to handle the relatively new "link" object nomenclature - but I would expect from the JSON-API spec that your example document should be considered valid.

Presumably this would be the equivalent in PATCH?

```
PATCH /posts/1

[
  { "op": "replace", "path": "/posts/0/links/author", "value": {"href":"http://example.com/people/17","type:"people"} }
]
```

What is confusing is how one would go about doing a replace or remove operation if author was a to-many relationship?  I didn't see anyone addressing PATCH in #187 - does the path "/posts/0/links/author/17" represent the author with the `id` of 17 as I believe it would in the case of an array of ids or the 17th element of the array?  If `id` isn't required in a link object it would seem the only way is to consider the patch as an array rather than a set of ids?

**Comment by dgeb** [comment]
@jcallaha - As discussed in #176 and #193, when updating arrays of documents, we should consider them functionally equivalent to sets that are keyed by document ids. It doesn't make sense in a distributed system to reference positions in an array that would need to be tested before each operation.

As for your example, I would prefer that the operation's path be relative to the request path (`"/links/author"` instead of `"/posts/1/links/author"`), although this is a change from the current spec.

So, if author is polymorphic, I think this should be valid:

```
PATCH /posts/1

[
  { "op": "replace", "path": "/links/author", "value": {"id":"17","type:"people"} }
]
```

I'm planning a PR to consolidate these thoughts and try to reach consensus.

**Comment by gr0uch** [comment]
@dgeb are you sure that the path you are trying to supersede is correct? Perhaps it should be `/posts/0/links/author` regardless of the ID of the post (whether it is `1` or `a38df90`), since the path is only concerned with traversing the structure of the document. 

For your reference, the current documentation has this example:

```
PATCH /photos/1
Content-Type: application/json-patch+json

[
  { "op": "replace", "path": "/photos/0/src", "value": "http://example.com/hamster.png" }
]
```

**Comment by dgeb** [comment]
@daliwali sorry, that was probably a bit of subliminal editorializing on my behalf because I find the current spec to be inconsistent in this regard. 

For example, arrays are treated as both arrays (`/photos/0`) and sets keyed by ids (`/comments/5`) in the to-many relationships section:

```
PATCH /photos/1

[
  { "op": "remove", "path": "/photos/0/links/comments/5" }
]
```

I'd like to iron out these inconsistencies by clarifying the schema against which PATCH operations are made, and ensuring that the request path and operation paths complement each other.

**Comment by steveklabnik** [comment]
Adding this to the 1.0 milestone for the same reason as #205, which may be the same thing.

**Comment by wycats** [comment]
I spoke with @dgeb about this and ultimately the solution is a "grand unified theory" that explains all of the operations in terms of `PATCH`. That way, we can describe any compound operation as a `PATCH` operation, and specify conveniences (`POST` with embedded, `POST` to a relationship) in terms of `PATCH` without fear that several conveniences will compose poorly.

Don't let "grand unified theory" scare you. It's a spec refactoring that we need to do anyway, and @dgeb has already taken a stab at it that's relatively compact and almost complete. Let's aim to get this spec refactoring in immediately after 1.0, and then start adding some conveniences right away to help people who aren't ready to let `PATCH` into their hearts.

**Comment by darkbaby123** [comment]
The `PATCH` is a good and flexible way for compound operations. But I'm curious that how to save multiple related resources in one request. Because some of the operations need the related resource ID, and the only way I can think out is generating ID in client side.

Given PivotalTracker as an example, it has multiple stories, and each story has many comments. The user can add a new story, then add some comments and save them together. I checked their API request, they uses their own way like `PATCH` + Rails nested attributes to save things together. Like this:

```
POST /services/v5/commands?envelop=true

{
  "command": {
    "command_uuid": "XXXXXX-XXXXX-XXXX-XXXX",
    "type": "story_create",
    "parameters": {
      "name": "Story name",
      "description": "Story description"
      "comments": [
        {
          "text": "Story comment 1"
        },
        {
          "text": 'Story comment 2'
        }
      ]
    }
  }
}
```

They use command (similar concept to `PATCH` operation) to express story creation but use nested comments to express the comments belongs to which story. I think without resource ID, a good way to express resource relationship is nested json structure. BTW since all operations are commands so they just use a single API endpoint `/services/v5/commands` to handle all kind of operations. It's similar with always using `PATCH` with root url.

With current JSON API this is what I can guess how to do it, but it MUST have client side ID.

```
PATCH /

[
  {
    "op": "add",
    "path": "/stories",
    "value": {
      "id": "AAAA-AAAA-AAAA-AAAA",
      "name": "Story name",
      "description": "Story description"
    }
  },
  {
    "op": "add",
    "path:": "/comments",
    "value": {
      "id": "BBBB-BBBB-BBBB-BBBB",
      "text": "Story comment 1",
      "links": {
        "story": "AAAA-AAAA-AAAA-AAAA"
      }
    }
  },
  {
    "op": "add",
    "path:": "/comments",
    "value": {
      "id": "CCCC-CCCC-CCCC-CCCC",
      "text": "Story comment 1",
      "links": {
        "story": "AAAA-AAAA-AAAA-AAAA"
      }
    }
  }
]
```

In this case, comment ID is not necessary to generate in client side, but story ID is necessary because the 2nd and 3rd operation need it to link comments to story.

But using client side ID instead is not an easy refactoring for many systems. So I expect JSON API has a standard to saving multiple related resources without client side ID.

Any thoughts?

**Comment by ahacking** [comment]
JSON API requires that client generated ids must be UUIDs (V4 is not prescribed but is the variant of UUID you should probably use).

I've suggested that JSON-API needs to have at least two profiles, one for V4 UUIDs aka "life is easy" and another for server assigned IDs aka "life is hard" for legacy use.  An API that supports client assigned ids is a very different beast to one that uses server assigned ids. Once you start trying to serialise or patch arbitrary object graphs, server assigned ids become unworkable IMO.  But switching to UUIDs may not be something that can easily be retrofitted to an existing system given assumptions/expectations about keys being monotonically increasing integers. 

My recommendation for new systems is to always use v4 UUIDs which can be assigned in clients, or in certain cases you can alternatively use a mostly invariant natural key (eg country code or ID assigned by an authority).  There are many benefits to UUIDs with the only downside being a slightly larger ID, but they also provide a bit more security on the server side (they're not guessable), they can also be used as a shard key for scaling the database backend, and they also better support arbitrary peer-peer synchronisation and eventual consistency models.

Once you have UUIDs you will look at your JSON API quite differently and things can be a lot simpler on both client and server.  It seems apparent that you can also have a reduced set of endpoints on a server once you start sending arbitrary object graphs via PATCH. Similarly when you have server sent events or web sockets its simpler to just have a single "/firehose" endpoint for subscribing to object graph changes.

**Comment by darkbaby123** [comment]
I checked the JSON API client generated ID again. Yes it must be UUID. The IDs in the example is not correct.

What I want to say is that we can not force user to use client generated ID for JSON API. Because many system still use server generated ID and can not easily change to client generated ID, and transform those system to client generated ID is not an easy thing. So for saving multiple related resources it's better not to force user to use client generated ID. But it can be a recommended solution and tell user with client generated ID things will become easier. :smile:

**Comment by ahacking** [comment]
Well my view is that it is kind of disingenuous to try and support both styles of IDs in the spec as you end up making so many compromises to accommodate both approaches,  the result is a sea of ifs, buts and MAYs and a spec that is far from streamlined, when in fact if you did make a firm choice everything could be much simpler.

A good spec has less choices and variations that implementors have to be concerned with yet is able to meet the requirements/use cases. The charter/goal of json-api AFAIKT is to settle on some very good design decisions and end the "json api design debate". Currently json-api doesnt quite get there because of the overwhelming options it provides and from where I sit it really is approching a kitchen sink committee designed  camel.  The only way to meet the goals of json-api  given where we are is a set of profiles on top of the spec as there are just too many options currently.

A big gap that I see in the current json-api effort is a well documented set of use cases and requirements for exactly what problems json-api is supposed to solve. Certain things need to be ruled in or out of scope for the spec, only then can anyone really evaluate the merits of different approaches to meet the required capabilities. What is currently occurring is detailed critique of features/approaches against some very flimsy unspoken requirements. So its never clear if a proposal or suggested change is meeting the needs or not, or if it is making the right trade offs. The rationale for why things are the way they are in json-api is largely lost.

**Comment by bintoro** [comment]
Is there some obstacle to simply including a `linked` container in the request that would hold the related objects?

``` json
POST /articles
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "articles": {
    "title": "Flask is à la carte",
    "tags": ["db987127-2fdc-44b3-9643-ec60fb240419", 
             "1b6be64d-0e4a-4599-87b3-c8c99ef8fc8b"]
  },
  "linked": {
    "tags": [{
      "id": "db987127-2fdc-44b3-9643-ec60fb240419",
      "label": "JSON"
    }, {
      "id": "1b6be64d-0e4a-4599-87b3-c8c99ef8fc8b",
      "label": "REST"
    }]
  }
}
```

If the implementation mandates server-generated IDs, the response would include the client-supplied IDs alongside the final IDs...

``` json
{
  "articles": {
    "id": "777",
    "title": "Flask is à la carte",
    "tags": ["386", "387"]
  },
  "linked": {
    "tags": [{
      "id": "386",
      "_temp_id": "db987127-2fdc-44b3-9643-ec60fb240419",
      "label": "JSON"
    }, {
      "id": "387",
      "_temp_id": "1b6be64d-0e4a-4599-87b3-c8c99ef8fc8b",
      "label": "REST"
    }]
  }
}
```

...or in a separate mapping:

``` json
{
  "meta": {
    "ids": [{
      "type": "tags",
      "client": "db987127-2fdc-44b3-9643-ec60fb240419",
      "server": "386"
    }, {
      "type": "tags",
      "client": "1b6be64d-0e4a-4599-87b3-c8c99ef8fc8b",
      "server": "387"
      }]
    }
  },
  "articles": {
    "id": "777",
    "title": "Flask is à la carte",
    "tags": ["386", "387"]
  },
  "linked": {
    "tags": [{
      "id": "386",
      "label": "JSON"
    }, {
      "id": "387",
      "label": "REST"
    }]
  }
}
```

**Comment by steveklabnik** [comment]
Given that this is an additive feature, I'm going to de-milestone it for 1.0.

**Comment by tkellen** [comment]
[This feature is milestoned for 1.1](http://discuss.jsonapi.org/t/json-api-weekly-meeting-june-22nd-2015/23)

/ref #795
