### ISSUE TITLE
Creating two related objects in one POST

### ISSUE THREAD

**Issue by searls** [json-api/json-api#205]
This seems quite related to @fivetanley's #202. I'm new to JSON API, so please be gentle with me.

We have a simple example where we'd like to create a `Chat` object with a single POST, but also embed the first `Message` in the same request. Whether we "side-post" them or embed them, the question is what the proper way to request they both be created at once _and_ related to one another. An example bit of JSON we imagined POSTing:

``` json
{
  "chats": [{
    "messages": [{
      "content": "O HAI"
    }]
  }]
}
```

And then receive a response like:

```
{
  "messages": [{
    "id": 2,
    "content": "O HAI",
    "chat_id": 1
  }],
  "chat": {
    "id": 1,
    "message_ids": [2]
  }
}
```

We've implemented this for ourselves, but we're curious if there's a "right" way per the spec (we searched and weren't able to find it).

**Comment by butsjoh** [comment]
We had the same need for something but we sticked with the given semantics of defining links and linked as the spec is using to describe relationships. Works out really well in our situation where we threat the creation of a conversation and the first message as one atomic action. It is consistent and easily understandable. I do agree it should be more clear in the spec on what could be valid implementations for certain situations but i can understand why this topic is not really easy to propose a solution for.

```
{
    "conversations": [
        {
            "subject": "Hello",
            "links": {
                "participants": {
                    "ids": [
                        "81bd6f56-41dc-419f-89b5-c9a3d53e010e",
                        "8f468f75-1332-42d2-8f3f-aa79aab0ebe2"
                    ]
                }
            }
        }
    ],
    "linked": {
        "messages": [
            {
                "body": "<p>\n\tWoooooowwww\n</p>"
            }
        ]
    }
}
```

**Comment by searls** [comment]
@butsjoh for your solution to work does that mean the client must generate IDs? That's a hurdle a lot of clients won't easily cross.

**Comment by butsjoh** [comment]
@searls That's not really true because i am not providing any id for the message i am sending (see linked section). Our rule is simple: 
- if you are attaching something existing (like participants in this case) we add it to the links of the main document
- if you are attaching something new (like the message in this case) we attach it in the linked section

We read the given body of my example as the following: "Create a conversation with has 2 participants with the given ids and link a new message with the given body".

I am not claiming this is the best way todo it but for us it seems the most logical way without introducing a new format.

**Comment by searls** [comment]
Ah, cool. So would you say that your approach is formally described in the spec as establishing that relationship? I can't find any language that suggests so.

**Comment by butsjoh** [comment]
The spec talks about how you define relationships (see Relationships section) and how you can embed (see Compound documents section) linked documents.

Below you can find an example of how we did it that is not wrong according to the spec:

For us a conversation has a least one message and also has the participants directly attached  (according to Relationships section). Since we don't want to generate client side ids it is not really clean to describe the new message in the links section we think so we decide to put it in the linked section (see Compound documents section).

```
{
                "conversations": [{
                    "subject": "Everthing fine today?",
                    "links": {
                      "participants": {
                        "ids": ["81bd6f56-41dc-419f-89b5-c9a3d53e010e", "8f468f75-1332-42d2-8f3f-aa79aab0ebe2"]
                      }
                    }
                }],
                "linked": {
                    "messages": [{
                        "body": "I was wondering how you where doing today"
                    }],
                    "attachments": [{
                        "id": "b927176f-7b27-4897-9e9e-c74dea7f67f3"
                    }]
                }
            }
```

The response for this request

```
{
                "conversations": [{
                    "id": "99e47e8f-1e6c-4d00-9259-82855296ae46",
                    "href": "http//host/api/99e47e8f-1e6c-4d00-9259-82855296ae46",
                    "subject": "How was your day?",
                    "created_at": "2013-05-21T00:00:00Z",
                    "updated_at": "2013-05-22T00:00:00Z",
                    "links": {
                        "participants": {
                            "ids": ["81bd6f56-41dc-419f-89b5-c9a3d53e010e", "8f468f75-1332-42d2-8f3f-aa79aab0ebe2"],
                            "href": "http://host/api/people/?ids={conversations.participants}",
                            "type": "people"
                        },
                        "creator": {
                            "id": "81bd6f56-41dc-419f-89b5-c9a3d53e010e",
                            "href": "http://host/api/people/81bd6f56-41dc-419f-89b5-c9a3d53e010e",
                            "type": "people"
                        }
                        "messages": {
                            "ids": ["f49dc39a-ee4c-4d06-8d8e-07d7ec8ad802"],
                            "href": "http://host/api/messaging/messages?conversation_id=99e47e8f-1e6c-4d00-9259-82855296ae46",
                            "type": "message"
                        }
                    }
                }],
                "linked": {
                    "people": [{
                        "id": "81bd6f56-41dc-419f-89b5-c9a3d53e010e",
                        "href": "http://host/api/resources/81bd6f56-41dc-419f-89b5-c9a3d53e010e",
                        "name": "Foo"

                    },
                    {
                        "id": "8f468f75-1332-42d2-8f3f-aa79aab0ebe2",
                        "href": "http://host/api/resources/8f468f75-1332-42d2-8f3f-aa79aab0ebe2",
                        name: "Wooza"
                    }],
                    "messages": [{
                        "id": "f49dc39a-ee4c-4d06-8d8e-07d7ec8ad802",
                        "href": "http://host/api/messaging/messages/f49dc39a-ee4c-4d06-8d8e-07d7ec8ad802",
                        "body": "Was wondering how you are doing today.",
                        "created_at": "2013-05-21T00:00:00Z",
                        "links": {
                            "creator": {
                                "id": "81bd6f56-41dc-419f-89b5-c9a3d53e010e",
                                "href": "http://host/api/resources/81bd6f56-41dc-419f-89b5-c9a3d53e010e",
                                "type": "people"
                            },
                            "attachments": {
                                "ids": ["eda2ddc5-5a48-416d-88e6-3022c643ca41"],
                                "href": "http://host/api/files?ids={messages.attachments}",
                                "type": "file"
                            }
                        }
                    }
                    }],
                    "files": [{
                        "id": "eda2ddc5-5a48-416d-88e6-3022c643ca41",
                        "href": "http://host/api/files/eda2ddc5-5a48-416d-88e6-3022c643ca41",
                        "file_size": 88347374,
                        "content_type": "image",
                        "mime_type": "application/jpg",
                        "created_at": "2013-05-21T00:00:00Z",
                    }]
                }
            }
```

**Comment by dgeb** [comment]
This is a real challenge and is not covered in the current spec. The compound document section covers document retrieval but makes no claims about applicability to updates. As I've been discussing across several issues, I really think we need to consider all updates as happening against a single "schema" (i.e. a JSON document accessible with consistent JSON pointers). I've been swamped, but will write that up soon.

Here's a contrived example that illustrates the need for explicit links when creating multiple resources: imagine creating a post, as well as an author and editor, both of which are "people". The post would need links to distinguish which person is the author and which is the editor. In this case we couldn't make assumptions about relationships, as @butsjoh is doing with `messages` and `conversations`. In order to solve this reference problem, I think that the cleanest solution that's consistent with the current spec is to require client-generated ids. Another solution might be to allow embedding related documents, but that's quite inconsistent with the rest of the spec.

However, I still have fundamental doubts about using a `POST` to one resource's URL to create that resource + related resources. I think that a better answer for bulk updates is an array of `PATCH` operations. Again, the reference problem would still need to be solved (probably with client-generated ids) when creating multiple related resources.

**Comment by butsjoh** [comment]
@dgeb I fully understand that our solution is definitely not the best. But we didn't found a correct way to have one atomic action (meaning 1 request) to create the stuff we need. The POST combined with some follow up PATCH operations might work if it can happen all in one request. We are spoiled with rails and ar that has nested attributes and all that stuff which can deal with creating all this stuff in one go but for an api this seems to be quite different.

**Comment by searls** [comment]
Thanks @dgeb; still feels to me like the spec should attempt to address this if possible to keep the implementation of clients simple -- I pinged @steveklabnik initially about this request and would love to hear his thoughts.

**Comment by steveklabnik** [comment]
Adding to the 1.0 milestone, we need to be sure to at least keep this possibility open, even if we don't have a full answer right away.

**Comment by petervandenabeele** [comment]
Converting current project to jsonapi.org.

We also need an "atomic nested post" and are now documenting this approach as shown below.
I am proposing this approach, but not really finding example or explicit description in the spec.
Feedback welcome ( /cc @butsjoh )

```
POST Request:

{"personen":
    [{
        "externe_referentie":"121527", 
        "familienaam":"De korte",
        "voornaam":"Jan",
        "links": 
        {
            "contactgegevens": 
            [
                {
                    "contact_type": "gsm",
                    "waarde": "0495-98.76.54",
                    "externe_referentie":""
                },
                {
                    "contact_type": "e-mail",
                    "value": "luc@gmail.com",
                    "externe_referentie":""
                }
            ]
        }
    }]
}

Response:

201 (Created)
Content-Type: application/json

{"personen": 
    [{
        "referentie": "1",
        "links": {"contactgegevens": ["5","12"]}
    }]
}
```

**Comment by petervandenabeele** [comment]
Hmmm, upon rereading, I now doubt if the above I wrote is really correct ...

The data for the nested "contactgegevens" (that are not yet existing) should probably have gone in the "linked" section.

I feel it is the server side that needs to generate all the id's (and return them in the response, using the _order_ in the array of the request as the way to know the link between the request data and the id's in the response). E.g. in my example,  contactgegeven "5" is for the "gsm 0495-98.76.54" and contactgegeven "12" is for the "e-mail luc@gmail.com".

**Comment by petervandenabeele** [comment]
Based on the version of @butsjoh above, I updated our spec to:

```
POST Request:

{
    "personen": [
        {
            "externe_referentie":"121527", 
            "familienaam":"De korte",
            "voornaam":"Jan"
        }
    ],
    "linked": {
        "contactgegevens": [
            {
                "contact_type": "gsm",
                "value":"0495-98.76.54",
                "externe_referentie":""
            },
            {
                "contact_type": "e-mail",
                "value": "luc@gmail.com",
                "externe_referentie":""
            }
        ]
    }
}
```

**Comment by butsjoh** [comment]
@petervandenabeele We are currently still using it like you described in your example. It seems the direction this is going is to express it in PATCH operations  (#202). According to me it should be more content type aware but that heavily depends on your backend. You could allow application/x-www-form-urlencoded with a structure that is similar to what rails and active record expect but then is not something that json api spec is usefull for i think.

**Comment by petervandenabeele** [comment]
@butsjoh thx for the confirmation :-)

We will stick with this POST version for now and then wait for the "grand unified theory" based on PATCH that @wycats suggests in #202.

**Comment by gr0uch** [comment]
I've sneakily implemented [multiple document posting](https://github.com/daliwali/fortune/blob/master/lib/route.js#L125) in [fortune](http://github.com/daliwali/fortune) in the manner that you described @petervandenabeele. There are clearly drawbacks with this approach however, such as when there are multiple links in the primary document(s) to the same type of linked entity.

**Comment by petervandenabeele** [comment]
Do I understand correctly that this issue:

"There are clearly drawbacks with this approach however, such as when there are multiple links in the primary document(s) to the same type of linked entity. "

is related to the fact that:
- "links" uses the name of the association (e.g. "creator", "author")
- "linked" uses the class of the entities (e.g. "people")

**Comment by gr0uch** [comment]
Well, it is ambiguous exactly what is being linked, it is implicit rather than explicit which leaves it open to many interpretations. Suppose there is a "creator" and "author" link as you describe, and there is a "people" document that is linked, should it be assumed that it is related to all links?

**Comment by philsturgeon** [comment]
> Well, it is ambiguous exactly what is being linked

This is why sideloading and sideposting is often a bit of a weak solution compared to embedding data. :trollface: 

Regardless, there needs to be some sort of ability to send multiple resources. I recently had the issue of trying to send a credit card to the API which has its own `/addresses` endpoint. I wanted to save that address too without inventing some fake field names just for the POST, and ended up not having any ability to get it done complying with JSON-API. 

I the end I just made made two API calls, one to save the credit card, one to save the address using `"links" : { "comment" : 1 }`. Not ideal at all.

**Comment by dgeb** [comment]
> This is why sideloading and sideposting is often a bit of a weak solution compared to embedding data.

Embedding can be ambiguous too [to be clear: embedding of "resources" is not supported by JSON API]. Embedding gets messy when mixing related resources that you want to create with relationships you want to create in the same collection (e.g. create an `article` and link it to an existing `tag` and create a new `tag` in the same operation). Furthermore, embedding doesn't address sharing of embedded resources across primary resources.

IMO, the "correct" solution to this problem is bulk creation with the [Patch extension](http://jsonapi.org/extensions/patch/) and client-generated IDs.

**Comment by danelowe** [comment]
Nice. In my particular case, I'd love a way to create an Invoice resource at the same time as a Payment resource that belongs to the Invoice, and if payment fails, have neither object created. I'd imagine that this could be a common use case, but perhaps is not worth the potential complexity? 

The questions I would still have are;
- Would such a use case be supported by 1.0, or supported at all?
- Would it be expected that the strategy suggested at https://github.com/json-api/json-api/issues/205#issuecomment-45076688 could be supported by the spec?
- Using the [Patch extension](http://jsonapi.org/extensions/patch/) would there be a canonical way to **create** a tree of **related** objects, and specify their relationships in the same request? Potentially quite difficult if the relation name doesn't match up with the associated resource name.
- Are batch operations always atomic, sometimes, or never? If sometimes, can it be specified by client? 
- If we have a primary resource for the operation, is there a convention that the client could use to infer the resource location?
- Is the order of operations in the request to be respected? Again, always, sometimes or never? 

At the moment I think I might just assume that what I'm trying to do is not supported (and just include payment data in the invoice), but would be so happy if it were, or an alternative could be suggested?

**Comment by bintoro** [comment]
@danelowe Even if this kind of thing is not codified in the spec, it's not prohibited either, so there's nothing to stop you from supporting such an operation.

For example, to create an invoice with its associated rows (that are further associated with products) in one request:

``` json
POST /invoices

{
  "data": {
    "type": "invoices",
    "number": 12345,
    "links": {
      "rows": {
        "type": "invoiceRows",
        "ids": ["c85c3efc-3c4c-441b-bf65-d54a0651cd09",
                "1710e448-c100-469f-bb58-0f8fb15fd3a5"]
      }
    }
  },
  "linked": [{
    "type": "invoiceRows",
    "id": "c85c3efc-3c4c-441b-bf65-d54a0651cd09",
    "quantity": 3,
    "links": {
      "product": {
        "type": "products",
        "id": "555"
      }
    }
  }, {
    "type": "invoiceRows",
    "id": "1710e448-c100-469f-bb58-0f8fb15fd3a5",
    "quantity": 8,
    "links": {
      "product": {
        "type": "products",
        "id": "999"
      }
    }
  }]
}
```

I see this as a rather obvious extension to the base spec as it uses the familiar syntax. The only requirement is the use of client-generated IDs.

IMO, POSTing related rows to `/invoices` is no more egregious than receiving sideloaded rows from the same URL. But if this seems unorthodox, consider POSTing to `/invoices?include=rows`.

**Comment by ahacking** [comment]
> IMO, POSTing related rows to /invoices is no more egregious than receiving sideloaded rows from the same URL. But if this seems unorthodox, consider POSTing to /invoices?include=rows.

Yes that is exactly how it should be done having `include=rows` without the include,  a PUT should fail since the representation foes not match what a GET would return. POST is a different story but should follow as close to what a GET would return.  There is a discussion on GET/PUT symmetry in #291 which is very relevant to this issue. I always use PUT to create things as it has better transactional semantics and using the appropriate scope via fields/includes actually targets a different resource as far as HTTP is concerned. Nothing unorthodox about it, read the HTTP RFC and you will see it caters for overlapping and partial resources, its right there in the text. :)

**Comment by bintoro** [comment]
@ahacking The thing is, a resource is allowed to maintain default includes. If `rows` were sideloaded by default, then _technically_ it would be okay to PUT/POST them without an explicit `include` param because the representations would be symmetrical. But, obviously, relying on defaults is not a robust approach if the server is being strict about what it accepts, since the defaults may change over time.

**Comment by ahacking** [comment]
@bintoro I think that behavior should be changed to make things predictable and uniform, regardless of resource type. It seems odd that `/posts?includes=comments` would be the same as `/posts`.

I'm in favour of the default being no side loading to make behavior predictable across endpoints from the same or even different services.

**Comment by bintoro** [comment]
@ahacking If this gets in the spec, I'm also strongly in favor of mandating an explicit `include` param when sideposting. The same goes for `fields` when using PUT for partial updates. Dealing with a potentially unknown set of defaults is just too unwieldy, and there's no real downside to making these params a MUST when applicable.

However, for side_loading_, default includes can be quite useful and should probably still be allowed IMO. When consuming an unfamiliar API, the server is the best expert on what related resources the client is going to need and can proactively include them. I hope this degree of in/out asymmetry is acceptable to everyone.

**Comment by ahacking** [comment]
The asymmetry is a problem as it means GET and PUT don't work together. I think @dgeb was interested in exploring symmetry of GET and PUT because it follows HTTP semantics much more closelt and allows both partial, bulk and related resource creation, update and deletion without requiring PATCH. 

/posts and /posts?include=comments are different resources as far as HTTP is concerned.  They may overlap, but the principal of GET and PUT and the return payload of PUT is based on symmetry of what GET would return.

**Comment by bintoro** [comment]
@ahacking GET and PUT will work together, don't worry. :smile:

> /posts and /posts?include=comments are different resources as far as HTTP is concerned.

Yes they are, but there's nothing wrong with a server exposing the same JSON API resources under multiple URIs. (Sidenote to interested readers: an _HTTP resource_ is the entirety of things accessible at a specific URI; it's a different concept than a JSON API resource.)

The asymmetry only affects the very specific case of targeting a URI like `/foo` without explicit `include` or `fields` parameters.

We can simply define that, for the purposes of PUT and POST, `/foo` targets the full primary resource, where any resources that might be linked by default (upon a GET) are excluded.

This represents only a slight and, importantly, perfectly well-defined deviation from pure symmetry that is unlikely to have any practical consequences. If a client tries to PUT a default include without being explicit about it, the server will complain with an error. No harm done.

I honestly don't see an issue here, as this would in no way be unexpected or surprising to users. The alternative (disallowing default includes altogether) would likely be met with opposition.

The behavior is also not ruled out by HTTP. The RFC says:

> A successful PUT of a given representation would suggest that a subsequent GET on that same target resource will result in an equivalent representation being sent in a 200 (OK) response. However, there is no guarantee that such a state change will be observable, since the target resource might be acted upon by other user agents in parallel, or might be subject to dynamic processing by the origin server, before any subsequent GET is received.

So, perfect symmetry is "suggested" rather than mandated. Whether this is because of the race condition that is pointed out or because the RFC authors wanted to grant servers some leeway in managing the resource representations, we can only speculate.

Personally I wouldn't necessarily be against removing default includes from GET requests either. But I realize how it can be a highly useful feature to many, so I think this is a reasonable compromise.

**Comment by steveklabnik** [comment]
Given that this is an additive feature, I'm going to de-milestone it for 1.0.

**Comment by Fivell** [comment]
what is status of this issue ?

**Comment by tkellen** [comment]
[This feature is milestoned for 1.1](http://discuss.jsonapi.org/t/json-api-weekly-meeting-june-22nd-2015/23)

/ref #795
