### ISSUE TITLE
two styles are hard to know about

### ISSUE THREAD

**Issue by steveklabnik** [json-api/json-api#224]
Now that we've unified the two styles, it's less clear that you can do it either way. We should come up with some way of making this more obvious.

**Comment by xogeny** [comment]
Just a comment about this from someone coming at json-api from a HAL background.  One of the things I really like about HAL is the fact that it only uses URLs for referencing things.  You can, of course, include an 'id', but it doesn't really mean anything since it is just data.  The things that really mean something (or at least whose semantics are defined by the spec) are the links (including 'self').

I'm open to the idea of a another hypermedia format that considers the methods that are supported by different links and formats that are designed to be used for `POST` requests and not just `GET`.  So in this way, I think there is room for innovation in the hypermedia format space beyond what HAL has to offer.  But it is essential for me that this format is usable without the need to introduce `id` data.  My goal is that the API should be completely self-discoverable by traversing links, the client only needs to know one URL to access the entire API and that the client never has to construct a URL (just like when you use a web browser).

I'm not saying json-api can't do this.  But if it can, it isn't clear to me how it could be used in this way.  The language seems very to very strongly encourage the use of 'id's which, for me, is not the way I want to go.  It also isn't clear how json-api is different from Siren.  In your FAQ, you only discuss HAL.

Just some feedback from an "outsider" in case it is useful.

**Comment by steveklabnik** [comment]
This is fine today.
