### ISSUE TITLE
Linked reference to primary resource (how to handle pagination etc.)

### ISSUE THREAD

**Issue by koemeet** [json-api/json-api#229]
Hi,

If you have a resource that has a field that maps to the same resource, a cyclic relationship. Would you put the `linked` resources inside the same collection as the primary results or would they live seperately inside the `linked` key.

Let's say we make a request to: `GET /users/1`

Should we get:

``` json
{
    "users": [
        {
            "id": 1,
            "username": "Steffen",
            "relatedToUser": 2,
        },
        {
            "id": 2,
            "username": "This one came along with Steffen"
        }
    ]
}
```

Or should we get:

``` json
{
    "linked": {
        "users": [
            {
                "id": 2,
                "username": "This one came along with Steffen"
            }
        ]
    },
    "users": [
        {
            "id": 1,
            "username": "Steffen",
            "relatedToUser": 2,
        }
    ]
}
```

With the above example, you could get in trouble when using pagination etc. How would this be solved in a smart way?

**Comment by dgeb** [comment]
You would use the latter example (but corrected to use a `links` object within user 1):

```
{
    "linked": {
        "users": [
            {
                "id": "2",
                "username": "This one came along with Steffen"
            }
        ]
    },
    "users": [
        {
            "id": "1",
            "username": "Steffen",
            "links" {
                "relatedToUser": "2"
            }
        }
    ]
}
```

The `linked` object separates primary resources from related resources, which allows for primary resources to be paginated. Given your schema, a request for the first 10 users sorted alphabetically should include 10 users as primary resources, and `linked` should contain any related users not also included as primary resources.

Of course, a particular endpoint may limit the number of related resources that could be returned with a primary resource. In those cases, it's best to provide an alternative URL so that related resources themselves can be requested as primary resources and thus paginated.

**Comment by koemeet** [comment]
Ty for this explenation. It makes more sense this way. Also, linked should not contain duplicates with the primary resource right?

**Comment by dgeb** [comment]
@steffenbrem - glad this makes sense :)

Also, you're correct - `linked` should not contain duplicates of primary resources.
