### ISSUE TITLE
How should we deal with 404's in requests that call multiple resources?

### ISSUE THREAD

**Issue by scotttrinh** [json-api/json-api#230]
I am wrapping a third party API to a JSON-API response incrementally. I'm at the point where I am trying to implement this from the docs:

> In this example, the posts.comments variable is expanded by "exploding" the array specified in the "links" section of each post. The URL template specification specifies that the default explosion is to percent encode the array members (e.g. via encodeURIComponent() in JavaScript) and join them by a comma, so in this example, fetching http://example.com/comments/1,2,3,4 will return a list of all comments.

I'm trying to figure out what to return when one of those resources is 404. Should I 404 the whole request, just return an empty object, return some type of error object for that one instance, or do something else entirely?

Maybe this isn't something that the API spec should address, but I wanted to get a little input on this case. Seems like it might come up a lot.

**Comment by steveklabnik** [comment]
My initial thought would be to return just the ones that exist, but this is a good question.

**Comment by ZenCocoon** [comment]
We took the party to return only the existing ones, which was easy to handle to be honest. But I think this should be defined at the spec level.

**Comment by dgeb** [comment]
I think that a request for `/articles/1,2,3` should behave similarly to individual requests for `/articles/1`, `/articles/2` and `/articles/3`. In other words, this is a request for multiple individual resources, which is subtly different from filtering a collection (e.g. `/articles?status=active`).

Therefore, I'd expect a 404 if any individual resource can't be located. I'm not in favor of allowing partially successful requests as a rule. Response status codes must apply to the entire request.

I agree that we need to clarify this in the spec and ensure that a useful message is returned that will allow for a minimal number of subsequent requests. For instance, by returning every resource ID that 404s, the client can trim the list (and hopefully modify its out-of-sync relationships) before requesting a new list.

**Comment by scotttrinh** [comment]
The only reason I'm worried about 404ing the whole request is it seems out of character to the rest of the web. If a css resource is requested, it doesn't break the web page, it just doesn't return the resource.

But, at the same time, it does actually 404 the individual request for the offending CSS file, hence my thought to return an error object or even an empty object. But, I suppose an empty object is not an error case, really...

@dgeb Are you suggesting returning the list of missing resources in the body of the 404 response?

**Comment by dgeb** [comment]
The difference between this scenario and a web page that references a css resource is that the html and css are requested separately. One response can return a 200 and the other a 404 - no problem.

I'd like to avoid requests that are partially successful because it creates situations that are very difficult for both the server and client to reason about. Imagine POSTing two resources that are dependent on each other - if the operation isn't atomic and only one POST succeeds, your server may end up in a bad state that your client will be left to rectify (which may or may not happen if your client goes offline before/after receiving the response). I know you're talking about GETs here, not POSTs, but I think the same principles apply.

I do recommend returning a list of missing resources in the body of the response, although we have yet to work out that format. Sorry to provide half of a solution... I hope to have a full answer soon.

**Comment by scotttrinh** [comment]
Cool. I can certainly work with the spirit of this answer, even if the details are not totally fleshed out. Luckily, the API that I am wrapping actually does that exact thing, so I can just pass the response through until there is a more standardized response body format.

Thanks everybody for weighing in! Should we leave this issue open until the spec is updated?

**Comment by pnsantos** [comment]
I think this comes down to what a GET /comments/1,2,3 is supposed to mean to the client. If the meaning of said request is equivalent of applying a filter to /comments where the id can be 1 **or** 2 **or** 3 then if a comment doesn't exist it should just not be included in the response (you could eventually receive an empty array, which would mean none of the requested comments exist).

If on the other hand, a GET /comments/1,2,3 is supposed to be the equivalent of doing 3 GET requests (/comments/1, /comments/2 and /comments/3) in a single request, then I would say that what is needed is a "multi-status" response. You could "hijack" the WebDav extension status code 207 defining a similar body content in json (or JSON-API could define it's particular body content for that status code). Barring that, I don't think there is one good answer since the "I was able to do something but not everything" doesn't really exist in HTTP (if you exclude 207). Both 200 or 404 have for and against points, the one most appropriate would depend on the use case...

**Comment by guillec** [comment]
@scotttrinh if you want to make it a little more formal, maybe return a http://tools.ietf.org/html/draft-nottingham-http-problem-06 in the mean time?

```
{
    "type": "http://example.com/probs/paritial-success,
    "title": "Partial Success.",
    "detail": "Some of the resources you requested are missing.",
    "instance": "http://example.net//articles/1,2,3",
    "status": 404,
    "articles": ["http://example.net/articles/1",
                 "http://example.net/articles/3"]
   }
```

**Comment by ahacking** [comment]
I'm with @dgeb on this, all or nothing.  

Perhaps JSON-API needs to define a filter type with "any of" / "in" semantics. This prompts the question that perhaps other operator types should be supported (all, excludes) and a general mechanism for query operators on any attribute (gt,lt,range,like,...)  

Whilst I present the above posibility I'm not keen to invent a poor mans SQL. I think the better model is parameterized search scopes and there is room for JSON API to define a convention for parameterised scopes as opposed to just simple attribute filters. To this end I believe the spec should be changed to nest filters in a filter param just as search is in a param to avoid clashing with resource attributes (a resource with an atrribute called 'search' couldn't be filtered in the current design). Following this convention scope parameters could be specified as well as simple filters as per the current spec. An example (unescaped):

`newest=1&rating[min]=3&rating[max]=5&filter[comments.author]=4&sort=title`

Above `newest` and `rating` are scopes, noting that `rating` is parameterised and `filter` is a basic atrribute matching scope as per the current spec, whilst sort is a sorting scope.

Just ideas for consideration but I've found parameterized scopes to be a useful construct in my APIs.

**Comment by hhware** [comment]
> You could "hijack" the WebDav extension status code 207

Why "hijack", wasn't it the exact purpose of it? I would vote for 
- standardization of handling of the case of mixed sub-statuses in the JSON API spec,
- "return all or nothing" approach, 
- HTTP status of the response: `207 Multi-Status`,
- response object: array of error objects with respective sub-statuses in them,
- leaving up to the server to decide how to proceed after the first error is found (give up right away or check the rest); different methods of a given API should be allowed to handle it differently.

**Comment by steveklabnik** [comment]
In today's spec, we explicitly deal with this: it's a 404 for the whole thing.

**Comment by scotttrinh** [comment]
:+1: Thanks everybody!
