### ISSUE TITLE
Support paging

### ISSUE THREAD

**Issue by matthewfl** [json-api/json-api#236]
I believe that this has been mention before, but I can't seem to find any issues about it.

Afaik the current way that is listed in jsonapi is to have an [array of identifiers](https://github.com/json-api/json-api/blob/gh-pages/format/index.md#relationships-) which reference the other resources.  However, this approach does not scale well to cases where there are hundreds or thousands of items in a collection.

**Comment by dgeb** [comment]
Related resources can also be referenced with a URL template in the top level `links` object.

Also, my [recent PR](https://github.com/json-api/json-api/pull/234) formalizes the concept of a ["collection object"](https://github.com/dgeb/json-api/blob/v1rc1/format/index.md#collection-objects-) that can be used to reference collections from within a resource's own `links` object.

**Comment by matthewfl** [comment]
The collection object with the href sounds like it is a step in the right direction, however is this going to support paging as it is impractical to send 1000+ items in a single page.

**Comment by dgeb** [comment]
One approach to pagination is to use the LINK header, as discussed in [RFC 5988](http://tools.ietf.org/html/rfc5988). Links can be used for relative pagination: first, last, next, prev. These relative links would obviously apply only to the primary resource collection.

Maybe we should recommend using the LINK header. However, it seems more in line with the rest of the spec to incorporate the concept in the top level `links` object. In this way, relative links for different resource collections could be specified (e.g. `"posts:first"`, `"posts:next"`, `"posts.comments:first"`, etc.).

I would be curious to collect use cases for pagination since it is such a common request. Some APIs use page-based pagination, others cursor-based. It seems like it might be difficult to make everyone happy in this regard. However, if one approach can meet 90% of use cases and allow for the option to override it (as discussed in the [Extending](http://jsonapi.org/extending/) section), then I think it would be worthwhile.

**Comment by steveklabnik** [comment]
I'm very much 50/50 on Link. I feel that its true use case is for adding hypermedia to types that don't natively support it.

I wonder what @mamund and @mikekelly think of that.

**Comment by mamund** [comment]
i prefer operational links appear within the body, not the metadata section of the response. part of this is that the header space should be kept small and using header space to define state transitions can get out of hand easily.

in addition, i think aesthetically, state transitions are not "meta" but actually part of the primary data sent between parties. i realize that POV is not universally shared, tho ;)

**Comment by xdmx** [comment]
I'd also prefer having the data within the body and not in the header, one reason is if the spec will support also paging data for included resources, that would add many headers (first, prev, next, last, for each resources).

I personally like [RestPack](https://github.com/RestPack/restpack_serializer)'s approach with a meta member with all the paging data inside it, for each resources (not just the main one but included resources too). That way it'd be able to include also extra information (how many records there are in total, the number of pages, the current page, and so on) useful when it's rendered in a page, which may not be the best option to have in the "links" member. Unless you're willing to add an extra member at the top level like "paging" and use it only for the paging data related to the response (it'd make sense to me)

**Comment by wvteijlingen** [comment]
:+1: for paging in the body. I would opt for cursor based pagination though.

There are some problems which I'm running into regarding paging of sideloaded resources. For example, what happens in the following situation: I retrieve two `users`, including `users.posts`, with the posts sorted on 'newest'. Both have 50 posts, but I limit the posts to 10.

Does this result in the newest 10 posts per user, which is 20 total? Or the newest 5 per user which gives 10 total? Or just the newest 10 posts, regardless of which user they belong to?

And what happens when I retrieve for example a `user`, and I include `users.friends`, `users.comments` and `users.friends.comments`...

**Comment by lgebhardt** [comment]
I have the same concerns for pagination over side loaded data. I'm just not sure it's feasible with deeply nested included resources.

I wonder if there should be a recommendation for how the system should respond if too many sideloaded resources would be generated. Is it an error? Do we just truncate the data? Omit it all and have a placeholder structure. Any thoughts?

**Comment by mikekelly** [comment]
I dont do it because it feels like it would make the client's life more difficult, be restrictive, and doesn't really provide any benefit (assuming you have control of the message body)

The acid test for whether information belongs in HTTP headers is whether or not it affords some kind of intermediary processing  (eg. Caching mechanisms). If it doesn't, it probably doesn't need to be made visible at a protocol level and is best in the message body.

**Comment by mikekelly** [comment]
Fwiw I wrote a paper on an example of an intermediate-process-affording use of link headers that enables cache invalidation that turned into an Internet draft (called "linked cache invalidation"). That's the kind of thing I think belongs in the headers.

**Comment by xdmx** [comment]
The cursor based pagination would be very useful for real time APIs, like a twitter feed, which changes a lot and frequently, and a normal pagination for those APIs used in websites like an ecommerce, where you may want to skip to the 10th page, without having to click "next" each time or scrolling for minutes. Since one approach cannot fit all cases, the spec should be flexible enough to support both and let the developer choose which one is the best one for the system she's developing.

What do you think about a response like (if the choice is put it in the body):

```
{
    "cursors": {
        "after": "fghij",
        "before": "abcde"
    },
    "paging": {
        "page_count": 68,
        "next_page": 3,
        "previous_page": 1,
        "current_page": 2
    },
    "count": 25,
    "total": 1683,
    "first_href": "https://domain.com/resource?limit=25&before=abcde",
    "previous_href": "https://domain.com/resource?limit=25&before=abcde",
    "next_href": "https://domain.com/resource?limit=25&after=fghij",
    "last_href": "https://domain.com/resource?limit=25&before=abcde"
}
```

With previous_href and next_href being the only required fields, and all others as optional

**Comment by wvteijlingen** [comment]
**Cursors**
I think cursor based pagination can be used for both examples you mentioned. Perhaps there is a good reason to use offset based pagination, but I haven't come across it yet. Inclusion of `first_href` and `last_href` seems nice.

In an API I'm developing now, we're looking at using the `meta` section for pagination:

``` json
"meta": {
    "users": {
        "include": ["posts"],
        "count": 32,
        "limit": 10,
        "before_cursor": "58D5E212-165B-4CA0-909B-C86B9CEE0111",
        "after_cursor": "BB6D2DBE-7B66-4B05-9668-9C16E42F223D",
        "previous_href": null,
        "next_href": "/users?limit=10&after=BB6D2DBE-7B66-4B05-9668-9C16E42F223D"
    }
}
```

**Paginating sideloaded resources**
I'm still thinking about paginating sideloaded resources. The main use case for sideloaded resources for me have been in the form of: "Get all users and the 5 latests posts per user". This means the posts are split into multiple collections and being paginated multiple times. There are some downsides to this:
- If you don't put a limit on the users, you don't know how many resources you will be getting in total. However, this is easily mitigated by limited every level of a relationship.
- You end up with multiple cursors for each 'collection' of sideloaded resources.

However, this models quite nicely into my client application which wraps every array of resources into a ResourceCollection object. Thus, each user has ResourceCollection `posts`, which can be paginated individually.

**Comment by mattecapu** [comment]
Would it be a sin to put "pagination constraints" in the request body as a JSON object?
It would be very flexible and powerful

**Comment by wvteijlingen** [comment]
The downside of putting pagination constraints in the request body as opposed to the URL is that then the same URL returns different sets of data. You will lose the ability to bookmark URLs as well as using them as links as `next_href` etc.

By the way, request body JSON was suggested for the SEARCH verb in another issue somewhere, but I don't know if that included paging.

**Comment by ahacking** [comment]
@wvteijlingen I agree with keeping paging in the URL.

I also agree with using cursor based pagination as the only way to page since a 'page' is context specific and arbitrary size, the client can compute 'offset' and 'limit' params to whatever sized page they need.

The issue where including a search query in the request body was proposed / discounted was #308

**Comment by mattecapu** [comment]
Yes, surely is a bit off the "pure" HTTP philosophy, yet it would be really useful.
But answering to you
- We can make mandatory the addition of the hash of the body to the URL: if a request come with an -incorrect hash the server responds with a 400 Bad Request.
  _Downsides_: feels a bit hacky, equivalent request bodies may have different hashes (differences in whitespace, properties order, and so on).
- `next_href` and `previous_href` could become objects exposing a URL and another object which is the new request object

Another less elegant but maybe more HTTP compliant way to do this would be adding such an object as a querystring parameter, you have then to double parse the querystring and you are limited by the URL length...

**Comment by mattecapu** [comment]
@wvteijlingen I actually read your comment about sideloaded resources pagination just now, sorry for the oversight.
Anyway, how would an URL for your example look like?

**Comment by ahacking** [comment]
@mattecapu yes hashing is an approach to solving some of the issues with request bodies.

Hashing request bodies / json documents requires a well defined normalised form. The JSON-LD W3C specification provides for normalisation for this exact use case.

I've suggested before in another proposal that json-api could take an approach based on JSON-LD similar to what Hydra does given json-api needs to deal with resource linking and aspects of schema. It just delegates all schema and linking concerns to an @context key at the root of the document and leaves the rest of your json however you want it so it is low impact on existing formats. There is also a http link header alternative so payload remains unchanged.

**Comment by xdmx** [comment]
@wvteijlingen :+1: I like your solution

I think that some kind of limit (and thus pagination) there should be on included resources, otherwise there is a risk when you request /users?include=posts. Users would be paginated, but if all posts are returned, if those users wrote hundreds (if not thousands) of posts, the response would be quite big.

Considering a limit of 5 posts it'd make more sense to me as well returning 5 posts for each users returned in the response. Limiting it to a generic 5 posts regardless of the owner there is a risk that some users won't have any posts returned in the included posts, which wouldn't be very useful (you'd have to go through pages to find those posts). Splitting it between the number of users would ensure some associated posts, but for low numbers (eg limit to 20 users, and 5 posts), would return 0.25 posts/users, which doesn't make sense.

**Comment by wvteijlingen** [comment]
I've been thinking some more about how we could implement such a system. Most of my use cases boil down to: "Get the 5 most recent posts, and for each post include the 5 most recent comments".

Such a request has a few requirements:
- You have to be able to sort the main resources
- You have to be able to paginate the main resources
- You have to be able to specify relationships that need to be sideloaded
- You have to be able to sort these related resources
- You have to be able to paginate these related resources

Then really in the response we have to include pagination data for each collection of related resources (in this case, 5 posts collections) as well as the main resource collection. This boils down to 6 sets of pagination data.

I think that if we design such a system, it has significant drawbacks.
- We quickly end up with a very complex querying/sorting/filtering/paginating system
- Library developers will probably be hesitant to implement such a system because it's a lot of work

I'm now leaning towards not supporting any of these features for sideloaded resources. You can still sideload deeply nested relationships, but they won't be filtered, paginated or sorted. This makes it more suitable for side loading to-one relationships (e.g. load posts and their authors).

If you want to fetch using more complex queries, you will have to just make separate requests.

**Comment by dgeb** [comment]
Side-loading is certainly useful but has its limitations. Because related resources are grouped by `type` under `linked`, and each resource may be present due to multiple relationships, I think that sorting and pagination of related resources is unworkable. It seems better to provide a link to related resources from which they can be sorted / paginated as primary resources in a separate request.

**Comment by xdmx** [comment]
I've written down some thoughts:

``` javascript
"meta": {
    "paging": {
        "count": 32,
        "limit": 10,
        "before_cursor": "58D5E212-165B-4CA0-909B-C86B9CEE0111",
        "after_cursor": "BB6D2DBE-7B66-4B05-9668-9C16E42F223D",
        "first_href": "http://example.com/users?limit=10&sort=age,-name&referral_id=123&include=posts"
        "previous_href": "http://example.com/users?limit=10&before=58D5E212-165B-4CA0-909B-C86B9CEE0111&sort=age,-name&referral_id=123&include=posts"
        "next_href": "http://example.com/users?limit=10&after=BB6D2DBE-7B66-4B05-9668-9C16E42F223D&sort=age,-name&referral_id=123&include=posts"
        "last_href": "http://example.com/users?limit=10&offset=30&sort=age,-name&referral_id=123&include=posts"
    }
}
```
- The meta object **MAY** include at most one _"paging"_ object
- The paging object **MUST** contain the keys/values: _"limit"_, _"before_cursor"_, _"after_cursor"_, _"previous_href"_ and _"next_href"_
- The paging object **MAY** contain the keys/values: _"count"_, _"first_href"_ and _"last_href"_
- When there are no _"previous_href"_ or _"next_href"_ available they **SHOULD** be set as _null_
- The paging object **MUST** be related to the primary resource, and **NOT** to the linked/included resources.
- The values of _"first_href"_, _"previous_href"_, _"next_href"_ and _"last_href"_ include all the needed data in order to move through pagination without alteration of the available results. And thus including in the values all needed params such as, and not limited to, filtering, sorting and including resources (e.g. "http://example.com/users?limit=10&after=BB6D2DBE-7B66-4B05-9668-9C16E42F223D&sort=age,-name&referral_id=123&include=posts"
- All included resources, if any, **MUST** all be loaded and not paginated

@wvteijlingen I've used your example, which I personally like. I've only added the _first_href_ and _last_href_ which may be useful to have in some occasions, considering them as optional. I've also set the _count_ value as optional, which would be useless for some scenarios (like events/activities/feeds) where there are thousands if not millions of available results. Plus I saw the _include_ key, and I think it may be better having it directly in the hrefs values to avoid the client to add them, although it'd bring some duplication. An alternative I thought could be a key _params_ which includes all params needed to add to the hrefs, which would be the job of the client.

Something like

``` javascript
"meta": {
    "paging": {
        "params": {
          "sort": ["age", "-name"],
          "include": ["posts"],
          "referral_id": "123"
        },
        "count": 32,
        "limit": 10,
        "before_cursor": "58D5E212-165B-4CA0-909B-C86B9CEE0111",
        "after_cursor": "BB6D2DBE-7B66-4B05-9668-9C16E42F223D",
        "first_href": "http://example.com/users?limit=10"
        "previous_href": "http://example.com/users?limit=10&before=58D5E212-165B-4CA0-909B-C86B9CEE0111"
        "next_href": "http://example.com/users?limit=10&after=BB6D2DBE-7B66-4B05-9668-9C16E42F223D"
        "last_href": "http://example.com/users?limit=10&offset=30"
    }
}
```

**Comment by dgeb** [comment]
As of #341 (RC2), pagination is now covered by the spec. See http://jsonapi.org/format/#fetching-pagination
