### ISSUE TITLE
Cannot link from embedded objects

### ISSUE THREAD

**Issue by ahacking** [json-api/json-api#238]
Referencing PR #237 as a few minutes ago it is not possible to link from resources which have internal structure, eg:

```
{
  "data": {
    "eab9b2af-73f0-4e13-b348-0bd4377fb06a": {
      "type": "contact",
      "name": "Some One"
      "address": {
        street: "some street"
        city: "<some city id>"
        state: "<some state id>"
        country: "<some country id>"
      }
    }
}
```

The spec doesn't deal with resources that have internal structure AFAIKT since it requires one to put all references under a "links" object within the resource.  In my example above addresses do not have ids, they are embedded properties of a resource. 

In my actual system, addresses are embedded arrays within contact resources, they have no id and cannot be resources, yet they link to other resources.

I am not sure what the rationale for embedded 'links' object it, but I have decided to abandon any conformance to json-api in my systems because of this issue plus not being able to have generic collections in linked resources and other observations commented on in PR #237.

I wish you all well with it, there is good work being done here but what works for me does not align with JSON API compromises and the many paradigms it is trying to simultaneously address.

My primary technical issues:
- links (why an object as opposed to just properties on the resource)
- server ids vs (v4) UUIDs
- typed vs generic collections (related to server ids/ UUIDs)
- polymorphism (base types vs specific types)
- schema window dressing (link templates)

I will check back from time to time with the hope things may mature enough to allow it to be a good reference for JSON APIs but my gut tells me that unless one nails down the server-id/UUID/  design choice up front then it will forever be trying to serve too many API designs simultaneously rather than being a minimal purposeful spec. As I have said before the UUID vs server assigned ID its not just about carrying an opaque field in a transport document, but is rather an entire paradigm which deeply affects the interactions between client and server when serializing object graphs and results in a very different API design to one with server assigned ids scoped to a resource type.  JSON-API tries to straddle both and despite some excellent work, IMO it fails in its key objective to settle good api design once and for all.

**Comment by dgeb** [comment]
@ahacking - I'm sorry to hear that JSON API is still not lining up with your needs. Your contributions have really been appreciated thus far.

> I am not sure what the rationale for embedded 'links' object it

The primary reason that `links` is required within individual resource objects is that, without it, there is no way for a generic client to distinguish a link from another attribute (e.g. `"author": "9"`). JSON API doesn't need to compromise on discoverability through the use of `links`. Similarly, link templates also allow for support of discoverability, especially for non-standard URLs.

> I have decided to abandon any conformance to json-api in my systems because of this issue plus not being able to have generic collections in linked resources

This discussion was just beginning in #237, and I don't think it's been closed. As I said, ["I can see that a generic linked collection of related resources is consistent with a generic, non-typed data collection of primary resources."](https://github.com/json-api/json-api/pull/237#issuecomment-47847482)

As @steveklabnik said, ["rather than continue to argue about it here, let's talk about them afterwards."](https://github.com/json-api/json-api/pull/237#issuecomment-48076361) 

So please, let's discuss these finer points in more focused issues.

**Comment by gr0uch** [comment]
@dgeb I think what @ahacking was trying to point out is that perhaps the top-level `links` provides sufficient information to determine which attributes are links:

``` js
{
  "links": {
    "posts.author": "http://api.example.com/people/{posts.author}"
  },
  "posts": {
    "id": "2",
    "author": "9"
  }
}
```

**Comment by dgeb** [comment]
@daliwali ah, you might be right. I am concerned with shifting responsibility to require entries in the top-level `links` for every `link`, just to identify it as such. The current spec allows for hrefs, ids, and types to be specified with or without URL templates. This flexibility might be needed for APIs with irregular URLs that can't conform to a template.

**Comment by ahacking** [comment]
Yeah PR #237 was closed when it got merged, hence starting this new issue. 

Some of my other use cases for embedded objects which have no identity are things like a collection of coordinates (describing a polygon) or dimensions describing an area or volume or product/component measurements/dimensions which and are never treated as a resource since they really are attributes of a complete resource but I need the internal structure in the resource to represent those attributes correctly and I also need to link to things that are resources from those embedded attributes (eg unit type, color description)

I think something like json-schema would address generic clients far more completely than link templates and requiring a resources links to be contained in a link object.

Also clients which have knowledge of the api coded into them dont need to do any schema discovery and the server doesn't have to include schema baggage in every response (and arguably to comply with PUT semantics the client probably should be including link templates too).

Deferring to json-schema would allow for separate resources representing the schema which can be queried by both developers and generic api clients and be a lot more useful and a more fuller description.

**Comment by sverhagen** [comment]
Would it make sense to create a new issue for the lean question in casu, here, which is about linking, as this issue has a lot of unrelated things mixed into it, much of which a bit emotional, if I may say so? If so, I could go ahead and create that issue. If not, I'd like to go ahead and add my five cents to this one.

**Comment by ahacking** [comment]
@sverhagen Emotional ? I don't think so,  I have listed some very technical reasons why I can't use JSON-API as it stands today despite that I would very much like to. If those problems didn't exist I would be conforming to it, there is no emotion in it. Others are likely to also come across these issues at some point once they use the spec in anger on moderately complex systems . I am implementing a large system, with many moving parts and found issues that really are show stoppers for me.

That is not to say that good work isn't being done, to the contrary I think json-api is advancing things forward and I respect those championing the effort, I have provided a lot of feedback on the drafts so my points above are not ill-considered. The reality is I have a pressing need for a solution that works well for me today and the problems I have highlighted mean I can't deliver product based on the draft, hence abandoning conformance for the time being. I do have reservations on the complexity side of things which will never go away because of the balancing act the spec must take due to supporting different id strategies.

I'll add another id issue right here which I have since discovered is non optimal in json-api and another show stopper for me (and others who have larger systems).

I have resources with references to 15,000 items through a many-to-many relationship.  Many-to-many is tough, especially when the cardinality gets large.  I can't adhere to json-api because it either wants me to list id's explicitly in links, or says I should comma separate them in a href.  Well no, that makes the initial response massive and the related query massive too, not to mention inefficient for a server to implement the query.  I prefer to use a href that passes the related model id as a query parameter. Its much more succinct to say:

```
/api/foos?bar_id=a1210292-025a-44a9-a1b0-14d9e711f6a3
```

than

```
    /api/foos/134aab44-9e1a-4570-bd57-51db6b2f6a85,.... x15 thousand of them
```

Or naively issue 15 thousand GET requests.

Since I use UUIDs which are 36 bytes  \* 15,000 this makes the request URL approx 540KB in size with the comma separators, and it results in a far less concise DB query.  My approach has a url length of ~54 bytes and a very efficient db query which is also easy to apply offset and limit for paged results.  Since there are various implementation limits for url lengths (as low as ~2000 bytes) the explicit id approach requires one to issue many batches or switch to a POST for 540KB of ids.  With a "multi GET" what if one of those 15,000 items gets removed or has the "visible/shared bit" changed? What should the GET response be? Should the whole response fail or should the server just silently drop the invisible ones? I would rather just avoid this kind of problem that json-api leads me into.

Now whilst the above sounds bad, its just the start.... we have to remember that for all 15 thousand of those results, they also have inverse links back to the original resource collection (since its a many-to-many relationship), so each resource could be carrying  540KB worth of ids assuming balanced many-many cardinalities. This means we end up shipping back 8325000000 link ids, totalling 8GB for that one inverse relation plus the original 540KB when using explicit ids.  My non conformant json-api approach ships 15000 urls (791K)  plus the initial link url of 54 bytes which is much more palatable.  Remember I am only trying to get 15001 resources and only the knowledge of what they may link to, we haven't included other relationships, or even the resource attributes, just a single many-to-many relationship from a single resource with a link cardinality of 15,000 related items.

I would of course like to see my original list of problems and the one above dealt with in the spec hence taking "a wait and see" stance to see if it matures, whilst right now purposely being non-conformant for very good reasons.

**Comment by dgeb** [comment]
@ahacking Given the scale of relationships you're working with, I would recommend referencing them via an `href` rather than by ID. You can declare hrefs for individual resources with [collection objects](http://jsonapi.org/format/#document-structure-collection-objects) or through [URL templates](http://jsonapi.org/format/#document-structure-url-templates) at the top level. In this way, you can avoid exceeding URL length limits, server processing inefficiencies, etc. You can also paginate related resources to avoid returning them all at once.

> With a "multi GET" what if one of those 15,000 items gets removed or has the "visible/shared bit" changed? What should the GET response be? Should the whole response fail or should the server just silently drop the invisible ones?

It is up to the server implementation whether a GET fails on the first error or with a comprehensive list of [errors](http://jsonapi.org/format/#errors). If multiple error codes are encountered, say 401 and 404, then the most generally applicable (i.e. 400) error code should be returned. This is [spelled out for bulk patch ops](http://jsonapi.org/format/#patch-responses-other), but should be made more clear in the GET section.

**Comment by dgeb** [comment]
@sverhagen please go ahead and discuss this issue's main topic "Cannot link from embedded objects" here rather than opening another issue.

**Comment by ahacking** [comment]
@dgeb Absolutely I do use href for all my one-to-many and many-to-many relationships but I consciously make sure to not follow the SHOULD recommendation of appending ids as the current draft suggests because it doesn't scale arbitrarily. Since I want a uniform approach for linking I now use href for many-to-one/belongs-to links as well.

My question about multi-get was rhetorical since I've already formed the view based on Http semantics that get either returns the requested resource or it should fail and not silently or otherwise skip ids that have been deleted or are out of scope due to access control. A foreign key query is a far more forgiving GET than using explicit ids as well as efficient and scalable. I think it should be the recommended approach for linking unless one is side loading resources.

**Comment by dgeb** [comment]
@ahacking I agree that SHOULD is too strong a recommendation for IDs instead of hrefs, except in the case of compound documents (in which IDs are required to associate resources). I don't have time right now to re-read the whole spec to isolate these instances, but I'd welcome a PR to make this recommendation less strong in the general case.

**Comment by ahacking** [comment]
Further to my above comment there probably needs to be some guidance on what strategy for linking is applicable when. It is reasonable to use ids for has-one/belongs-to and it is required for side loading. But href should be used for other cases. Perhaps a new section could be added on coalescing hrefs via link templates as well to support building a union of foreign key requests to avoid 1+N queries.

**Comment by ahacking** [comment]
Ok we posted simultaneously.

Seems we are in agreement. :)

**Comment by sverhagen** [comment]
I felt that you were expressing frustrations (which may not be the same as emotions) that went beyond the scope of linking from embedded items. While I appreciate the use of Github issues to reflect on the larger project in this way, it being in the same issue as where a discrete subject such as linking from embedded items is discussed might be confusing to later readers like myself. Meanwhile I've read my way through things, so I'm good from here on. For empathetic reasons as well as selfish reasons, I am sorry to see that jsonapi.org isn't working for you (now).

My first reaction when reading some of your situation is that there is some design issues with your system. That's naive (if not stupid) of me to think, because you seem an intelligent person, who has put ample thought into this, I am not familiar with your requirements, and you may also have system constraints that are beyond your scope or control. And, after all, I'm also struggling with some things, hence I'm here. For the time being we're adopting jsonapi.org -- but with a few exceptions defined.

<hr/>

My question is about links, let me be clear first what links I'm talking about:
- Top-level links (`links`)
- Resource object links (`data.links`)

Per my interpretation, the format describes that top-level `links` are only in support of resource object `links`. I arrive at that conclusion since `posts.author` implicitly corresponds to `posts.links.author` (from the example on the main page). Now, what is represented by such link? This model seems to fit very well for loose relationships: "here I give you the resource object, and -- by the way -- here's some useful links for it".

The objects that we are designing have other relationships, that sometimes are even essential for the description of the item, and we're wondering how to use a mechanism like the `links`/`data.links` for that.

Okay, a more concrete example of a resource object:

```
data: {
    id: 1,
    itemType: 3, # would like to link this
    project: 5, # would like to link this
    customFields: {
        name: "my item",
        description: "whatever",
        commentCount: 7,
        color: 11 # would like to link this
    },
    links: {
        comments: [13, 17, 19, 23, 29, 31, 37], # no issue here within the format
      et cetera...
}
```

As you can see there's a bunch of things in here that we would like to link to some other resource, using top-level `links`, but that we don't want to stick in the resource object `links` (`data.links`).

I can see a nice solution in using fully-qualified keys on the top-level `links`, so that I can unambiguously link to whatever place in the resource object. For instance the following top-level `links` section:

```
links: {
    data.itemType: { ... },
    data.project: { ... },
    data.customFields.color: { ... },
    data.links.comments: { ... }
}
```

**Comment by ahacking** [comment]
@sverhagen My issue is not with the design of the system, it uses a moderately normalised database schema but some modern postgres features for efficiency and convenience.  My problem is with the inability to express attributes with structure that happen to contain links, when those attributes are not a string, date, bool, or number.

Your example is not the correct structure:, when using the `data` key, resources should be identified by `type`, not `itemType`.  However using a link for type has been ruled out as it should correspond to a resource collection name when using typed collection containers.  For polymorphic types it gets problematic (do you use the base class or can you partition into subclasses, and how do you express the concrete type in the resource, can it be different to the container its in?, how would clients get knowledge of the type hierarchy?), but that is a separate issue but it is related to trying to support ids that are scoped to collections, vs just using UUIDs.

The `project` attribute in your example would be put into `links`, and if you carry `itemType` and `type` then `itemType` would also be put into links.

The bag of `customFields` example does illustrate the difficulty of segregating links, I similarly have a bag of custom fields in my models for product resources, but some of those custom field values can also link to other resources.  I also have things like `dimensions`, which require each dimension to specify its length and reference a units definition, and things like tint/colour, which reference branded colours (think paint manufacturers and the tens of thousands of colours they have.  I just cant express those kind of attributes within a resource when half of the attribute value must exist in the resource and the other part of it within `links`.  If you have a value which is an array (eg an array of measurements with a link to unit type and scalar value) the `links` container becomes unworkable.

A solution moving forward would be to just drop the`links` object altogether, I cannot see what benefit the partitioning of attributes and links provides, it only gets in the way of serializing attribute values which as part of their value construction may actually need to link to something.  If there is an argument regarding automatic handling of link resources, then I would say that is what JSON schema or indeed link templates are there for.

I'm not a fan of link templates either as I think API discovery concerns should be deferred to JSON Schema rather than burdening every request/response with schema documentation just in case the client is trying to be the equivalent of a semantically barren JSON based registry editor of the internet. Including API documentation is a slippery slope because link templates won't cut it for an ignorant client and the temptation is always there to keep embellishing the templates/quasi schema to describe more and more aspects of relationships and resources.  Hence why I say don't go there, just defer to JSON schema. This is another thing I would like to see changed in json-api: drop templates altogether and include a JSON-Schema Link header as per RFC5988 to a JSON schema document for API discovery so all those internet registry editors that have no idea of what they are trying to process can build their forms.

**Comment by sverhagen** [comment]
> Your example is not the correct structure:, when using the `data` key, resources should be identified by `type`, not `itemType`

Resource objects MAY contain a `type`, is what I read, and mine don't, as it's irrelevant for the example. I can see how the `itemType` is confusing in this example, but it does not define the structure of the shown JSON, it's just meant as a link to a resource object of another structure, for which `"type": "itemtypes"` would probably be true.

> The `project` attribute in your example would be put into `links`

If I were to comply with the specification: yes. But that's exactly the core of the question. I don't want to be forced to do that.

> drop the `links` object altogether

I would not go that far, one could consider it a good practice. But I don't care too much either way. As long as I am allowed to indeed do this:

> serializ[e] attribute values which as part of their value construction may actually need to link to something

That is exactly what I have a need for, and I want to do it by being allowed to refer from the top-level `links` to **anything**/**anywhere** in the resource object. And for that I propose keying the top-level `links` with fully qualified paths into the resource object, such as: `data.customFields.color`, `data.links.comments`.

> JSON schema [...] are there for

That is a very valid suggestion, but adopting this specification is already a good evolution in our approach to REST APIs. We have to pick our battles, and we don't want to introduce a thing like JSON Schema at this time.

**Comment by ahacking** [comment]
My point about`type` which seems to have been lost is that if you did want it to be a link to  a resource, you can't with the current spec as `type` must be an attribute, (it cannot live inside `links` and also should be the name of a resource collection.

If anyone can provide a good reason why the `links` container is absolutely required then please speak up, it just seems like an idea that has little merit and only serves to hurt attribute value serialization.

We do pick our battles, I say drop link templates because the use case for them is questionable. The only clients that benefit are those that don't understand the api they are trying to use, but then they cant create or update resources, or really do much with the api even with link templates.  Link templates buy very very little for clients that have no understanding of the api they are targeting.  Given there is a reference document model in json-api the link template really isn't required at all. A client can't magically use a link template without being written to understand the json-api spec conventions, the reference document model and the transport document transform.  A client can't know how to apply the template either since the RFC doesnt say where values come from. So please explain where you see the value of link templates other than documentation ?

If you can state a clear use-case that provides value I'll be all ears. Right now  I can't see the value of including documentation within my api messages. I would strongly suggest that API discovery and documentation is better achieved using a Link header and deferring to JSON schema than adding cruft to json-api.

The json-api spec will be smaller without link templates and that is a good thing.  I wont ever use link templates or put API documentation into my requests/responses because it is has no value. I am happy to include a Link header for api discovery and that may have value for all those json registry editors out there, plus its nice to be able to reference an api spec as a developer.

**Comment by sverhagen** [comment]
> Given there is a reference document model in json-api the link template really isn't required at all

I was made to understand that the client shall never hard-code URLs (which includes composing them on their own accord). Even if they know all the types (`type`s) they should not make assumptions about URLs, should they? Clients that do seem to be considered unRESTful by (what I consider to be) purists.

> A client can't know how to apply the template either since the RFC doesnt say where values come from

Given a value of `{posts.author}` doesn't the specification teach me that I can find the value-to-be-substituted in `posts.links.author`?

> If you can state a clear use-case that provides value I'll be all ears

I find the use case in the specification (`post.author` to resolve one of `authors`) pretty clear. You may well argue that you know other ways to do it, or that you know circumstances under which this way is not ideal, but you are not mandated to use the links.

In that respect and for the particular topic of "links from embedded objects" it seems that the specification isn't in your way even (you can choose to just not use the feature). But it is in my way, since I want to link "attribute values" that do not live in the resource object's `links`.

>  I wont ever use link templates or put API documentation into my requests/responses because it is has no value

And you're free to do so -- that's well within the specification. I agree that API documentation is a no go inside the actual API (that makes me mostly think about resource object formats, since URLs are to be discovered anyway). And I also agree that link templates might allow for a sliding slope. But that's up to the API designer to use things wisely. Don't think you're gonna be able to craft a spec that prevents bad APIs ;)

**Comment by sverhagen** [comment]
> My point about `type` which seems to have been lost is that if you did want it to be a link to a resource, you can't with the current spec as `type` must be an attribute

The same could be said about `id`. The specification provides some... one may say features... one may say limits?

**Comment by ahacking** [comment]
@sverhagen I think you're missunderstanding what I have written.

> I was made to understand that the client shall never hard-code URLs (which includes composing them on their own accord). Even if they know all the types (types) they should not make assumptions about URLs, should they? Clients that do seem to be considered unRESTful by (what I consider to be) purists.

In my API's I have moved away from using ids as they have scalability issues as previously outlined.  In that respect I am closer to a hyper-media api, as no additional client processing is required to infer a link, but I really care less about hypermedia for API's as the assumptions by those purists are plain wrong.  Modern clients have state mashed up from many endpoints  so the basis of application state is not any ones api.

> Given a value of {posts.author} doesn't the specification teach me that I can find the value-to-be-substituted in posts.links.author?

My point is that the spec **does** allow a client that is written in the knowledge of the JSON-API specification and reference model to build the url. I don't need a template.

In order apply a link templates a client requires special knowledge of the json-api reference document model and the transport document model to aquire the variables to substitute into the link template to build the uri. So what is the point of link templates then?  Go read the RFC 6570 for URI templates, you will see that the source of substitution variables is not defined. A client has to have other knowledge..  that knowledge is the json-api spec, and with that knowledge I now don't need link templates. Again where is the value, you have not demonstrated they actually solve anything. Link templates are superfluous.

> In that respect and for the particular topic of "links from embedded objects" it seems that the specification isn't in your way even (you can choose to just not use the feature). But it is in my way, since I want to link "attribute values" that do not live in the resource object's links.

Not sure what you're saying. I raised the original issue of `links` inside embedded values as a disappointing show-stopper issue for me. If you have understood what I have said, you should realise my values have links to other resources within them. Just like you, I have attribute values, which need to link to other resources.  My values are not resources in their own right, they don't have identifiers and they don't have endpoints yet they link to things.  The spec requires all links out of a resource to other resources to be in the `links` bag, lets not pretend it doesn't, its not an optional feature, its what the spec requires.  You can use the same argument, ignore links altogether and we can all go our separate ways and we achieve nothing with json-api.

> And you're free to do so -- that's well within the specification. I agree that API documentation is a no go inside the actual API (that makes me mostly think about resource object formats, since URLs are to be discovered anyway). And I also agree that link templates might allow for a sliding slope. But that's up to the API designer to use things wisely. Don't think you're gonna be able to craft a spec that prevents bad APIs ;)

I disagree, the goal/charter of json-api is to end/subdue the debate over json api design and be able to use something that puts you in a safe place.  I think I've given enough arguments where it doesn't quite achieve that goal, and in fact taken on face value makes recommendations that can hurt. By providing experience using json-api in anger I hope to improve the spec and @dgeb has made many adjustments on user feedback such as this.  I could just quietly ignore json-api but I really do want to see something come of it so I can focus my efforts on building my applications using tools and libraries based on json-api that work really well rather than worrying about how to do the plumbing.

**Comment by ahacking** [comment]
@sverhagen 

> The same could be said about id. The specification provides some... one may say features... one may say limits?

The `Resource Attributes` section defines the reserved keys in resource objects and their use.

**Comment by sverhagen** [comment]
My suggestion wasn't to ignore the specification, I already said being sorry that jsonapi.org isn't working for you. In this particular case I was just arguing that the spec not requires you to use everything that it offers:

> A document's top level MAY also have [...] `"links"`

You _did_ raise the original issue of `links` inside embedded values. But you then continue to argue against `links` and URL templates altogether (I'm sure you'll correct me if that's possibly a misinterpretation), where _I_ am still in a place where I want to fix (and keep) them.

Different (prospective) users of this specification will be at different levels of maturity at which they build RESTful or other APIs, JSON, URLs, etc. Different levels on an individual basis, but also of their organizations and API users. This is even still true when you leave different requirements, different fields of application out of the equation. Maybe some day I may agree with all your observations, but that day is not now.

I do appreciate your insightful posts, but I feel we have now extensively argued where each of us would like to take this issue. If possible, I would like to hear some other voices, at this point.

**Comment by ahacking** [comment]
@sverhagen Id also like to hear some other voices and indeed have requested that others speak up on sound use-cases/ rationale for link segregation within resource and use cases/rationale for link templates. I don't want excuses and apologies for things in the spec, or "you can ignore this or that".

I have argued about the problems with the way links are modelled within resources, yes I have painfully explained the issue with `links`, and the solution I propose  is to remove the segregation.

That IS a solution.  You haven't said why you don't like it and why you need to keep `links` even though it is the cause of your problem.

I have asked for people to speak up on the value of the `links` segregation, as it only serves to hurt.  You want `links` but you cant say why, you haven't given me a use case or defensible rationale supporting `links` in resources or link-templates.

> > A document's top level MAY also have [...] "links"

I am talking about `links` in a resource. Link definitions at the top level are not a stake through the heart but `links` in a resource are. My only concern about `links` at the top level is that they are superfluous and unless someone speaks up, the use for link templates doesn't appear sound. I'm happy to be corrected and will humbly admit defeat when the rationale is justifiable.

>  Maybe some day I may agree with all your observations, but that day is not now.

Respectfully I don't mind if you agree with all of my observations or not, I never sought your approval. But if you are going to stand defiant, or by saying that attempt to discount my arguments, you better defend your position.  I am very happy to move my position if I am wrong on anything and as new information comes to light so there's an opportunity for you to show me where I am wrong or what I haven't considered.

My issue simply stands until a solution is found or it can be shown to be a non issue or not a problem json-api wants to solve. The first option (finding a solution) is my preference as I know others will undoubtedly arrive at a similar crossroad, but I didn't raise the issue to have the approval of everyone, I want to see if there is a solution that has quorum consensus.

Your comments have thus far muddied the initial issues I raised, and to be honest have not shed any more light on a SOLUTION. The json-api is a draft, it is not even a draft RFC, its just a draft document a bunch of people are rallying around, its not appropriate to treat it as some kind of immovable dogma. I am happy to slash and burn anything that cant fend for itself or provide useful value and a sound rationale for existing. I've chaired and participated in a number national standards committees and json-api is a long way off from that level of preciousness (thankfully).

I would sincerely ask that you or others come up with an alternative solution, defend your need for the `links` segregation in resources, defend you need for link templates with a sound use case and show exactly why they really are needed.  We can simply discuss the merits of the various options as opposed to the hand waving. I'll be happy to concede the need for these things if there is a sound rationale for them.

All said, its pretty simple, I want a ratified solution or I just go elsewhere and the issue can be closed. I am very willing to participate in arriving at the solution and I value rational defensible input.

**Comment by sverhagen** [comment]
I already said that I don't care either way whether the special meaning of `posts.links` and its reserved status is removed or maintained. What I want is to be allowed to match a top-level `link` to _any_ attribute in the resource object. So that I become allowed to add top-level `links` for `data.customFields.color` (from my example), `data.eab9b2af-73f0-4e13-b348-0bd4377fb06a.address.city` (from your example) or `posts.links.author` (if I were to choose to have a `links` attribute in my resource object after all). That would be a _solution_ to my perception of the problem. I want this to be able to add URL templates and thus effective links out of my response, to model the "foreign key" relationships to other resources, and because I want to use the `linked` section that only exists in conjunction with the (top-level) `links` section. Sorry if that didn't stand out enough from this long-winding discussion :wink:

**Comment by ahacking** [comment]
You can use URLs in your links (wherever they end up being located) and use JSON pointer uri fragment to address internal fields.  The current spec uses json-pointer for patch. I use it in my API for pointing at problem fields (validation errors) on error responses.

The spec could explicitly include support for JSON pointer uri fragments in the relationship URLs section similar to what is done for PATCH as the URL is against a reference document not the transport document.

**Comment by ahacking** [comment]
Really your issue is more an attribute/fragment/sub-resource level linking problem than a resource linking issue.

Your issue is about links into something, my issue is about linking out of something

**Comment by ethanresnick** [comment]
Tempted to agree with @ahacking on the following: if link templates (or a schema) can identify which attributes in a resource are links, there shouldn't be a need for the separate resource-level `"links"` key. The only argument for keeping it, then, is that it lets you give a specific linked resource/collection a custom `"href"`, if it's location doesn't conform to the template/schema. But that seems more like the edge case than the common case, and so could be treated as such. This might look like the following:

```
{
  "links": {
    //either of the below could also be in the {href: "x", type: "y"} form, as currently allowed
    "books.author": "http://example.com/author/{books.author}",
    "books.publisher": "http://example.com/publisher/{books.publisher}"
  },
  "books": {
     "title": "My title",
     "author": "16",
     "links": {
       "publisher": "http://www.macmillan.com/index.json"
    }
}
```

Above, I've changed the meaning of the resource-level `"links"` key so that all it does is provide custom resource urls when a template can't apply. Otherwise, it's not needed. If, as I said above, custom urls are the exception and not the rule, then this seems more appropriate. (Btw, with this new meaning we could rename it to something other than "links"...I just left it at that because links is already a reserved key.)

Building on the above, and addressing @ahacking's concern about sending the url templates with every response, the top-level `"links"` key could have an alternate meaning in which it simply points to a url that returns all the templates. E.g.:

```
{
  "links": "http://example.com/my-url-templates",
  "books": {
     "title": "My title",
     "author": "16",
     "links": {
       "publisher": "http://www.macmillan.com/"
    }
}
```

This would be functionally identical to the prior example; the client would have to request the url templates url once (unless it already knows the api), but then it'd be all set. (I'm suggesting the above format over having a `Link` header that points to a JSON Schema only because it seems like less of a departure from the current design, while perhaps giving you most of the same benefits. I should confess though that I don't know much about the JSON Schema spec, or what other advantages/drawbacks using it would bring.)

Either of the above examples could solve the linking to embedded resources problem simply by letting the path point to nested attributes, which is along the lines of what @sverhagen has suggested. E.g.:

```
{
  "links": {
    "books.dimensions.unit": "http://example.com/units/{books.dimensions.unit}"
  },
  "books": {
     "title": "My title",
     "dimensions": {
        "width": 200,
        "height": 40,
        "unit": "4"
    }
}
```

**Comment by dgeb** [comment]
As of #341 (RC2), relationship links are officially supported through a resource's `links` object. The top-level `links` object is no longer used to template resource relationship links.

It is recommended that embedded objects with IDs and links be "normalized" as full resources themselves.
