### ISSUE TITLE
Relationship URLs Repsonses

### ISSUE THREAD

**Issue by lgebhardt** [json-api/json-api#251]
I need some clarification on the responses for relationship URLs.  If we have a relationship URL like `/photos/1/links/comments` what should the response look like? For a GET request is the primary document simply the array of comment ids from the /photos/1 resource where includes are relative to the parent photos links resource? For example:

```
GET /photos/1/links/comments?include=comments
```

responds with:

```
{
  "comments": ["1", "2"]
}
"linked": {
    "comments": [{
      "id": "1",
      "body": "Nice!!!"
    }, {
      "id": "2",
      "body": "I've taken better"
    }]
}
```

Or is this URL actually a request against the comments resource (filtered for a photo) such as:

```
GET /photos/1/links/comments?include=photos
```

responds with:

```
{
    "comments": [{
      "id": "1",
      "body": "Nice!!!"
    }, {
      "id": "2",
      "body": "I've taken better"
    }],
  "linked" {
    ""photos": [{
      "id": "550e8400-e29b-41d4-a716-446655440000",
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    }]
  }
}
```

I think my issue is I'm not clear on what the primary document type is for relationship requests. When making a GET request (`/photos/1/links/comments`) is seems the primary document type is, in this example, comments. However when posting a new comment relationship to the same url it seems we are modifying the photo resource and the response should be relative to that. Either way I think we should be consistent.

**Comment by ZenCocoon** [comment]
I believe your second version to be more logic, therefore accessing `GET /photos/1/links/comments` should request against the comments resource (filtered for a photo).

When creating a new comment using the same URL `POST /photos/1/links/comments` you actually create a Comment and define it's photo association with the Photo having the id `1`.

**Comment by lgebhardt** [comment]
I agree those two cases it does seem logical to structure it around the comments resource. But wouldn't `DELETE /photos/1/links/photographer` more logically go on the photos controller since we are editing the photo resource?

**Comment by ZenCocoon** [comment]
What do you expect to do with this URL `DELETE /photos/1/links/photographer`?
1) To delete the photographer?
2) To delete the association between photo 1 and it's photographer?
3) To delete the photo 1?

**Comment by dgeb** [comment]
@ZenCocoon (2) should definitely occur. The server may optionally perform (1) and/or (3) as a result of deleting the association (but it seems unlikely in this example).

@lgebhardt I don't think your question is addressed by the current spec. You're basically asking how to request a particular format (full object vs. id-only) of a resource, which seems to be a gray area between `include` and `fields`.

I would expect that the following request would return only IDs:

```
GET /photos/1/links/comments
```

And the following request (or an alternative specified by a URL template) would return resource objects:

```
GET /comments?photos=1
```

Given that both of these options are covered by the spec, I'm not sure that we need to cover a hybrid approach as well.

**Comment by ZenCocoon** [comment]
@dgeb. Agreed on ID-only here.
@lgebhardt Based on option (2), you are then tapping on a has and belongs to many "join" table, therefore I would expect the returned object to be only about the join table, optionally including linked objects.

Examples:

Request

```
GET /photos/1/links/photographer?include=photographers,photos
```

Response

```
{
  "photographers_photos": [{
    "id": "123", // ID of the joining object
    "links": {
      "photos": "1",
      "photographer": "2"
    }
  }],
  "linked": {
    "photos": [{
      "id": "1",
      "src": "https://..."
    }],
    "photographers": [{
      "id": "2",
      "name": "Yuri Arcurs"
    }]
  }
}
```

P.S.: For comments, I don't see a has and belongs to many need in this context (but might be wrong) so would use an URL like below to simply tap in the comments controller.

```
GET /photos/1/comments
```

**Comment by lgebhardt** [comment]
@ZenCocoon But it could also be a simple one to many relationship such as a comment containing the post_id. In that case we wouldn't be exposing a linking table. Maybe linking tables should be handled with a separate resource to represent the linking table entries.

@dgeb If we include only the ids do you think we should support includes, and if includes do we support fields as well? That allows the fetching of full objects, but it seems a bit confusing since it's not clear what the primary resource is. Maybe the best is to just return the ids with no support for includes.

**Comment by dgeb** [comment]
> Maybe the best is to just return the ids with no support for includes.

I agree. The use cases for calling GET on relationship URLs (e.g. `/photos/1/links/comments`) seem pretty narrow. It will be far more common to call POST and DELETE on these URLs to manipulate relationships.

Furthermore, it will be much more common to call GET on the related resource's URL (e.g. the recommended `/comments?photos=1` or the alternative `/photos/1/comments`) to retrieve related resource objects. Support for `include` and `fields` makes perfect sense with these endpoints.

I'm afraid I didn't spell out the difference between relationship URLs and related resource URLs as clearly as I should have in the latest rev of the spec. I'll submit a PR for review soon.

> Maybe linking tables should be handled with a separate resource to represent the linking table entries.

Yeah, a relationship that contains any data beyond links should become a resource itself.

**Comment by ahacking** [comment]
It seems the complexity/uncertainty is coming from nesting resources. 

The reference document model is a flat resource space, I'd suggest sticking to flat endpoints too and treat "parent" ids simply as a filter. I also don't buy into the rails activerecord-ism of ownership based relations and prefer a one-to-many, many-to-one, many-to-many perspective of describing relationship cardinality. Your nesting of resources comes from a flawed data modeling perspespective because resources can simultaneously "belong to" many things and you then have no canonical endpoint for a resource.

Now I know some people just want to have nested resources because they are used to rails, activerecord and sever rendered views but this is another case of a flawed view point and unneeded complexity which can be avoided if intelligent choices are made upfront. I'm always concerned about a spec trying to be all things to all people. If the intent is to be able to support any API then we have a long road ahead, but I was under the impression JSON-API is about making good choices not unnecessary ones that make life hard.

Given the examples above it would seem reasonable to traverse an arbitary number of resources ie /photos/1/photographer/friends/4/photos/comments/7/commenter/photos/1

Any level of nesting is contrived for an api and unnecessary given we have filtering and a reference document model that is flat.

**Comment by dgeb** [comment]
> The reference document model is a flat resource space, I'd suggest sticking to flat endpoints too and treat "parent" ids simply as a filter.

I agree. This is why `/comments?photos=1` is [recommended in the spec](http://jsonapi.org/format/#fetching-filtering). 

> It seems the complexity/uncertainty is coming from nesting resources.

To be clear, relationship URLs such as `/photos/1/links/comments` are not allowed to be arbitrarily nested. They are still part of the flat resource space.

Speaking only for myself, the uncertainty in this issue comes from not having fully spec'ed out relationship endpoints (specifically for GET).

**Comment by ahacking** [comment]
@dgeb Thanks for that. Perhaps as part of the endpoint treatment we should have some SHOULDs regarding recommending flat endpoints or MUST for canonical flat resource endpoints even if nested endpoints MAY also exist.  I'd also like to see first class treatment for using foreign key based filter URLs instead of link ids as per my previous scalability rant. I can probably draft something up but I don't want to step on your toes.

**Comment by dgeb** [comment]
> Perhaps as part of the endpoint treatment we should have some SHOULDs regarding recommending flat endpoints or MUST for canonical flat resource endpoints even if nested endpoints MAY also exist.

I'm pretty sure MUST is too strong for anything URL-related in the spec. We do use SHOULDs already for URLs for [collections](http://jsonapi.org/format/#urls-resource-collections) and [individual](http://jsonapi.org/format/#urls-individual-resources) resources. MAY is used for [relationship URLs](http://jsonapi.org/format/#urls-relationships) - the added flexibility there is more that the endpoints may not be present at all. Feel free to submit a PR to tweak any of this wording and then we could discuss it there.

We should re-focus this issue back on _responses_ from relationship URLs, if there's anything left to discuss.

**Comment by steveklabnik** [comment]
Yes, the spec **MUST** not have any **MUST** s relating to URL structure. :)

**Comment by dgeb** [comment]
Closing in favor of the more specific #348.
