### ISSUE TITLE
Contradiction on document top level members

### ISSUE THREAD

**Issue by damienalexandre** [json-api/json-api#257]
This section (http://jsonapi.org/format/#document-structure-top-level) tell:

> A document's top level MAY also have the following members: "meta", "links", "linked"
> No other members should be present at the top level of a document.

But the errors node (http://jsonapi.org/format/#errors) is missing from this authorized list:

> Error objects SHOULD be returned as a collection keyed by "errors" in the top level of a JSON API document

Also, adding a full example of response with an error could be nice.

**Comment by dgeb** [comment]
Errors are the primary resources in the response. This should probably be made more explicit.

> Also, adding a full example of response with an error could be nice.

Agreed! Sorry... I've been meaning to add some examples for a while.

**Comment by damienalexandre** [comment]
Ok I didn't understand it that way. 
So it should also be stated that "errors" can't be the name of a real resource (what if my API exposing the last errors in a system has an error? :neckbeard:).

**Comment by dgeb** [comment]
> So it should also be stated that "errors" can't be the name of a real resource

Yes, good point!

**Comment by jwhitlock** [comment]
I'd like an example of errors in the docs as well.  The proposed JSON API Error format is richer than a lot of server frameworks currently support.  I'd like to see examples of:
- A failed PUT to create a resource, due to a validation error on an attribute (important for client-side decoration of forms)
- A failed PUT to update a resource, due to a validation error on a linked resource (for example, when choosing one of several profile images for a user, picking an image for a different user or a nonexistent image ID)
- A failed PATCH (this could be several examples)
- An authentication error (such as a 403 due to credentials not supplied)
- A failed request due to invalid JSON (for example, using single quotes rather than double quotes)
- A failed request due to invalid application/vnd.api+json (missing a required key, or passing a list rather than a dictionary)

You can see some examples of my attempts on kevin-brown/drf-json-api#3, but these examples are constrained by what is easy with the current framework.  Showing 'ideal' examples will encourage the big changes needed in the frameworks.

Let me know if I should open a new ticket.

**Comment by dgeb** [comment]
@jwhitlock sorry to take so long to reply. Seems that some examples are referenced in PR #281, but I think a new ticket with a list of error examples that you'd like to see would be useful.

Going to close this since #341 addresses the primary focus of this issue.
