### ISSUE TITLE
Handling hash attributes in the resources

### ISSUE THREAD

**Issue by wijet** [json-api/json-api#258]
Hi,

I'm developing JSON API compatible API and I would like to ask
about handling nested attributes - hashes. I'm going to use them for
displaying models translations but surely hashes will be handy in other cases.
I didn't find any example with hashes in official docs.

My idea is to display them with locale name as keys and translated strings
as values. I've checked below json with latest [json api schema](https://github.com/json-api/json-api/blob/gh-pages/schema) and it's valid. 

``` json
{
  "posts": [
    {
      "id": 12,
      "title": {
        "en": "English title",
        "fr": "French title"
      }
    }
  ]
}
```

Is it the best way to do it? I know that json api aims to be flat, without 
embeding child documents recursively. This way it's pretty easy to access it on client side. Right now I have only ruby client for it and later on there will be one in ember.js.

**Comment by ZenCocoon** [comment]
In cases like this, hash content is unique to its parent object so loading multiple time the same content can't append. Not being an independent object either, It feels perfectly justified to me as you presented it.

@dgeb It's there any official position on this or it's left to the API developer to use hashes when felt justify?

**Comment by dgeb** [comment]
The spec does not prohibit the use of nested / embedded objects. @wijet's use here seems reasonable.

IMO, embedding really breaks down when the embedded object either has an ID itself or links to other resources. In those cases, I would consider the embedded object a resource itself and not allow it to be embedded as an attribute. This is an area of the spec that we really should clarify before 1.0.

Linking from embedded objects is being discussed in #238.

**Comment by ahacking** [comment]
I've encountered cases where I have embedded attributes that do link to things, many cases in fact. Eg a name that has personal title first,middle, last, period of use, and registry. The registry being a resource and names being an ordered array of current and past names. The name is an attribute of the person and not a separate resource, it has no ID and ordering is significant.

I have similar constructs for residential and postal addresses too, in fact many of my attributes have multiple values for historical record keeping. I also have other attributes in resources such as colour which has rgb and also cielab colourspace and optional link to a branded color name.  Forcing IDs whenever an attribute may be composed of things (when it is not just a string, number or bool) eg coordinate or rational number would be harmful and the spec correctly doesn't prohibit it.

The thing that hasn't been addressed is linking out of such attributes and it is why I've been asking for the rationale and use case for the current segregation of attributes and links in resources because that part is harmful to many data modelling constructs when it forces ID and resource endpoints anytime composition is required.

**Comment by dgeb** [comment]
@ahacking I understand your perspective from #238 and intend to have a discussion with @steveklabnik and @wycats about it soon.

**Comment by ahacking** [comment]
@dgeb thanks, appreciate the effort you're putting into this.

**Comment by ZenCocoon** [comment]
@dgeb @ahacking Thanks for your clarification and inputs on this.

**Comment by wijet** [comment]
Thanks for you responses guys, I'm going to close this one.
