### ISSUE TITLE
Should resource urls be specified when "fields" is forced?

### ISSUE THREAD

**Issue by damienalexandre** [json-api/json-api#260]
I'm not sure what I must do when the "fields" option is used:
- let the "non-resources" fields like "href", "type" or "links"?
- remove them if the end user do not allow them explicitly

I think there is room for interpretation reading the spec,
and I find this response totally ok for a `posts?fields=body` request:

``` json
  [{
    "id": "1",
    "href": "http://example.com/comments/1",
    "body": "Mmmmmakase"
  }, {
    "id": "2",
    "href": "http://example.com/comments/2",
    "body": "I prefer unagi"
  }]
```

http://jsonapi.org/format/#fetching-sparse-fieldsets
http://jsonapi.org/format/#document-structure-resource-urls

Thx for your help!

**Comment by dgeb** [comment]
Yes, there is some room for interpretation in the spec. I think that, as long as the server includes the requested fields, it MAY also choose to return others. Perhaps we should explicitly specify this wiggle room.

I see no problem with always returning `id`, `href`, or any other attributes that are required to use your API. However, I would try to keep this list to a minimum to keep payload size down (since that's a large part of the point of `fields`).
