### ISSUE TITLE
Merge key names in resource-level "links"

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#277]
In a resource level `"links"` object, currently the related model id(s), if included, are at the "id" key if the relationship is a to-one, and the "ids" key if it's a to-many relationship. @wvteijlingen have both talked about merging those into a single key name to simplify things a bit. (Clients would still be able to look at the data type on the key to determine whether the relationship was a to-one or to-many.)

In #276, he proposed calling that key "ids". I proposed calling it "refs" (as in "x references y") . @dgeb asked about using "ref". Frankly, I'm not super passionate about what the key's called, though I do think using a single key is a worthwhile simplification.

**Comment by ahacking** [comment]
+1 for using a fixed set of keys regardless of relationship cardinality. I want this principle to apply where-ever possible, regardless of the actual choice of key.

So on the choice of key, everywhere 'one or more' things are allowed the convention has been a pluralised name, eg endpoint names, and links such as comments, even though there may be zero or more comments. Using `id` semantically seems to rule out more than one, whilst `ids` fits a definition where the key can contain one or more identifiers.

I don't feel comfortable with `ref`, the reason `href`makes sense is because it is a single reference, even though it may contain multiple ids in its encoding, or represent many resources, but that same constraint doesn't fit so well with the id/ids key as there can be multiple values, its not an encoded thing.

You could also go super terse and use `h`, `i`, `t` for `href`, `id[s]` and `type` respectively, which doesn't convey much meaning to an uninformed human, but also doesn't trip up on english inflection rules and also saves a few bytes.  I also don't mind the acronym **h.i.t.** as it says this is what you should hit to get the related things.

**Comment by dgeb** [comment]
If the `id` and `ids` keys are to be merged, I would prefer to use `id` to match the key used in resource objects. I can even rationalize the semantics of this since "id" is itself an abbreviation.

@steveklabnik @wycats thoughts?

**Comment by dgeb** [comment]
Object linkage was revisited in #341 and is described in detail in http://jsonapi.org/format/#document-structure-resource-relationships

Please open a new issue based on this definition if there are still concerns.
