### ISSUE TITLE
put /collection/id1,id2 - are ids realy necessarry in url (thoughts)?

### ISSUE THREAD

**Issue by alexbyk** [json-api/json-api#305]
Hi. An example with `PUT /products/1,2,3` looks neat with small ids, but with  long ids (MongoDB for example with id length 24 characters) it looks not so funny `PUT /products/507f1f77bcf86cd799439011,507f1f77bcf86cd799439012,507f1f77bcf86cd799439013`.

For example, if you will try to update a simple field `{ active: 1}` for many items with mongodb ids, your request will be almost 1,5-2 times larger, than it can be.

Also it may be a surprise sometime to find out that most popular servers have headers limits much smaller than body size and it would be impossible to update more than ~340 mongodb records with default nginx configuration

I propose to allow updating multiple resources with url `PUT /products`

```
PUT /articles
{
  "articles": [{
    "id": "507f1f77bcf86cd799439011",
    "title": "To TDD or Not"
  }, {
    "id": "507f1f77bcf86cd799439012",
    "title": "LOL Engineering"
  }]
}
```

1) It will reduce a request size twice in some cases
2) Server side implementation have to determine ids from body all the same, so ids in url are unnecessary. Without ids in a message header servers will work faster in the most cases

Also according this logic I don't see a reason to keep ID in url for updating a single resource

**Comment by alexbyk** [comment]
It may look different from common REST practices, but the most practices says that PUT request must replace a whole resource while according to jsonApi PUT req. updates only given attributes, so it already differ from the most common practices

**Comment by alexbyk** [comment]
If someone is not sure, is it a real world example: imagine you have a store with many goods. It's a normal if you want to activate 1000+ records. Or for example delete 1000+ records...

So if someone will find this issue have a reason, the next candidate to reconsider is "deleting multiple resource" syntax. Right now it'll be impossible to delete 1000 records in one request according to jsonApi because of message header limitations. And this limitation doesn't make sense, because you can create 1000 resource

**Comment by ahacking** [comment]
Well perhaps you could consider [my proposal at the end of #276](https://github.com/json-api/json-api/issues/276#issuecomment-61397312).

I have a real application with thousands of relationships between resources and it gets difficult to scale given the approach suggested with json-api.  Like you I also use v4 UUIDs so urls blow out.  I do avoid sending ids on resources from the "one-to-many" side and only return id's on the "one-many/belongs-to" side. That cuts things down considerably but [even despite saving gigabytes of wasteful id transfer](https://github.com/json-api/json-api/issues/238#issuecomment-50761768), you still get large request urls when you coalesce related resource requests to avoid  the dreaded 1+N query/request problem.

The spirit of my proposal is that I want json-api to keep out of saying anything about ids, or resource structure and delegate all linking/relationship/scoping concerns to link templates/transforms.  IMO you should be able to use or derive any url the server understands to PUT/POST/DELETE and effect whatever the server considers a resource scope (which could cover many sub resources). I believe what I am proposing deals with far more valid use cases whilst actually simplifying the processing rules so that generic implementations that work for everyone could be a reality as the proposal inherently supports any conceivable resource modelling or identification scheme with no special case logic. Ultimately I want json-api to say less and actually do more in a universal yet simpler way than it does currently.

**Comment by hesalx** [comment]
If you want to delete 1000 items they should have some similar criteria, I think.
If they are unrelated 1000 items it would be harder for a user to choose them then to request their deletion, I think.

I would propose to improve `DELETE` spec with [Filtering](http://jsonapi.org/format/#fetching-filtering) feature from `GET`.
It does not cover all the cases but some of them does. The amount of items which a user can delete "by hand" is not very large. But if a user wants to delete all the items were retrieved with some filters such `DELETE` will be very lightweight with the same filters.

This feature can be a little dangerous and I not recommend it as default for any resource, as fas as mass updating, though. It would be an optional feature, but might be indispensable useful for some of resources.

**Comment by gr0uch** [comment]
Hmm, I'm not sure if this is compatible with [HTTP semantics for PUT](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6). Moreover, the IDs in URIs are useful for fetching/updating relationships such as `/posts/1/author`.

**Comment by alexbyk** [comment]
I can say more, this isn't compatible with HTTP semantics for PUT at all. The truth is HTTP semantics s...ks, everybody feels it but nobody has eggs to admit it. (I have the same thoughts about all other RESTfull stuff too...)

In our case I described a real problem and suggested how to solve it. jsonApi already has many "should" and "may" to consider that it's not 100% compatible with HTTP semantics or other stuff. So  the question should be "which one is lesser of two evils"?

About `/posts/1/author` - I propose to allow multiple updates without id's in url ('may' world), not to restrict

**Comment by ahacking** [comment]
I also commented [here](https://github.com/json-api/json-api/issues/308#issuecomment-61766606) in respect of PUT semantics on a collection resource. Again this in line with my proposal linked above where json-api needs to stop overstepping the line.

**Comment by ahacking** [comment]
@alexbyk I think we share some similar frustrations. I  intend to work up a PR and if it has no interest then consider establishing a rival spec that does get the job done.

**Comment by alexbyk** [comment]
@ahacking yes, looks like. But I suggest let's wait for other opinions for a little)

**Comment by dgeb** [comment]
As part of the new [Bulk extension](http://jsonapi.org/extensions/bulk/), we've removed the requirement that bulk PUT and DELETE requests address multiple individual resources:

> Multiple resources can be updated by sending a PUT request to a URL that represents a collection of resources to which they all belong.

And:

> Multiple resources can be deleted by sending a DELETE request to a URL that represents a collection of resources to which they all belong.

Instead the `type` and `id` of each resource must be included in the request payload, as described.
