### ISSUE TITLE
Rename "data" to "primary"

### ISSUE THREAD

**Issue by ethanresnick** [json-api/json-api#312]
Right now, top-level resources can be keyed under `"data"` when they identify their type within the resource. I think we should rename this key to `"primary"` as that more clearly expresses the relationship between those resources and any resources that may be in the `"linked"` key

**Comment by steveklabnik** [comment]
More generic words are better, because they're less likey to be reserved for some purpose.

**Comment by lgebhardt** [comment]
In this case only reserved keys are allowed at the top level, so a change to `primary` should be doable. However I'm not in favor of the term `primary`. I'd rather see something that is more specific like `primary_resources`. Then there are `linked_resources`. However I think it's fine to shorten those to `resources` and `linked`.

**Comment by dgeb** [comment]
The thinking with `data` was that it could sound natural whether used with a single object or an array.

**Comment by dgeb** [comment]
My above comment is just explaining the rationale behind the choice of the generic `data`. I agree that it doesn't exactly scream "primary resources". Let's leave this open to mull over and decide firmly before 1.0.

**Comment by bintoro** [comment]
Another vote for `primary`! While I tend to use actual resource names in my own implementation, `primary`/`related` makes a ton of sense.

**Comment by SphtKr** [comment]
Giving some thought to this...and some thesaurus searching. What about: `principal` and `related`? Agree that `data` is maybe a little over generic. `principal` pairs very well with `related`, but also stands well on its own and via-a-vis `meta` and `links` in a non-compound document.

**Comment by dgeb** [comment]
Just a reminder that we're trying to avoid multi-word reserved keys so that the spec can remain agnostic about word delimiters (see #341).

**Comment by miguelsan** [comment]
@SphtKr thanks for pointing me out this issue, I was already starting to feel uncomfortable discussing this at #341.

@everybody
We currently have two kinds of resources on the top level: a main content chunk plus the rest of related content wrapped together. In the specification the main content is called _the document's "primary data"_ and the related content is called _a list of resource objects that are linked to the primary data_. We probably agree in that we need not to use those terms in the keys, but they should be a guide for the final decision. The keys should be one-worded, not mistakable for other ones and meaningful by themselves.

My point is that the requirement of distinctness bans `linked` as a candidate, since it is too close to the everywhere present `links` keyword. `resource` (or `resources`) would also fall out, since both `primary_resources` and `linked_resources` could be meant under it, which does not give enough significance to this keyword candidate. The same could be applied to `data`, since both resources include data in the same sense.

What's left? `primary`, `principal` or `main` for the first keyword, `secondary` or `related` for the second one. If nobody has other candidates to offer, those should be enough to take a decision.

**Comment by mattecapu** [comment]
+1 for `main` (brevity) and `related` (distinctness), although `data`, `primary`, `<resource name>`, `linked` never bothered me

**Comment by bintoro** [comment]
Fully agree that `related` is way better than `linked`. Its meaning is immediately obvious, whereas the similarity between `links` and `linked` is a constant source of confusion.

As for the primary resources, an explicit label such as `primary` is IMO preferable to `data`. The related resources are data, too. And as long as the spec talks about "primary resources", I think `primary` trumps both `main` and `principal`. There's nothing wrong with these two, but it just makes sense to keep the key in sync with the language of the spec.

**Comment by dgeb** [comment]
At this point, I may have stared at these terms so long as to no longer be able to reboot my ability to have a "first impression".

It's clear that a lot of people dislike `linked`. I'm fine with `related` as an alternative. It's more accurate than `secondary`, because it may in fact contain secondary, tertiary, etc. resources. Another option that occurs to me is `included`, which pairs well with the `include` param, but I'm not sure I like it better than `related`.

I am concerned with how well `primary` stands on its own without a complementary `related` (or similar) member for balance. I think `data` stands well on its own and works well for objects and arrays. I don't know that I'm terribly concerned with other "data" being present in the rest of the document (that seems analogous to being concerned about having a top-level `meta` co-existing in the same document as `meta` objects throughout the document).

**Comment by gr0uch** [comment]
I think the key names are fine as is. `data` is pretty generic but it doesn't imply that it's the primary entity. `linked` is ok too since it is complementary to `links` and implies that the entities are included due to links in the primary entities.

**Comment by ahacking** [comment]
I also don't mind linked either, as @daliwali said the concept is linked resources, but I'll give a list of possible key names for consideration anyway...

"Primary" content: root/match/matched/main/result/results

"Secondary" content: etc/extra/aux/supp/cache/related/included/linked/auxilary/supplementary

**Comment by bintoro** [comment]
Whatever the keys in the JSON structure, ideally they should derive from the language of the specification. What I'd like to see is crisp terminology that is applied consistently. Please, let's not label something "foo" in the spec and then call the same thing "bar" in the JSON payload.

The spec states:

> A document's top level SHOULD contain a representation of the resource or collection of resources primarily targeted by a request (i.e. the "primary resource(s)").

If "primary" doesn't stand well on its own, then surely this definition should be reconsidered as well, no?

**EDIT:** Oops, I was looking at the older RC. But still, the word "primary" remains; now it's just "primary data" instead of "primary resources". (By the way, why drop "resources" here yet preserve it elsewhere? The word "data" is just so generic as to be almost meaningless.)

**Comment by dgeb** [comment]
@bintoro I think you're getting to the heart of the problem: the primary data can actually be either a resource object, an array of resource objects, _or a link object_. Clearly, we need to expand the definition in the ["Top Level" section](https://github.com/dgeb/json-api/blob/v1rc2/format/index.md#top-level-), which currently reads:

> The document's "primary data" is a representation of the resource or collection of resources primarily targeted by a request.
> 
> The primary data MUST appear under a top-level key named "data". The primary data MUST be either a single resource object or an array of resource objects.

Link objects are used to [update relationships](https://github.com/dgeb/json-api/blob/v1rc2/format/index.md#updating-relationships-).

**Comment by bintoro** [comment]
@dgeb I know, and I'm surprised by the decision to use the same key (`data`) for two distinct things (resources and lone link objects), when everything else has its own key that is actually descriptive.

Apologies if this has been discussed elsewhere, but was a dedicated key for updating relationships considered?

A minimal document:

```
{
  "data": { "type": "photos", "id": "123" }
}
```

Just by looking at this thing it's impossible to know whether it represents a (mostly empty) resource or a link. You'd have to know the URL it is destined for.

In practice this probably does not matter greatly, but one situation that I foresee is getting such a request to a nested collection `/someresource/1/otherresource`. A server might want to be able to verify that the client indeed wants to save an empty resource object instead of a link that should have been sent to `/someresource/1/links/otherresource`.

**Comment by miguelsan** [comment]
That's a pretty interesting point. The document (the body) must at any time be descriptive enough to know which kind of resource we are talking about without looking at the URL. There shouldn't be exceptions on that (even if that implies adding further keys). Unluckily, that's currently not the case, as bintoro has shown.

**Comment by hhware** [comment]
Another vote for `primary` and `included` (`related` is also good).

IMHO, the fact that the word "data" is never used in the specification as a _term_ speaks for itself. The specification always refers to "primary data" -- an implicit acknowledgement of the fact that the word "data" is so generic that it requires refinement. Everything is data: request URL, headers, body, status code, whole / part of request / response...

It is hard to tell the difference between the words "links" and "linked", especially when some of us who speak with accent are saying them over the phone. Please have mercy!

**Comment by kjwierenga** [comment]
+1 for 'primary' and 'related'

**Comment by bintoro** [comment]
Solving this elegantly may require rethinking the top-level keys and the related concepts a bit.

For reasons I do not understand, there's now this multipurpose concept of _primary data_ which can be either
- one or more **resource** objects (when targeting a resource URL)
- one or more **link** objects or `null` (when targeting a relationship URL).

But link objects are never accompanied by any kind of secondary or related data, so bundling them under the moniker of "primary" seems pointless. However, here the naming of the `data` key actually comes into its own — it's not easy to come up with a good descriptive key for link objects.

Perhaps the main issue with `data` is not its nonspecificity but the fact that `linked` constitutes such an integral part of resource data (as opposed to metadata).

So why not put all data under `data`? Seems rather logical, huh?
- `data`
  - `primary`
  - `linked` or `related`
- `links`
- `meta`

Suddenly `data` looks pretty good to me.

**Comment by hhware** [comment]
To me, moving `primary` and `linked` one level down does not really solve anything. There are less than a handful items on the top level anyway, why split them over two levels?

No matter where `data` is placed, it is too abstract. If `meta` are not data, what are they?

> But link objects are never accompanied by any kind of secondary or related data, so bundling them under the moniker of "primary" seems pointless.

Why? I think it would be very natural to accompany link objects with the resources they are linking.
Besides, even if some endpoints (not necessarily relationships, may be primary resources) never supply `related` data, why does it make `primary` pointless? It just means this endpoint only returns primary data and there is no way to request anything related.

**Comment by bintoro** [comment]
@hhware Generally, metadata by definition merely describes but is _not_ part of the main data that is being requested or acted upon: http://en.wiktionary.org/wiki/meta-.

Also, if `primary` was to become a universal top-level key, then that would make it just as generic and ambiguous as `data` is now. Primary what? This entire discussion originally came about from the desire to get a descriptive key for **primary resources** as they were called prior to RC2.

What I proposed in my previous comment accomplishes two things:
- There's guaranteed to be a top-level key called `data` that will contain the main payload regardless of what it is (a resource, a relationship, or perhaps a message to a custom endpoint that exposes something that is neither) without appearing semantically stupid.
- For resource objects, the second level provides the primary/related distinction that is pretty much the whole point of this issue.

**Comment by hhware** [comment]
> Generally, metadata by definition merely describes but is not part of the main data that is being requested or acted upon: http://en.wiktionary.org/wiki/meta-.

A quote from this wiktionary page: "metadata is data that describes data". So it _is_ data, although indeed not _main data_. Following the definition from the wiktionary, `main` would be the appropriate name for it.

If the top-level key were to be added, I would suggest to call it just `resultset`. This is pretty much an exact term for what it is, and does not seems likely to clash with any application-specific term.

**Comment by bintoro** [comment]
> If the top-level key were to be added, I would suggest to call it just `resultset`.

`resultset` or maybe even just `result` might be workable, but it only seems appropriate for responses, not requests. JSON API needs something that can accommodate both.

> I think it would be very natural to accompany link objects with the resources they are linking.

This is a good point. I didn't consider the possibility where `primary` and `related` might not contain items of the same kind.

What it all boils down to is that, if we want a generic top-level key, then _something_ must be special-cased. Right now the special case is `linked` which is defined to always hold a set a _related resource objects_, no matter what goes in `data`. This, I understand, is dissatisfying to many.

An alternative would be to special-case a top-level key like `resources` that would hold all resource objects. Everything else would go in `data` (relationships and possible future uses).

And finally, there's still the option of dedicated keys, which I believe is a popular approach. How about `relationship` or `relation` for relationships? It's quite befitting, since that's what they are, and the singular form naturally applies to both to-one and to-many relationships.

```
{
  "relationship": { "type": "tags", "ids": ["2", "3"] }
}
```

`link` would be okay as well but is probably too confusing unless `linked` is turned into `related`.

With dedicated keys everything can remain on the top level and still have nice semantics: `primary / related` (or `resources / related`) and `relationship / related` both look like sensible combinations to me, presuming the old definition of _primary resources_ could be reinstated.

**Comment by hhware** [comment]
> `resultset` or maybe even just `result` might be workable, but it only seems appropriate for responses, not requests. JSON API needs something that can accommodate both.

Right, I keep forgetting that RC2 requires `data` in the request object as well. However, is it really necessary to use the same key in both request and response? Why cannot request be something like

```
{
  "request": {
    "id": "123",
    "type": "comments",
    // ...
  }
}
```

for the request and soemthing like

```
{
  "results": {
    "id": "123",
    "type": "comments",
    // ...
  }
}
```

for the response?

**Comment by mattecapu** [comment]
@hhware doubling the syntax seems unnecessary complexity to me

**Comment by bintoro** [comment]
I'd like to try to continue to refine the terminology and hope the naming predicament will resolve itself.

First, let's be mindful of the fact that, in JSON API parlance, the word _resource_ has a different meaning than in HTTP.

In JSON API, a resource is basically an entity that has attributes, and a _resource object_ is its JSON representation. Neither of these is directly defined anywhere, but this is clearly the intent.

In HTTP, a resource is simply whatever a server makes available at a specific URI endpoint.

For example, `/api/photos` would expose a _collection of resources_ according to JSON API vocabulary, whereas in HTTP it's a _single resource_ whose representation consists of multiple meaningful objects. Note that, in HTTP, linked objects are also part of the resource, as they are available at the URI.

Whatever the definition going forward, it should be documented, as it will have implications if #291 happens.

Let's imagine for a moment that the definition of _resource_ were aligned with HTTP. It would look something like this:
-   A _resource_ is a service identified by a URI ([RFC 7231](https://tools.ietf.org/html/rfc7231#section-2)). A request targets exactly one resource at a time.
-   A resource maps to any number of concrete _resource elements_ that correspond to the underlying data model. An element is the fundamental unit the client and server want to exchange JSON API messages about. (This is a slight superset of what the spec currently means by _resource_. For example, a _relationship_ accessible at `/api/photos/1/links/author` would be a resource element, too.)
-   The JSON representation of a resource element is called a _resource object_, which matches the current definition.
-   The _primary resource_ of a request is the part of the full resource that is accessible without resolving interelement relationships. (Setting the `include` query string parameter would therefore change the full resource target in accordance with HTTP, but it would not have an effect on the _primary_ resource target.)
-   _Primary elements_ are the elements that make up the primary resource. _Linked elements_ are the elements that fall outside of the primary resource. (These terms match the current meanings of _primary resources_ and _linked resources_, respectively.)
-   Thus, the JSON representation of the primary resource is either a resource object or a collection thereof. This can be referred to as _primary data_, which again matches the current definition.

Now, if we just replace the term _resource element_ with _resource_, this looks a lot like RC2 does today. So the main issue is with the elusive definition of _resource_. In particular, it's currently implied that a relationship is not a resource, yet it's represented by a _resource object_. It almost seems as if the term _primary data_ was coined to close this conceptual gap. I think everything should be a resource (or a resource element in the alternative scheme), which would eliminate this weirdness.

The notion of _primary resource_ is crucial and clearly applicable to any kind of endpoint. In contrast, _primary data_ is not a very prominent concept, so it doesn't feel right for "data" to mask "primary" in the JSON structure.

However, I would actually favor _main resource_ over _primary_ because it comes without any primary/secondary connotations. A top-level key `main` would be succinct, easily understood, and capable of standing on its own.

**Comment by miguelsan** [comment]
I am personally for `main` before `primary` too. It stands on its on even when there is no further `included` present in the resource, This again is better as `related` since your URL looks like: `GET /articles/1?include=comments`. Succinct and unmistakable.

**Comment by kriswill** [comment]
This looks icky:

``` json
{
  "data": {
    "type": "bobs",
    "id": "bob1"
  }
}
```

I think that putting the type in there is just a crutch for not wanting to map the resource to the type.  Perhaps, splitting out the metadata is a solution.  something like:

``` json
{
  "bobs": [{
    "id": "bob1"
  }],
  "meta": {
    "resource_map": [{ "key": "bobs", "type": "bobs"}]
  }
}
```

Where the `meta/resource_map/bobs` would be implicit if there was only one resource.

**Comment by bintoro** [comment]
@kriswill An endpoint may well return a collection of objects with miscellaneous types, hence the generic key on the container.

**Comment by kriswill** [comment]
@bintoro I realize there are edges where multiple linked resources are returned from a request.  I just think that the structure of nesting under a generic key is an over complication of the format.  The resource information should be as straight forward as possible, and fluffing up the data with schema metadata isn't appropriate for the principal resource information.  I think it's fine to include it, it should just be distinct and separate from the data itself.

**Comment by kriswill** [comment]
also, I believe the form of:

``` json
{
   "plural-resource-name": [{
     "id": "zzz",
     ...
   }]
}
```

is fairly standard format used by a majority of REST API's that produce JSON records.
I think that JSON:API should try to go with status quo on this one, and make optional additions that improve expressiveness and usefulness.

**Comment by ahacking** [comment]
@kriswill there are many driving factors for the current approach which is actually simplifying from the previous approach (which is what you are proposing). I will list some of them:
- ordered heterogenous results
- ordered polymorphic results (similar to above)
- ability to separate primary ordered results vs linked/secondary/side-loaded data of the same type
- reduced sorting / grouping overhead on the server
- having an explicit type in all resources does support polymorphism better than not having it.  It is a property of the resource and may actually be mutable.
- identical processing for main/primary results and for secondary/linked/side-loaded data.

The approach is simplifying and it is certainly not less straightforward to support the above use cases with the old approach. Sorting is ruled out with partioning on type and partitiong introduces more problems with polymorphism. If you need to separated primary results from linked results (and most applications do) you need two top level containers anyway.

**Comment by bintoro** [comment]
@kriswill Sorry I should have been more precise. It's not just the linked resources but the primary resources as well.

Granted, you could put all resource objects (both primary and linked) in a combined registry where everything is keyed by type. But then you'd still have to have a primary resource sequence where each item is represented by an id–type combination. They can't be split into multiple sequences because then the ordering would be lost.

``` json
{
    "primary": [
        {"id": 123, "type": "typeA"},
        {"id": 456, "type": "typeB"},
        ...
    ],
    "resources": {
        "typeA": [
            {"id": 123, "attr": "foo"},
            {"id": 124, "attr": "bar"}
        ],
        "typeB": [
            {"id": 456, "attr": "baz"},
            {"id": 457, "attr": "quux"}
        ],
        ...
    }
}
```

**Comment by kriswill** [comment]
@ahacking I can agree that it's easier for a single set with heterogenous resource, where in the context is assumed to be polymorphic, since why would you have a single endpoint for not polymorphic types?  I think that it's a protocol level detail, like metadata not being in the principal payload, but instead in HTTP headers, just like all of the other protocol stuff like GET, POST, PATCH, etc... Putting the metadata into the data, just smacks of WSDL and SOAP, and I'd prefer not to go back there.

**Comment by ahacking** [comment]
@kriswill I see type as an innate property of the thing, not something auxiliary and external to the thing. If you want to describe the object/resource and relationships more fully then I would regard the schema and semantic link data as a meta-data concern and look to things like JSON-LD which provide can provide context and semantics. Even with such grand approaches, resources still get tagged with a @id and @type unless you alias them to another key, regardless they are still there.

**Comment by ahacking** [comment]
@kriswill. Can you give an example where meta data in headers can describe each element in a  heterogenous collection? I don't think that is possible or practical, the type tagging needs to be  in the data.

The goal is uniform and predictable processing, not sometime have things and other times not. That just creates more work, more exceptions, more code, more processing, more bugs, less interoperability.

If you can show headers describing all elements of a payload without type tags in the data I am sure the W3C and OASIS standards bodies would be interested to learn of the approach.

**Comment by kriswill** [comment]
@ahacking @bintoro Here's my first naive attempt at doing a polymorphic version of @bintoro 's example:

``` json
GET /foobar-bazquuxes

200 OK
JSON-API-RESULT-TYPE: polymorphic foobar bazquux

{
  "foobar-bazquuxes": [
    {
      "id": 123,
      "type": "foobar",
      "attr": "foo"
    },
    {
      "id": 456,
      "type": "bazquux",
      "attr": "baz"
    },
    {
      "id": 124,
      "type": "foobar",
      "attr": "bar"
    }
    {
      "id": 457,
      "type": "bazquux",
      "attr": "quux"
    }
  ]
}
```

I agree that in the non-trivial aggregation case you would need a type indicator.

**Comment by bintoro** [comment]
@kriswill I fail to see any benefit to this approach. How do you discern what is primary and what is linked? Also, I'm not convinced accessing a constant `data` or `main` member is a "complication" over putting together `foobar-bazquuxes` based on the header. **EDIT:** Just to be clear, my example was an illustration of what it would imply to key everything by type; the format is certainly not something that's currently in the spec.

**Comment by kriswill** [comment]
@bintoro I see all of the components of both arguments.  It has metadata to describe what types are in the payload, that they are related resource types, and have a natural order.  Any metadata could be in headers, paging, links, mapping, type information, etc.  This would actually lend itself to [HATEOAS](http://en.wikipedia.org/wiki/HATEOAS) quite well.  Afterall, we are putting things like 'Content-Length', 'Content-Type', and other information about the payload in the HTTP headers.

**Comment by bintoro** [comment]
@kriswill So in essence you're just moving the bits and pieces around. You'd need a header like this:

`JSON-API-PRIMARY: [{"id":123, "type":"foobar"}, {"id":456, "type":"bazquux"}]`

I understand the point of moving "metadata" out of the payload, but this is now bordering on the philosophical. Which objects belong to the set of primary resources is pretty intrinsic to the data, so it's not at all clear that it shouldn't be part of the payload. Also, having to extract this sort of information from the HTTP headers will hardly simplify anything from an implementation point of view. (**EDIT:** I believe it's a good rule not to put anything in the headers that is critical for interpreting the document. A response body should be self-sufficient.)

**Comment by kriswill** [comment]
@bintoro I appreciate your opinion about headers, I'm not a huge fan of headers myself.  I just think it's cleaner to use them for their intended purpose, expressed in the protocol, rather than clutter up data with metadata.  I would like to have clear concise information in the payload, that efficiently transmits the important facets of my data.  Not have it polluted with system intrinsics like database type information, constraints and other schema stuff that a consumer of that data should not have to care about.
I get that tooling cares about schema, and it's a separate concern, and should remain separate.

I think the reason so many web developers have gravitated to REST, HTTP and JSON as the defacto form of web API, is they appreciate the lack of constraints, and freedom to be expressive and simplistic in the data format.  If we just bolt on XSD/WSDL/your favorite schema format into it, it will have the same fate that SOAP had.  I think we can do better.

**Comment by tkellen** [comment]
:+1: to merge from me.  Also, re: our conversation yesterday @dgeb, it looks like some domain relative links made it into this PR, so I won't be sending one to add a few.

**Comment by SphtKr** [comment]
@bintoro Good breakdown above. `main` works for me, though I think there are possibly better options.

Just one more plug for `principal`, and another one I thought of that might work is `content`--also doesn't imply anything vis-a-vis `linked`/`related`. It's also what's used to represent the contents of a promise in Ember Data...which is a plus in that it's a similar meaning, but is a minus in that it's similar enough that it might cause confusion in the Ember Data implementation :-). Or `payload`, but that may be almost as bad for ambiguity as `data`.

Another point that @bintoro and perhaps others has brought out is that `primary` currently seems natural because the docs frequently reference the "primary resource", but that's the tail wagging the dog I think: if we decide to call it `principal` or `main` then the docs just need to be updated to refer to the "principal/main resource" uniformly, and then all of a sudden whatever we pick makes as much sense as "primary" seems to now.

Also FWIW, as a user I totally get and agree with the need to put the "primary/main/principal" data in it's own grouping, and like the current approach, IMHO. I am starting to need polymorphic and sorted results, and the current plan solves all my problems. I think if it weren't for opening up the discussion about the key name, we probably wouldn't be discussing going back to the resource-name-keyed format. Just wanted to make sure that there's not a selection bias if only those who want it changed are speaking up.

**Comment by ethanresnick** [comment]
Hey guys! After reading all of your comments, here's the naming I'm thinking about now:
- At top level: `data` becomes `primary`; `linked` becomes `included`
- In link objects: `id`, `ids`, and `data` all become `linked`.

I think this solves a lot of problems, but I'm sure it'll create new ones as well, that I hope we can discuss.

Here's an example payload:

```
GET /people/1?include=employer.parentCompany

{
  "links": {
    "self": "/people/1"
  },
  "primary": {
    "id": "1",
    "type": "people",
    "name": "John Smith",
    "links": {
      "employer": {
        "type": "companies",
        "linked": "4"
      },
      "skills": {
        "type": "skills",
        "linked": ["1", "2", "3"]
      },
      "favorites": {
        "linked": [
          {"type": "posts", "id": "4"}, 
          {"type": "people", "id": "2"}
        ]
      }
    }
  },
  "included": [{
    "type": "companies",
    "id": "8",
    "name": "Parent Company of John's Employer"
  }]
}
```

Comments:
1. Using `included` at the top level instead of `linked` has a few advantages. First, it resolves the similarity between `links` vs. `linked` at the top level, which has caused much confusion. Second, it's more accurate, at least in a sense, since the `employer.parentCompany` in the example above isn't linked to directly from the primary resource, even though it is being included in the response.  And, third, it frees up the `linked` key to be used within link objects, where I think it makes more sense (see point 3).
2. As far as `included` vs. `related` goes... I prefer `included` first because it offers parallelism with the `include` parameter. Second, I think it's less vague; there are a lot of resources that might be in some sense "related" to the primary resource, but that aren't include-able through any of the links. And, third, I think `included` generalizes better to the side-posting case, where these terms will likely be repurposed (i.e. "I'm POSTing my author and have included his first article").
3. Using `linked` inside the link object, rather than `id`, `ids`, and `data` is a revival of the idea in #277. It simplifies parsing.
4. For the name of the top-level `data`/`main`/`primary` key, we'd ideally find a word that says "this is the essential data, but it's not necessarily the whole of the request/response". I played with a few words in that vein, like `"essential"`, `"necessary"`, `"basic"`, `"elementary"`, etc., but they all made for payloads that read really awkwardly. So, I think we're left with choosing from imperfect options. We could stick with `data`, which is seems to somewhat contradict `included` when the `included` section is present. Or we could go with `main` or `primary`, which, when the `included` section is absent, will read imperfectly to people who don't know that an `included` section could be present. Ultimately, I think the `main`/`primary` route is the better of these imperfect options. 
5. And as far as why I picked `primary` instead of `main`: I wasn't convinced that main stood any better in isolation (since "main" still implies "in relation to secondary concerns"), so I fell back on primary because it's more consistent with the language of the spec.

**Comment by gr0uch** [comment]
@ethanresnick I really don't like this change: "In link objects: id, ids, and data all become linked."

I think the distinction between `id` and `ids` is important, indicates to-one or to-many relationship.

**Comment by bintoro** [comment]
@ethanresnick, you may want to have a look at my [summary of terminology issues](https://github.com/json-api/json-api/issues/363#issuecomment-76544439), which ties pretty heavily into this.

Like you, I'm bothered by the disconnect between the word "linked" and the `include` param. It would make sense to define "included resources" as the related (non-primary) resources that are included in a compound document. Then, `included` would follow naturally.

(I'm confused as to why both _related resources_ and _linked resources_ are currently a thing. Perhaps "linked resources" was at some point intended to mean "included resources", but that would be totally weird because _links_ are relationships in general.)

Combining `id`, `ids`, and `data` would be neat because `data` is ugly, but I'm not crazy about the semantics of `linked` in that context. @daliwali, the type of the value (ID vs. array) can be used to determine cardinality.

One thing to keep in mind is that the "primary data" key needs to go well with link objects, too. For some reason, "primary" doesn't sit well with me in this case, but it may be due to old associations (the fact that the term used to be "primary resource").

**Comment by bintoro** [comment]
One option is to just consider the `{id, type}` objects as kinds of IDs:

```
{
  ...
      "skills": {
        "type": "skills",
        "ids": ["1", "2", "3"]
      },
      "favorites": {
        "ids": [
          {"type": "posts", "id": "4"}, 
          {"type": "people", "id": "2"}
        ]
      }
  ...
}
```

Another candidate for the key could be `ref` for "reference".

**Comment by ahacking** [comment]
I like the use of `included` as it aligns with the `include` query param, although I probably have to discount that alignment to some degree as I would prefer to see `include` go away in preference to a single param for controlling inclusion of fields and related resources. Irrespective of that I still think `included` is a good key and conveys the right meaning.

To clarify what I mean by a single param I would prefer something like `select=title,author(name,avatar),comments`  which selects the title field and the related author name and avatar, it also related comments in full.

Whilst it proabably doesn't impact this change I think it works nicely with rich/structured attributes raised in other issues and keeps the URL length shorter with less repitition of the pathnames. I see this similarly impacting sorting/ordering which could be defined by fields on related resources. A very similar nesting syntax would be used with a +/- prefix.  I am considering raising a PR for this to see if others also like the idea of unifying `fields` and `include`.

**Comment by ethanresnick** [comment]
@daliwali As @bintoro pointed out, `id` vs `ids` is redundant, as you can tell whether it's a to-many or to-one relationship based on whether the value is an array or not.

@bintoro Your summary of the terminology issues is great! I hadn't seen that before, and I think it adds a lot of clarity. My proposal seems to be touching on this point of yours:

> I'm confused as to why both related resources and linked resources are currently a thing. Perhaps "linked resources" was at some point intended to mean "included resources", but that would be totally weird because links are relationships in general.

I totally agree with you about all of that and I think you're right about the history: when linked was introduced, I'm pretty sure it meant simply "included resources".

As far as the semantics I'm proposing for `linked`... we considered a bunch of keys back in #277, including `ref`, `refs`, `id`, and `ids`. I think @dgeb's favorite was `id`. Like I said back in #277, I don't really care what the key's called, but I would like to only have one. I'm throwing out `linked` now simply because it wasn't a reasonable option before (as we were using it at the top-level too).

One way to read the `linked` that I'm proposing might be to think of (type, linked) as loosely analogous to (rel, href). I.e. for the employer relationship, "It's a companies-type link that specifically points to company 4." Then, polymorphic links don't get a type because the linked items are of multiple types.

@ahacking Glad to hear you like `included`! As far as merging the parameters goes, let's discuss that in a separate issue?

**Comment by bintoro** [comment]
> we considered a bunch of keys back in #277, including ref, refs, id, and ids.

Interesting. I wonder why it didn't go anywhere. If it's just because people couldn't agree on singular vs. plural, then let's simply define a _reference_ as one of:
- an ID,
- an array of IDs, or
- an array of (ID, type) tuples.

Clearly, a **reference** could be labeled `ref`. No semantic controversy there.

The trouble with `linked` is that it's actually the entire link object that represents what's linked, so having a nested object named "linked" somehow doesn't feel right...

Also, the feasibility of `linked` depends on what's going to happen with the "related"/"linked" terminology. The whole "link" business seems to be a carryover from HAL, and I don't see any compelling reason for its existence unless we assign a useful meaning to the word "link" (see #380). If _link_ continues to mean what it means today, then I don't know why we don't simply talk about "relationships" and "related resources" instead. Both of these are existing concepts in the spec anyway.

**Comment by ethanresnick** [comment]
Cf. my proposal for `"target"` in #392

**Comment by dgeb** [comment]
We're renaming `linked` to `included`. `data` remains.

**Comment by ethanresnick** [comment]
Sounds good!
