### ISSUE TITLE
Prefix reserved keys in resources

### ISSUE THREAD

**Issue by lgebhardt** [json-api/json-api#313]
There is a strong possibility of a name conflict within the key space of a resource with the four reserved keys, [`id`, `type`, `href`, `links`]. I'd like to float the idea of prefixing these keys with an underscore (or other character). Thus we would have the reserved keys of [`_id`, `_type`, `_href`, `_links`].

The primary benefit is that it opens up the possibility of using a key with one of the currently reserved key names. I think it is quite likely for some existing datasets to be using the `href` and `type` keys and this will save developers the need to rename these existing keys. A secondary (and minor) benefit is that it's easy to pick out the special keys visually.

The only downside I see is the adding of an extra character to each key, but with compression that is mostly a non issue. It's also possible there could still be conflicts, but its probability is probably a couple of orders of magnitude less.

An example:

``` json
{
  "posts": {
    "id": "1",
    "title": "Rails is Omakase",
    "post_href": "/rails_is_omakase"
  }
}
```

would become:

``` json
{
  "posts": {
    "_id": "1",
    "title": "Rails is Omakase",
    "href": "/rails_is_omakase"
  }
}
```

or 

``` json
{
  "posts": {
    "_id": "1",
    "_type": "posts",
    "_href": "http://example.com/posts/1",
    "title": "Rails is Omakase",
    "href": "/rails_is_omakase",
    "_links": {
      "author": "9",
      "comments": [ "4", "5" ]
     }
  }
}
```

Thoughts?

**Comment by steveklabnik** [comment]
I am very, very strongly against adding an underscore prefix. It's quite
ugly.

**Comment by lgebhardt** [comment]
Fair enough. I find it a bit ugly too, but I worry the namespace collisions may prevent some existing apps from converting to JSON API compliant tools. Is there a more appealing way to mitigate the namespace collisions?

**Comment by steveklabnik** [comment]
FWIW, Hal is also considering removing their underscore prefixes.

I don't think that this will actually affect a significant number of
people, as they are already probably using id, so that's not a conflict. If
they're not using hypermedia already, then links and href aren't going to
be used.

The only one I can see is 'type', and we would probably be in line with
whatever that is already.

**Comment by dgeb** [comment]
I also oppose the prefixes. I haven't personally heard of any conversion pains, perhaps because the keys are already pretty natural (as @steveklabnik points out). And the bottom line is that I'd rather not compromise the usability / aesthetics of the spec.

**Comment by lgebhardt** [comment]
Well I'm not convinced, but I'll close the issue now. I just reserve the right to say "I told you so" in the future :-)

**Comment by hhware** [comment]
New attempts to "tell so": #361 and #362

**Comment by bintoro** [comment]
FWIW, JSON-LD uses `@id` and `@type`. I wouldn't necessarily be opposed; in fact, it would make the format more human-readable by clearly identifying reserved field names. But in terms of the proposed rationale, I fail to see what value this would bring to the table. How is mapping `@id` to, say, `username` in the backend any different from mapping `id` to `username`?

**Comment by mattecapu** [comment]
`$` prefix?

**Comment by ahacking** [comment]
@bintoro further to your JSON-LD comment providing @context or context via http headers would allow a close but not close enough json-api implementation to work with clients that understand how to process JSON-LD contexts. The server wouldn't be json-api but a front end proxy could translate from json-api-like to proper json-api using the provided JSON-LD context.

I'd recommend a quaratine like approach for deficient/lazy servers rather than polluting the json-api spec and requiring everyone to map. Those being lazy or non-compliant should wear the pain of operating a proxy.  It may also be a useful mechanism for converting between legacy/proprietary json and latest json-api. Its always a case of living with what the server actually supports but it is a valid way to extend the reach of a non-compliant system.

In addition to the above I don't mind using the '@' prefix for @id and @type as JSON-LD uses by default (noting that in JSON-LD @context can map/alias them to anything). I am not proposing we support JSON-LD for that purpose, but perhaps  something more useful...

We probably should allow JSON-LD as an extension / recommendation for the purpose of mapping from json-api wire format to semantic resource types. This is the opposite of the proxy use case I mention above.  So you could describe the json-api payload and relationships in semantically rich terms using interoperable schemas. It has no impact on json-api clients and servers since there is no required processing. But it would inform JSON-LD aware clients/servers of the semantics being conveyed in the json-api payload.  Basically makes id, type and links more meaningful to those things that are aware of JSON-LD.

**Comment by hhware** [comment]
> How is mapping `@id` to, say, `username` in the backend any different from mapping `id` to `username`?

@bintoro Of course, there will be no difference between these two mappings for machines, but there may be a difference for humans, who are involved in development and support of the applications. (I tried to elaborate on the human-related aspect of it in #361 and #362. Both of them are closed now, I will not be repeating my arguments here.)

**Comment by bintoro** [comment]
I've thought about this and am tentatively warming up to the idea of prefixing reserved keys, since it would facilitate further development of JSON API in a compatible manner. Once the spec hits 1.0, it will never again be possible to define new special keys in resource objects, but using a known prefix would lift this limitation.

And while it's true that applications can deal with naming clashes, why not eliminate them once and for all if it can be had for free?

**Comment by opsb** [comment]
It seems inevitable that JSON API extensions will want to add more reserved keys at which point it will be necessary to introduce prefixed keys. At that point it seems nicer to use a consistent naming scheme and just prefix all reserved keys.

**Comment by dgeb** [comment]
@opsb JSON API extensions are not required to be compliant with the base spec. They can extend and even change it, such as the JSON Patch extension requiring an array of operations at the top-level of a request document. Extensions are actually separate (but related) media types, so we don't have to leave room for every possible extension in the base media type.
