### ISSUE TITLE
More RESTful relationships (proposal)

### ISSUE THREAD

**Issue by hesalx** [json-api/json-api#317]
Totally mindstormed by #316
Inspired by [GitHub API](https://developer.github.com/v3/), REST and @RSSchermer.
## The problem

Impossibility of `POST` to relationship URL is non-RESTful.
If it is possible to `GET` resources from a relationship URL, it should be allowed to `POST` homogeneous resources to that relationship URL.
## The proposal

**tl;dr** The main part of proposal is to take out relationships from the payload to the URL. 
### Creating Related Resources

(There is no such paragraph in the spec now.)
#### Creating To-One Related Resources

To-one relationship MAY be created by sending a POST request to the relationship URL.

``` javascript
POST /users/1/links/photo
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "photos": {
    "title": "John Doe",
    "src": "http://example.com/images/avatar.png"
  }
}
```

A POST request should only succeed if no relationship is currently defined.
#### Creating To-Many Related Resources

To-many relationship MAY be created by sending a POST request to the relationship URL.

``` javascript
POST /articles/1/links/comments
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "comments": {
    "body": "I love REST!"
  }
}
```
#### Updating To-One Relationships

To-one relationships MAY be updated along with other attributes by including them in a links object within the resource object in a PUT request.  (The same as in the current spec)

To-one relationships MAY be updated by sending a PUT request to the relationship URL with identifier of the related resource included into the URL. The body of the request SHOULD be empty.

``` javascript
PUT /articles/1/links/author/1
```

A to-one relationship MAY alternatively be added by sending a POST request with identifier of the related resource included into the URL. The body of the request SHOULD be empty.

``` javascript
POST /articles/1/links/author/1
```

A POST request should only succeed if no relationship is currently defined.
#### Updating To-Many Relationships

To-many relationships MAY optionally be updated with other attributes by including them in a links object within the document in a PUT request. (The same as in the current spec)

To-one relationships MAY be updated by sending a PUT request to the relationship URL with identifiers of the related resources included into the URL. The body of the request SHOULD be empty.

``` javascript
PUT /users/1/links/articles/1,2,3
```

A PUT request sent to the URL of a relationship SHOULD completely replace every member of the relationship.

A to-many relationship MAY be added by sending a POST request to the URL of the relationship with a single resource identifier included into the URL. The body of the request SHOULD be empty.

``` javascript
POST /users/1/links/articles/17
```

More than one relationship MAY be added by including an array of resource identifiers:

``` javascript
POST /users/1/links/articles/5,7,9
```
#### Deleting To-One Relationships

To-one relationships MAY be deleted individually by sending a DELETE request to the URL of the relationship:

``` javascript
DELETE /users/1/links/photo
```

A server SHOULD delete only the relationship, not the resources themselves. 
A server MAY delete the linked resource, if the primary resource is required for the linked resource, to preserve consistency. A server SHOULD NOT delete the primary resource in requests to the relationship URL.
#### Deleting To-Many Relationships

To-many relationships MAY be deleted individually by sending a DELETE request to the URL of the relationship:

``` javascript
DELETE /articles/1/links/tags/1
```

A server SHOULD delete only the relationship, not the resources themselves. 

Multiple to-many relationships MAY be deleted by sending a DELETE request to the URL of the relationships:

``` javascript
DELETE /articles/1/links/tags/1,2
```

**Comment by RSSchermer** [comment]
I realize #316 is a bit of a ramble, but it does provide some context for this that may be necessary. The gist of it is, that shallow nesting is imho actually a good practice for API's, especially when you need to do authorization + the current `/links` implementation is kinda but not really shallow nesting with some oddities. (I'd estimate it took me about 5000 words to make these points).

@arantir I find this a very interesting take on an implementation.

> Creating Relationships

I don't know if it's really creating a relationship. It more like creating a related object. I think the relationship already implicitly exists as soon as the parent object was created, it may just have been null. Not really sure how I would call this myself though. I'd consider it more updating, but by posting a new object as a payload, that did not previously exist on the server.

> To-many relationship MAY be created by sending a POST request to the relationship URL.

Do you mean that a new entity may be added to a to-many relationship by sending a POST request to the relationship URL? If so this would definitely fix my use case.

It definately seems better thought out than my rough proposal at the end of this comment: https://github.com/json-api/json-api/issues/316#issuecomment-63211458

I'm curious what others think, both of the authorization issue and of this solution.

**Comment by hesalx** [comment]
> I don't know if it's really creating a relationship.

I had just called so because "updating" is used for `POST` requests in a different manner.
I would call it "Creating related resources".

> Do you mean that a new entity may be added to a to-many relationship by sending a POST request to the relationship URL?

Yes, indeed. 
The first place usage is to allow relationships URLs be first-level citizens as primary resources URLs are. This would allow a client to behave simply and RESTfully.
Let learn by example:

``` javascript
{
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": [ "1", "2", "3", "4" ]
    }
  }]
}
```

If I want to get comments I would `GET /posts/1/links/comments`
If I want to get recent comments I would `GET /comments/4,3,2`
If I want to create a comment I would

``` javascript
POST /posts/1/links/comments
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "comments": {
    "body": "I'm curious what others think..."
  }
}
```

If I want to delete a comment I would `DELETE /posts/1/links/comments/1`
If I want to delete a recent comments I would `DELETE /posts/1/links/comments/2,3,4`
If I want to purge all the comments? `DELETE /posts/1/links/comments` MAY be allowed too.

I would definitely know that a comment cannot exist without a post, so it will be either deleted completely or becomes inaccessible and, may be, would be cleaned up by server's garbage collection procedures, but I already don't care anyway.

I'm intend to unify the spec such way that completely link-driven APIs are possible:

``` javascript
{
  "links": {
    "posts.comments": "/posts/{posts.id}/comments{/posts.comments}"
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "comments": [ "1", "2", "3", "4" ]
    }
  }]
}
```

`GET /posts/1/comments`
`GET /posts/1/comments/4,3,2`
`POST /posts/1/comments` (payload striped just for simplisity)
`DELETE /posts/1/comments/1`
`DELETE /posts/1/comments/2,3,4`
`DELETE /posts/1/comments`

So any link is not constructed by a client itself either, but is always determined in the payload as a URL template.

Such behaviour is not very clear with the current spec. It is possible with the spec by itself, but requires some customized behaviour on a client. This behaviour MUST NOT be required, but is also very desirable to be supported by a general client out-of-the-box (other words, the ideal client SHOULD support it).

This also may requires additional information about allowed methods of linked resource. This gracefully refers to the proposals of @ahacking (https://github.com/json-api/json-api/issues/311#issuecomment-63026279) and @lgebhardt (#310), they're welcome to leave their comments here too.

**Comment by RSSchermer** [comment]
> If I want to delete a comment I would `DELETE /posts/1/links/comments/1`

I would distinguish between removing a relationship and removing a resource. I think this should remove the relationship, but the comment may still exist on the server. If I would want to remove the comment I would just do `DELETE /comments/1`. If it has relationships, then depending on how you handle your foreign key constraints, this would either not be allowed, or the comment is deleted and all relationships are nullified or cascaded. In this example, just removing the relationship doesn't make sense, because the comment probably could not exist without the post. 

> `GET /posts/1/links/comments/4,3,2`

I would also say this is better accessed at `GET /comments/4,3,2`. I think the general point is, that when the comments own ID is available, nesting is not necessary anymore. It is only necessary when there is no comment ID available such as for `GET /posts/1/links/comments` or `POST /posts/1/links/comments` (see 2.7.2 Shallow nesting at http://edgeguides.rubyonrails.org/routing.html#nested-resources).

I'm personally definitely on board with the gist of this proposal though, or a modified version depending on other people's concerns.

**Comment by hesalx** [comment]
> I would distinguish between removing a relationship and removing a resource.

I had mentioned at the first post that it should only delete the relationship at the first place. Side effects, like cascading by foreign keys constraints, are naturally possible, though, and can not be forbidden. By knowing the side effect you are just allowed to make some things simpler on the client-side.

>  I would also say this is better accessed at GET /comments/4,3,2.

Sorry, it's a typo. Indeed, the spec leads the client to request `comments/:ids` directly. 
My examples are not so great. I had wrote all this in one breath, so don't be meticulously =) The proposal should generally conforms the REST and the current spec concerns and main lines. Remarks about misconceptions are welcome.

I will tidy up my post a bit.

**Comment by RSSchermer** [comment]
> so don't be meticulously

Sorry, it's a personality flaw :grin:. I figured that was probably what you intended, but I always tend to want to have things explicit.

**Comment by ahacking** [comment]
I agree with following HTTP semantics and a lot of what is proposed could be less specific just by deferring to HTTP.

POST is the http "do anything" method so I'm not sure it appropriate to restrict to just object creation and only creation on a to-one endpoint if a resource doesn't already exist. There may be valid reasons for a POST to be a replace/supersede or some other operation unrelated to creating a resource.

I also create resources with PUT and I can do that because I use v4 uuids and don't need to use POST to get server assigned ids.

I think the principle that should be stated is that whatever GET returns should be valid to PUT as a replacement. This includes removing sub resources and bulk changes.

It also also possible to scope a GET/PUT to just a set of subset of attributes or resources. Eg I may have posts with thousands comments and I just want the comments with the highest score (eg 4 or 5 stars). I should be able to bulk mark those as read so in effect my PUT would only be marking posts with 4 or 5 stars as read. Also I may scope the GET/PUT to just the star-rating or just the read/unread flag `?fields=hasRead)` and my PUT can replace just the `hasRead` flag without obliterating other attributes or needing to use PATCH.

So whilst I agree json-api needs to be more RESTful I think we can better follow the spirit of HTTP with just a simple statement that you should eat your own dogfood. ie if GET can scope it, PUT should replace it.

Maybe POST needs some default behavior defined but it needs to be careful to not intrude on valid uses of POST for processing that has side effects that the server may support on a resource endpoint.

**Comment by hesalx** [comment]
Sometimes people just want a simple straightforward way to do the things...

A huge amount of valid uses of HTTP and REST are prevented by JSON API. 
Simple HTML web-site is more RESTful than all that "mainstream ajax APIs". [Really](https://en.wikipedia.org/wiki/Representational_state_transfer#Uniform_interface).

IMHO, it looks to me that JSON API is about the most common interfaces of 95% mainstream web-frameworks. HTTP and REST are far more beyond the needs that frameworks ever had.

**Comment by bintoro** [comment]
It seems to me there's currently substantial confusion around representing nested resources in the URL. To wit, consider the recently raised issues #325 and #326.

I believe the intention behind the spec is that usage of the `links` segment signifies that the operation solely deals with _relationships_, never the target resources themselves. This interpretation is supported by @dgeb's comment in issue #244

> BTW, if an API does choose to use nested URLs instead of top-level, filtered resources, I would discourage including links in the URL to nested resources. There is a distinction between a URL to the link itself and the related resource which can be conveyed by including links in a URL. This allows for distinctions between, say, creating / deleting a resource vs. creating / deleting a link to a resource.

Indeed, if `links` was to be used for nested URLs as well as relationship URLs, then it would be completely superfluous and could be eliminated entirely!

But to realize this takes a very careful reading of the spec. Also, the spec takes no stand on whether the full resources might be available via nested URLs, adding to the confusion. So, I think all of this should be spelled out more clearly.

**A nested resource** is requested simply via `/posts/1/comments/4/author`. No mention of `links` anywhere. This would return the full `people` resource for the `author` associated with comment 4.

Contrast this with `/posts/1/comments/4/links/author`, which targets the **relationship** and hence would not return the full `author` but just the ID.

Importantly, observe that `links` should only appear at the end of the path.
Something like `/posts/1/links/comments/4/links/author` is not only ugly; it makes no sense because the `/posts/1/links/comments/4/` part already represents a relationship. A relationship doesn't have an attribute `author`.

Some examples from this thread and what I think they should mean:

`POST /users/1/links/photo` — This case is already in the spec; it should link the photo to user 1 unless the relationship already exists.

To create the relationship _and_ the resource simultaneously, omit the `links` segment:

```
POST /users/1/photo
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "photos": {
    "title": "John Doe",
    "src": "http://example.com/images/avatar.png"
  }
}
```

`POST /articles/1/links/comments` — Add a relationship (ID posted in request).

`POST /articles/1/links/comments/4` — Add a relationship (ID in URL, request body empty).

`POST /articles/1/comments` — Create a full `comment` resource and add to the post.comments collection. Notice the absence of the `links` segment in the URL.

`DELETE /posts/1/links/comments/1` — Delete the association between comment 1 and post 1, not the resource itself.

`DELETE /posts/1/comments/1` — Delete the actual comment.

I think this is all very straightforward. A server can choose to support any level of nesting, and you may explicitly choose to operate on full resources or their relationships:

`/a/b/c/d/e/some_resource_under_e` — Send and receive full resource objects

`/a/b/c/d/e/links/some_relationship_of_e` — Send and receive IDs

**Comment by hesalx** [comment]
@bintoro great, it makes the things much more clear. Although, it looks like allowed by the current spec, the details aren't mentioned in it. I have a lack of time now, but you may wish to make a PR. If it does not break compatibility, such PR might be welcome.

Also, some requests might look ambiguous, like `DELETE /posts/1/comments/1`, I have to mention that there are very complicated cases in the world. What you're doing with such nesting is actually ensure that only the related resource should be deleted (delete comment 1 if and only if it belongs to post 1). 
In some circumstances it may greatly reduce possibility of mistakes if an UI and/or a backed are quite complicated already. So, such behaviour should not be forbidden generally.

**Comment by RSSchermer** [comment]
@bintoro, your proposal is actually quite close to my rough proposal in #316.

I had another think and I'll try to share my preferences and my remaining concerns. There's things I'm decently sure of and some things that I haven't quite worked out:

### Things I'm decently sure of:

I think the spec should allow nesting and it should at least be somewhat described, maybe something along these lines:

An 'owned' resource collection that is defined by a relationship to an 'owner' resource MAY be accessible through a nested URL. The nested URL is formed by appending `/<owned-resource-collection-name>` to the URL of the 'owner' resource:

```
/photos/1/comments
```

A resource that does not yet exist on the server MAY be added to such a collection by making a `POST` request to the nested URL. This SHOULD both create the 'owned' resource and relate it to the 'owner' resource:

```
POST /photos/1/comments
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "comments": {
    "title": "I just wanted to say...",
    "text": "... that I love JSON-API!"
  }
}
```

A resource that already exists on the server MAY be added to such a collection by making a `POST` request with a single resource ID to the URL representing the relationship between the 'owner' resource and the 'owned' collection. The URL representing this relationship is formed by adding `/links/<owned-resource-collection-name>` to the URL of the 'owner' resource:

```
POST /photos/1/links/comments
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "comments": "1"
}
```

A resource MAY be removed from an 'owned' collection by making a `DELETE` request to the URL representing the relationship between the 'owner' resource and the 'owned' collection. This URL is formed by appending the 'owned' resource's ID to the URL representing the relationship between the 'owner' resource and the 'owned' collection. This should destroy the relationship between the 'owned' resource and the 'owner' resource, but should not destroy the 'owned' resource itself:

```
DELETE /photos/1/links/comments/1
```

### Things that I haven't quite worked out

First of all, shallow nesting. I don't think that the spec should prohibit deep nesting, but should it explicitly state a preference for shallow nesting?

> An ID SHOULD be represented by an "id" key and its value MUST be a string which SHOULD only contain alphanumeric characters, dashes and underscores.

The way I read this, this basically seems to disallow compound keys, which I think is a very sane decision. That also means that shallow nesting is always possible and deep nesting should never be needed.

The other issue is what to do with `GET /photos/1/links/comments`. 

The first option is to maintain the current behavior described by the spec, which would mean that it is exactly the same as `GET /photos/1/comments`. I don't really like this option, I don't really think these URL could be considered as describing the same thing.

The second option would be to make it return ids only. Something like:

```
GET /photos/1/links/comments
{
  "linked_comments": ["2", "4", "11"] 
}
```

The final option would be to just not describe it in the spec at all.

I think this would be a pretty major overhaul to the way relationships are dealt with in the spec. It touches quite a few parts of the document and I think that it would be a pretty large pull request.

**Comment by bintoro** [comment]
@arantir: Yep, this whole business seems to be omitted from the spec (although it's not 100% clear; see below my response to @RSSchermer). Consequently, the emphasis on representing _relationships_ has lead a lot of people (myself included) to erroneously conclude that nested URLs would have to be littered with useless `/links` segments.

Your interpretation about `DELETE /posts/1/comments/1` is exactly right. Not only is it correct, it's the only reasonable interpretation. So I don't consider such as request ambiguous at all.

@RSSchermer, what you're saying is in perfect agreement with what I've described in my comment.

As for what to do with `GET /photos/1/links/comments`, it should without a doubt return an array of IDs as you suggest. The current wording in the spec is unclear. Given that simple ID representations are used for links throughout the spec, it may very well be that this is already the intention. If it's not, then I would surely propose to change it.

All in all, this is not a drastic change. Either the nested resource syntax is not in conflict with the existing spec at all, or it only conflicts with it on the topic of GET requests.

By the way, I know there's been talk about possibly abandoning the `links` object inside resource objects. That is, ~~linked resources~~ relationships would be included beside scalar members like so:

```
posts": {
    "id": "1",
    "title": "Rails is Omakase",
    "author": "12"
}
```

If the client doesn't have prior knowledge about what's a relationship and what isn't, it can just look it up in the top-level `links` container.

I don't know what the status of this proposal is, but I'm tentatively in favor. If it turns out `links` will go, then we need to ask what the optimal way is to represent links in the URL, since we're not bound by the resource object structure.

See, I think it's kind of weird that going from `/photos/1/comments/23` to the corresponding link requires adding the `/links` segment in the middle: `/photos/1/links/comments/23`.

As an alternative, how about simply adding a specifier at the end?
Consider `/photos/1/comments/23?link` or `/photos/1/comments/23/link`. Just some food for thought.

**Comment by RSSchermer** [comment]
> As an alternative, how about simply adding a specifier at the end?

I agree completely. If the links object is removed from the resource object (which is something I would definitely support), then moving it to the end would be more sensible. It's easier to describe in the spec (e.g.: to reference the relationship itself, just add `/link` to the end). I also think in all other cases the final URL segment kind of identifies the type of the resource and this would be more consistent with that. For that reason I'd also prefer `/photos/1/comments/link` over `/photos/1/comments?link`.

**Comment by dgeb** [comment]
A couple things to consider:
- If we move forward with my #311 proposal (and we're leaning toward it), then `links` will be removed as containers of relationship IDs and from relationship URLs.
- Resources can be represented as either IDs or objects. This allows for flexibility to POST either representation to relationship URLs.

**Comment by RSSchermer** [comment]
@dgeb very interesting! So if I'm interpreting this right, this would end up somewhat like this:

`GET /parents/1/children` will retrieve the children that belongs to parent 1.

```
POST /parents/1/children
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "children": {
    // Child attributes
  }
}
```

Will create a child resource that did not yet exist on the server and relate it to parent 1.

```
POST /parents/1/children
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "children": "3"
}
```

Will create a relationship between the existing child 3 resource and parent 1, replacing (in my previous example):

```
POST /parents/1/links/children
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "children": "3"
}
```

What about deleting? `DELETE /parents/1/children/3` will destroy the relationship between parent 1 and child 3, but will not destroy child 3, replacing `DELETE /parents/1/links/children/3`?

I actually really like this. It's very simple, very flexible and I currently don't see any major issues with this.

**Comment by bintoro** [comment]
@dgeb: Yeah, I just finished re-reading #311, and I think your main proposal there looks very good: IDs go alongside simple members and link descriptors go in `links`. This makes sense.

However, ideally we'd maintain the ability for URLs to make a distinction between
- a resource that's part of a relationship/collection 
- the corresponding link.

For `POST` requests this is indeed not mandatory, as the server can just look at the request and figure out if it's an ID or a full resource. But for `DELETE` operations there's a crucial difference (remove association or delete entire object). And I see no harm in recommending accurate semantics throughout, and then it's up to the server to decide how lenient it wants to be.

What I suggested in my previous comment was just a rehash of the current `/links` format:

`DELETE /photos/1/comments/23/link` would detach comment 23 from photo 1.

`DELETE /photos/1/comments/23/` would delete comment 23. (If the comment was not related to photo 1, the request would be refused.)

I'm not too picky about the eventual syntax, but certainly both cases should be accommodated somehow.

**Comment by dgeb** [comment]
`/photos/1/comments/23` would be a relationship URL, so `DELETE /photos/1/comments/23` would delete the relationship. The server could optionally delete the related resource if it's wholly dependent.

Ideally, I would like to see `comments` also accessible at the top level, since this allows a single request to delete resources across multiple `photos` and clarifies the intent of deleting a relationship vs. resource. For example: `DELETE /comments/1,2,23`. A DELETE request to the resource URL would delete the resource itself.

**Comment by RSSchermer** [comment]
> Ideally, I would like to see comments also accessible at the top level, since this allows a single request to delete resources across multiple photos and clarifies the intent of deleting a relationship vs. resource.

I agree completely, I guess that's kind of what I meant by shallow nesting. Just for clarity, in my mind the standard basic set of operations on a `comments` resource then sort of looks like this:

`GET /comments`: returns all comments (may not make sense for fully dependent/'weak' entities).

```
POST /comments
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "comments": {
    // Comments attributes, may also create relationships by including e.g. "post": "1"
  }
}
```

creates a new comment (may not make sense for fully dependent/'weak' entities).

```
PUT /comments/1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "comments": {
    // A subset or all of the comments attributes
  }
}
```

updates comment 1.

`DELETE /comments/1` destroys comment 1.

`GET /post/1/comments` returns all comments that belong to post 1.

```
POST /post/1/comments
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "comments": {
    // Comments attributes
  }
}
```

creates a new comment and relates it to post 1.

`DELETE /post/1/comments/3` destroys the relationship between post 1 and comment 3, but does not destroy comment 3 itself.

**Comment by bintoro** [comment]
While contemplating this in the shower I came to the same conclusion. If `links` is going to be axed from URLs anyway, then that by itself will eliminate confusion about how relationship URLs are to be constructed.

So, for `GET/POST/PUT`, the association vs. full object distinction shall be inferred from the request (unless someone can come up with an example of an ambiguous request). For `DELETE`, the target is first and foremost the relationship. To completely delete an object, a client must issue `DELETE /resource/id`.

**Comment by hesalx** [comment]
This discussion goes wrong way, too many obsession about URLs.

Let forget about URLs structure for a moment. There are just a few rules you should follow to make the API certainly consistent.
1. When you `POST` a resource and get 201, it definitely must be accessible after on path provided by server (or whatever other way).
2. When you `DELETE` a resource and get 204, it definitely must not be accessible after on the requested path.
3. When you `PUT` to a resource and get 2xx, it definitely must be accessible after, containing the data you have sent.
4. When you `PATCH` a resource and get 2xx, it definitely must be accessible after, differs from previous its version in the way you have provided in the payload.

**Nothing said** about any other paths and resources. It is completely relies on implementation, use cases and circumstances.

Just ask yourself what should happen after a request according to those 4 rules.

`DELETE /post/1/comments/3`?
There is just must not exists such resource anymore after this request. 
What does it mean? Definitely, there is no more a relationship between `/post/1` and `/comments/3`.
Should `/comments/3` be accessible? It definitely can! 
Does it makes any sense for you? Oh, no? You never accessing comments via `/comments/:id`? OK, just delete it then, no problem.

`POST /parents/1/children/1`?
There should be a `/children/1` belongs to `/parent/1` after this request. Because `/parents/1/children/1` must be accessible after. 
Oh, they're both exist? OK, then just create a relationship. You've already provided all needed data (ids), so there is nothing more to put into the payload.

`POST /post/1/comments` 
Same staff. There must exists some resource after this. Logically, it should be `/post/1/comments/<new post id>`. In that case a relationship definitely to be created.

After all, `/post/1/links/comments` and `/post/1/comments` are **two different representations**. There is absolutely nothing to complaint with any of them either. They may be used for different purposes and can play together gracefully in some circumstances, I think. There are imaginable cases when 4 behaviours (CRUD) of primary collection isn't enough and you may wish to add additional ones via a collection of relationships.

**Comment by bintoro** [comment]
> After all, /post/1/links/comments and /post/1/comments are two different representations.

Could you elaborate on what you mean?

I agree that, in the current version of the spec, requesting `GET /post/1/links/comments` should logically return an array of IDs, while `GET /post/1/comments` should return the full objects. Also, there's a difference as far as `DELETE` goes.

But if these two cases are the only ones where there's any practical difference, then I'm not quite sure anymore that complicating the spec with a `/link(s)` segment adds enough value. After all, if you really wanted to `GET` a list of IDs in a relationship, this could be specified in the query string.

What I would like, though, is the ability to glean from the response whether `DELETE /post/1/comments/3` deleted the entire comment or just the association. A nice way to achieve this would be to specify 204 for _link deleted_ and 200 for _object deleted_ (with the deleted object included in the response body). But sadly the spec already stipulates that a successful `DELETE` must return 204.

**Comment by hesalx** [comment]
> A nice way to achieve this would be to specify 204 for link deleted and 200 for object deleted (with the deleted object included in the response body). But sadly the spec already stipulates that a successful DELETE must return 204.

Contrariwise, actually. Success request returns either `200` with a body or `Location` header, or `204` which means kinda "no more information for you after this request".
Usually, `PUT`/`POST` returns `200` with a resource. And `DELETE` returns `204` means that there is no resource anymore.
But following your example, `DELETE /post/1/comments/3` may return `200` with `Link` header pointing to both resources and saying kinda "you may look how those were changed". Or `204` means "nothing more left".
But this is too specific to be included into the spec.

> Could you elaborate on what you mean?

You might with to always delete (or whatever) the whole resource if you're making a `DELETE` (or whatever) to a collection which represents whole resources. Although, this is not required by HTTP semantics of REST, it might be a preferred behavior for public APIs.
In this case you have no way no delete the relationship. So you introduce a dedicated collection for this case and request all relationship actions on it.
`DELETE /user/1/post/1` Delete the post entirely.
`DELETE /user/1/links/post/1` Delete the link. "Unlink post from user". (Make post anonymous, though.)
`POST /user/1/post` Create a new post for the user.
`POST /user/1/post/1` Likely `405 Method Not Allowed`.
`POST /user/1/links/post/1` Create a link. "Link post to user". Make the user to be an author of the post.
`GET /user/1/post/1` Get the entire post.
`GET /user/1/links/post/1` Check if the post is linked to the user. For example, `204`/`404` as `true`/`false`.
`PUT /user/1/post/1` Change the post itself.
`PUT /user/1/link/post/1` Likely `405 Method Not Allowed` for this case.

You may choose the opposite case and change only relationships via nested URLs, but change resources via direct (one-level depth) URLs. In this case you may not use `/links/` at all too.

If you like to create and delete resources via their direct (one-level depth) URLs, and change relationships via payload (as any other attribute) and have no relationships URLs at all.

Or you may wish to use only top-level URLs for creating and modifying, but do not want to use payload for relationships, you may use `/links/` and have to other nested URLs at all.

And any of these cases fits the best in certain circumstances, depends of what resources and relations between them you have, how large is your API and how widely it is used (internally; for a number of partners; public entirely).

**Comment by bintoro** [comment]
@arantir, we're definitely on the same page here. The menu of URL permutations you just posted is exactly how I imagined it in my first contribution to this thread.

However, since it now appears that the resource-level `links` object is about to lose its original role as the sole container of relationship data, the reasons to have the `links` segment as part of the URL seem slightly less compelling.

As you yourself noted, there are meaningless variants among the possible URLs (the 405s). Even without the `/links` syntax, it's possible to express the following:

##### To-many (users.posts)

`DELETE /posts/1` Delete the post entirely (admittedly not a nested form).
`DELETE /users/1/posts/1` Detach the post from user.
`DELETE /users/1/posts` Detach all posts from user.
`POST /users/1/posts` Create a new post for the user (data in request body).
`POST /users/1/posts` Associate existing post with user (ID in request body).
`PUT /users/1/posts/1` Modify a single post.
`PUT /users/1/posts` Replace the user's entire collection of posts at once.
`GET /users/1/posts/1` Get a single post.
`GET /users/1/posts` Get all of the user's posts.

##### To-one (users.role)

`DELETE /users/1/role` Detach role from user (set to null).
~~`POST /users/1/role` Create a new role in the system and associate with user.~~
`PUT /users/1/role` Associate existing role with user (role ID in request body)
`PUT /users/1/role` Associate role and update role object (data in request body).
`GET /users/1/role` Get the role object.

On the other hand, the `/links` format does have the advantage that the intended meaning is more readily obvious to a human: Does the URL end with `/link(s)`? Okay, you're dealing with an abstract relationship, not a resource object. Importantly, you don't need knowledge about the request body in order to figure out what is being requested.

I'm kind of on the fence here. The linkless syntax is neat and compact, but the explicit link specifier would improve readability and add some expressive power.

**Comment by hesalx** [comment]
@bintoro URLs structure should not be a barrier between you and the most convenient case in any kind. #311 makes a step towards it. A client should knows how to delete a relationship (regardless of side effects, like deleting a detached comment). A server should just provide a URL which client should act on.

Even without `/links` you don't have to know the request body, because the route `POST /users/{users.id}/posts/{posts.id}` has only one sane usage. 
At the same time, you get the whole CRUD for a relationship with just a single template.

``` javascript
"primaries": {
    "secondaries": "/primaries/{primaries.id}/secondaries{/secondaries.id}"
}
```

So client shouldn't know the URL. It knows the quite simple rules:
1. If you `POST` to `primaries.secondaries` with `primary` id and `secondary` body, you will create a new `secondary` belongs to this `primary`.
2. If you `POST` to `primaries.secondaries` with `primary` id and `secondary` id, you will connect this `secondary` to this `primary`.
3. If you `DELETE` to `primaries.secondaries` with `primary` id, you will delete this collection (all the `secondaries`) from this `primary`.
4. If you `DELETE` to `primaries.secondaries` with `primary` id and `secondary` id, you will detach this `secondary` from this `primary`.
5. If you `PUT` to `primaries.secondaries`  with `primary` id, you will replace this collection.
6. If you `PUT` to `primaries.secondaries`  with `primary` id, `secondary` id and `secondary` body, you will change this `secondary`.
7. If you `GET` to  `primaries.secondaries` with `primary` id, you will get all the `secondaries` of this `primary`.
8. If you `GET` to  `primaries.secondaries`  with `primary` id and `secondary` id, you will get the `secondary`.

The only restriction is to allow a client to pass ids into URL. Further structuring is completely your choice.
If a client wants to delete/create/change a resource itself, it should make `DELETE`/`POST`/`PUT` to resource's `href` directly. You can not know exactly the `href` of the original resource in relationship unless you request the entire resource via relationship URL (a single one or from a collection). Although, you already know the `href` if you already `GET` the resource via its `href`.

Also, you may wish to merge the 8'th rule case with direct resource's URL (`/users/1/posts/1` with `/posts/1`), you can do it gracefully with HTTP semantics, using `303 See Other` and `Location` header, no any special spec required.

**Comment by bintoro** [comment]
@arantir: Item 2 in your list doesn't quite conform to HTTP semantics. You're supposed to `POST` to the collection's URL and include whatever is being added in the request body, never in the URL. This is the very definition of `POST`.

In fact, I fell into the same trap in my previous comment. `POST /users/1/role` is not an ideal usage of `POST`. To create and attach a singular resource, the client can simply issue `PUT /users/1/role` or forgo nesting and say `POST /roles` and set the association from that side (as an attribute of the newly created resource).

Also, you're igoring to-one relationships here. If `secondaries` is just a `secondary` and not a collection, there will never be an ID segment after the `secondary`. Thus, you can't infer anything from its absence.

Indeed, `PUT /users/1/role` can mean any of the following:
- create and associate (when body contains a resource object with no known ID)
- update (when body contains a resource object with a known ID)
- associate existing (when body contains an ID only).

An aside about terminology: If you're sending a request to `/foo/{foo.id}/bar`, then `bar` is actually the _primary_ resource (as you will be sending or receiving representations of `type(bar)`), and `foo` is its parent or context. In this sense, the template `/primaries/{id}/secondaries/{id}` has the resource names reversed.

**Comment by wvteijlingen** [comment]
@bintoro: Nice list. However, to me it seems weird that we can create a new post by POSTing to the nested collection, but we cannot delete a post by DELETing from the nested collection. One creates a resource and a association, the other just deletes the association.

This is why I like the current setup using `links`. It makes a very clear distinction between working with the actual resource, or just the association.

**Comment by hesalx** [comment]
@bintoro It's not my rules don't conform HTTP, it's HTTP does not conform my rules ("Chuck Norris joke" =)
Really... You're right generally. HTTP semantics isn't enough for a client to act on URL with a knowledge of just this URL. There at least should be a (method, URL) pair for each common action. Other words, `GET /<path>` acts as a solid unit of client-server interaction.

So there is two ways to solve the problem. It's either prescribe all methods and paths for all actions, or allow do tell a client how it should make a common action, providing a method and a URL for each. That's why there is #310.
I'm not the one who decide. I like jsonapi because it fits my need. If my needs grows and the spec don't, I will just implement my own. Although, I make proposals with the issues I faced, because it's nice to spread convenient solutions and either improve them.

@wvteijlingen I think, you told about my list? Anyway...

> However, to me it seems weird that we can create a new post by POSTing to the nested collection, but we cannot delete a post by DELETing from the nested collection. One creates a resource and a association, the other just deletes the association.

You `POST /user/1/posts` and then you see the new post in the `GET /user/1/posts`.
You `DELETE /user/1/posts/1` and then you don't see the post in the `GET /user/1/posts` anymore.
Side effects are widespread. When you `DELETE /posts/1`, there will be one less posts in `/user/1/posts`. Similarly if when you `POST /user/1/posts`. But you consider `POST` behaviour is ok, and `DELETE` doesn't. Shouldn't you just forbid nesting? No nesting, no problems, though =)

Although, it wasn't proposal, it's just an example. It's not to be consistent.

I'm often refer to REST. But... The count of the word `rest` in http://jsonapi.org/format/ is **zero**.
May be I'm just wrong trying to make it RESTful?

**Comment by dgeb** [comment]
Thanks for your work here @arantir. All of these discussions went into forming #341.
