### ISSUE TITLE
Update examples to include Accept header

### ISSUE THREAD

**Issue by lausobo** [json-api/json-api#32]
It would be possible that a given service implements two or more different representations. Shouldn't the request include the header `Accept: application/json`?

**Comment by steveklabnik** [comment]
I'm not sure what you're asking, exactly. Can you re-phrase?

This describes the (soon to be) type `application/vnd.api+json`, so that's what it should get served with. At the moment, it is going through the registration process, so it can only be `application/json`, but after that, it's not appropriate.

**Comment by lausobo** [comment]
Let's say that a web service serves both json (via this spec) and xml.

Independently of the value (`application/json` or `application/vnd.api+json`), every request to a json api must include the `Accept` header to specify the media type expected in the response.

**Comment by steveklabnik** [comment]
Sure. That has nothing to do with this spec, though, that's how HTTP works, no?

**Comment by lausobo** [comment]
Right. Then I guess that the issue will have to be renamed: "Update examples to include Accept header". :blush:
I will submit a PR later.

**Comment by steveklabnik** [comment]
Cool. :)
