### ISSUE TITLE
Permit custom verbs via an "actions" pseudo-subcollection on a resource

### ISSUE THREAD

**Issue by ncoghlan** [json-api/json-api#320]
It's sometimes desirable to be able to easily request complex server side actions that aren't readily represented as the create-read-update-delete operations offered by HTTP's POST/GET/PATCH/DELETE.

The Pulp repository management system, for example, needed the ability for clients to say "sync this repository now". That's implemented by sending a POST request to `<repo-resource-url>/actions/sync` (http://pulp-dev-guide.readthedocs.org/en/pulp-2.2/integration/rest-api/repo/sync.html#sync-a-repository)

This would be a MAY, as most resources wouldn't need this kind of capability.

Pulp only offers a write-only API for the actions pseudo-collection, but a slightly more fleshed out behavioural specification might look like:
- GET on `<resource-url>/actions` returns a list of available custom actions on the resource
- POST, PATCH, and DELETE would not be permitted (read-only collection)
- GET on `<resource-url>/actions/<command>` returns information on what the custom action does
- POST on `<resource-url>/actions/<command>` would initiate the command
- PATCH, and DELETE would not be permitted (read-only collection)

**Comment by hesalx** [comment]
Are there any reason why you could not do this right now?

Request `GET resource/actions` and respond with

```
{
  "links": {
    "actions.action": {
      "href": "resource/actions/{actions.command}"
    }
  },
  "actions": [
    { "command": 'sync', "method": 'POST' },
    { "command": 'event', "method": 'POST' }
  ]
}
```

Map methods to CRUD actions and make respective action (e.g. create) on a linked resource `actions.action` with your normal JSON API client.

**Comment by ncoghlan** [comment]
Yes, that's exactly the kind of thing I had in mind. The value I see in having it explicitly in the spec is (as with other parts of the spec) to reduce bikeshedding: this is a need that comes up occasionally, so saying to folks up front, "if you need this capability, do it this way" helps reduce the tendency for folks to go invent their own spelling.

The idea of modelling custom commands this way, rather than switching to a different approach entirely (like JSON-RPC) isn't necessarily going to be obvious to folks.

**Comment by hesalx** [comment]
Ok, as for the spec-level support there are some proposals about machine-readable meta data:
https://github.com/json-api/json-api/issues/311#issuecomment-63026279 (a bit offtopic there, don't bother that issue with this)
https://github.com/json-api/json-api/issues/310 Schemas

You may find them interesting. Unified approach is a bit preferable, you know :)

Possible outcomes of the #310 proposal may provide more clear solutions for your case as well.
For example:

``` javascript
{
  "profile": {
    "resources": {
      "links": {
        "actions": {
          "href": "/resource/actions",
          "methods": ["GET"]
        }
      }
    },
    "actions": {
      "links": {
        "action": {
          "href": "/resource/actions/{actions.command}",
          "methods": ["POST"]
        }
      }
    }
  },
  "resources": [{
    "id": "1"
  }]
}
```

So you can read `resource/actions` and then create (aka initiate) an action. Exactly like you would in your proposal. Unallowed methods will be rejected on the API level with all the consistency.

(The example is quite drafty, just to get the point)

**Comment by ncoghlan** [comment]
I think either the basic "links" format in the existing spec, or the proposed profile format in #310 would work well for the GET operations.

I don't actually have a strong opinion about what the GET methods should return - Pulp's API is write-only, so the only way to know what URL to hit is through explicitly programmed URL construction. However, a POST-only API would be rather contrary to the spirit of the spec, hence the suggestion of also including GET support to make the custom actions more self describing.

**Comment by steveklabnik** [comment]
Custom verbs are generally an antipattern, I'm not sure I want to suggest that people make them.

**Comment by ncoghlan** [comment]
I think they make more sense in contexts where more actuators are involved than just the passive updates of stored data that are the heart and soul of most web applications.
The Pulp sync command, for example, kicks off an immediate full repo update - it only makes sense for repos which are derived from a parent repo, rather than those that are the authoritative store.
Other cases are more likely to come up in an internet-of-things context, where there are actual real world devices connected - turning LEDs on and off, controlling motors and relays, that kind of thing.

**Comment by steveklabnik** [comment]
POST provides for abitrary processing, and the uniform interface is one of the core strengths of REST.

**Comment by ncoghlan** [comment]
Actually, thinking about it, you can model any custom action as a true collection by keeping a _history_ of the actions being triggered. So rather than "action/sync" (as Pulp does), you could have a "sync_events" subcollection, and a POST to sync_events would kick off a new one.

**Comment by staab** [comment]
Hey @steveklabnik , I was wondering if you could give me a link or two about (or expound on) how custom verbs (e.g., `POST /resource/id/make-my-breakfast/`) are an anti-pattern. I'm currently working on a new api that has quite a lot of non-pure-crud actions (i.e., there are lots of side effects and conditions to be met).

I read through the spec for [Siren](https://github.com/kevinswiber/siren) and really appreciated their actions section, but decided not to go that route because of the level of community around json-api (django plugins and js clients). My current approach is to extend the json-api spec with a profile that defines a top-level `actions` key thus:

```
"actions": {
  "action-name": {
    "method": "POST",
    "href": "http://example.com/api/resource/id/action/",
    "type": "content/type",
    "fields: {
      "param_name": {json schema object}
    }
  }
}
```

I'm not sure how I'm going to handle url templating (particularly since it seems to be going away soon), or parameters. But what is the json-api-ish way to accomplish this? I don't like @ncoghlan 's idea of putting actions in a separate collection, because that would lose the resource namespacing by flattening actions out at the root level of the api. I also don't like manipulating the POST verb into meaning whatever you want it to mean by changing how you define your domain specific requirements. But I know that one is probably just me not drinking the kool-aid.

I also need to be able to filter resources based on available actions (which is a whole different can of worms), but that makes me inclined to follow the links pattern - list permitted actions per entity, and define the actions at the root level.

**Comment by steveklabnik** [comment]
@staab, I don't have the time to write something longer than this, my apologies.

Basically, one of the core tenets of REST is the 'uniform interface constraint.' Basically, by sharing verbs rather than creating custom ones, you get to use generic processors rather than specific ones. It also reduces confusion due to name clashes. For example, is a `COMMIT` verb something that goes with a VCS web app or a DBS app? Can't tell.

Using just POST isn't ideal, but it's also not terrible. See http://roy.gbiv.com/untangled/2009/it-is-okay-to-use-post and http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven

**Comment by staab** [comment]
Thanks for the reply! That's helpful.
