### ISSUE TITLE
Are deep linked resources requests allowed?

### ISSUE THREAD

**Issue by mattecapu** [json-api/json-api#325]
Are URLs such `/comments/3,4,5,6/links/post/links/author` allowed by the specification?

In the example, every `comment` has a _belongs to_ relationship to a `posts`-type resource, and every `posts`-type resource has a _belongs to_ relationship (called `author`) to a `users`-type resource.
The query will thus return every user that is author of one of the posts the comments 3, 4, 5, 6 belong to.

**Comment by hesalx** [comment]
Complex search queries are outside of the spec, generally. Usually, other kinds of APIs are used for this purpose, like custom QL with something like [treetop ruby gem](https://github.com/nathansobo/treetop).

But it looks like nested [filters](http://jsonapi.org/format/#fetching-filtering) should be supported as well as [sparse fields](http://jsonapi.org/format/#fetching-sparse-fieldsets) and [includes](http://jsonapi.org/format/#fetching-includes) are.
Also https://github.com/json-api/json-api/pull/293 would simplify that.

So you would do `/user?filters[posts.comments]=3,4,5,6` or similar.

**Comment by wvteijlingen** [comment]
This is also being discussed in https://github.com/json-api/json-api/issues/317. Complex search queries were somewhat discussed in https://github.com/json-api/json-api/issues/308.

Personally I'm not in favor of supporting nested resource URLs like this because they make implementing the spec a lot harder on the server side.

**Comment by mattecapu** [comment]
Even if I'm not a fan of this type of URLs, I've found them quite easy to implement from shallow ones.
You can check my implementation [here](https://github.com/mattecapu/carpenter/blob/master/source/parseUrl.js#L51)

**Comment by attitude** [comment]
All parts of the URI could be perceived as constrains, only made _visible_ in the address bar.

Simple example: these requests are same provided authorized (logged in) user ID is `123` for the third one:

```
GET /users/123/links/posts
GET /posts?users=123
GET /posts
```

There's a decent chance the issue URI path above is possible to rewrite as search query similar to `/posts?users=123`. The issue example has one difficulty to process: the `author` endpoint is the post's author or the author of the comments 3, 4, 5, 6, or is the author of such comments just one? It would probably need to be specified in the spec how to understand such path.

Still such path looks a lot like a query which could be represented as one of (not sure about the original path meaning of the issue):

```
GET /authors?comments=3,4,5,6 (simple as SELECT author WHERE *...*)
GET /authors?posts.links.comments=3,4,5,6 (requires extra JOIN)
```

The linked posts constrain is probably unnecessary. The returned result could be 1, but maybe 4 different authors, since the comma means `OR`. Such resources represented by URLs should be able to receive payloads too (I suppose) and it would need to be addressed in th implementation too. Supporting such resource paths gets less error-prone and it gets complicated: should resources matching such criteria be changed/updated in batch (which might not be intended).

Even the 3 level URI path could be perceived unnecessary but it clearly states type-ID(-attribute) constrain required. This way you know which object to SELECT and is therefore useful. 

For sake of simplicity, later nesting paths is impractical over the URL search query:
- it requires extra parsing, where as the search query can be natively parsed into a variable by you language of choice
- it gets more complicated when authorization policies get involved (failing such path with 400 Bad request for example needs explanation where in the chain it failed)
- supporting more options complicates implementation, it's already possible to use search query to get results

**Comment by mattecapu** [comment]
@attitude
The ambiguity in the URL I wrote vanishes when I tell you that `/links/post` and `/links/author` are relationships, like in the definition of the API where you should have them clearly and unambiguosly described (and I think that having a clear and coerent schema isn't something we have to write in the specification, like you don't write in the Java specification to write good code).
So I don't see the need for a complex and redudant search query. It isn't very RESTful, nor more elegant, to me.
As I stated before, the parsing logic for URLs like the above can easily be ported from shallow parsing, just use a bit of recursive wizardry.

Answering to your "critics" (no flame intended :smile:)
- "Extra parsing" is very dependent on how you implement parsing. In any case, you should parse the search query too. (I didn't understand the second part... do you mean `eval`ling the search query directly with the language parser?)
- This point could be made against the "search query" option too, since they're equivalent. Anywat, wity a robust parsing, I think you can provide necessary information in both cases, yet I agree with you it would be tricky. Moreover, we are analyzing an edge case, I wouldn't suggest to anyone to write impossibly long URLs, with 2/3 relationships you are already pretty far in the ER graph.
- Is it already possible? What part of the specification are you referring to?

**Comment by gr0uch** [comment]
I disagree with deep linking. I think that the purpose of having a URL specifically for retrieving related resources is twofold:
1. Compact the length of the URL so that it doesn't go over any safe limits on length. IDs are opaque to the client until the related entities are retrieved.
2. Lazily retrieve related IDs on the server, so that it doesn't spew out a long list of IDs on an entity with lots of links.

The only case in which deep linking might be helpful is if the alternative is to sequentially load related resources based on previous requests, but even then it would be more helpful to implement a query language.

**Comment by attitude** [comment]
GET could work, other methods complicate things. 
1. PHP has I guess `parse_str()` function, the URL query is pairs already, where as mapping URL to n-level relation could get tricky.
2. Should `PUT /posts/123/links/comments/12345` fail or succeed provided I own the comment but not he post?
3. Refers to previous. To update resource of `comment` or linked `author` of linked `post`, would you use the deep linking? I assume not. Would you support/implement more options or rather be specific?

**Comment by gr0uch** [comment]
I just want to add that the `include` query string syntax covers retrieval of nested relations. OP's example could be rewritten as:

```
/comments/3,4,5,6?include=post.author
```

**Comment by mattecapu** [comment]
@attitude 
1. `parse_str()` is nice, but any string manipulator like it leaves the burden of implementing the actual logic to you, so I wouldn't base this choice upon available string functions (URL paths are trivial to parse, too)
2. `/posts/123/links/comments/12345` resolve to the comment 12345, so any method implemented at `/comments/12345` should work also there. A clever URL parsing shouldn't mind.
3. Obviously the implementation of deep nested URLs shouldn't be mandatory, but I can't see any reason to explicitly forbid them. If your API doesn't need them, don't support them, like any other end-point.

@daliwali 
That's not exactly true. `include` adds a resource to the `linked` resources, while my example URL replace the `primary` resource. Semantically they're pretty different.
For example, a request to `GET comments/3,4,5,6/links/post/links/author` could return

```
{
  "people": [{
      "name": "George",
      "surname": "Washington",
      "id": 123
    },
    {
      "name":"Barack",
      "surname": "Obama",
      "id": 456
    }]
}
```

While `GET comments/3,4,5,6?include=post.author`, [as stated by the spec](http://jsonapi.org/format/#fetching-includes) should return the comments as its primary resource, and then add the authors in the linked resource.

```
{
  "comments": [{
     {"id": 1, "body": "Lorem ipsum", "author": 123, "post": 1},
     {"id": 2, "body": "Hello world", "author": 123, "post": 1},
     {"id": 3, "body": "sdsdf", "author": 456, "post": 2},
     {"id": 4, "body": "Something something", "author": 123, "post": 1},
   }],
  "linked": {
    "people": [{
        "name": "George",
        "surname": "Washington",
        "id": 123
      },
      {
        "name":"Barack",
        "surname": "Obama",
        "id": 456
      }]
  }
}
```

The main difference is with non-safe methods, where the resource targeted by the action actually changes.

**Comment by gr0uch** [comment]
@mattecapu as far as retrieval goes yes, it's just a matter of semantics, but you get the same data (and a little more). I don't understand why it would be necessary to use a complicated URL structure. From the `include` query, you already get URL templates to the `people` collection, so why can't the client just update them by making requests to `/people/{id}`? Is there ever a case when deeply nested links would be exposed to the client?

**Comment by attitude** [comment]
@mattecapu, suggested deep-linking could be easily supported with rewriting URLs without breaking/complicating specs, since it's not different from `GET /people?links.comments.id=3,4,5,6` as @daliwali pointed out as well.

_(Not sure if the query is OK, could not find it in the spec right now, but you should get the point.)_

I just think simplicity (less options to support in spec) is the best way to go.

---

_Note I would like to point out: I'm thinking about supporting some sort of "aliases" of some resources too, e.g. `(resource/(name|id)`, so I definitely see your goals. I assume what's not forbidden is allowed._

**Comment by dgeb** [comment]
URLs are opaque to the base spec, and have been moved to [recommendations](http://jsonapi.org/recommendations/#urls). Furthermore, we no longer make recommendations for URLs for multiple individual resources, as discussed in this issue.
