### ISSUE TITLE
Is entire-collection linked resources fetching allowed?

### ISSUE THREAD

**Issue by mattecapu** [json-api/json-api#326]
Let's say we have three types of resources: `users`, `posts` and `comments`.

Every `comments`-type resource has exactly one `author` relationship to a `users`-type resource and exactly one `post` relationship to a `posts`-type resource; and every `posts`-type resource has exactly one `author` relationship to a `users`-type resource.

**How I fetch all `users` whose `post`s have at least one `comment`?**

I can think of something such as `/comments/links/post/links/author`, but omitting the ID is never mentioned in the specification. Maybe using a reserved word like `any`?
Is that allowed by the [Alternative URLs](http://jsonapi.org/format/#urls-alternative) section?

**Comment by dgeb** [comment]
[The `filter` param is now reserved for filtering data](http://jsonapi.org/format/#fetching-filtering), but  specifics for implementations have been moved to [recommendations](http://jsonapi.org/recommendations/).

I'd recommend using this strategy rather than trying to construct URLs that provide some of the filtering constraints.
