### ISSUE TITLE
PATCH updates using the regular JSON API format

### ISSUE THREAD

**Issue by bintoro** [json-api/json-api#327]
How about allowing two flavors of `PATCH` requests to accommodate implementations that do not wish to abuse the `PUT` method by employing it for partial updates?
- `PATCH` with `application/json-patch+json`: As currently specified.
- `PATCH` with `application/vnd.api+json`: Payload as in `POST` or `PUT`. Explicit intention to update the target resource with only the attributes present in the payload.

JSON API already leaves the door open for an implementation to limit `PUT` to its original purpose, which is to replace the target resource in its entirety. The proposed change would make it easier for services to establish this convention by simply announcing their interpretation of `PUT` out of two possible choices.

Right now, if a service wanted to do this, it would also need to define new rules for `PATCH` and would end up in violation of JSON API.

**Comment by dgeb** [comment]
Certainly the new [Patch extension](http://jsonapi.org/extensions/patch/) can be used as an alternative to PUT. 

The use of PUT for updates is pretty firmly defined in the base spec (as of RC2) for [updating resources](http://jsonapi.org/format/#crud-updating). However, I'll link to your [other comment from #341](https://github.com/json-api/json-api/pull/341#issuecomment-74243140), which I think is a reasonable point:

> Perhaps this is a needlessly academic concern, but isn't it a reasonable requirement that a client should be able to perform a true PUT to request the resetting of some server-side properties that it doesn't have direct control over?

**Comment by dgeb** [comment]
I'd like to clarify the rationale for PUT-as-update instead of PUT-as-replace because I'm aware that it is somewhat controversial.

Basically, it comes down to the rather nebulous definitions of "whole resources" that should be replaced. This is especially an issue for relationships. Should every to-one and to-many relationship also be replaced along with attributes? I think this would be surprising to many clients, who might expect only attributes, or perhaps only attributes and to-one relationships, to be replaced. How about relationships that have inverses?

We've avoided much of this murky territory in JSON API by spec'ing PUT-as-update. This also simplifies implementations that don't also need to support both PATCH and PUT to be compliant with the base spec.

With that said, I certainly appreciate points like you've made above, and I know that this won't please everyone. However, I wanted to at least be clear about the rationale.

**Comment by bintoro** [comment]
Indeed, it's not immediately obvious how a true PUT should behave vis-à-vis relationships, but that's pretty much the point of specifications: to decide one way or another and then standardize.

The way I see it, PUT-as-replace should by default leave relationships intact. The alternative doesn't add as much value because the "replace everything" scenario can already be accomplished by doing a DELETE+POST combo.

> If a request does not include all of the fields for a resource, the server MUST interpret the missing fields as if they were included together with their current values. It MUST NOT interpret them as null values.

I wouldn't mind having to use an additional header or a magic query string parameter to indicate that a PUT request should be interpreted as a replacement, but I'm assuming the above technically precludes it, right? Some implementations will likely want to do this, so it would be great to allow for some kind of convention to emerge without violating the spec.

**Comment by dgeb** [comment]
It is reasonable, and compliant with the spec, for an implementation to interpret the setting of a particular attribute to `null` as a cue to "reset" one or more of a resource's attributes. The server is free to mutate one attribute based upon the setting of another (e.g. `updated-at` might always be changed). Obviously, this is all implementation-specific, and not to be baked into the spec.

Perhaps we should consider allowing support for an explicit reset header of some sort post-1.0.
