### ISSUE TITLE
Questions about client implementation for JSON-API

### ISSUE THREAD

**Issue by xiaohanyu** [json-api/json-api#329]
Hi:

Recently days I've adopt this project as one of the API design workflows in my company and I'm tring to implement an API client library on top of JSON-API. 

I found it's a little complicated to implement the full JSON-API semantics since it has lots of "MAY"s. 

I've written a simple jsonapi-helper: https://github.com/huhulab/jsonapi-helper . However I still has some questions about parsing JSON-API data from `links` and `linked` properties. 

For example, in the follow example JSON-API response, if I wanna to get data from top-level `linked`, I should do as following steps:
1. figure out keys in primary resources(`['author', 'comments'])
2. combined with the top-level primary key `posts` we get `['posts.author', 'posts.comments']`
   - **QUESTION**: if the primary key is `data` instead of `posts`, how should I reach `posts.author` and `posts.comments`?
3. get necessary `type`, that is `people` for `posts.author`, and `comments` for `posts.comments`
   - **QUESTION**: if `links['posts.author']` is an object with `type` property, then all is well, if not, how should this `type` info be retrieved? For now, I get this `type` info from the `href` url property, don't know whether it is right to do this way.
4. find necessary data for `posts.author` from `linked['people']` and for `posts.comments` from `linked['comments']`.

```
{
  "links": {
    "posts.author": {
      "href": "http://example.com/people/{posts.author}",
      "type": "people"
    },
    "posts.comments": {
      "href": "http://example.com/comments/{posts.comments}",
      "type": "comments"
    }
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase",
    "links": {
      "author": "9",
      "comments": [ "1", "2", "3" ]
    }}, {
    "id": "2",
    "title": "The Parley Letter",
    "links": {
      "author": "9",
      "comments": [ "4", "5" ]
   }}, {
    "id": "3",
    "title": "Dependency Injection is Not a Virtue",
    "links": {
      "author": "9",
      "comments": [ "6" ]
    }
  }],
  "linked": {
    "people": [{
      "id": "9",
      "name": "@d2h"
    }],
    "comments": [{
      "id": "1",
      "body": "Mmmmmakase"
    }, {
      "id": "2",
      "body": "I prefer unagi"
    }, {
      "id": "3",
      "body": "What's Omakase?"
    }, {
      "id": "4",
      "body": "Parley is a discussion, especially one between enemies"
    }, {
      "id": "5",
      "body": "The parsley letter"
    }, {
      "id": "6",
      "body": "Dependency Injection is Not a Vice"
    }]
  }
}
```

All in all, I think it's better for JSON-API to provide some more details and hints about how to parse and get proper data for client library implementation.

**Comment by wvteijlingen** [comment]
The top level `linked` section and `links` are separate. You do not need to parse one to use the other.

> If the primary key is `data` instead of `posts`, how should I reach `posts.author` and `posts.comments`?

I assume you mean how to figure out the type of the primary resource if it's keyed as `data`. The spec states "The "type" key is REQUIRED when the type of a resource is not otherwise specified in a document.". In my interpretation this means that if the primary resources are keyed `data`, every resource should contain a `type` key that contains the type.

>  If `links['posts.author']` is an object with `type` property, then all is well, if not, how should this type info be retrieved?

Good point, I don't see this explained in the spec. If you have control of the server side, you could make sure that a `type` is always included. Otherwise, you might want to include it in a client side configuration. I don't recommend getting it from the `href`, there is no guarantee that it actually contains the correct type.

**Comment by xiaohanyu** [comment]
> The top level `linked` section and `links` are separate. You do not need to parse one to use the other.

But how should I parse for this example? I mean, the keys for `posts` resource is:

```
"links": {
     "author": "9",
     "comments": [ "1", "2", "3" ]
 }
```

However, this top-level `linked` element is:

```
"linked": {
  "people": [Object],
  "comments": [Object]
}
```

**QUESTION**: How shoud I connect `author` with `people` ?

> "The "type" key is REQUIRED when the type of a resource is not otherwise specified in a document."

So you mean I should put the "type" key in **EVERY** object of primary `data` resources? Is this a little redundancy? **QUESTION**: Isn't it better to put this "type" key in the top-level `meta` object?

> If you have control of the server side, you could make sure that a type is always included.

The problem is, as a client library developer, I may not have the right to control how server responds. All I have is this JSON-API spec. **And the current serious problem of JSON-API is, it has many MAYs, which leads into lots of combinations.** For example, the `links` object in primary resource can be a single resource id or ids, or some resource objects; the top-level `links` object can contains a simple URL or an Object to designate how to get data from it. All of the above makes it quite complicated to implement a client library for JSON-API spec. 

I know that the `links` and `linked` key bring some SQL-like object-relation type thing into JSON-API compatible response, and it seems good. However, client should have a simple way to do some `select * from * where *` thing. So I think it's better to provide some more details and explicit steps to demonstrate how should a client do **PARSING** work. 

BTW, **the final QUESTION, do you think my newly written https://github.com/huhulab/jsonapi-helper is a good way to work with JSON-API responses**? I consider this library as a data adapter which transforms JSON-API data to more client-friendly data format. If some people feel good about this library, I think a should make a PR that mentions this library for JSON-API Examples section.

Thanks!

**Comment by wvteijlingen** [comment]
> QUESTION: How shoud I connect author with people.

The client needs to somehow figure out that the attibute `author` is of type `people`. If this data isn't present in the response somewhere, it must be configured in the client somewhere. JSON-API doesn't provide any real scheme and discoverability right now.

> QUESTION: Isn't it better to put this "type" key in the top-level meta object?

No, if you want to get rid of the redundancy, you should put the primary resources under the type instead of `data`.

> And the current serious problem of JSON-API is, it has many MAYs, which leads into lots of combinations.

I wholeheartedly agree on the abundance of MAYs. I've created a Swift client library and I ran into same problems as you are. However, it seems that for most people it's not a priority to change those MAYs right now.

> Do you think my newly written jsonapi-helper is a good way to work with JSON-API responses.

I don't think 'expanding' the response like that is a good way to deal with the payload. If you have 20 primary resources that all link to the same linked resource, that linked resource gets duplicated 20 times. I don't know if JS optimizes this, but even then it doesn't seem like the best solution. Also, if you want to work with a centralized Store client side, you don't want duplicate resources in there.

**Comment by dgeb** [comment]
Please review the latest rc2 spec, which has been simplified and many ambiguities have been removed. Specifically, the top-level `links` object no longer supports URI templates, which goes a long way to addressing your concerns here.
