### ISSUE TITLE
question on naming

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#332]
If you want a compound document you specify the `include` param in the url. This adds a top level `linked` object which is in turn referenced in the primary resource as a `links` key.

Just wondering why we don't use `include` for every key (the top level key containing the included resources, and the primary resource key specifying the ids that relate)?

**Comment by tkellen** [comment]
cc @jmeas

**Comment by wvteijlingen** [comment]
You mean using `include` instead of `linked` and `links`? I think links/linked matches better because a primary resource actually 'links' to another resource. Another resources is in turn actually 'linked' to. Its more a matter of semantics I guess.

Having said that, if we go through with https://github.com/json-api/json-api/issues/311, this won't be an issue anyway.

**Comment by dgeb** [comment]
Let's defer to the naming discussion in #312 re: the top level `linked` array.
