### ISSUE TITLE
ambiguities for nested includes

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#336]
The spec states that if you request a nested relation, only the last relation should be serialized in the result. So, a request `posts?include=comments.authors`, should only include `authors` in the `linked` section of the response (even though we had to query through comments to get the authors).

So, fine, that is easy to implement.  The question I have is this: I have not seen any references to having nested relations under `links`.  Should the `links` key for a given `post` in this request appear like this?

```
{
  links: {
    "comments.authors": {
      "type": "authors",
      "ids": [...]
    }
  }
}
```

**Comment by tkellen** [comment]
Upon further reflection, this seems like it is obviously what the spec intends. Perhaps an example showing this would be useful for others who might overthink this as I did? I'd be happy to add one once the next draft lands.

**Comment by dgeb** [comment]
@tkellen This seems like a slippery slope that could introduce quite a bit of complexity to implementations. 

Consider the different serializations that would be required for these two requests:
- `GET /posts?include=comments.author` - Each `post` resource would have to include `comments.author` in its `links` object. _This distant relation would only appear in the `post`'s `links` when `comments` was not also requested._
- `GET /posts?include=comments,comments.author` - Each `post` resource would only have to include `comments` in `links`, and then each `comment` resource would need to include `author`. By far this is more straightforward to construct on the server and unpack on the client.

In order to avoid this complexity, which increases the more distant the relationship, I'm comfortable with only providing direct relationships in a resource's `links` object. If has-many-through relationships are required on the client, then the client can easily request each relationship. I realize this limits the use cases for requesting a distant relation without a direct relation, but I think it's worth it to keep implementations straightforward.

**Comment by tkellen** [comment]
I'm surprised to hear you say that. I think the spec should support this, but the implementation of it is definitely non-trivial. Supported or not, I think some clarification around this is warranted.

**Comment by dgeb** [comment]
I don't see any harm in an implementation including deep links like this, but I don't think we should make it a requirement. Either way, I agree that clarification is warranted.

**Comment by dgeb** [comment]
@tkellen I may be coming around to your perspective after unsuccessfully trying to come up with scenarios where has-many-through links could be useful without including the linkage IDs in the primary resources.

This may simply be a case of an optional feature that is non-trivial to implement.

**Comment by tkellen** [comment]
So, it turns out that supporting this is not _that_ hard.  However, implementors who do this will want to whitelist the allowed relations or you can create some pretty nonsensical requests.  Say you have an organization with projects and the projects have utilizations (days worked by employees). A request to `utilizations?include=project.organization` is handy, whereas a request to `utilizations?include=project.organization.projects` drills into a relation that has nothing to do with the primary resource.

**Comment by tkellen** [comment]
Here is another question. Say you request `/employees/1?include=utilizations.project` to get all of the projects a given employee worked on.  In this system, an employee can have multiple utilizations on a single project, yielding results like this:

``` js
{
  "linked": {
    "projects": [
      {
        "id": 30,
        "name": "some project"
      },
      {
        "id": 43,
        "name": "some other project"
      },
      {
        "id": 62,
        "name": "yet another project"
      },
      {
        "id": 67,
        "name": "another project still"
      }
    ]
  },
  "employees": {
    ....
    "links": {
      "utilizations.project": {
        "type": "projects",
        "ids": [
          30,
          43,
          62,
          67,
          30
        ]
      }
    }
  }
}
```

Note that project 30 is shown more than once under the links key (because there is more than one underlying utilization for this employee referencing that project).  The entry for it in `linked` is already limited to appearing once per the spec... should the redundant links entries be uniqued too?  Also, what if one or more of them is null?

**Comment by tkellen** [comment]
As an aside, I'm aware it would be easier to just make another relation option called `projects` that selects the distinct ones. I'm just bikeshedding this particular concept.

**Comment by dgeb** [comment]
The purpose of including `ids` is to provide a linkage between the primary and linked data in the response document. Therefore, I believe the IDs listed in `ids` should be both unique and non-null.

I'll try to spell this out more clearly in a big PR coming very soon.

**Comment by steveklabnik** [comment]
This was handled with RC2.
