### ISSUE TITLE
WTF you changed the structure again!

### ISSUE THREAD

**Issue by AlexParamonov** [json-api/json-api#355]
What are those "data" top level keys, why they are here? Who desired to rewrite everything and broke the compatibility? Where is the history of the document with explanation of each change?

**Comment by dgeb** [comment]
The spec has not reached 1.0, but we are trying to get it there in the next few weeks. No breaking changes will be allowed after 1.0.

Please see https://github.com/json-api/json-api/issues/352#issuecomment-75111466

**Comment by AlexParamonov** [comment]
The status page has this:  "It is currently missing some details about the meta attribute and could be more precise about details of working with relationships". OK, it is fine to change some minor things under meta key, but not the root level structure of everything!

**Comment by dgeb** [comment]
`"data"` top-level keys have been an option in the spec for almost a year. Frankly, the problem was that there were _so many_ options that the "spec" was more of a set of guidelines. It was exceedingly difficult to write implementations that would cover a full range of options. Because of this, compatibility between implementations was loose at best.

Of course, in narrowing the number of options, some had to be eliminated. I'm sorry that this led to breaking changes. And I regret that the spec has been in an unfinished state for so long.

Please refer to #341 for a full list of recent changes and discussion.
