### ISSUE TITLE
Problem with reserved resource attribute names

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#361]
The goal of this proposal is to solve a specific practical problem of representing resources generated by _existing_ applications in _unaltered_ form via JSON API.
#### General problem

The application behind the API may be implemented using object attribute naming conventions and other considerations which may be in conflict with conventions of JSON API RC2. There are 4 reserved resource attribute names in JSON API: `id`, `type`, `links`, `meta` (plus `ids`). If an existing application already uses any of these terms internally (in business logic, DB) with different meaning than that in JSON API, then it seems that there are only three ways out, and neither of them looks particularly attractive:
- refactor the application, rename the offenders -- not always feasible/practical,
- submit to the fact that the particular term means different things in internal implementation and externally, in the API -- a permanent burden for humans involved in development on all levels,
- forget about compliance with JSON API.

It would be great if JSON API, as a communication format, would be flexible enough not to go in anyone's way and could adjust to existing conventions of communicating parties.
#### Specific example

One reserved word that I am particularly concerned with is `id`. It is very common to use column `id` for DB primary key and correspondingly in the application code. The best practice for primary keys is to be system-generated, and it makes sense to have the same convention (integers, UUIDs, etc.) for IDs for all entities in the system. At the same time, externally, on the API side, it may be convenient to use different IDs for _selected_ entities. For example, entity User has a natural ID `username`, and although it is not suitable as primary key and as internal ID for various reasons, it is very convenient as ID for the outside world, and there is actually no need to expose `id` of Users via API.

An example in pre-RC2 format:

```
{
  "linked": {
    "comments": [{
      "id": 45,
      "href": "http://example.com/comments/45"
      "links": {
        "author": {
          "username": "admin",
          "type": "users"
        }
      }
      // ...
    }],
    "users": [{
      "username": "admin",
      "href": "http://example.com/users/admin"
      // ...
    }]
  }
  // ...
}
```

How to make this compatible with RC2?
#### Proposed solution for the general problem

Allow to override all reserved resource attribute names via JSON schema. This completely removes possibility of name clashes. Here is a quick example which overrides names of 3 out of 5 attributes:

```
{
  "$schema": "https://example.org/api-schema/v1.2.3",
  "type": "object",
  "properties": {
    "identifier": {
      "jsonapi": "id"
    }, 
    "identifiers": {
      "jsonapi": "ids"
    }, 
    "type": {
      "jsonapi": "type"
    }, 
    "included": {
      "jsonapi": "links"
    }, 
    "meta": {
      "jsonapi": "meta"
    }
  }
}
```

Then, if the ID can be called `identifier` in the API, the application behind the API can map `username` to `identifier` for entity User and map `id` to `identifier` for all other entities:

```
{
  "linked": {
    "comments": [{
      "identifier": "45",
      "href": "http://example.com/comments/45"
      "links": {
        "author": {
          "identifier": "admin",
          "type": "users"
        }
      }
      // ...
    }],
    "users": [{
      "identifier": "admin",
      "href": "http://example.com/users/admin"
      // ...
    }]
  }
  // ...
}
```

I am not talking here about overriding attributes of relationships (`self`, etc.) because I think it would not have much practical value, although allowing that would be in line with this approach.

The URL for schema can be supplied either as an attribute of top-level `meta` of request/response or in the headers of request/response. If the schema is versioned via URL (as in the example above), it can be cached forever, so there is no performance penalty.

This capability may be provided as an extension, but IMHO such extension would only make sense if it is official and supported by major implementations.

**Comment by hhware** [comment]
If no solution of the general problem can be attained for one reason or another, I suggest #362 as a solution to my specific practical problem outlined in the example above.

**Comment by ahacking** [comment]
You are introducing a mapping layer into the 'wire format' so isn't it better to just implement the mapping in your server code instead of forcing everyone to accept your choice of mapping which may not be ideal and similarly clash with internal concerns depending on the client?

Either way there is always a logical mapping layer from "wire format". If your server doesn't have a place to implement serialization concerns then that's a fatal design flaw and not a problem json api needs to solve.

In my systems 'id' maps perfectly to my id column as I use v4 uuids. I have had cases like country codes or tax identifiers that have natural keys so I just deal with that mapping problem in those specific cases.

Your proposal would also allow clients to specify a mapping as json api is birectional, so your server would have to accept and process a client mapping also.  So what have you saved?   I think it's better to settle on some fixed keys over the wire and instead put the mapping in your code not in the protocol.

**Comment by hhware** [comment]
> forcing everyone to accept your choice of mapping which may not be ideal and similarly clash with internal concerns depending on the client?

I agree, there would still be a chance of a clash, but I would have freedom to select something which is unlikely to clash. In my particular case, only `id` is a problem, but if I could override all reserved attribute names, I would personally never selected `type` to be a reserved word. 

If reserved attribute names are hardcoded in the JSON API spec, then "everyone" you are referring to is everyone using JSON API. If JSON API allowed to override reserved attribute names, then "everyone" is just those consuming the API which is using that particular mapping. The latter might be considerably easier to manage than the former in many practical scenarios.

> If your server doesn't have a place to implement serialization concerns then that's a fatal design flaw and not a problem json api needs to solve.

We have a place for that, but that would mean that we would have to "submit to the fact that the particular term means different things in internal implementation and externally, in the API -- a permanent burden for humans involved in development on all levels". 

In other words, I am not saying that I will find myself in a stalemate if neither #361 nor #362 is approved, I am saying that I will find myself in a situation when everyone referring to something as ubiquitous as user ID would have to either explicitly specify which user ID he actually means, "internal" or "external", or just hope that it is clear from context. I honestly think that this mishmash is just unnecessary and can be handled better by a spec which has not yet reached v1.0.0.

> In my systems 'id' maps perfectly to my id column as I use v4 uuids.

I do not dispute that `id` works perfectly for many systems. Moreover, in the example I described above, `id` also maps perfectly, but I want to have a freedom to select another attribute to serve as ID for selected entities. My example describes entity User, which has internal (i.e., in code/DB) ID `id`, and this ID could be mapped to JSON API perfectly. However, I would like to have a freedom to designate `username` as ID specifically for the entity User because it is convenient and very natural for this particular entity. I cannot make `username` primary key and internal ID for User because it is not system-generated and because it is not even unique if soft deletion is used.

> Your proposal would also allow clients to specify a mapping as json api is birectional, so your server would have to accept and process a client mapping also. 

How does ability to accept specific mapping(s) turn into a requirement to accept any possible mapping? What is wrong with returning 400 if the client is trying to use his own mapping in the request?

What I am trying to solve here is not an abstract problem, but a practical one. Suppose someone has a working server-side application with API incompatible with JSON API RC2, but decides that the next incarnation of his API (which does not exist yet and therefore has no clients) should adhere to JSON API to simplify adoption. But the application happens to have attribute name clash with JSON API. If reserved word mapping is supported by JSON API, then the offending attribute is simply taken care of by the mapping, and amount of work required to adjust the existing applications to JSON API  has decreased. The clients which use a library with good support for JSON API probably don't notice any difference because the mapping is taken care of by the library. Those clients who do not use any libraries will probably just hardcode the non-standard attribute names, so it is unlikely to make much difference to them.

> So what have you saved?

I have saved nothing on development of serialization layer because it has already been there. But since I can keep things simple, team communication and project documentation is not polluted with confusing conventions of "this `id`" and "that `id`", fewer bugs are introduced because of misunderstanding of those conventions, etc.

**Comment by ahacking** [comment]
There has been a lot of discussion on what keys should identify a resource. It is also possible to have composite keys to identify things as well as natural keys.

Allowing flexibility has implications for linking as well. I've previously proposed approaches that allowed anything to identify a resource and the use of link templates/descriptors for building links to related things. You can search the issues for anything I've posted and you will see I have challenged the status quo on many different fronts.

If anything I would not approach this as an attribute mapping problem but one of  how do we identify and link resources given we have some existing schema. Given json api is wanting to codify a specific approach for new APIs rather than allowing too much flexibility you are probably wanting a different specification with different goals.

There is no need to externalize the mapping. Your data layer can just as easily fetch a mapping from an internal place as it can from the payload. Its chiefly not a wire format concern but a layer above. The OSI network model applies today as much as it applied decades ago, concerns are addressed in specific layers and conflating them just makes life harder for everyone.

> How does ability to accept specific mapping(s) turn into a requirement to accept any possible mapping? What is wrong with returning 400 if the client is trying to use his own mapping in the request?

Well why wouldn't your agument (if we assume for a moment that it has validity) apply equally to consumers? Consumers of an API can be servers too and if your argument is valid api consumers would have the same need to express an external mapping.  Put this way its pretty clear that you want the world to conform to your internal deficits in one case but not afford the same luxury to other consumer or servers who may have similar deficits. Thats a bit one-sided and not the thing to encourage for interoperability sake.

The proposal can be characterised as "certain json api agents may have deficits that prevent them conforming to the json api specification wrt attribute keys. We therefore need an externalised on the wire fixup table to accommodate those deficient agents in mapping attribute keys. However we have a bias for only accommodating one sided deficits, whereby the deficient side mandates a mapping impost on the other sides processing and requires the other side to not have similar deficits. The canonical use case is based on the server being deficient and the impost on consumers of the non confirming server. Such servers are not envisaged to be participating in other services lest they become subject to similar imposts they have mandated on others."

**Comment by hhware** [comment]
> There has been a lot of discussion on what keys should identify a resource. It is also possible to have composite keys to identify things as well as natural keys.

My argument about surrogate/natural keys was just an example.

> If anything I would not approach this as an attribute mapping problem but one of how do we identify and link resources given we have some existing schema.

It is my understanding from reading previous discussions that JSON API is trying to stay away from complexity associated with that. If it weren't the case, I am sure my proposal would have been totally different, hopefully not even needed. Again, I am trying to solve a practical problem, knowing that JSON API is RC2 now and is likely to stabilize soon.

> There is no need to externalize the mapping. Your data layer can just as easily fetch a mapping from an internal place as it can from the payload. Its chiefly not a wire format concern but a layer above. The OSI network model applies today as much as it applied decades ago, concerns are addressed in specific layers and conflating them just makes life harder for everyone.

I respectfully disagree. One of the points of JSON is to be human readable. Human readability is chiefly not a wire format concern. Why is JSON popular, why not use binary protocol with less overhead? Although OSI model certainly does apply, it is not the _only_ thing that applies. Humans are less efficient than machines in abstracting data into layers, it makes sense to accommodate them as well.

I am not the first one who brought up questions of attribute naming here. I believe that the problem is not how to handle serialization in the application, but more of a human perception problem. The need in externalizing the mapping arises from the fact that API is application's interface to the world. It is documented using API conventions, and those conventions may be needed for communication in teams (developers/management/support) on the server side and between teams on the server side and teams on the client side. It would be helpful to avoid confusion in these conventions. Having the mapping internal does not help much.

> Well why wouldn't your agument (if we assume for a moment that it has validity) apply equally to consumers?

OK, I agree with you that it would be logical extension of my proposal to support the mapping supplied by the consumer in the request, although I think it has less practical value and therefore even lower chances to be accepted than my proposal, if we assume for a moment that you are actually proposing this equality :)

However, I do not see how consumer-supplied mappings invalidate my point. API communication is bidirectional, but API as a whole is not -- it is provided by the server to the client, they are not equal in this relationship. All development process on the server side and all human communication on the server side and between client and server sides can still be happening on the terms of the server (with JSON API as it stands now, it will be happening on the terms of JSON API). In every given request, the client can override attribute names, and deserialization on the server could take care of that, given that the mapping supplied by the client conforms to the rules.

**Comment by bintoro** [comment]
I've thought about this and can't really see the utility here. I mean, anything other than a very rudimentary server is going to need some translation capabilities in the serialization logic anyway, so what's the problem?

In fact, I see a danger here that this would only hinder interoperability, as it would inevitably fall to API consumers to handle translation concerns on behalf of lazy servers.

> submit to the fact that the particular term means different things in internal implementation and externally, in the API -- a permanent burden for humans involved in development on all levels

But the translation occurs right at the boundary of the system. Only those who deal with the raw JSON need concern themselves with it. Others can remain blissfully ignorant of what goes on. How is this an overarching burden?

**Comment by dgeb** [comment]
Mappings can be performed on both the client and server, but your API should serve as a strict boundary that prevents these concerns from leaking through.
