### ISSUE TITLE
Dictionary of reserved words

### ISSUE THREAD

**Issue by hhware** [json-api/json-api#363]
IMHO, it would be helpful if the specification included a section where all reserved words were listed, with short explanations and references.

An example:
- `data` -- mandatory attribute for the list of primary data; reserved key for the top-level request and response objects ([details](https://github.com/dgeb/json-api/blob/v1rc2/format/index.md#top-level-))
- `id` -- mandatory attribute for every resource object; pair `(id,type)` forms unique (per-response) composite key of a resource; reserved key for resource objects ([details](https://github.com/dgeb/json-api/blob/v1rc2/format/index.md#resource-attributes-))
- ...

**Comment by dgeb** [comment]
I believe that every reserved key is specified in the contact in which it is reserved. If there is any ambiguity, please file an issue or PR re: the particular infraction.

We should consider your larger point of aggregating reserved keys and terms into a dictionary, which could be useful to avoid hunting through the spec for a particular definition.

**Comment by hhware** [comment]
@dgeb "to avoid hunting through the spec" was my motivation. If approved, I would be glad to prepare a PR for it. If you have preferences for formatting, please let me know.

**Comment by tkellen** [comment]
How about doing a list of words without definitions, and just linking to the first place in the spec they appear?

**Comment by steveklabnik** [comment]
It would be better as a separate page, a supplement, than in the spec itself, and then link that that page from the usage in the spec.

**Comment by dgeb** [comment]
@steveklabnik sounds good to me :+1:

**Comment by bintoro** [comment]
Whether its an index or a glossary, right now the trouble with the main spec is that its not always clear what constitutes a definition. Quotes seem to be used a lot for this, but I would prefer some more specialized way of visually emphasizing terms when they are first defined. This way they would be easy to spot and the reader doesn't have to wonder, "should I know this word already?".

**Comment by bintoro** [comment]
@dgeb suggested elsewhere that this issue could serve as a meta issue for terminology worries. That's a good idea because such issues are very much interrelated.

**EDIT:** All concerns originally listed here have now been addressed one way or another.
-   _resource_ — The definition is clear but the term has confused many because a REST/HTTP resource is not the same thing. Addressed in PR #376.
-   _resource object_ — The JSON representation of a resource, ~~a relationship, or a links container.~~ In a [comment to PR #357](https://github.com/json-api/json-api/pull/357#issuecomment-76199818), I proposed that we should limit the use of _resource object_ to resource representations **only**. UPDATE: Now resolved in exactly this way.
-   _data_, _data object_ — ~~This, I believe, should be the preferred term when collectively referring to _resource objects_, _link objects_, and _links objects_. It is already used in the spec on a few occasions in precisely this meaning (that is, _data object_ and _resource object_ are currently being used synonymously).~~ Term eliminated by #427.
-   _primary data_ — The definition is clear ~~but the JSON key is controversial (#312). `data` is now used even though "primary" is the qualifying term~~. Resolved.
-   _link_ — An umbrella term for relationships and hyperlinks. This is not defined anywhere but rather implied by what can appear in _links objects_ (#380).
-   _link object_ — A JSON representation of a _relationship_.
-   _links object_ (resource-level) — "represents linked resources, keyed by the name of each association"
-   _links object_ (top-level) — Contains hyperlinks that deal with the entire document.
-   _related resource_ — A resource related to another (duh). ~~The spec uses this term when describing relationships and operations on them.~~ UPDATE: Now used consistently (#405).
-   _linked resource_ — ~~The spec uses this term when describing compound documents, so it's easy to get the impression that "linked resources" refers to those related resources that are being included in a compound document.~~ Resolved by #403. ~~Now synonymous with _related resources_.~~ Term eliminated by #405.
-   _related resource URL_ — ~~Definition somewhat unclear (#379).~~ Resolved in #433.

**Comment by hhware** [comment]
@ethanresnick is touching on this in #480. @bintoro, perhaps it would make sense to make a PR out of your last comment, so that the content of this bling could be edited by everyone?

**Comment by tkellen** [comment]
Closing this as resolved. If anyone disagrees, please feel free to re-open with a PR that proposes a solution we can all review.
