### ISSUE TITLE
Do not hurry for 1.0

### ISSUE THREAD

**Issue by AlexParamonov** [json-api/json-api#365]
Hello.

Recenty merged pull request https://github.com/json-api/json-api/pull/341 contains breaking changes to the previous JSON API resource structure. It actually not the resource anymore, but data. Everything is a data now.

And I completely disagree with that. I believe there are other people who thinks differently that PR author.
Previous version was online for quite a long time, and it was adopted and loved for it old structure. **Don't rush** for irreversible changes and lock the 1.0. Listen to other people before changing the standard.

Now, lets get closer to what I am disagree with exactly.
It is the `data` root namespace and required `type` key.
Don't let the bad code practices fool you. It is absolutely not needed and adds more problems that it could possibly solve (if any):
### Naming.

"data" keyword means nothing. Server returns a set or unknown things. Query the /videos enpoint and get some unknown data objects that could be identified only by the type key.

Linked objects. ungrouped and comes in a mess:

```
"linked": [{
    "type": "people",
    "id": "9",
    "first-name": "Dan",
    "last-name": "Gebhardt",
    "twitter": "dgeb",
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "5",
    "body": "First!",
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "body": "I like XML better",
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
```

Clients are forced to go item by item to build required collection (comments or people).
### Pseudo help for sti.

Don't leak your DB structure to the API!

If response should contain objects of the different type, don't return unnamed data mess.
return the "covers" or "thumbnails" instead:

```
{
  "thumbnails": [
    {
      "id": "laonet",
      "title": "LAO NET TV",
      "cover_image": {
        "sd": "http://example.com/sd.jpg",
        "hd": "http://example.com/hd.jpg"
      },
      "href": "http://example.com/channels/laonet",
      "type": "channel"
    },
    {
      "id": "dexter",
      "title": "Dexter",
       "cover_image": {
        "sd": "http://example.com/sd.jpg",
        "hd": "http://example.com/hd.jpg"
      },
      "href": "http://example.com/shows/dexter",
      "type": "show"
    },
}
```
### ~~Resource~~ Data creation.

POST /photos

```
{
  "data": {
    "type": "photos",
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png"
  }
}
```

What? This explicitly says that /photos endpoint can create any resources.
This call does not create a resource, it create some abstract "data mess".
Compare:

POST /photos

```
{
  "photos": {
    "title": "Ember Hamster",
    "src": "http://example.com/images/productivity.png"
  }
}
```

If in doubt, try to think why this API uses JSON but not the XML. The last one has more adaptive structure, can have attributes and other bells and whistles. But for some reason people pick JSON, guess why?

Thank you for your time.
_To be continued_

**Comment by mattecapu** [comment]
Thank you, I was thinking the same things lately, when refactoring (sigh) a whole API wrapper

Let me stress the linked resource problem.
How do you query that mess? If I need an article with comments and author information along, previously I could just do something like this

``` js
let res = fetch('/articles/42?include=comments,author', 'GET');

res.articles.forEach((a) => renderArticle(a));
renderAuthor(res.linked.author);
res.linked.comments.forEach((c) => renderComment(c));
```

Pretty neat. All the stuff is just _a key away_ in the response object.
The new specification adds a lot of extra fun

``` js
let res = fetch('/articles/42?include=comments,author', 'GET');

res.articles.forEach((a) => renderArticle(a));

let author = res.linked.filter((r) => r.type === 'people');
renderAuthor(author);

let comments= res.linked.filter((r) => r.type === 'comments');
comments.forEach((c) => renderComment(c));
```

And that's going to become a humongous mess if I include multiple resources with the same type

**Comment by tkellen** [comment]
Why filter them separately? Just do a single iteration and reduce it down to the linked object you want. Keying on type alone isn't enough to support polymorphic relations. The spec doesn't prevent you from including the name of the relation in entities, either, if you're concerned about retaining that.

**Comment by mattecapu** [comment]
@tkellen the point is, why filter them?

**Comment by tkellen** [comment]
Because the segregation on type doesn't work for polymorphic relations.

**Comment by AlexParamonov** [comment]
But polymorphic relations are the egde case. And usually can be avoided.
Why ruin the usability and readability to support feature that will be used
by very small amount of developers?
Give them an extension, but keep the core clean and easy to use.

**Comment by AlexParamonov** [comment]
include the `type` when needed, present your resources as meaningful entities and 99% times you will not need the root `data` and required `type` attribute:

```
{
  "thumbnails": [
    {
      "id": "laonet",
      "title": "LAO NET TV",
      "cover_image": {
        "sd": "http://example.com/sd.jpg",
        "hd": "http://example.com/hd.jpg"
      },
      "href": "http://example.com/channels/laonet",
      "type": "channel"
    },
    {
      "id": "dexter",
      "title": "Dexter",
       "cover_image": {
        "sd": "http://example.com/sd.jpg",
        "hd": "http://example.com/hd.jpg"
      },
      "href": "http://example.com/shows/dexter",
      "type": "show"
    },
}
```

It this example the `type` is not used by the client right now. It was added as `future proof` and there are no factors in to start using it.

**Comment by bintoro** [comment]
Wait, what? How is any of this an issue? Surely a well-designed application doesn't poke the freshly deserialized structure directly but has an API layer that populates the results into a more convenient mapping (which _may_ be keyed on type if you'd like) and only then hands it off to the actual business logic. No?

**Comment by mattecapu** [comment]
@bintoro An API for the API? It seems overkill to me. I have to write **2** serialization logic: database -> api, api -> mapping, 3 if you consider mapping -> interface.
Aderence to a spec should be a way to reduce complexity, not to increase it.
Then what prevents me from just removing the middle layer and stuck with my own format, tailored to my application?

@tkellen you're right here, yet I tend to agree with @AlexParamonov
Anyway, this is a spec so _it is_ supposed to accomodate the most wide range of cases.

**What about keying resources by relationship name?**
No filtering, supports polymorphic relationships, and it's even a bit more semantic

``` json
GET /articles?include=comments,author

{
  "data": {
    "type": "articles",
    "id": 1,
    "title": "Rails is omakase"
  },
  "linked" : {
    "comments": [{
      "type": "comments",
      "id": 3,
      "text": "quux is foo"
    }, {
      "type": "comments",
      "id": 4,
      "text": "foo is bar"
    }],
    "author": [{
      "type": "people",
      "id": 5,
      "name": "John Smith"
    }]
}
```

**Comment by tkellen** [comment]
> What about keying resources by relationship name?

If the same entity appears in two relations it will unnecessarily appear twice.

**Comment by bintoro** [comment]
@mattecapu, I mean that the component in the application that handles the physical fetching of resources is also responsible for turning the raw results into a structure that makes sense for the rest of the application. Keying objects by type is literally a few lines of code — for the entire app! How does that add complexity? If your code really is issuing HTTP GET requests all over the place, then the first step to reduce complexity is to implement a shared service that does this, not dumb down the message format.

**Comment by ahacking** [comment]
@bintoro keying by type doesn't align with the primary/main result set and the desire to preserve order regardless of the resource types present in the result. Having two ways to specify a collection of resource objects is just unnecessary and means two code paths to get right.

Partitioning into types also introduces another layer of sorting on the server. When dealing with large result sets this increases latency as you can't send the response until you have fully processed the entire response.

The approach used in the new json-api spec actually allows streaming the response immediately. Your server can be pulling records from the database (as a stream) and serializing onto the wire as a stream. You can't do that with type based partitioning so latencies are larger, server memory requirements are larger. Why create unnecessary processing and memory requirements when it is also trivial on the receiving end to organize objects into type based collections if that is what the receiver must do for presentation or other reasons?

**Comment by bintoro** [comment]
@ahacking, I'm _opposed_ to keying by type, not in favor. Was just pointing out how trivial it is to perform said transformation on the consumer side if needed.

**Comment by dgeb** [comment]
> I believe there are other people who thinks differently that PR author.

@AlexParamonov the "PR author" also wrote a good portion of RC1, which you hold in such esteem (see  #237). I should point out as well that @wycats and I actually co-authored RC2, and Yehuda wrote the very first version of the spec. I advise that you keep discussion technical instead of personal; we are all trying to solve shared problems for which it is very difficult to reach consensus.

Your objections above are based almost entirely upon RC2's support for heterogenous data. This is a discussion worth having.

> Give them an extension, but keep the core clean and easy to use.

This is so much easier said than done. An extension that supports polymorphism/heterogenous data would be as different from the base spec as RC1 and RC2. However, it also impacts other extensions, including both the bulk and patch extensions (we would need alternative versions of both to support the different formats). This would lead to a fragmentation of tooling and implementations. Furthermore, an API that introduces a single heterogenous collection would then require fully breaking all endpoints by switching to the new extension(s). This places an enormous upfront cost on the decision of which version, homogenous or heterogenous, of JSON API to support.

And I say all this without tending to support heterogenous data in APIs that I design. So while I would love to be able to ignore the issue, I don't think the spec has that luxury if it is going to succeed.

**Comment by ahacking** [comment]
Oh thanks for clearing that up, I misunderstood what you meant by 'Keying objects by type is just a few lines of code'. Glad to hear we are in agreement.

**Comment by AlexParamonov** [comment]
@tkellen 

> If the same entity appears in two relations it will unnecessarily appear twice.

it is edge case.
if you worry about data amount transferred, add the `format=flatten` option (or extension).
It is great to have data dry, but it is secondary, not needed 90% of the time.

**Comment by AlexParamonov** [comment]
@ahacking 

> The approach used in the new json-api spec actually allows streaming the response immediately.

This is a strong point which worse it. Unfortunately, again, it is an edge case.
But as far as I know https://github.com/brianmario/yajl-ruby deals with it.

**Comment by AlexParamonov** [comment]
@dgeb sorry, I could sound harsh. Did not mean anything personal.
Regarding the tech part.
if I ask the question: what do you value more? Polymorphism/heterogenous or clean and meaningful structure (20 or 80). Do the spec orients on 80 or want to satisfy 20? Both are the fair targets.
I just need to know where you really want to go. Be clean, readable and enjoyable to use, or try to cover every possible edge case sacrificing everything else?
That will be the core, you could not change it afterwards.

**Comment by bintoro** [comment]
@AlexParamonov It seems to me you haven't really explained what the practical problem with the `type` member is. Would you mind? Because I don't readily see it.

Also, you complain that the absence of typed keys means that it's now difficult to identify what the data represents. But I think this is a fallacy. A server can define an unlimited number of endpoints that return collections of "photos" based on some context or delimiting factors. Typed keys or not, **the URL is the only way to know what the precise context is**. It's not the job of the keys because they can never fully perform that job.

I would suggest including the `self` member in the top-level `links` container (**EDIT:** or, even simpler, put a custom `type` member in `meta`). It will allow you to unequivocally determine the context and the type of the primary result set without inspecting the types of individual resources.

**Comment by ahacking** [comment]
@AlexParamonov  I don't regard efficient serialization as an edge case as it makes a big difference to application latency and throughput which can equate to many times less (sometimes an order of magnitude less) servers for the same workload, little things can have big impacts. Its not the sole concern but it certainly was a consideration in the current design because myself and others brought it up in previous iterations of the spec. Dan and co have incorporated many different use cases to find a sweet spot that supports more requirements and simplifies the spec in many respects and elimantes lots of MAYs and SHOULDs which leads to better interoperability.

I also wrote [to_json](https://github.com/ahacking/to_json) a DSL for serializing JSON in ruby which drove the addition of the streaming serializer interface in Oj. Its an example that serializing json has real overheads and little things do make a big difference.   Forcing type based collections forces higher overhead and delayed response generation as well and rules out streaming since the server has to organize all objects into type bags first before it can send.

I also don't regard polymorphism and/or mixed collections and maintaining sort order in the face of this as edge cases. Its pretty common to have different sub-classes of things distinguished by type and I'm sure you can recognize that others may have legitimate cases for such things. Maybe for your current use cases these are 'edge cases' but not for the intended audience of json-api which is trying to solve these cases UNIFORMLY. <-- an important concern for reducing complexity, reducing code paths and increasing the chances of interoperability between different implementations as there is just less to get right.

**Comment by steveklabnik** [comment]
I can appreciate frustration with changes, we are making them _now_, so that we can not make them in the future. We haven't rushed towards 1.0, the initial version of the spec arrived in May of 2013.

It's hard to discuss the particulars of what is here because there are a number of things in this single issue, and dealing with 'edge cases' is a large amount of the work in developing a specification in the first place.

We are taking all of these decisions seriously, and have been weighing them carefully amongst a ton of different things.

I don't belive that this issue is actionable, and so I'm giving it a close. Thanks.
