### ISSUE TITLE
Clarify the meaning of "related resource URL"

### ISSUE THREAD

**Issue by bintoro** [json-api/json-api#379]
Is it the intent of the spec that a _related resource URL_ (as defined in [Resource Relationships ](http://jsonapi.org/format/#document-structure-resource-relationships)) SHOULD always reflect an up-to-date state of the relationship? In other words, are we saying that the URL SHOULD NOT be the canonical URL of a to-one related resource?

Currently the definition is followed by:

> A related resource URL SHOULD remain constant even when the resource(s) it represents mutate.

I find it obvious that when _resources_ mutate, their URLs should remain unchanged.

I suspect this is trying to say: "A related resource URL SHOULD remain constant even when the _relationship_ (the set of referenced resources) mutates". That would be the equivalent of the rule stated in the first paragraph, i.e., no canonical URLs please.

It's important to set this straight because when a client performs an operation on a related resource, it needs either the related URL or the canonical URL depending on intent. They're not (generally) interchangeable, so there must be no room for confusion.

(cc @tilboerner)

**Comment by bintoro** [comment]
Let me also point out that, regardless of the answer to the question presented here, the current situation is suboptimal.

If a _related resource URL_ is allowed to be a canonical URL, then that's a worst-case scenario. A generic client will have no idea what it can (safely) do with it, as the whole thing becomes an application-specific convention.

If the URL is not supposed to be a canonical URL, then great. But an application may wish to eschew related URLs altogether in favor of using canonical URLs all the time. Doing that now is quite awkward because the canonical URL must be looked up in the `self` of an included resource.

A better approach would be to accommodate both needs explicitly right there in the link object:

```
{
  "type": "articles",
  "id": "1",
  "title": "Rails is Omakase",
  "links": {
    "self": "http://example.com/articles/1",
    "author": {
      "self": "http://example.com/articles/1/links/author",
      "href-linked": "http://example.com/articles/1/author",
      "href-canonical": "http://example.com/people/9",
      "type": "people",
      "id": "9"
    }
  }
}
```

A server could provide `href-linked`, `href-canonical`, neither, or both. Voilà.

(Note: The JSON keys can be whatever. Perhaps "absolute" instead of "canonical"?)

**Comment by ethanresnick** [comment]
I think a PR that fixes the typo you caught is an obvious first step.

Then, in an ideal world, I'd actually just want to stick with one key and say that related resource URLs MUST (rather than SHOULD) always return the entities that are _currently_ being linked. Then, if the client wants the canonical url, I think that requesting the related resource URL and then looking at `"self"` isn't that big a deal.

But, I have a feeling that that SHOULD was put in the spec carefully, given that nearly everything else has been converted to a MUST. (Perhaps it's a SHOULD to save servers the requirement of having to support non-canonical urls at all.)

So, if that SHOULD isn't going to change, then I'm on board with your two-key solution, which would certainly allow us to specify a MUST for each key individually.

**Comment by steveklabnik** [comment]
Milestoning due to thie canonical issue, I think we should just allow any link relation, and then, you can just use `canonical` directly.
