### ISSUE TITLE
dasherized attributes with python and flask?

### ISSUE THREAD

**Issue by devpascoe** [json-api/json-api#391]
So as you know python implodes at the first sign of a - so you cant write out (easily) json which would read { first-name: 'foo' }
Thus attributes have underscores eg, first_name.

Any recommendations? Or just press on with underscores.

**Comment by bintoro** [comment]
Three options:
- Use the subscription syntax (`obj['first-name']`) if made possible by your framework.
- Transform everything on import/export.
- Just use underscores in names.

I've been meaning to open an issue on this too, as I'm curious as to why dasherized names are recommended when they are not valid identifiers in ~~any~~ many programming languages. I like dasherized names in URLs, too, but don't see any obvious reason to favor them in JSON keys.

**Comment by steveklabnik** [comment]
> they are not valid identifiers in any programming language

It doesn't really affect your point, but various Lisps use dashes in identifiers.

**Comment by gr0uch** [comment]
I would much prefer that the recommendation for attribute names is underscored instead of dasherized, and I don't think the dasherized recommendation is very popular.

**Comment by devpascoe** [comment]
Its an interesting one right, camel case is popular given its javascript origins but IMO is fugly when representing data. Dashes are ok and underscores cast back to elitist geekery. Considering dashes cause issues in languages such as python as we shoehorn in support it would be great to settle on one style to rule them all that is supported by all natively.
Droppin' bombs.

Regardless i think i'll keep the underscores for now.

**Comment by kevin-brown** [comment]
In the [Django REST framework adapter](https://github.com/kevin-brown/drf-json-api) that I maintain we currently don't enforce dashes for this very reason.  It's relatively easy to force dashes when the output is being manually generated, but when it's used as part of another library with existing conventions (specifically, Python's `snake_case`) it's slightly more difficult.

Of course, this is just one more reason to _find out how it can be done_, which is why I'm not entirely opposed to enforcing dashes in attributes. The general consistency between the client and the server ends up being a plus in the long run.

**Comment by steveklabnik** [comment]
This would be a great question for the eventual forum at https://github.com/json-api/json-api/issues/295 , but it's not an issue with the spec itself, so I'm going to close it. Hopefully we'll get that forum up soon. Thanks!

**Comment by devpascoe** [comment]
Thanks @steveklabnik and I <3 your talk at APIdays Sydney :)
