### ISSUE TITLE
Using DELETE to remove to-many relationship

### ISSUE THREAD

**Issue by wuher** [json-api/json-api#445]
The section http://jsonapi.org/format/#crud-updating-to-many-relationships states that _to-many_ relationships may be removed using `DELETE`. While I like this idea, isn't it going against HTTP if client sends `DELETE /articles/1/links/comments` but after that `GET /articles/1/links/comments` would still return `200` with the representation of the relationship (regardless of the content in the original `DELETE` request)?

I have been under the impression that if client receives successful response to a `DELETE` request, that resource shouldn't exist anymore.

I think using `DELETE` is still possible if we add the ids in the URL. For example `DELETE /articles/1/links/comments/12,13`. After that if client would send `GET` to the same URL, it wouldn't exist and `404` would be returned.

If we did add the ids into the URL, then replacing the relationships could probably use `PUT` instead of `PATCH` which i suppose could be even more intuitive since `PUT` is meant for replacing the representation entirely.

**Comment by ColtonProvias** [comment]
In the current version of the spec, a resource is referred to both ID and type.  I don't see anywhere in the spec that defines how to best format this pair in URLs.  The issue is that a relationship does not have to be a single type, as is the case of generic relationships.

Let's assume for a moment that we have a platform (such as Tumblr) on which people can post likes, replies, and reblogs in a chronological manner to an object.  This can be implemented as a single generic relationship in the back-end, thus returning a relationship made up of three different types.  Now what if we wanted to delete a Like that has the ID 385019 from that relationship?  It can be a problem just referring by ID if there is also a Reply that has an ID 385019.  Thus the need for explicit type declaration with each object.

Now how do you format types in a way in URLs that is back-end agnostic?  Those of us on Python prefer underscored names, and thus you would see things like `email_addresses` appear.  Yet those coding with Node.js prefer camelCase and would rather write `emailAddresses`.  Would we use hyphens, commas, underscores, colons, periods, pipes, etc?

**Comment by bintoro** [comment]
> Now how do you format types in a way in URLs that is back-end agnostic?

@ColtonProvias Whether it appears in the URL or not, the client still needs to specify an exact type in order to issue a DELETE — or any relationship operation for that matter. There's no hard rule about how to format it. The client just needs to know.

@wuher From RFC 7231:

> The DELETE method requests that the origin server remove the association between the target resource and its current functionality.

A lenient reading of this would seem to accommodate what JSON API does. The _current functionality_ is no longer there. In particular, the RFC does not even suggest that a subsequent request to the same HTTP resource would be expected to return a 404.

> [...] replacing the relationships could probably use PUT instead of PATCH

This makes sense, but in effect the two are equal in this case. PUT does seem more intuitive, I agree.

**Comment by wuher** [comment]
Thank you for your quick responses.

@bintoro If you continue reading that paragraph it also says that

> In effect, this method is similar to the rm command
> in UNIX: it expresses a deletion operation on the URI mapping of the
> origin server rather than an expectation that the previously
> associated information be deleted.

To me, that says that the URL is indeed the _association_ that should be removed. So the deleted URL should not be there anymore even if the _current functionality_ would be. Furthermore, RFC 2616 says following about `DELETE`:

> the server SHOULD NOT
> indicate success unless, at the time the response is given, it
> intends to delete the resource or move it to an inaccessible
> location.

**Comment by bintoro** [comment]
@wuher Exactly. The association between the URI and its current functionality is to be removed. I don't see any rule that the same URI cannot continue to provide a different functionality, in this case a partial set of the previously existing relationship targets.

**Comment by ColtonProvias** [comment]
With a document storage back-end, `DELETE` in that sense works well.  However, for a relational database solution, `DELETE` as per RFC 7231 will not work as you essentially need to kill off the relationship completely.  It can be faked by claiming a request to an empty relationship as a 404, but otherwise it conflicts with the nature of serializing records.

**Comment by dgeb** [comment]
There is a note in JSON API:

> Note: RFC 7231 specifies that a DELETE request may include a body, but that a server may reject the request. This spec defines the semantics of a server, and we are defining its semantics for JSON API.

The relevant section in RFC 7231 states:

> A payload within a DELETE request message has no defined semantics;
> sending a payload body on a DELETE request might cause some existing
> implementations to reject the request.

**Comment by ethanresnick** [comment]
Fwiw, if this is a problem (and I'm not sure it is), then it also affects bulk DELETE's in the `bulk` extension.
