### ISSUE TITLE
Rename 'examples' to something like 'libraries'

### ISSUE THREAD

**Issue by wvteijlingen** [json-api/json-api#493]
The examples page in its current form is more a list of libraries that implement/work with JSON:API. With 1.0 converging on a a standard to improve interoperability, maybe it would be more accessible to rename this page to Libraries?

**Comment by steveklabnik** [comment]
Yes, absolutely.

**Comment by bintoro** [comment]
I think there may be a need for a dedicated section to host additional usage examples that aren't crucial to include in the base spec. Renaming _Examples_ to _Libraries_ would free up the _Examples_ page for such examples. An alternative would be just a section at the end of the main document. Opinions?

**Comment by hhware** [comment]
I would rename _Examples_ to _Implementations_. For example, if some CMS or other generic piece of software implements JSON API, it could also make sense to list it there.

**Comment by tkellen** [comment]
:+1: to calling this Implementations. @wvteijlingen would you like to create a PR for this?

**Comment by bintoro** [comment]
Just a tiny detail: if the header menu is supposed to fit in an 800px wide element, then the current design isn't going to accommodate both _Examples_ and _Implementations_.

**Comment by dgeb** [comment]
I think that the term "Examples" could cover both libraries as well as a showcase of compliant APIs. The main Examples page could be broken down into sections such as "Libraries" and "Implementations" (or perhaps "Showcase" or "Compliant APIs").

There's some fuzziness / overlap in these terms and I can see "Implementations" and "Examples" being used interchangeably. This is why I think a single main menu item might work best, since it allows further distinctions to be made clear from context on the page.

**Comment by bintoro** [comment]
@dgeb What I'm trying to accomplish here is a place to put extra usage examples, as in model payloads etc. that are either too long or too special-case to go in the main spec. That's what the remaining _Examples_ page would be for. A prime example of such content would be the complex attributes example which is pretty clearly needed but was rejected from the main doc.

**Comment by dgeb** [comment]
@bintoro oh, that makes sense, and is a good reason to use "Implementations" as a container for libraries and compliant APIs. I'm :+1: on leaving examples open for what you've described.
