### ISSUE TITLE
Body uses envelope to transfer meta data

### ISSUE THREAD

**Issue by PatrickWolleb** [json-api/json-api#533]
Why does this spec propose a body envelope if HTTP provides headers to transfer meta data. 
Document links must be contained in the payload.  
Imagine a html document with body tag that contains a<data> and a <links> for all anchor links. 

``` html
<html>
  <head></head>
 <body>
  <data>
    <div id="awesome_app"></div>
  </data>
  <links>
   <a ref="self">Some link</a>
  </links>
</body>
</html>
```

This does not make sense and does not conform to any spec. 
The same rule applies for JSON payloads since it uses HTTP as the protocol. 

If someone could outline why this spec proposes such an approach that would be great.

**Comment by PatrickWolleb** [comment]
Just for your info. It was not not an april's fool joke.

**Comment by ethanresnick** [comment]
I'm not sure exactly what you're asking/what you mean when you say "Why does this spec propose a body envelope if HTTP provides headers to transfer meta data?" If you could clarify, I'm sure someone will be able to give you a good answer :)

Here are some generic explanations that might get at what you're asking. (Again, if not, please clarify and I'll do my best!)

This spec uses HTTP headers where appropriate (e.g. in extension negotiation), but most things aren't covered by HTTP headers.

The spec uses the `"data"` member at the top-level, because there can be members at that level in addition to the primary data (which is all `"data"` represents), like related resources included with primary ones, or errors (the `"included"` and `"errors"`) keys respectively. And the spec uses a special `"links"` section at least in part because there is no equivalent to the `<a>` tag in JSON; that is, there's [no standard way](https://www.mnot.net/blog/2011/11/25/linking_in_json) of representing a link that any json client can detect no matter where it lives in the document. So the spec makes links identifiable as such by telling clients to expect them only in explicit places, including in `"links"` containers.

**Comment by hhware** [comment]
@PatrickWolleb, one of the reason: that JSON API supports compound documents, i.e. multiple resources can be returned in a single response. In this case it is natural to return links related to a given resource inside the representation of that resource and not in the HTTP headers, otherwise it would be difficult to figure out what they belong to.

**Comment by tkellen** [comment]
I'm going to close this as resolved. I feel that @ethanresnick and @hhware covered this clearly. Please feel free to continue the discussion if you're still unclear on this @PatrickWolleb!

**Comment by PatrickWolleb** [comment]
Thank you for your responses and I can understand that your solutions work but they are abusing the concept of HTTP by creating a pseudo protocol that can only be understood by having out of band info on this protocol. 

Linking: There certainly is an anchor equivalent  and it is called "link" key on documents. Each document can be represented in a schema and each schema can have links. Therefore the links are within the context of the object and they imply what object they belong to. 

Compounding:  This can be achieved through including the documents instead of the links. The link can be a link object or if embedded the actual resource.  Or if in worst case the API needs to compound one choose a client-controlled approach through query strings. http://dev.billysbilling.com/blog/How-to-make-your-API-better-than-the-REST

I can give you an example of a schema

``` json
{
  "title": "Fruit",
  "description": "A fruit",
    "type": "object",
    "properties": {
        "color" : {
      "type" : "string"
        },
    "links" : {
      "type" : "object",
      "properties" : {
        "self" : {
          "type": "string"
        }
      }
    },
        "elements" : {
      "type": "array",
      "items": {
        "$ref": "Element"
      }
    }
    }
}


{
  "title": "Element",
  "description": "A chemical element",
  "type": "object",
  "properties": {
    "id" : {
      "type" : "number"
    },
    "links" : {
      "type" : "object",
      "properties" : {
        "self" : {
          "type": "string"
        }
      }
    }
  }
}
```

For documents:
/fruits/apple?include=elements will respond with a fruit object containing all belonging elements.

For collections:
/fruits?include=elements will respond with a collection containing fruit objects containing all belonging elements

**Comment by ethanresnick** [comment]
Your examples for linking (use a `"links"` key) and doing compound documents (use an `?include` query parameter) sound like exactly what we're doing...so I'm still confused.

**Comment by PatrickWolleb** [comment]
Checkout this book http://shop.oreilly.com/product/0636920021575.do or even better Roy Fielding's paper on REST https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm

**Comment by hhware** [comment]
> abusing the concept of HTTP by creating a pseudo protocol

@PatrickWolleb, IMHO, JSON API is a protocol and data exchange format, built on top of HTTP. JSON API is using features of HTTP relevant to it. Why does it have to use every available feature?

Consider the following analogy: is HTTP abusing TCP? Building stateless layer on top of stateful layer is ignoring one of the major features of the underlying layer. Is it an act of abuse, or would anyone claim that this makes HTTP a "pseudo protocol"? Also, HTTP can be used over different transport layers, and JSON API can in principle be used over something other than HTTP.

Perhaps relation between HTTP and JSON API should be described more clearly somewhere in the FAQ...

> or even better Roy Fielding's paper on REST https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm

I would love to know where exactly is the contradiction with the Fielding's thesis. Would appreciate a more specific reference or quotation. Thanks!
