### ISSUE TITLE
revisit status code MUSTs

### ISSUE THREAD

**Issue by tkellen** [json-api/json-api#534]
Are these necessary? We may wish to do recommendations here, or use MUST for the status code range vs mandating specifics.

**Comment by estoner** [comment]
In my experience, status codes do become a significant bikeshedding issue, so I appreciate the MUSTs and even the specific codes.  We've seen pretty serious arguments around returning a 404 vs. returning a 200 with an empty array response, for example, where API developers prefer a 404 because it feels more RESTful while client developers don't want to build a code path to deal with that error.

**Comment by dgeb** [comment]
I think it's a good idea to revisit the MUSTs simply for compliance with HTTP. We need to be clear that, above all, responses MUST be compliant with HTTP. Status codes such as `202 Accepted` must be valid, even if we don't enumerate every possible one.

With that said, I agree with @estoner that the spec should reduce bikeshedding wherever possible. It's a fine line for the spec to walk.
