### ISSUE TITLE
Is it possible to request different subsets of one type with "fields"?

### ISSUE THREAD

**Issue by ksimka** [json-api/json-api#535]
Let's say we have posts and comments, both have authors of type "people". And say "people" has "photo" which have several fields with urls to different sizes of photo ("big", "medium", "small", ...) When fetching post with comments we want to get a big photo for the author of the post and a small photo for authors of comments. Is it somehow possible with current version of jsonapi?

(let "people" has a "userpic" field of type "photo")
As I can see we can only request `include=author,comments,comments.author,author.userpic,comments.author.userpic&fields[photo]=big,small` to get both, so we'll get useless data (big photos for commenters, small photo for author).

Can we implement something like `include=author,comments,comments.author,author.userpic,comments.author.userpic&fields[photo:author.userpic]=big&fields[photo:comments.author.userpic]=small` or so?

**Comment by dgeb** [comment]
Fields are specified by type instead of relationship because a single representation of a resource will be included in a response document. Therefore, the person in your example above should only be included once in the `included` array, even though that person is both the author of a photo and a photo's comment. 

I think it would be too onerous to ask server implementations to provide a superset of fields specified for that single person, based on the relationships in which they are involved in for a particular request. The spec's pragmatic approach is for the client to take on that responsibility and accept some extra data in the response.

**Comment by ksimka** [comment]
Ok, thanks.
