### ISSUE TITLE
Official extension proposal: Embedding related resources

### ISSUE THREAD

**Issue by dgeb** [json-api/json-api#536]
The spec has been dancing around the concept of embedding related resources in create / update requests for some time (ref #131, #165, #202).

I don't favor "side-posting" (see #202) as a general solution because:
- it potentially merges "new" and "pre-existing" objects in a single representation of linkage
- it relies on client-generated IDs to provide linkages

Instead, the alternative that I've favored is the [JSON Patch extension](http://jsonapi.org/extensions/jsonpatch/). The order of operations explicitly requires related resources to be created before parent resources, so there's no ambiguity.

However, there are some problems with proposing the JSON Patch extension as a general solution:
- it is not additive to the base spec, and therefore requires a lot more work to implement
- it also relies on client-generated IDs to provide linkages

So, I'd like to propose an extension that has none of the limitations of side-posting or JSON Patch: an official "embedded" extension. Here's how I envision it:

> A link object could contain an `embedded` member that would include representations of _new_ resources. The `embedded` member could be included alongside the `linkage` member, so that both pre-existing and new resources could be referenced.

I believe this would be very useful for creating resources along with a POST or PATCH operation to a parent resource.

Here's an example that links a new article to two pre-existing tags and creates two new ones:

```
POST /articles
Content-Type: application/vnd.api+json; ext=embedded
Accept: application/vnd.api+json; ext=embedded

{
  "data": {
    "type": "articles",
    "title": "Flask is à la carte",
    "links": {
      "tags": {
        "linkage": [
          {"type": "tags", "id": "1"},
          {"type": "tags", "id": "2"}
        ],
        "embedded": [
          {"type": "tags", "label": "JSON"},
          {"type": "tags", "label": "REST"}
        ]
      }
    }
  }
}
```

Here's an example that replaces an existing article's tags with two new ones:

```
PATCH /articles/1
Content-Type: application/vnd.api+json; ext=embedded
Accept: application/vnd.api+json; ext=embedded

{
  "data": {
    "type": "articles",
    "id": "1",
    "links": {
      "tags": {
        "embedded": [
          {"type": "tags", "label": "JSON"},
          {"type": "tags", "label": "REST"}
        ]
      }
    }
  }
}
```

A few considerations:
- As an additive extension, this is not a blocker to 1.0.
- I don't believe that we need to support embedding at relationship URLs, which only accept linkage data.
- This representation provides no benefits for fetching related resources, so I don't want to encourage its use (although I'm not sure we can/should prohibit it either).

---

> Edit 4/23 - Please see https://github.com/json-api/json-api/issues/536#issuecomment-95626658 for the latest version of this proposal.

**Comment by hkroger** [comment]
I like the idea but it leaves something still unsaid: What if you want to include a more complex resource with new embedded resources pointing to each other? Is there way to handle that?

Example: Let's say you want to create an order with a customer hierarcy. There is a customer "Acme Corp" and it has a branch called "Acme Finances New York".

The main resource is the order. The delivery address for the customer for the order is "Acme Corp" and the "Acme Finaces New York" is the billing address. You also want to indicate that "Acme Finances NY" is actually linked to the main "Acme Corp".

So this would need some sort of linking between the new embedded resources. How could that be handled? There are also reasons why you don't want to do these in separate API calls and there are reasons why you don't want to make one customer resource embedded inside another (because then it would be hard to indicate that the sub customer would be the billing customer).

This might be an artificial example but hopefully you can see what I am after here.

**Comment by dgeb** [comment]
This scenario could be handled with client-generated IDs using either the Embedded extension (this proposal) or the JSON Patch extension.

However, with server-generated IDs and the Embedded extension, you would be limited to establishing a single relationship per "embedding" in a single request.

I'm glad you brought this up - it's important to recognize the limitations of different ID generation strategies upfront.

**Comment by hhware** [comment]
@dgeb, IMHO, it is a great idea and I would like to add my +1 to it!

> As an additive extension, this is not a blocker to 1.0.

I dare to disagree, for the same reasons as in https://github.com/json-api/json-api/pull/431#issuecomment-90378980: it is additive for the spec and libraries, but not the actual APIs implementing it. 

I would not repeat my argument here, instead I would like to illustrate it with an example of [creation of a resource along with a relationship](https://rawgit.com/hhware/json-api/i415-p431-example/i415-p431.html#creating). As shown, it can be done within idiomatic JSON API via relationship `container.parent`, which is built on the same data as the corresponding parent's `container.children`. Imagine for a moment that `container.children` is the only relationship actually needed by the API. Still, the API would have to provide `container.parent`, only for the purposes of creation of containers: if `container.parent` did not exist, it would not have been possible to create a container in one API call within idiomatic JSON API. This extension would have allowed to do that in one call without `container.parent`. 

So in the absence of this extension, the API designer would have to add the unnecessary relationship just because of technical limitations of the spec. When/if this extension becomes official post 1.0, it will not help that API designer: the endpoint for creation of content is already "set in stone".

On a broader scale, I think that bulk extension and the extension proposed here deserve to be included into the base spec via **MAY**: they are compatible with the base spec and provide very useful functionality.  IMHO, the spec and the ecosystem which will grow out of it should not be fragmented by providing such functionality as extensions.

**Comment by mmartinson** [comment]
+1

**Comment by gr0uch** [comment]
:-1:
- How to associate `id` to embedded resource?
- The response not defined, should the embedded resources that were just created be `included`?

**Comment by outerim** [comment]
It seems I missed this when commenting on https://github.com/json-api/json-api/issues/562.

This solution would work for my present needs. The only use case we occasionally encounter that I can think this wouldn't work for is nested resources in which order is important. For example in the example you showed @dgeb there's no way for the API to know how the tags should be ordered. There are probably other ways to deal with this. For ex if the relationship with tags is more like a HABTM structure you could do something like the following (assuming nesting of embedded resources is permitted):

``` json
...
    "links": {
      "taggings": {
        "embedded": [{
          "type": "taggings", 
          "links": {
            "tag": {
              "embedded": { "type": "tags", "label": "JSON" }
            }
          }
        }, {
          "type": "taggings",
          "links": {
            "tag": {
              "linkage": { "type": "tags", "id": "5" }
            }
          }
        }]
      }
    }
...
```

@daliwali In response to your first question, I would assume that this extension would not negate the ability to provide client generated ids as with any other resource creation request. Perhaps I misunderstand your concern.

I don't think this should change the expected response format in any way. I think it would be good practice for the server to include at least any links which had embedded objects in the response by default which is within it's prerogative. The base spec is silent on use of `?include` on anything but GET requests. Perhaps this should be changed and the server should respect that parameter. So in essence if you want to get back all the dependent objects you just requested be created you'd need to POST with the proper include query parameter.

**Comment by dgeb** [comment]
Thanks @outerim for bringing up the ordering issue. I was talking this over with @lgebhardt, who came up with an alternative for representing embedded resources in the `linkage` member:

```
{
  "data": {
    "type": "articles",
    "title": "Flask is à la carte",
    "links": {
      "tags": {
        "linkage": [
          {"type": "tags", "id": "1"},
          {"type": "tags", "id": "2"},
          {"embedded": {"type": "tags", "label": "JSON"}},
          {"embedded": {"type": "tags", "label": "REST"}}
        ]
      }
    }
  }
}
```

I favor this alternative for a couple reasons:
- it allows order to be preserved between linked and embedded objects
- it provides a non-breaking path to support embedded data operations at relationship URLs
- it is perhaps more obvious that linked and embedded objects are members of the same collection

@daliwali as @outerim has stated, this extension still allows for the usage of client-generated IDs. Also, we should further specify use of `include` with non-GET requests, which I'd like done regardless of this extension.

If the above alternative is generally favorable, I will work up a PR soon.

**Comment by outerim** [comment]
@dgeb I like the proposed solution and definitely agree regarding use of `include` with non-GET requests.

What do you think should be included in the extension regarding the ability of the server to set limits on the depth of embedded nesting, or the types allowed for embedded data. Currently the server can return 409 conflict if the client attempts to post a `type` which doesn't match the endpoint. I think something similar should be allowed to give the server side some control over what it will allow to be supplied at a given endpoint.

**Comment by dgeb** [comment]
> What do you think should be included in the extension regarding the ability of the server to set limits on the depth of embedded nesting, or the types allowed for embedded data.

I agree this should be specified. Perhaps simply `400 Bad Request`, such as when a server does not support sorting as requested.

**Comment by tkellen** [comment]
Would this be valid for creating arbitrarily nested resources?

``` json
{
  "data": {
    "type": "book",
    "name": "J. R. R. Tolkien",
    "date_of_birth": "1892-01-03",
    "date_of_death": "1973-09-02",
    "links": {
      "books": {
        "linkage": [
          {
            "embedded": {
              "type": "books",
              "date_published": "1954-07-29",
              "title": "The Fellowship of the Ring",
              "links": {
                "linkage": [
                  {
                    "embedded": {
                      "type": "chapters",
                      "title": "A Long-expected Party",
                      "ordering": 1
                    }
                  },
                  {
                    "embedded": {
                      "type": "chapters",
                      "title": "The Shadow of the Past",
                      "ordering": 2
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by tkellen** [comment]
Whoops, revising that...

**Comment by bintoro** [comment]
I'm curious about this criticism of the sideposting approach:

> it potentially merges "new" and "pre-existing" objects in a single representation of linkage

Is the idea here that a human should be able to look at a `linkage` array and immediately determine which items are new resources and which ones already exist? Why is that important? The server will figure it out. It has to perform the lookups anyway.

**Comment by dgeb** [comment]
> Why is that important? The server will figure it out. It has to perform the lookups anyway.

Side-posting would rely on client-generated IDs. If new resources are included in `linked` and pre-existing resources actually exist on the server, then there is no problem. I believe the ambiguity results when the referenced resource does not exist on the server and is not included in the request document. In that case, it is unclear whether the request has omitted a new resource or whether it expects the resource to exist on the server. The server would have to choose one or the other and it might be unexpected to the client. I'd prefer that it be unambiguous whether a resource is being created or just linked.

**Comment by bintoro** [comment]
Okay, I get it.

Basically, in the current proposal, the presence of a wrapper object with an `"embedded"` member indicates that we have a new resource to be created.

There's nothing to stop you from doing an equivalent thing with sideposting:

```
{
  "data": {
    "type": "articles",
    "title": "Flask is à la carte",
    "links": {
      "tags": {
        "linkage": [
          {"type": "tags", "id": "1"},
          {"type": "tags", "id": "2"},
          {"type": "tags", "id": "670de04c-059f-4565-9502-9005e8357cd4", "included": true},
          {"type": "tags", "id": "1af1f0e1-81cf-44e6-98b9-f91b82c785cf", "included": true}
        ]
      }
    }
  },
  "included": [
    ...
  ]
}
```

Perfectly unambiguous.

Or, to support updates as well (and why not!):

```
...
        "linkage": [
          {"type": "tags", "id": "1"},
          {"type": "tags", "id": "2"},
          {"type": "tags", "id": "670de04c-059f-4565-9502-9005e8357cd4", "op": "create"},
          {"type": "tags", "id": "1af1f0e1-81cf-44e6-98b9-f91b82c785cf", "op": "update"}
        ]
...
```

It's true that sideposting necessitates (at least temporary) client-generated IDs, but that's actually a separate concern.

**Comment by hhware** [comment]
> I was talking this over with @lgebhardt, who came up with an alternative for representing embedded resources in the linkage member:

@dgeb, perhaps I am missing something, but it was my impression that linkage arrays represent unordered sets. The spec says:

> the server MUST append the specified members to the relationship using set semantics

AFAIK, _sets_ are [unordered](http://mathworld.wolfram.com/Set.html). Does the spec actually imply _totally ordered sets_? If so, does the spec _mandates_ all relationships to be ordered or just _supports_ ordered relationships? If the former, need to support ordering will be an unnecessary burden for the server in many cases cases where order is not important or makes no practical sense. If the latter, how the client can tell the difference between ordered and unordered relationship? Is this detail supposed to be described in the API docs, and response format alone is not enough to define the semantics?

I tried to bring up the question of ordering in https://github.com/json-api/json-api/pull/431#issuecomment-90378980 (see item 12). I still believe that relationship attributes are the best way to address it. Unfortunately, that PR was rejected.

**Comment by ethanresnick** [comment]
I think @dgeb's solution here, especially with revision that [puts](https://github.com/json-api/json-api/issues/536#issuecomment-95626658) the embedded resources under `"linkage"`, is quite elegant, but I see a couple issues:
1. The biggest is that it's impossible to reference the embedded resource in more than one relationship. 
   
   For example, suppose I'm adding a new person resource, and my person has two different relationships: `wants-to-learn` and `wants-to-hire`. These relationships hold collections of `skills` resources that the person wants to develop in themselves and hire in someone else, respectively. Now, suppose that there's a skill that this new person both `wants-to-learn` and `wants-to-hire`, and that this skill doesn't yet exist in the database. Creating it in the `POST` request for the new person is impossible with this proposal, because there's no way to embed it in the linkage for _both_ the `wants-to-learn` and `wants-to-hire` relationship without creating a duplicate `skills` resource.
   
   Problems of this sort only become more common when this strategy is used in conjunction with the bulk extension. For example, suppose that I want to create multiple articles at once and tag both of them with the same new tag...this is impossible. Or, on a job board, I want to add multiple job postings at once and link them with the same new employer.
2. Also, cyclical relationships among the embedded resources cannot be represented. This is arguably an advantage (since these graphs can be a pain), but it also seems fair to say that a more robust format would allow such relationships to be serialized, and then the server would simply have the option of rejecting the request if it can't handle it.

To address these issues, I want to propose an alternate format. It's similar to ones that have been proposed before, but it takes advantage of the fact that, even when server side ids are being used, each resource object has an _implicit client id_ in the request document by virtue of its [json pointer](https://tools.ietf.org/html/rfc6901). So my proposal looks like this:

```
POST /articles

{
  "data": {
    "type": "articles",
    "title": "Flask is à la carte",
    "links": {
      "tags": {
        "linkage": [
          {"type": "tags", "id": "1"},
          {"type": "tags", "id": "2"},
          {"embedded": "/embedded/0"},
          {"embedded": "/embedded/1"}
        ]
      }
    }
  },
  "embedded": [
    {"type": "tags", "label": "JSON"},
    {"type": "tags", "label": "REST"}
  ]
}
```

Again, this allows the same embedded resource can be referenced more than once. It also allows, cyclic relationships—and even relationships _from_ the related resources _to_ the primary data—using the JSON Pointers, but we can decide to disallow whatever cases we want.

Other details/caveats:
1. This strategy is compatible with either client or server assigned ids. If client ids are in use, the example above would change _only_ in that the resource objects under the `"embedded"` key would have an `"id"`.
2. This format can easily be applied to relationship urls too. 
3. I called the top-level key `"embedded"` rather than `"included"`, even though I was initially drawn to the request/response symmetry of using `"included"`, because that symmetry is actually a false one. If it were really symmetrical, an `"included"` key in the request body would include _all_ the linked resources, not just the embedded ones.
4. <a name="test"></a>It's true that, when client ids are not being used, a client can't easily identify which `"included"` resources in the request document became which resources in the response document. But I don't think that's a big deal. APIs that need this functionality can simply use client-assigned ids or use the `"meta"` key to communicate this information as follows. (The below is adapted from [@bintoro comment here](https://github.com/json-api/json-api/issues/202#issuecomment-65960949).) 

```
POST /articles
{
  "data": { 
    //my new article
  },
  "embedded": {
    "tags": [{
      // my new tag...
      "meta": {"client-id": "arbitrary-string-not-necessarily-a-uuid-1"}
    }]
  }
}
```

And then, in the initial 201 Created response:

```
{
  "meta": {
    "ids": [{
      "arbitrary-string-not-necessarily-a-uuid-1": "386"
    }]
  },
  "data": {},
  "embedded": [{"type": "tags", "id": "386", // my tag... }]
}
```

Thoughts?

**Comment by bintoro** [comment]
@ethanresnick I think your proposal is an improvement over the original, as I really dislike the idea of having full resource representations inside the `linkage` array.

> I called the top-level key "embedded" rather than "included" [...]. If it were really symmetrical, an "included" key in the request body would include all the linked resources, not just the embedded ones.

A resource that is referred to in a `linkage` member is not required to appear in `included`.

> It's true that, when client ids are not being used, a client can't easily identify which "included" resources in the request document became which resources in the response document. But I don't think that's a big deal.

I think it is a rather big deal, and it's exactly why I tend to prefer temporary client-generated IDs. However, if resource ordering is always significant in this extension, then the order alone could be used to convey this information. It feels slightly error-prone, though.

**Comment by hhware** [comment]
@ethanresnick, I guess you are essentially offering a version of "sideposting" (#202). I think the proposed solutions is positioned differently from "sideposting": not as a replacement, but as another option, which allows to solve a limited set of problems without involving client-generated IDs, which is nice. If "sideposting" were considered, I would agree with @bintoro that temporary client-generated IDs are a more robust option than ordered list. The [option](https://github.com/json-api/json-api/issues/202#issuecomment-65960949) with a separate mapping seems the most attractive to me because the returned resources are not polluted with temporary IDs.

On ordering: @dgeb, it did not occur to be that ordering might be ["significant in this extension"](https://github.com/json-api/json-api/issues/536#issuecomment-96644273) only. It is an option, of course, but I think it would be very confusing to have it significant in the extension but not in the base spec...

**Comment by ethanresnick** [comment]
@bintoro 

> A resource that is referred to in a `linkage` member is not required to appear in included.

Right; I meant all the related resources at the specified relationship path. That is, `GET /articles/3?include=tags` should include _all_ of article 3's tags. But, if we tried to get symmetry by `POSTing` to `/articles?include=tags`, we'd only put the to-be-newly-created tags in the request body's `"included"` key. The tags that the user wants to link to article three, but that already exist in the API, wouldn't be included under `"included"`—even though they would be returned under "included" with a `GET` request. That's the asymmetry I was talking about.

> I think it is a rather big deal [that the client can't easily deduce which resource objects in the request body were assigned which ids]

Can you explain this a bit more, and maybe provide a couple examples? I can imagine that this functionality might be necessary in some cases, I just haven't run across them yet. (For me, it's been sufficient to simply replace my collection of pre-request resource objects with the resource objects in `201 Created` response, without establishing a one-to-one mapping.)

Nevertheless, I think we really should establish how important this functionality is because, if it's a big deal, then we should port whatever solution we come up with here to the bulk extension, which has the same problem.

**Comment by ethanresnick** [comment]
@hhware 

> I guess you are essentially offering a version of "sideposting". I think the proposed solutions is positioned differently from "sideposting": not as a replacement, but as another option, which allows to solve a limited set of problems without involving client-generated IDs, which is nice. If "sideposting" were considered, I would agree with @bintoro that temporary client-generated IDs are a more robust option than ordered list.

To be honest, I've never understood exactly what "sideposting" is supposed to mean :) But I definitely considered #202 when making my proposal.

My understanding was this: 
1. @dgeb and others wanted to avoid mandating that the server persist objects under client-generated ids, which I agree with.
2. Using temporary client-generated ids (just to establish linkages) on APIs that will ultimately remap those ids is kind of ugly, because you have to put the temporary ids somewhere in the request and response document.
3. And yet, solutions that use embedding don't make it possible to reuse the same embedded relationship o



 "sideposting" here is just being used to denote 
>

**Comment by ethanresnick** [comment]
@bintoro

> A resource that is referred to in a linkage member is not required to appear in included.

Right; I meant all the related resources at the specified relationship path. That is, `GET /articles/3?include=tags` should include all of article 3’s tags. But, if we tried to get symmetry by `POST`ing to `/articles?include=tags`, we’d only put the to-be-newly-created tags in the request body’s `"included"` key. The tags that the user wants to link to article three, but that already exist in the API, wouldn’t be included under `"included"`—even though they would be returned under `"included"` with a GET request. That’s the asymmetry I was talking about.

**Comment by ethanresnick** [comment]
@everyone

The theory behind my proposal was that: (1) Forcing the server to persist objects under client-generated ids is obviously a no-go. But (2) getting the benefits of _temporary_ client ids is appealing. Except that (3) they are ugly/add clutter to the request and response documents. So (4) if we could use JSON Pointers, we could get most of their benefits without the clutter.

While this is true, it overlooked the fact that supporting json pointers could be a pain on the client. It’s easier for the client to generate an arbitrary temporary id (say, a timestamp) than it is for it to keep track of the order of the items in a request document that it may be building up over time (e.g. as the user of a CMS fills out a form).

Therefore, I’m now leaning towards a temporary client id solution, which also solves @bintoro’s and @daliwali’s concerns a about the client not being able to easily deduce which resource objects in the request were assigned which ids by the server.

But I want to hear a bit more about @dgeb’s thinking behind his proposal. Specifically, I wonder: are there downsides of the _temporary_ client id based approach that we haven’t heard yet? (E.g. maybe defining the rules for what types of graphs the server must support adds too much complexity?)

If the downside is only that the temporary client ids add a bit of clutter, then that doesn’t seem to me like enough of a reason to give up on added functionality they offer.

**Comment by senid231** [comment]
what the status of this extension?

**Comment by outerim** [comment]
I'd love to hear more from @dgeb and others on this as well. The solution proposed by @ethanresnick in this [comment](https://github.com/json-api/json-api/issues/536#issuecomment-96635505) seems good to me. I don't currently need the functionality provided by moving embedded resources out of linkage and instead referencing them from there but the burden on the server of supporting this format doesn't seem extreme to me for the flexibility it provides.

**Comment by mcmire** [comment]
I would also like to hear an update on this. This seems like a major feature post-1.0 to me. I'm currently looking to add something like this to my current project. But at this point, we have so many proposals and considerations going on that I'm rather lost as to what's the best approach here and why.

**Comment by mcmire** [comment]
For instance, @dgeb keeps mentioning that in order to do this using the side-posting strategy, the request must be made with client-generated IDs. Can someone tell me what the issue here is and why this is necessary?

**Comment by tkellen** [comment]
Closing in favor of #795.
