### ISSUE TITLE
Successful related response needed

### ISSUE THREAD

**Issue by ColtonProvias** [json-api/json-api#543]
The section being referred to: http://jsonapi.org/format/#fetching-resources-responses

At the bottom is an example of a response from a GET request to `/articles/1/author`.  However, only an unsuccessful request is shown, so no example of how to best format this response if an author is found is provided.

Would it be similar to a request to `GET /articles/1/links/author` or would it take a format of:

``` json
{
  "links": {
    "self": "/articles/1/author"
  },
  "data": {
    "id": "21",
    "type": "person"
  }
}
```

**Comment by ColtonProvias** [comment]
Thinking about it further, I fail to see the point of having both `/articles/1/author` and `/articles/1/links/author`.  It seems rather redundant to me.

**Comment by tkellen** [comment]
The relationship url (`/articles/1/links/author`) allows you to directly manipulate the author(s) related to an article independently from the article itself. For a to-one relationship this may seem a bit useless, but for a to-many relationship it is quite important for supporting non-destructive updates.

**Comment by alexwen** [comment]
@tkellen I am wondering if you could potentially elaborate a bit more with respect to the difference between self, related on relationships. Perhaps an example of how one would manipulate a relationship and how that would differ from the self link? Why wouldn't related go to the author resource for instance? For example:

```
  "relationships": {
    "author": {
      "links": {
        "self": "/articles/1/relationships/author",
        "related": "/people/9"
      },
      "data": { "type": "people", "id": "9" }
    }
```

**Comment by tkellen** [comment]
@alexwen Could you please raise this question on http://discuss.jsonapi.org?

The members of a `links` object always refer to the container it resides in. Because JSON-API [allows direct manipulation of relationships](http://jsonapi.org/format/#crud-updating-relationships), the self link of a relationship is the "relationship url".

In the example you've provided, no matter who the author of the article is, you can find it at the relationship url `/articles/1/relationships/author`. The related link points to the actual author, but that can change any time.
