### ISSUE TITLE
How to include unknown keys in 'data'

### ISSUE THREAD

**Issue by lode** [json-api/json-api#558]
I'm writing an application which reads a potentially unknown database and outputs its using json:api. When outputting a resource, the `data` key (mostly) just contains the data from the database row. For the json:api format other special keys need to be added like `id`, `type`, `links`, etc. This conflicts when a database table contains such keys as columns. I.e. `type` is not uncommon as a table column and could mean something else than the resource type (i.e. table name).

I can imagine several ways to solve this conflict. AFAIK only the last variant is allowed according to the spec, but according to the human eye and sense, is also the most strange one.

``` json
{
    "data": {
        "id": 1,
        "type": "foo",
        "links": {},
        "resource": {
            "title": "...",
            "type": "...",
            "bio": "...",
        }
    }
}

{
    "data": {
        "_id": 1,
        "_type": "foo",
        "_links": {},
        "title": "...",
        "type": "...",
        "bio": "...",
    }
}

{
    "data": {
        "id": 1,
        "type": "foo",
        "links": {},
    },
    "meta": {
        "data": {
            "title": "...",
            "type": "...",
            "bio": "...",
        }
    }
}
```

Is there a common way to solve this problem? Or is json:api not really suited for this kind of usage?

**Comment by gr0uch** [comment]
I don't see anything wrong with your first example.

**Comment by lode** [comment]
You're right, nothing against the spec. But I find it a bit nasty in a few ways:
- if the spec will define a `resource` key in the future, there is a conflict (i.e. in php reserved methods often have a `__` prefix, so you will never run in conflicts)
- another nesting level feels clunky as it already is a resource

But it is probably the most logical one.

**Comment by tkellen** [comment]
I think it is fair to say that the spec does not encourage exposing database tables directly over the wire. This leaks implementation details and tightly couples every client to your database.

JSON-API can handle this use case, but some level of massaging is required, especially if you want to represent relationships:

> Although has-one foreign keys (e.g. author_id) are often stored internally alongside other information to be represented in a resource object, these keys SHOULD NOT appear as attributes. If relations are provided, they MUST be represented under the "links object".

Given that some transformation must necessarily occur, I'd suggest adding support for remapping the reserved words as well?

I'm curious, is this planned to be read only or a full proxy?

**Comment by lode** [comment]
Our use case is generic database administration (full editing as well indeed). It is not that strange (at least at the moment) to expose the names of the database. The tight coupling for clients is also ok. The api is just a frontend for the database, working with any database structure further unknown to the code of the api. Clients will have to follow this concept and cannot assume fields to stay the same.

I would say that in general it is not recommended to do so, I agree with you on that. But I see that more as a general developer advice. It would be great if these kind of specs don't enforce such advice.

Foreign keys are also remapped indeed. And as you say, it is not strange to generate slugs of table-column names, and with that, prevent the collision with json:api keys.

**Comment by ksimka** [comment]
Just FYI: we're using underscores for "system" fields (_id, _type, _links, ...) in resources as in your second example, but we're not going to fully follow the spec.

**Comment by tkellen** [comment]
If you have `id` fields already, what's the value in remapping them to `_id`? If you _don't_ have `id` fields, why wouldn't you have the necessary remapping code use `id` instead of `_id`? The complexity is the same. The same question goes for the `type` field.

As an implementor, I feel pretty confident in saying that the code required to make your server as described will be equal in complexity to the code required to make it spec-compliant.

Whatever the case, it's great to hear that your team feels JSON-API is appropriate for your needs... it's too bad you won't be able to use any of the clients for it though (ember-data, orbit.js, etc)!

**Comment by ksimka** [comment]
@tkellen, we have a huge legacy codebase with different fields, where "type" is not a model name but can be anything. So we decided to separate "system" fields from regular ones in order to avoid any possible collisions. Yes, we remap ids fields, but not all the "type" and "links" that can be met here and there.

Actually, the reasons are lying deeper. Currently we're trying to implement only some principles from jsonapi, not the whole thing. We already have Swagger api and we want to use jsonapi's related resources feature over our existing api.

Maybe later we'll review all the models and then will be able to fully implement jsonapi spec.

**Comment by tkellen** [comment]
@lode

> It would be great if these kind of specs don't enforce such advice.

When I said "I think it is fair to say that the spec does not encourage exposing database tables directly over the wire." I was referring to our representation of relationships, not to the prefixing or not-prefixing of reserved keys.

That being said, if we took any of your approaches it would only bolster this advice, making even more difficult to dump raw table data in JSON form over the wire in a compliant manner.

**Comment by lode** [comment]
I'm closing this in favor of https://github.com/json-api/json-api/issues/573.
Although it doesn't matter for my personal case, `type` is such a generic keyword that it should not be reserved.

**Comment by hhware** [comment]
> `type` is such a generic keyword that it should not be reserved.

@lode, I agree! Further, if `id` & `type` were renamed to, say, `identifier` (#362) and `classifier` or something similar, the chances of conflicts (not necessarily conflicts in the sense of shared namespace, just misunderstandings in documentation and verbal communications) would drop orders of magnitude. Since JSON API is essentially a transmission format, IMHO it would be nice if it accommodated the widest possible variety of content being delivered via it, same as moving vans makers tend not to install anything protruding inside to accommodate the widest variety of furniture. But the common opinion is to disregard those considerations, so we are beating poor dead horse here.
