### ISSUE TITLE
Linkage arrays and duplicate type/id combinations

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#565]
I read that "A compound document MUST NOT include more than one resource object for each type and id pair", but shouldn't this rule be extended for linkage arrays that could also contain objects with the same type and id?

**Comment by tkellen** [comment]
Linkage arrays are populated with resource objects--this restriction applies to them already:

> In a compound document, all included resources MUST be represented as an array of resource objects in a top-level "included" member.

**Comment by cziegenberg** [comment]
Yes, you're right. This solves it. Thanks!

**Comment by ethanresnick** [comment]
@ziege I read your initial comment as saying that, in the following code, the duplication of linkage objects under the `myToMany` relationship name should be disallowed.

```
{
  "data": {
     "id": 1,
     "type": "b",
     "links": {
       "myToMany": [{"type": "a", "id": "1"}, {"type": "a", "id": "1"}] 
     }
  }
```

If that's what you're proposing, then I'm pretty sure there isn't a restriction covering that yet.

The restrictions @tkellen alluded to make sure that the duplicate linkage objects only result in the resource _actually being included once_, but I don't think they prevent the double listing under `links`.

Imo, disallowing this double listing wouldn't really be worth the extra complexity in server implementations, since this case will occur fairly infrequently and the biggest consequence of it is that the client might make an extra request. But that's a conversation we can have.

**Comment by cziegenberg** [comment]
@ethanresnick Yes, that's true. I'm implementing JSON API and would set the links are automatically when a resource is included - but this could still occur is set manually. I think it SHOULD be avoided, because of the unnecessary request, but isn't a check one MUST implement.
