### ISSUE TITLE
Recommendation for hierarchical types?

### ISSUE THREAD

**Issue by SFEley** [json-api/json-api#571]
Today's version of the [Recommendations](http://jsonapi.org/recommendations/) page suggests an extremely limited set of characters for names:

> It is recommended that resource types, attribute names, and association names be "dasherized"; i.e. consist of only lower case alphanumeric characters and dashes (U+002D HYPHEN-MINUS, "-").

I can see the virtue of this for attribute names, where any other punctuation might collide with the multitude of ways of specifying paths (dot-nesting, URIs, JSON Path, et cetera).  But I'm having trouble with it when trying to map type names to their concrete representations in other languages — in particular, it gives no room for namespaces or inherited subtypes.

My real world example is this: we have a Ruby abstract class called **Segment** which represents a set of customers. By itself it makes sense, and if no specialization were needed I could call the JSON API type `"segments"` and be done with it.  But we have different _kinds_ of segments.  Some segments are broken out by demographics or purchase history.  Some of them represent lists in third-party service providers such as MailChimp. These usually have additional properties and behavior — classic inheritance, in other words.

For reasons that are debatable but out of scope, we're often using namespaces to indicate the class relationships.  So there's a **Segment::AgeRange** and a **Segment::NeverPurchased** and a **Segment::MailChimpList** and so forth.  It'd be swell if the JSON API type alone were sufficient to inform the client what kind of object to construct, and the fully qualified name is necessary.  (We have other kinds of MailChimpList in our third-party service wrapper; we're not just namespacing for fun.)

So the question is, what to call the types?  Off the top of my head I can think of a few options: 
1. Ignore the problem. Call the types `"segment-never-purchased"` and so forth, and rely on external knowledge to map that to the actual class. This presents some maintainability issues, to put it mildly.
2. Overload the hyphen, allowing multiple hyphens in a row to represent a namespace separator. This has a couple of problems:
   1. The name `"segment--never-purchased"` looks ugly to me. And while that isn't a technical issue, I'm the kind of programmer who gives out _The Pragmatic Programmer_ as gifts and believes in my gut that aesthetics matter. Stop caring about elegance and you'll stop noticing broken windows.
   2. The double-dash has other kinds of implicit meaning in some of our representations, e.g. Markdown documentation, where it often gets automatically converted to a long em `—`. We're using [Apiary](https://apiary.io) and [API Blueprint](https://apiblueprint.org), so inconsistent Markdown behavior _is_ a technical issue.
   3. I only noticed this while typing the above two paragraphs, but my Mac _really_ loves to auto-correct `--` to `—` whether I'm in code or prose, and I have to work kind of hard to stop it.  I could turn that off, but then someone else will have the same problem and not notice it.
3. Call them _all_ `"segment"` and let some other field specify the subclass.  In other words, the `type` is no longer the complete type. Bleh.
4. Ignore the recommendation and use some other punctuation, like a colon or a tilde or something, and don't make a `Mountain` out of a `class Molehill < Mound`.

Out of all of the above, I'm leaning towards #4, but I wanted to ask first in case anyone has any better ideas or has also encountered and solved this issue.  (Or perhaps, as a longshot, felt the issue might be interesting enough to consider accommodating in the recommendation. Hubris, I know.)

Thoughts?

**Comment by ethanresnick** [comment]
My first thought is that, if you're assuming clients will map `types` to particular classes, then you're already making a few assumptions about the client (i.e. that it's written in a language that has classes; that it needs to distinguish between all these subtypes; that it will do so by having a class for each one; etc). That sounds almost more like an SDK than a generic api client. Given that, I think managing this mapping is the client's responsibility, which means option 1 would make the most sense. (And is one hashmap really a big maintainability issue? If so, option 4 would be fine too in my opinion.)

**Comment by SFEley** [comment]
It's not so much that they have to map 1:1 to class names; you're right that that makes too many assumptions about client language. It's more that I see reasons for type names to _sometimes_ carry information about taxonomy, so that the client can model `is-a` or other relationships however it needs. I went into language detail just to exemplify the problem.

**Comment by jcarlson** [comment]
@SFEley As the co-worker who sparked the debate, here's my retort, in writing.

The server may know about a multitude of segment types, as you've mentioned: purchase history segments, mailing list membership segments, and so on. But the API we're exposing is just "segments". While each segment sub-type _may_ have features the other segments types don't support, _all_ of the segment types must conform to the "segments" interface.

Importantly, the API client has to treat each segment as just a generic segment so long as you're requesting a collection of segments.

Since, as the API client, I am fetching a set of segments from a segments endpoint, I would expect the type for all the resources to be "segment". Otherwise, as @ethanresnick points out, you're making a few assumptions about the client. Since in JavaScript, a Hash is a Hash is a Hash, there would be no proper "class" to construct anyway, based on the type attribute.

In a situation where the client depended on all of the segments to support a certain feature, then what the client is _really_ asking for is a specific sub-type of segment. The client should specify this as a filter on the collection endpoint, or the API should support a separate collection endpoint for the various sub-types of segments.

I would suggest that if a segment document needs to identify itself as a specific sub-type, then the document should have a `sub-type` attribute. Short of that, I would just go with option 1 above and let the client worry about how to map types, since that is a problem for the client to solve, not the server.

**Comment by ethanresnick** [comment]
@SFEley Thanks, I understand the problem better now. 

My suggestion would be to always have the `"type"` string pick out the deepest (i.e. most-specific) subtype that the segment is. Because `"type"` is all JSON-API formally gives you to communicate type information, I think you want to make sure it describes all the properties of your resource. Then, if you need to communicate `is-a` information, you can do two things:
1. Rely on the `is-a` that's already implicit in the request. That is, if you request `GET /segments` and you get back a bunch of `segment-never-purchased` and `segment-age-range` resources, you know those are segments because you requested the `segments` collection.
2. Since option 1 is only a partial solution (especially if you have a type hierarchy that's deeper than two levels), provide any extra information with `"meta"`, either at the resource or document level. For example, you could add a `"parent-type"` property to each resource's `"meta"`, or you could document your whole type hierarchy in the top-level `"meta"` key.

**Comment by jcarlson** [comment]
Good feedback. Thank you.

**Comment by ethanresnick** [comment]
@jcarlson Happy to help! If you and @SFEley want to think through the other cases and put together a PR with a formal recommendation for how handle hierarchical types, I'd definitely support it for inclusion on the spec's recommendations page!

**Comment by tkellen** [comment]
Closing this as a resolved, but we'd love a PR with a formal recommendation @SFEley / @jcarlson!
