### ISSUE TITLE
Proposal to reserve "extensions" member at the top level of documents/resource objects

### ISSUE THREAD

**Issue by cziegenberg** [json-api/json-api#574]
In addition to #573, I suggest to introduce a new top level member "extensions", which enables extensions to add additional data without creating conflicts (as previously described in #569).

One example:

I thought about an extension to sign requests and responses, therefore I would have to add signature information to the document. To avoid conflicts (with attributes, other top level members and other extensions), every extension needs its own namespace.

So I would suggest to wrap them (following the suggested structure in #573) like in the following example (example name of the extension is "signature"):

```
{
  "id": "1",
  "type": "person",
  "attributes": {
    "firstname": "Justin",
    "lastname": "Timberlake",
    "signature": "http://commons.wikimedia.org/wiki/File:Justin_Timberlake_signature.svg",
  },
  "extensions": {
    "signature": {
      "value": "...",
      "algorithm" : "...",
      "canonicalization": "...",
      "key": "..."
    }
  }
}
```

As you can see, "signature" is defined as an attribute. The extension also uses this a member of this name, but the namespace prevents a conflict.

Please note: 

This is just a simplified example. An extension as described above would normally add data at the document level (to sign the whole document), not at the resource object level - but other extensions could add resource object specific data. So I request to add this member to both.

**Comment by hhware** [comment]
Would not this be covered by top-level `meta`?

**Comment by tkellen** [comment]
I don't think so. We've walled off `meta` for implementations specific data. If we started mandating usage there for extensions we'd run the same risk of collision that I'm trying to prevent with #573 (would love your feedback there @hhware).

That said, I don't think this addition is something we should discuss in the abstract. I'm cautiously interested in the concept, but given that it is additive, and that we don't have a concrete need for it (yet), I don't think this should be put in the spec now.

**Comment by ethanresnick** [comment]
> I'm cautiously interested in the concept, but given that it is additive, and that we don't have a concrete need for it (yet), I don't think this should be put in the spec now.

My thoughts exactly!

**Comment by lgebhardt** [comment]
If `attributes` is reserved at the top level then there won't be name collisions between attribute names and any keys extensions choose to use. So I see this as unneeded at this point. An extension could freely define any keyword in this space to use. For example the extension you define that wants to sign a response could safely use the `signature` key at the top. No real need to nest it.

**Comment by hhware** [comment]
> So I request to add this member to both.

IMHO, if `extensions` is added, it should be added everywhere where `meta` is allowed (response, resources, relationships, etc.), otherwise it would only serve a fraction of use cases and therefore will not be able to assist in achieving desired consistency. 

> We've walled off meta for implementations specific data.

Is it even possible to strictly adhere to this dedication of `meta`? Some "implementations specific data" can become common enough so that an extension grows out of them. On the other hand, a particular implementation may choose to declare an extension for internal use, only for the purposes of providing "implementations specific data". To me, difference between `meta` and `extensions` is vague and not enforceable. IMHO, having `meta` on all levels is enough.

> If we started mandating usage there for extensions

I doubt it is even possible to "mandate" anything, given the freedoms which extensions are granted...

>  we'd run the same risk of collision

IMHO, such risk exists for `extensions` proposed here unless extension names are guaranteed not to collide, either via registering them in a central repository or via self-administered namespace structure (e.g., similar to Java packages). 

Needless to say, risk of collisions is inherent for `meta` because it is intentionally not regulated by the spec. Should the spec provide a recommendations for for self-administered namespaces for members of `meta`?

**Comment by cziegenberg** [comment]
@tkellen: 
I agree, that there is no concrete need for it at the moment, but as an extension developer I'd like to know how to do this, also from version 1.0. And a definition in the spec wouldn't break anything, because clients and servers only have to support the additional member, when they begin to support an extension that uses it.

@lgebhardt: 
Resource object "attributes" are defined by the API, while extension attributes are defined by an extension, not controlled by the API. The API can only decide if to support and extension or not. So collusions are possible and would force the API to change its attributes, which would break clients in the next step.

And extensions that add members at the top level could conflict with new to level members introduced by future versions of the spec or members of the same name, introduced by other extensions that are used at the same time. 

@hhware:

I agree that the "extensions" member should be available where the "meta" member is, but again I have to say that one has to differ data from the API (sets the meta data) and data from independent extensions - they don't know each other and should be separated to avoid conflicts. The proposal offers a way to easily activate extensions and be sure, that there won't be any conflicts.

Of course this could also be solved by namespacing "meta", but I think it's good to keep "meta" unregulated and allow the API (not extensions) to add additional information of any type there (copyright, debug data, whatever).

Collusions between extension names is a general problem that isn't covered by the spec. (How to handle it in the Content-Type header?) This proposal assumes that each extension name is unique  - or at least that you can only use an extension with the same name at the same name.

**Comment by lgebhardt** [comment]
> Resource object "attributes" are defined by the API, while extension attributes are defined by an extension, not controlled by the API. The API can only decide if to support and extension or not. So collusions are possible and would force the API to change its attributes, which would break clients in the next step.
> 
> And extensions that add members at the top level could conflict with new to level members introduced by future versions of the spec or members of the same name, introduced by other extensions that are used at the same time.

@ziege You are right that extensions could conflict with future versions of the spec. I was only thinking about conflicts amongst other extensions. I'm now in support of adding the `extensions` top level member. Better to have the spec fully control every top level member.

**Comment by ethanresnick** [comment]
Per #603, I now think this is a great idea and would vote for it to be added before 1.0.

**Comment by ethanresnick** [comment]
Also, unless we add something like this that provides a way for additive extensions to ensure they'll always be additive, this sentence in the base spec doesn't make sense:

> Servers MUST NOT provide extended functionality that is incompatible with the base specification to clients that do not request the extension...

That is, the clause "that is incompatible with the base specification" must be removed, because anything could become incompatible with the base specification after the server is authored. (I say this even though I remember why we added that clause—namely, to allow the server to opt-the client in to additive extensions, which could still be useful).

**Comment by ethanresnick** [comment]
Closing this in favor of #650, which I believe has assimilated these concerns. I'm also about to open another issue (superseding #650) that takes this into account.
