### ISSUE TITLE
How to handle huge linkage arrays

### ISSUE THREAD

**Issue by nevson** [json-api/json-api#582]
I've a question regarding the handling of huge linkage arrays. Lets say that there is a to-many relationship between an article and comments as [shown in the example here](http://jsonapi.org/format/#document-structure-compound-documents). In case there are hundreds of comments it won't be really possible to include all references in the linkage array. Actually there are use cases where you can even tell only the overall number of references but you won't be able to list them all at once (via {id, type} identifiers).

So the question here is if it's ok to let the `linkage` property away in the response and just include the `related` property? If not, would I need to work with a `linkage` pagination somehow?

Another question would be how I can prepend or append a single reference to this huge linkage array. 

Sorry in case I'm asking nonsense. I'm new to JSON API and just want to get my head around it :)

**Comment by nevson** [comment]
I was playing a bit around with the node json-api server to figure out how appending linkage objects works but had no luck so far. So far I did try to append an object like shown below but without any luck (server just responses 204 No Content)

```
POST /articles/1/links/comments
{"data": [
  {"type": "comments", "id": "123"}
]}
```

Or would I need to POST into the related resource URL `/articles/1/comments`? But somehow the `related` property is missing so far in the [node json-api server example](https://github.com/ethanresnick/json-api-example) :(

**Comment by ethanresnick** [comment]
@nevson 
1. It is ok [according to the spec](http://jsonapi.org/format/#document-structure-resource-relationships) to exclude the `"linkage"` property in the response. I believe it's also possible to paginate it. That said, excluding `"linkage"` isn't yet supported by my implementation, because related urls aren't yet supported (per https://github.com/ethanresnick/json-api-example/issues/1), and removing `"linkage"` before you have a `"related"` url to replace it isn't legal.
2. Re appending linkage objects: `204 No Content` means that things are working correctly! You'll see in the spec that 204 is [the appropriate response](http://jsonapi.org/format/#crud-updating-relationship-responses)  when the append succeeds. After appending, you can also reload the resource and you'll see that the new linkage is present.
3. If you have any other questions about the capabilities of the [ethanresnick/json-api](https://github.com/ethanresnick/json-api), please ask on that repo! That library is just my implementation of this spec; it isn't officially affiliated with the json-api organization!

**Comment by nevson** [comment]
@ethanresnick Awesome, thanks a lot for your detailed answer! Glad to hear that the `linkage` property can be excluded in such cases.

Not sure if this is now an implementation specific question or not, but how could a client control whether the `linkage` property shall be included or not? Or is it up to the server to decide if he adds the linkage or not depending of the array size?

Sure, if I've further questions directly related to your implementation I'll post them in your repo :)

**Comment by ethanresnick** [comment]
@nevson happy to help!

> how could a client control whether the linkage property shall be included or not? Or is it up to the server to decide if he adds the linkage or not depending of the array size?

The spec doesn't define any way for the client to control this, so it's up to the server. (Though the server could define some custom query parameter that lets the client control it.)

**Comment by nevson** [comment]
@ethanresnick Thanks for the infos. I think that answers so far my questions. Hopefully this topic will be covered in the JSON API documentation with some recommendations how to handle such huge arrays and what are best practices regarding that.
