### ISSUE TITLE
Support for read-only non-persisted resources

### ISSUE THREAD

**Issue by wvteijlingen** [json-api/json-api#648]
I'm running into a use case for an API regarding read-only, non-persistent resources. This API needs to have some endpoints for statistics. These statistics are calculated on the fly by the server and are not persisted in any way. For example: getting all visits within a certain date range.

The current spec states that resources MUST contain an `id` key, which is useless in this case because these resources do not have to be uniquely identifiable. I see some old issues and pull requests that indicate that support for such a thing was present but removed at some point.

Why was this removed, and will it be troublesome to reintroduce this? Perhaps we could add some kind of key that indicates that a resource is ephemeral and thus does not contain an ID?

**Comment by dgeb** [comment]
If the statistics do not contain a type and ID, then they are no longer considered resources from the spec's perspective. This was done in order to ensure a consistent representation and simplify processing by both clients and servers.

Here are some options:
- Statistics could be returned as members of a complex attribute on a resource. Any JSON values are allowed for attribute values. In this way, statistics would not be resources themselves.
- You could create an extension that removes the requirement for `type` and `id` for resources. Your endpoints could require use of this extension at those endpoints. In that way, clients will be prepared for the response.
- You could use a different media type entirely at these endpoints.

**Comment by bintoro** [comment]
Another option is to generate a UUID or timestamp to be used as an ID, in which case the statistics may be represented as ordinary resources. There's no requirement that resources must be persistent or updateable.

**Comment by dgeb** [comment]
Good point, @bintoro. That's definitely a valid option too.

**Comment by wvteijlingen** [comment]
Hmm I see your point in that they should not be considered resources in this case. I think I'll make use of an extension for these endpoints then. Thanks!

**Comment by ethanresnick** [comment]
Fwiw, I'm with @bintoro. Give them a temporary, meaningless id and then, if that's ever requested in the future, return `410 Gone`. That's much easier than defining an extension, I think.

**Comment by tkellen** [comment]
Chiming in to agree with @ethanresnick.
