### ISSUE TITLE
Provide exception for compound document "full linkage"

### ISSUE THREAD

**Issue by dgeb** [json-api/json-api#670]
Allow an exclusion in the full linkage requirement for compound documents when `fields` excludes a particular relationship that would otherwise contain linkage.

**Comment by ethanresnick** [comment]
@dgeb I think part of this is addressed by #580, which still looks mergeable. I'm trying to write up a PR for the rest of it now too~~, but (and I'm probably missing something insanely obvious), I can't find the normative requirement for full linkage in the current spec. Is it there? The only thing I see is the non-normative note that starts with "Because compound documents require full linkage,...". Should I add a normative counterpart to that too?~~ D'oh. I found this. It was just under the compound document section. I'll work on adding the remaining needed exception to PR #580.
