### ISSUE TITLE
Specify `id` and `type` value requirements

### ISSUE THREAD

**Issue by dgeb** [json-api/json-api#677]
We do not explicitly address valid values for `id` and `type`, beyond that they MUST be a string.

`type` values should probably use the same restrictions as member names. We need to ensure that types can be identified in `field[TYPE]` params for instance.

Requirements for `id` values could be less restrictive, but I'm not sure that they should be.

**Comment by dgeb** [comment]
Just read [this related comment](https://github.com/json-api/json-api/issues/675#issuecomment-104853359) from @ethanresnick proposing:

> The value of the `"type"` member **SHOULD** only contain characters that are [unreserved in URIs](http://tools.ietf.org/html/rfc3986#section-2.3).

**Comment by ethanresnick** [comment]
Yup, the `type` value should definitely follow the member name rules to avoid url conflicts. 

That SHOULD I proposed would basically then be an extra recommendation to avoid Unicode and the resulting percent a encoding. But it wouldnt be a MUST, because using unicode in `"type"` might sometimes be neccesary.
