### ISSUE TITLE
URL length limitations

### ISSUE THREAD

**Issue by chasm** [json-api/json-api#72]
I'm a bit concerned about this requirement in the proposed standard:

> An API that provides a to-many relationship as an array of IDs MUST respond to a GET request with a list of the specified documents with a URL formed by joining:
> 
> A base URL that represents the type of the related resource (this must be hardcoded in the client)
> ?ids=
> A comma-separated list of the specified IDs
> 
> In the above example, a GET request to /comments?ids=5,12,17,20 returns a document containing the four specified comments.

My applications use UUIDs as the ID, so each consumes (with the comma) 37 characters in the URL. Many servers appear to have pretty severe limits to URL length. If, for example, the limit is 2000 characters, then my associated objects would be limited to no more than 54. How would I handle a case where I need to load 100 or even 1000 associated objects?

I don't have a workaround for this -- GET is clearly the right method here -- but I'm wondering if anyone has given this any thought.

**Comment by SphtKr** [comment]
I think in this case you'd have to rely on a couple of alternate methods, the first of which comes to mind is the URL template based pattern, which can be used to fetch associations without foreknowledge of all the IDs:

```
{
  "links": {
    "posts.comments": "http://example.com/posts/{posts.id}/comments"
  },
  "posts": [{
    "id": "1",
    "title": "Rails is Omakase"
  }, {
    "id": "2",
    "title": "The Parley Letter"
  }]
}
```

So that would at least work in cases where you needed to get 100 records related by some association. I'd guess that would cover many of the use cases where this kind of thing would come up. I like your point though, and it's another reason this pattern needs to be supported (by the spec and by client and server implementations).

However, this wouldn't suffice if you needed to get 100 arbitrary IDs for some reason.

I'm guessing that, to deal with this, the client library would have to implement some kind of batching mechanism, that would fetch some configurably-sized chunk of records at a time. This would probably be pretty straightforward to implement in a client-side library. As a worst-case, the client could fall back to requesting one ID at a time (for example as the current Ember Data code does if your adapter doesn't implement `findMany`), but of course that's not a good solution for the volume of records you're talking about.

Either way, I don't think this reflects a problem with that part of the specification per se, since some mechanism like this would have to exist to allow such a batching or paging mechanism to be implemented at all. And you're right, I don't think there's a good alternative to GET in this case, so there's really no other place to put the requested IDs besides the URL (query string or otherwise). The length limitations are just something that will have to be worked around in the implementations.

**Comment by steveklabnik** [comment]
I'm not sure if there's anything we can do here either, other than maybe relax the requirement on how multiple things are fetched.

**Comment by steveklabnik** [comment]
URLs technically have no limit. There is some software that can't handle long URLs, but that's their problem, not the specifications.
