### ISSUE TITLE
Complex data structures

### ISSUE THREAD

**Issue by neomerx** [json-api/json-api#754]
Is it allowed by the spec to have IDs of other resources in complex attributes? For instance

``` json
{
    "data": [
        {
            "type": "manufacturers",
            "id": "M_CODE",
            "attributes": {
                "properties": [{
                    "name": "Manufacturer's name",
                    "description": "Manufacturer's description",
                    "language": "eng"
                }]
            }
        }
    ]
}
```

Where `eng` is actually an ID/code of a `language` resource. If not how can I minify/simplify the same record below?

``` json
{
    "data": [
        {
            "type": "manufacturers",
            "id": "M_CODE",
            "attributes": null,
            "relationships": {
                "properties": [{
                    "data": {
                        "type": "manufacturer-properties",
                        "id": "90"
                    }
                }]
            }
        }
    ],
    "included": [
        {
            "type": "manufacturer-properties",
            "id": "90",
            "attributes": {
                "name": "Manufacturer's name",
                "description": "Manufacturer's description"
            },
            "relationships": {
                "language": {
                    "data": {
                        "type": "languages",
                        "id": "eng"
                    }
                }
            }
        },
        {
            "type": "languages",
            "id": "eng",
            "attributes": {
                "name": "English"
            }
        }
    ]
}
```

**Comment by ksimka** [comment]
Looks like a synthetic example. Are you trying to implement a l10n that way? If so — simply response with a requested language. 

``` http
GET /manufacturers?lang=ru

{
    "data": [
        {
            "type": "manufacturers",
            "id": "M_CODE",
            "attributes": {
                  "name": "Manufacturer's name",
                  "description": "Описание производителя"
            }
        }
    ]
}
```

If you for some reason need a language's name, I don't think that `relationships` is a good place for it, cause it's not a natural relationship. Maybe use `meta`.

But I recommend to use locale param since we have, say, not only UK english, but also US english and more. Even if you don't support so many languages it'll be useful with date and time formatting.

``` http
GET /manufacturers?locale=en_US
```

**Comment by neomerx** [comment]
@ksimka I think `locale` would be outside of the spec and this approach doesn't work if I want to `GET` more than one property set (e.g. eng, spa, etc). Meta could be an answer however it's basically the same as storing language code as field so why using it instead?

**Comment by ksimka** [comment]
Can you please tell what kind of problem are you trying to solve? Cause needing to get a string with multiple translations at a time confuses me.

**Comment by neomerx** [comment]
Just look at this example not from read-only point of view but from edit (`GET` + `PATCH`).

**Comment by ethanresnick** [comment]
@neomerx The first code sample you gave would be valid (i.e. it's perfectly allowed), but generic JSON API clients wouldn't be able to know that the `"language"` key is an id. Unfortunately, there's no built-in mechanism for defining a relationship from a complex attribute—though that's been [actively discussed](https://github.com/json-api/json-api/issues/383) and may be added in the future.

Therefore, if you need your clients to be able to find the related language resource, you'd have to use something like your second example. It just needs a couple small tweaks for some syntax errors, namely: 1) `attributes` must always hold an object, even if it's empty, rather than `null`; and 2) in the `properties` relationship, the value at that key should be an object—it's the `data` member that needs to hold the array. So the final JSON would look like:

```
{
    "data": [
        {
            "type": "manufacturers",
            "id": "M_CODE",
            "attributes": {},
            "relationships": {
                "properties": {
                    "data": [{
                        "type": "manufacturer-properties",
                        "id": "90"
                    }]
                }
            }
        }
    ],
    "included": [
        {
            "type": "manufacturer-properties",
            "id": "90",
            "attributes": {
                "name": "Manufacturer's name",
                "description": "Manufacturer's description"
            },
            "relationships": {
                "language": {
                    "data": {
                        "type": "languages",
                        "id": "eng"
                    }
                }
            }
        },
        {
            "type": "languages",
            "id": "eng",
            "attributes": {
                "name": "English"
            }
        }
    ]
}
```

That said, if you don't need the language resources to be referenceable, you could even use something more concise than your first example, like this:

```
{
    "data": [
        {
            "type": "manufacturers",
            "id": "M_CODE",
            "attributes": {
                "en-US": {
                    "name": "Manufacturer's name",
                    "description": "Manufacturer's description"
                },
                "es": {
                  "name": "...",
                  "description": "..."
                }
            }
        }
    ]
}
```

**Comment by neomerx** [comment]
@ethanresnick Thanks a lot!
