### ISSUE TITLE
Do I need to `include` everything on a relationships data attribute?

### ISSUE THREAD

**Issue by mrcasals** [json-api/json-api#758]
Take the example JSON response from the frontpage of JSONAPI.org: https://gist.github.com/mrcasals/7353c916f256279ea391

From the post, I can know who is the author and what comments it has. From the `relationships` object I know it has only _one_ author, and _many_ comments. But once I get to the author, I can't know how it relates back to the post: does it have _one_ post, or does it have _many_ of them?

One way to solve this can be the one suggested here: https://github.com/json-api/json-api/issues/736#issuecomment-108007100 (using the `meta` object on a relationship to mark whether it's a _to-one_ or a _to-many_ relationship). 

Another way this could be solved could be including the `relationships` object in the included object (author, comments), and adding a `data` field with content to show whether the relation is a _to-one_ or a _to-many_, but I haven't seen any example with `included` objects with relationships inside. If I followed this path, do I need to add every object in a relationship `data` attribute to my `included` list of objects? Or is it OK to reference those objects and loading them later when needed (without having them in the `included` key?

Thanks!

**Comment by dgeb** [comment]
You can specify relationships within any resource objects, regardless of whether they are primary or included data. You can use `data` within a relationship object to show that an inverse relationship exists (say, between a person and posts or comments and a single post). If a partial set of to-many data is included, it should be paired with pagination links in the relationship's `links` object.

> If I followed this path, do I need to add every object in a relationship data attribute to my included list of objects? 

No, only the requested data should be included. It's possible to specify `data` for a relationship without also including those resources in `included`. The "full linkage" requirement [specifies the inverse](http://jsonapi.org/format/#document-compound-documents):

> Compound documents require "full linkage", meaning that every included resource MUST be identified by at least one resource identifier object in the same document.

**Comment by ethanresnick** [comment]
> I haven't seen any example with included objects with relationships inside.

@mrcasals Right, like @dgeb said, having relationships in `included` resources is completely allowed. So I think you haven't seen any just because our examples are bad :) My reading of the homepage example is just that, the author doesn't have a relationship to _any_ posts. That is, it looks like the posts point to authors, but not vice-versa. And, that's fine; not every relationship needs to be mirrored on both sides. 

If the authors did have a relationship to their posts, there would, as you suggest, be a `relationships` object in the `included` resources that had that relationship, and the `data` in that relationship, if provided, could signal cardinality, all as you suggest.

**Comment by mrcasals** [comment]
Awesome, thanks for your replies. I'll work on this.
