### ISSUE TITLE
Few questions related to POST, top level members..

### ISSUE THREAD

**Issue by benoittgt** [json-api/json-api#771]
Hello

First thanks for the spec. I saw Steve Klabnik talking about it few month and trying to turn my api to v2 with the json api specs, but I have few questions
- I want to be able to _add_ or _update_ comment related to an app. Api response to successful post or update (different status code) with that.

`POST`/api/v1/:store_id/applications/:mobile_application_update_id/comments`201 if created`

``` json
{
  "links":{
    "self":"https://store.com/api/v1/applications/:application_id/comments"
  },
    "data":{
      "type":"comment",
      "id":3904,
      "attributes":{
        "comment":"yeehhhhaaa",
        "rating":"3.0",
        "user_name":"B. 2",
        "user_id":123,
        "created_at":"2015-05-29T16:23:20.639+02:00",
        "updated_at":"2015-05-29T16:23:20.639+02:00"
      },
      "relationships":{
        "rating":0,
        "comments":[
        {
          "type":"comment",
          "id":3904,
          "attributes":{
            "comment":"yeehhhhaaa",
            "rating":"3.0",
            "user_name":"B. 3",
            "user_id":123,
            "created_at":"2015-05-21T09:05:19.388+02:00",
            "updated_at":"2015-05-21T09:59:22.417+02:00"
          }
        },
        {
          "type":"comment",
          "id":3875,
          "attributes":{
            "comment":"love tdd",
            "rating":"4.0",
            "user_name":"B. 3",
            "user_id":114,
            "created_at":"2015-05-20T15:12:25.988+02:00",
            "updated_at":"2015-05-20T15:12:25.988+02:00"
          }
        }
        ]
      }
    }
}
```
- First I found that adding **attributes** is quite "noisy". In the spec it's wrote that it : _MAY contain any of these top-level members_. Is it for clarity ? 
-  `rating` here, have not top level member, doesn't seems a problem for me except for constituency with the rest of the json response. What do you think?
- For the **Fetching Relationships** parts, does [the urls given](http://jsonapi.org/format/#fetching-relationships) just below are recommendations?

Thanks in advance for your feedbacks.

Benoit

**Comment by ethanresnick** [comment]
> I want to be able to add or update comment related to an app.

POSTing the new comment to `/api/v1/:store_id/applications/:mobile_application_update_id/comments` is easy, as in your example. But including related comments-to-be-created with the new comment isn't supported yet. This has been much discussed though. See #536 for the latest.

> First I found that adding `attributes` is quite "noisy".

The attributes bag in the spec so that top-level members that the base spec may add to resource objects in the future (that is, sibling properties to `"attributes"`) won't be at risk of conflicting with user-defined attributes.

> `rating` here, have not top level member

Since `rating` is just a scalar value, it seems like it should just go in `attributes`. Is there any reason not to do that? (Also, what is rating representing here...I'm a bit confused.)'

> For the Fetching Relationships parts, does the urls given just below are recommendations?

Yes, those are just examples based on the recommendations. No particular URI structure is mandated by the spec.

**Comment by benoittgt** [comment]
> This has been much discussed though. See #536 for the latest.

Thanks, very interesting.

>  Is there any reason not to do that? (Also, what is rating representing here...I'm a bit confused.)'

Because on my app, this is difference object. rating is an average of the rating of all the comment. :) It's probably not the right name.

Thanks Ethan
