### ISSUE TITLE
Outline cropped on smaller viewports

### ISSUE THREAD

**Issue by jgwhite** [json-api/json-api#772]
The fixed-position document outline is super useful but unfortunately gets cut off on smaller viewports.

![screen_shot_2015-06-17_at_17_58_52](https://cloud.githubusercontent.com/assets/34030/8213571/a8d8ca5c-151a-11e5-8c21-3e972818ac46.png)

Tried introducing `overflow: auto` when the sidebar is fixed but this has some unfortunate side effects such as double-scrolling and over-running the footer.

@wvteijlingen any workarounds spring to mind?

**Comment by wvteijlingen** [comment]
Ah yes, this has been pointed out before. The quickest solution that springs to mind right now is to create a breakpoint on viewport height, and forego the fixed position below a certain height. Otherwise we could fix it with scrolling overflow, but as you said, that creates some ugly scrolling.

I'm a bit busy now but I'll see if I can whip up a fix in the next couple of days.

**Comment by tkellen** [comment]
Thanks for the heads up! I'm closing in favor of #785.
