### ISSUE TITLE
meta attributes in POST request?

### ISSUE THREAD

**Issue by beauby** [json-api/json-api#778]
Hi, I'm pretty new to JSONAPI, but taking a great interest: I think it's about time some standard emerges.

Consider the following: I have a /sessions resource, and I want to allow a session to be created by a user POSTing to /session with his credentials. Where should those credentials go, since they're not part of the resource? I haven't seen a mention of the use of `meta` in the case of creating resources. Would putting the email/password (or whatever credentials) under `meta` be compliant?

**Comment by ethanresnick** [comment]
Putting the credentials in `meta` is one option; there's nothing in the spec that prevents that. Another option would be to use the [Authorization](https://tools.ietf.org/html/rfc7235#section-4.2) header, with the [Basic scheme](http://tools.ietf.org/html/draft-ietf-httpauth-basicauth-update-07) if the credentials are username/email and password (and a [different scheme](http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml) if they're something else). 

With any of these options, though, you should be aware that you'll be relying on SSL for all your security, since that's the only thing keeping the plaintext credentials out of the request. This can be a [bad idea](http://hueniverse.com/2010/09/29/oauth-bearer-tokens-are-a-terrible-idea/), so you might want to consider signing/hashing the credentials before sending them.

**Comment by beauby** [comment]
Using Authorization header does indeed make sense here. Thanks for the answer.
