### ISSUE TITLE
Any recommendations for the format of a 207 response?

### ISSUE THREAD

**Issue by sglanzer-fire** [json-api/json-api#787]
We're dealing with some multistatus responses in a project using JSONAPI and Ember Data.  I don't see anything in the current guidelines or issues for this - can anyone comment on a recommended format?

**Comment by ethanresnick** [comment]
Multi Status is often not a great idea, in part because 207 isn't part of the core HTTP Standard (instead, that status code comes from webDAV).

The "Other responses" sections of the JSON API spec say responses with other status codes must comply with HTTP semantics, where the phrase HTTP semantics links to RFC 7231. Since that RFC doesn't include 207, I think JSON API prohibits the use of it. (@dgeb please chime in here if I'm misreading things here or if this is unintentional.) 

Some of this might change as we think more about how to apply JSON API to non-HTTP protocols, but, for now, I think the spec's position is to pick the status code that best emcompasses the multiple results (this approach is outlined explicitly in the spec in the context of errors) or to restructure your API so that each response has a single, less ambiguous status code. If you have questions about doing the latter approach on your project in particular, please ask on our discussion forum: http://discuss.jsonapi.org/

**Comment by sglanzer-fire** [comment]
@ethanresnick Thanks for the response, I'll mull this over and continue the discussion in the forum if necessary.
