### ISSUE TITLE
Discuss: Is JSON-API the right name?

### ISSUE THREAD

**Issue by feightree** [json-api/json-api#835]
Im starting this issue to discuss wether or not json-api is the right name for this project. 

The main reason for bringing this up is that it gives alot of noise when searching for solutions and plugins related to this, simply because both JSON and API is two words used everywhere in the frontend world, making it next to impossible to find the results you want.

Searching for 'rest api' gives you pretty much what you want. But searching for 'json api' gives you 1 result linking to jsonapi.org and the rest of guides to various languages on how to make a json api (which mostly return in a restful format anyway).

Does anyone else share this concern?

**Comment by gr0uch** [comment]
This topic has been discussed repeatedly I think, but I'm too lazy to find the links right now. I have always been of the opinion that it's a bad/inappropriate name.
- It's always ambiguous whether JSON API means an ad-hoc API that happens to use JSON, or this specification, even when discussing the spec.
- There are plenty of other specifications which use JSON as a format, such as JSON-LD + Hydra, HAL, Collection+JSON, Mason, Siren, Micro API, etc. some of which share the goal of providing a unified format for building APIs over HTTP.
- Discoverability is terrible, hard to disambiguate search terms.

Even _Ember API_ would be a better name, since this spec arose from the needs of a particular client, Ember Data. Also people tend to be looking for unified stacks to avoid too much friction, I hardly see a Meteor backend used with anything other than Meteor in the frontend, or Facebook's GraphQL used with any frontend tech other than Relay/React (though it's way too early to tell). Angular seems to stay agnostic about backend with their `$http` module. 

Not sure if it's too late to change the name I think, since the media type has been registered as "JSON API" (`application/vnd.api+json`), but it may be still possible to drop "JSON" as part of the marketing name for the spec and put something else instead. I'd suggest "Ember API" but that may come with another problem: people thinking that something called "Ember API" may only be consumed by Ember Data.

**Comment by steveklabnik** [comment]
JSON API is not intended to be Ember or Rails specific, even though it came out of that.

Yes, we could have used a different name, but three years in, this isn't something that's going to change.
