### ISSUE TITLE
Case sensitivity with respect to query parameters.

### ISSUE THREAD

**Issue by ben-crowhurst** [json-api/json-api#884]
Nothing is mentioned within the 1.0 specification regarding case-sensitivity and query parameters.  

One and the same?

```
Fields=
fields=
FiElDs=
```

Please can this be clarified?

**Comment by ethanresnick** [comment]
JSON API distinguishes between two types of query parameters: those that it defines, and custom ones that users may use in their own apis. The latter are called "implementation-specific" query parameters. JSON API requires that all implementation-specific query parameters have one non-[a-z] character; that way, json api can add more query parameters in the future without risk of conflict. This all comes from http://jsonapi.org/format/#query-parameters:

> Implementation specific query parameters MUST adhere to the same constraints as member names with the additional requirement that they MUST contain at least one non a-z character (U+0061 to U+007A). It is RECOMMENDED that a U+002D HYPHEN-MINUS, "-", U+005F LOW LINE, "_", or capital letter is used (e.g. camelCasing).

So, how all this relates to your question:
- `Fields`, `fields`, and `FiElDs` are not automatically the same. The fact that JSON API allows a capital letter to be used to indicate an implementation-specific parameter (above) implies clearly that it considers these names to be case sensitive.
- However, because `Fields` and `FielDs` both do contain a capital letter, they're implementation-specific, which means you can define them to behave however you want. If you want to make them synonyms for `fields`, go for it.
- Nevertheless, you can't simply lowercase every query parameter that comes in. For example, imagine if you defined a query parameter like `myMagicParam`. If you accepted `mymagicparam` in its place, that would be a spec violation, becuase the lowercased `mymagicparam` has no non-[a-z] characters, so it's reserved by the specification for future use.
- If you do want to lowercase everything blindly, make sure that any custom query parameters you define also have some other non-[a-z] character in them, like a `-`. So you could have `my-magic-param` and then `my-MaGIC-paraM` could be an alias for it, because even after the lowercasing, it doesn't intrude on the JSON API-reserved namespace.

Make sense?

Also, remember, if you do receive requests with any parameters in the JSON API namespace that you don't know about, you MUST reject it:

> If a server encounters a query parameter that does not follow the naming conventions above [i.e. the ones for implementation-specific names], and the server does not know how to proccess it as a query parameter from this specification, it MUST return 400 Bad Request.
