### ISSUE TITLE
Is there a a specified encoding that should be used with `application/vnd.api+json` responses?

### ISSUE THREAD

**Issue by fake-name** [json-api/json-api#889]
I'm working with a web-service that implements a JSON-API, and there is no definitive encoding that is specified for the API responses, and the server doesn't return a content-disposition header with the encoding.

Realistically, I'm pretty sure the server here is responding in UTF-8, but the JSON spec allows UTF-8, UTF-16 or UTF-32 ([ref](https://tools.ietf.org/html/rfc7159#section-8.1)), so it's ambiguous.

It'd be nice to have the standard either require a proper content-disposition header, or specify a encoding that must be used in the absence of any other response metadata.

Is this within the scope of the JSON-API specification? I'm not sure.

**Comment by ethanresnick** [comment]
Basically, the various JSON specifications have never defined a way to provide information about which particular unicode encoding in use because this can be detected reliably by the client. This JSON specification offers [instructions](http://tools.ietf.org/html/rfc4627#section-3) for doing so, assuming the sender properly leaves out the byte order mark. (You'll need to use more complicated logic if you want to handle the case that the BOM is, improperly, included.)

Alternatively, you could just use a JSON parser that handles this all for you :)
