### ISSUE TITLE
Why are link templates gone? This prevents my lib from updating to 1.0

### ISSUE THREAD

**Issue by skqr** [json-api/json-api#891]
Hi, guys.

I'm working on a Python project attempting to implement JSON-API without a framework; the ones we investigated are not mature enough.

That said, I did write a full PHP framework a while ago, https://github.com/GoIntegro/hateoas. It was based on a pre-v1.0 spec.

The PHP framework implemented absolutely everything on the spec, and it was quite dependent on the link templates.

Now I'm reviewing the new spec with a teammate and in attempting to describe a link (of a single kind) between a resource and two others, I find there is no way to properly do this according to the spec.

Currently, I'm hit with a little message stating that "in the future a collection link might include a list of URLs". I consider this to be a pretty basic requirement, which the pre-v1.0 spec accomplished.

Am I missing something? How can I describe this link and provide URLs for both linked resources on my resource object?

Thanks!

**Comment by ethanresnick** [comment]
>  in attempting to describe a link (of a single kind) between a resource and two others, I find there is no way to properly do this according to the spec.

I _think_ that what you're looking for is the `links` bag within each relationship object, which has a `related` key for linking to the associated resource(s). Different relationships can have different `related` links, so the client can find the associated resources for each.

If you want to find the URI for each target resource in a to-many relationship, you'll have to fetch that relationship's `related` URI and then look at the `self` links in the response. This should give you everything you need, since it actually returns the related resources too.

If you're looking for a way to get the URI for each of the to-many related resources _without_ fetching that collection, there isn't currently a way to do that. But there's an open issue for it that we'll likely be addressing in 1.2 (#477) and, until then, you can put the URI in the resource identifier objects' `meta` key if need be.

Do any of those options work, or am I misunderstanding your question?

**Comment by skqr** [comment]
Actually, I think you nailed it.

The `related` links will definitely do. It does prevent me from fetching each of the to-many targets individually (which the pre-v1 spec allowed through URI templates), but I'm happy to fetch the entire collection for the specific scenario we're developing currently.

Thanks, @ethanresnick!

**Comment by ethanresnick** [comment]
Glad to help! And again, re fetching each individually: that'll likely be supported soon through #477.
