### ISSUE TITLE
What happens if a user defines a hasOne to a model named "relationship"

### ISSUE THREAD

**Issue by tsteuwer** [json-api/json-api#912]
For instance:

```
GET /:model/:id/relationships
GET /:model/:id/relationships/relationships
```

As per the original question on [Loopbacks JSONAPI Component](https://github.com/digitalsadhu/loopback-component-jsonapi/issues/44) thread... :boom:

**Comment by bobintornado** [comment]
Maybe a little bit book keeping will help? Use a flag to capture if we enter the relationship key? But this definitely gone to make stuff complicated. 

And I think this is kind of inevitable, as it's very hard to keep naming both human readable (has human meaning) and unique.

**Comment by tsteuwer** [comment]
Can I propose maybe having reserved words for models, such as `relationship` and `relationships`? Something along the lines of:

> A resource MUST not be any of the following reserved words:
> - relationship
> - relationships

**Edit: This would make it a lot easier on developers trying to conform to the specification**

**Comment by dgeb** [comment]
This isn't so much about the spec itself as it is about [recommendations for relationship URLs](http://jsonapi.org/recommendations/#urls-relationships), which exist outside of the spec.

There aren't recommendations for the `/:model/:id/relationships` path itself, so that path could still represent the related resource URL for a `relationships` relationship. And `/:model/:id/relationships/relationships` could represent the corresponding relationship URL. Even though this reads like some twisted legalese, and no doubt makes implementations more tricky, I don't think there are any actual conflicts.

> Can I propose maybe having reserved words for models, such as relationship and relationships? 

We can't reserve words at this point, since that would break backward compatibility. However, there's nothing saying that your particular implementation has to support a relationship named `relationships`.

**Comment by ethanresnick** [comment]
Yeah, I also don't think there's an actual conflict, with either the normative spec text or the recommendations.

**Comment by tsteuwer** [comment]
I disagree. How would the backend know to pull the relationship `relationships` or the relationships of the requested resource?

```
GET /resource/:id/relationships (i want relationships of resource)

versus

GET /resource/:id/relationships (i want all the relationships resources of resource :id)?
```

**Comment by dgeb** [comment]
The first example is not a recognized endpoint for the spec:

```
GET /resource/:id/relationships (i want relationships of resource)
```

In other words, the spec doesn't contain the concept of an endpoint that returns all the relationships of a particular resource.

**Comment by tsteuwer** [comment]
OK perfect!
