### ISSUE TITLE
Question: What would be the JSON API way of permforming actions?

### ISSUE THREAD

**Issue by abrykajlo** [json-api/json-api#935]
The intention of actions in this case is providing a way to do things like duplicating models or activating models, things that require extra logic behind the curtains. This would be some form of extension. For our use case we have a model that the user can duplicate which has many other relations that need to be duplicated as well. We have all the logic planned out and implemented just haven't tied it in to our API. We were planning on doing something like a `POST` or `PATCH` to `/v2/:model/:id/duplicate` but I am thinking there might be a better more JSON API way of doing things. Like a `POST` to `/v2/:model` with body 

```
{
    "data": {
        "actions": {
              "duplicate": {
                     "id": "2"
              }
        }
    }
}
```

Also should there be a conformity to how to go about extending JSON API? Should the extensions extend the style of urls or body of the request or are both okay.

**Comment by ethanresnick** [comment]
There's been some talk about how to do this, but nothing official yet. For now, I'd suggest `POST`ing to `/v2/:model/:id` with a custom (i.e. non JSON API) body, and just sending that request as plain `Content-Type: application/json`, rather than using the JSON API media type. Then, once JSON API supports this, you can switch that POST endpoint over to accepting both the custom JSON form and the standard JSON API one, and gradually transition your clients over to the latter.

**Comment by patrykorwat** [comment]
@ethanresnick I agree with that.

You could model your action as some processes (resources), where `POST` triggers an action, but for non long running tasks, in which you could also implement `GET` request to check the status of your task, is overengineering.

**Comment by ethanresnick** [comment]
Closing in favor of #745
