### ISSUE TITLE
PDF/ePub files

### ISSUE THREAD

**Issue by Turbo87** [json-api/json-api#937]
Are there any exports of the specification to PDF or ePub files?

**Comment by steveklabnik** [comment]
There is not, but it might be nice!

**Comment by ethanresnick** [comment]
:+1: to what @steveklabnik said. 

In the mean time, though, there's a good print stylesheet, so if you print the Specification page and save that to PDF, you'll get an ok output (albeit with links formatted for print, rather than for onscreen display). That stylesheet could also probably be the basis of some export-to-pdf script that we could run each time we publish a new version.
