### ISSUE TITLE
Should error title/detail be translated ? Should they be displayed to users ?

### ISSUE THREAD

**Issue by ghost** [json-api/json-api#955]
Hi,

As the error title is a human readable explanation, what if the user doesn't speak the language of the developer of the API ? so should the errors be translated ?

If yes, can the client use them to display the error to the users, or is it just functional and the client should only rely on the code to display the cause of the error in the appropriate language.

Finally, If the error should be translated (actually even if not !), I think the client should always send the Accept-Language header to tell the server in which language the error should be translated, or even if data can only be accessed to certain language, or if a data field can be translated.

**Comment by ethanresnick** [comment]
Title and detail can both be translated, and this translation can be governed by `Accept-Language`. I think the specification alludes to this possibility for `title`, since it says that the value should always be the same "except for purposes of localization" (which implies that it can be localized). However, the definition of the `details` member doesn't allude to localization, so I'll put together a PR to fix that soon.

As far as translating data fields goes (i.e. fields in resource objects), that's something you probably shouldn't do. Instead, the different translations should have different JSON API resource objects with different `id`s. Then, you can (optionally) link the user to the alternate versions (using, e.g., the HTTP Link header or a JSON API relationship, like [here](https://github.com/json-api/json-api/issues/613)). The reason for not translating the data fields stems from the fact that JSON API doesn't have the same separation between a resource and a representation that HTTP does; in JSON API, a resource (object)'s fields _are_ its state.
